### ISSUE TITLE
Add dependabot to allowed users for cla bot

### ISSUE THREAD

**Issue by glennawatson** [dotnet-foundation/projects#1]
A lot of the dnf users use dependabot. 

When the cake team brought up the issue in the past the suggestion was to add the dependabot user to a whitelist for the cla bot. At the moment some changes on dependabot pr fail the cla if they are large enough commits.

**Comment by gep13** [comment]
It was discussed on Twitter here:

https://twitter.com/dependabot/status/1093837459895578629

**Comment by jongalloway** [comment]
We're using an install of the CLA Assistant that is maintained by the open source project office at Microsoft. CLA Assistant also list that in their FAQ - we have to whitelist bot accounts individually in each org or repo: https://github.com/cla-assistant/cla-assistant#faq (which echoes the dependabot instructions). We can't whitelist for the entire CLA system. I've asked about getting that changed, but we don't have an answer yet. So for now, let me know what orgs or repos, and which bot accounts to be whitelisted. In the future, we'll want to get the project support team involved in admin for these.

**Comment by glennawatson** [comment]
The MvvmCross project asked about it on leadership slack, and we decided to put a issue in, also the ReactiveUI project has dependabot dependencies, and also the cake team.

**Comment by jongalloway** [comment]
I set up MvvmCross, ReactiveUI, and Cake. Let me know how those work, and I can keep rolling out to other repos and projects.

**Comment by haacked** [comment]
> We can't whitelist for the entire CLA system

I'm assuming that's a policy decision and not a technical issue. If so, maybe we should suggest an API for whitelisting. That way we can do that as part of our onboarding.

**Comment by jongalloway** [comment]
It's a technical issue. We're using [CLA Assistant](https://github.com/cla-assistant/cla-assistant#faq) and it's a per-project setting. There may be a way to get it changed globally, but would require some dev. Our CLA system is maintained by the Microsoft Open Source Project Office, I just sent a ping to them asking about it. Keep in mind that this CLA is also used by CoreCLR, CoreFX, ASP.NET, etc. so it may not be possible to do this globally for that reason.

**Comment by haacked** [comment]
> There may be a way to get it changed globally, but would require some dev

Well, good thing it's open source! https://github.com/cla-assistant/cla-assistant Has anyone logged an issue about this?

> Keep in mind that this CLA is also used by CoreCLR, CoreFX, ASP.NET, etc. so it may not be possible to do this globally for that reason.

I can't think of a situation where you wouldn't want dependabot white listed. But assuming they're not OK with this, we may be better served by an API.

Would be nice if someone who better understood the issue to research whether CLA Assistant has an API to change settings, and if not, to log an issue to create an API for this.

**Comment by SimonCropp** [comment]
@jongalloway can u add https://github.com/VerifyTests/ to the allow list

**Comment by jongalloway** [comment]
![](https://pics.onsizzle.com/its-an-older-code-sir-but-it-checks-out-quiekmeme-com-24511126.png)

Added, but going forward the best way to get any project support is by creating a [Project Support Request issue](https://github.com/dotnet-foundation/projects/issues/new/choose). That will notify the current project support team.

**Comment by ChrisSfanos** [comment]
We are migrating all projects to the new [CLA service](https://github.com/microsoft/ContributorLicenseAgreement), so I'm going to close this older issue.  Please feel free to re-open or (probably better) create a new issue - thanks!
