### ISSUE TITLE
linq2db

### ISSUE THREAD

**Issue by jogibear9988** [dotnet-foundation/projects#10]
## 1.   General Information

**Project Name:** linq2db

**License:** MIT

**Contributor (Company, Organization or individual name(s)):** https://github.com/linq2db

**Existing OSS Project? (Yes/No):** yes

**Source Code URL:** https://github.com/linq2db/linq2db

**Project Homepage URL (if different):**

**Project Transfer Signatories:**
Full legal name and email address required of the individual(s) with the authority to transfer or contribute the project to the .NET Foundation. Note that if you'd prefer not to include this in the public application, it can be submitted via e-mail to contact@dotnetfoundation.org (referencing this issue number).

Igor Tkachev (igor.tkachev@gmail.com)

## 2.   Description
**Please provide a brief statement about your project in terms that are understandable to the target consumer of the library or project, i.e. an elevator pitch for the project:** 

LINQ to DB is the fastest LINQ database access library offering a simple, light, fast, and type-safe layer between your POCO objects and your database.

Architecturally it is one step above micro-ORMs like Dapper, Massive, or PetaPoco, in that you work with LINQ expressions, not with magic strings, while maintaining a thin abstraction layer between your code and the database. Your queries are checked by the C# compiler and allow for easy refactoring.

However, it's not as heavy as LINQ to SQL or Entity Framework. There is no change-tracking, so you have to manage that yourself, but on the positive side you get more control and faster access to your data.

In other words LINQ to DB is type-safe SQL.

**Please provide a 1 sentence (<140 character) summary of your to help users when searching the .NET Foundation projects**

LINQ to DB is type-safe SQL.

## 3.   Project Governance
Please complete this section about who will be maintaining the open source project and how it will run.
**Project Lead:**
(Who is the primary contact point for the community and the .NET Foundation when discussing governance of the project.)

Name:   Igor Tkachev 
 Email:   it@rsdn.ru
 GitHub Profile URL: https://github.com/igor-tkachev

**Committers:**

Which individuals have commit / write access to the repository, what is their GitHub ID and who is their employer (if contributions are on behalf of an employer)

Svyatoslav Danyliv - sdanyliv 
MaceWindu
Ilya Chudin - ili

**Governance Model:**

Please describe how new code changes are proposed to the project, how those changes are reviewed and how a decision is made to accept proposed changes. Also describe the process for identifying and appointing new committers.

Community members submit pull requests which are reviewed by the core committers for quality and fit. If they are approved they are committed to the project. Core committers are identified through their participation in the community as well as through pull requests they have submitted.

**CLA**

If already an OSS project, was a Contribution License Agreement in place for contributions accepted? How does the project check who has signed one?

This project would like to utilize the .NET Foundation CLA system

**CLA Notification Alias**
Provide an email address that will receive CLA related notifications from the .NET Foundation CLA automation

it@rsdn.ru

**Project Transfer Type**

Projects may join the .NET Foundation in one of two ways and you should chat with your .NET Foundation contact to discuss the best mechanism for your project. You can either a) assign the copyright of the project's source code to the .NET Foundation or b) contribute the project source code to the .NET Foundation under an open source license. Assignment is the preferred approach, but licensing a project to the Foundation may be more appropriate for longer running open source projects that have not previously had a contribution license agreement and have accepted contributions from many different sources.
a) Assignment
b) Contribution

b.

## 4.   Repository Layout
The .NET Foundation host guidance for new projects and details on recommended structure here:
[https://github.com/dotnet/home/tree/master/guidance](https://github.com/dotnet/home/tree/master/guidance)

Note that the open source repository should be the master where changes are made by the core development team using the same PR process that is used for non-committer contributions.

Please define below any changes you would want to make to your repositories as part of the process of joining the .NET Foundation

## 5.   PR Plan
Please summarize the public relations plan for the announcement when joining the foundation (and releasing as open source if appropriate). What is the main story we wish to promote, through what channels, what issues should we be aware of?  For significant news events then please also work with your .NET Foundation contact to ensure a [full PR plan](https://dotnetfoundation.sharepoint.com/Shared%20Documents/PR/Communications%20Plan%20TEMPLATE.docx?web=1) is developed.

## 6.   Infrastructure Requirements
Please describe any infrastructure requirements for the project. For example, how will build servers be operated? Any web hosting or service hosting requirements? Do we need to set up SSL certificates or provide Authenticode Code Signing arrangement for releases?

## 7.   Additional Notes
Please provide any additional information required or use this area for notes during the onboarding process. If this open source project has similarities with any other projects in this space then please detail them and why this project is different. If there are any potential issues that you feel the project might need help with early on then also state them here and discuss with your .NET Foundation Contact.

**Comment by jogibear9988** [comment]
We also have a slack channel wer we could discuss more needed infos

**Comment by jogibear9988** [comment]
@jongalloway do you have a time schedule when the projects get a answer about the process?

**Comment by jogibear9988** [comment]
@jongalloway hey jon, any news to this?

**Comment by jogibear9988** [comment]
@jongalloway is there any document describes what the requires between the differnet steps are? when does a project get from "New Project Application" to "Reviewing"?

**Comment by jogibear9988** [comment]
@jongalloway any news to this?

**Comment by jogibear9988** [comment]
@ChrisSfanos can you also tell if we need to do something...

**Comment by ChrisSfanos** [comment]
At the moment I don't think so - I'm following up with @onovotny to see what steps are next - thanks!

**Comment by jogibear9988** [comment]
@ChrisSfanos any News?

**Comment by ChrisSfanos** [comment]
From my view, this project needs to get approved by the board.  @onovotny - can you chime in as to when this project will be presented?

**Comment by ChrisSfanos** [comment]
Hi everyone
I'll be assisting with the on-boarding and post-onboarding process for bringing this project to the .NET Foundation

As part of the on-boarding, we need to:
1) Sign the CLA via DocuSign
2) Onboard the CLA via GitHub

To complete Step 1, I need the email addresses of:
@ili
@sdanyliv
@MaceWindu 

If you don't want to post your email address here, please send it to me: chris.sfanos@dotnetfoundation.org

**Comment by jogibear9988** [comment]
ili:
chudinia@gmail.com
sdanyliv:
sdanyliv@gmail.com

**Comment by jogibear9988** [comment]
@ChrisSfanos 
hopefully you should now have all email addresses.

**Comment by ChrisSfanos** [comment]
Yes I do - the CLA is out for signing

**Comment by jogibear9988** [comment]
@ChrisSfanos 
CLA should be signed, is it okay?

**Comment by ChrisSfanos** [comment]
Yes, it's good - I'm moving forward with the next steps shortly

**Comment by ChrisSfanos** [comment]
Next step is CLA Onboarding via GitHub - email sent with details

**Comment by ChrisSfanos** [comment]
We will track the remaining onboarding work via this checklist:

## Onboarding
- [ ] CLA Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Post Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Enable CLA automation for future contributors
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)

**Comment by jogibear9988** [comment]
@ChrisSfanos @MaceWindu did not get a mail

**Comment by ChrisSfanos** [comment]
I forwarded the mail - the original just went to @ili

**Comment by jogibear9988** [comment]
Seems wee did the most:

Joining the Project leader mailing list -> done
Joining the Project leader Slack channel -> done (MaceWindu and I did)
Joining the Project leader Slack channel -> MaceWindu did
Updating license/copyright in the repo + updating file headers -> Licencense seems okay?
Reviewing the .NET Foundation Code of Conduct -> I created a pull req (https://github.com/linq2db/linq2db/pull/2130)
Enable CLA automation for future contributors -> What do we need to do?
Add Project to the .NET Foundation project list => see: https://github.com/dotnet/foundation/pull/167
Project layout cleanup (as appropriate) -> seems we do not need to do anything
README Guidance updates -> do we need to do some more?
Project website updates (outside of GitHub) -> we do not have any outside of GH, do we need to add smth here: https://linq2db.github.io/index.html?

**Comment by ChrisSfanos** [comment]
Thanks!  For your questions
- MIT license is good - no action required
- CLA Automation: No actions required
- README - Per the guidance, can you add the Code of Conduct and .NET Foundation pointer (info is here: https://github.com/dotnet/foundation/blob/master/guidance/readme-guide.md)
- Project website: Can you add the reference/link to the .NET Foundation.

Thanks!

**Comment by ChrisSfanos** [comment]
Hi @jogibear9988 - any updates on the README and Project website updates?  Once those are done, we can wrap up the on-boarding efforts!

**Comment by jogibear9988** [comment]
Readme is done

**Comment by ChrisSfanos** [comment]
Thanks - taking a look at the github.io site, I think we don't need anything added.  That wraps up the list and we can close this out

**Comment by jogibear9988** [comment]
I've created a pull to add it to the HP:
https://github.com/linq2db/linq2db.github.io/pull/1

also this pull need's to be merged
https://github.com/dotnet/foundation/pull/167

**Comment by ChrisSfanos** [comment]
Awesome - thanks!
