### ISSUE TITLE
Project Spotlight Request: DotVVM

### ISSUE THREAD

**Issue by tomasherceg** [dotnet-foundation/projects#100]
## General Information

**Project Name:** DotVVM

**Contributor (Company, Organization or individual name(s)):** Tomáš Herceg (most of the team is from the RIGANTI company)

**Source Code URL:** https://github.com/riganti/dotvvm

**Documentation URL:** https://www.dotvvm.com/docs

**Contribution URL:** https://github.com/riganti/dotvvm

**Project Homepage URL (if different):** https://www.dotvvm.com

**Please provide a brief statement about your project in terms that are understandable to the target consumer of the library or project, i.e. an elevator pitch for the project:** 
DotVVM is an open-source framework that allows building ASP.NET apps using the MVVM approach with just C# and HTML. The framework is integrated in the ASP.NET ecosystem, ships with an extension for Visual Studio, and can be also used for modernizing old ASP.NET applications as it supports both OWIN and ASP.NET Core.

**Please list 5 top non-maintainer contributors to your project**
Stanislav Lukeš, Milan Mikuš, Ladislav Šesták, Michal Tichý, Andrej Čižmárik

**Month you would prefer to be featured**
We discussed November on Slack.

**Timeline when to conduct a short interview**
Any time that works for you.

**Comment by isaacrlevin** [comment]
@tomasherceg @sbwalker We are probably going to skip November due to .NET Conf and such. @sbwalker is that ok if we push you to Jan or Feb?

**Comment by sbwalker** [comment]
Obviously it would be more impactful to do the Oqtane spotlight in December - as Oqtane 2.0 was just released this week for .NET 5. But I can certainly wait to January if we need to push the schedule.

**Comment by tomasherceg** [comment]
@isaacrlevin No problem. :-)

**Comment by isaacrlevin** [comment]
Hey @tomasherceg, when would you be free for a 30 minute timeslot for your interview?

**Comment by tomasherceg** [comment]
@isaacrlevin What is your timezone? I am in CET but I am happy to do the interview in the evening hours. My schedule i quite free on Friday 15th or Monday 18th.

**Comment by isaacrlevin** [comment]
PST. What does your day look like Friday?

**Comment by tomasherceg** [comment]
Can we do Friday at 9 AM or 10 AM PST?

**Comment by isaacrlevin** [comment]
10 PST works great, can you give me an email to send the invite to?

**Comment by tomasherceg** [comment]
@isaacrlevin Please send the invite to info@dotvvm.com

**Comment by isaacrlevin** [comment]
@tomasherceg can you provide the github alias for your community contributors?

**Comment by tomasherceg** [comment]
@isaacrlevin Not sure what you mean by "GitHub alias", but thinking of what we spoke about during the interview:
- Issues that are good for new contributors are using the "good first issue" label: https://github.com/riganti/dotvvm/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
- Our main repo is https://github.com/riganti/dotvvm
- Help for new contributors: https://github.com/riganti/dotvvm/blob/main/contributing.md
- Gitter chat where the team is available and ready to help: https://gitter.im/riganti/dotvvm
- Twitter: https://twitter.com/dotvvm

**Comment by isaacrlevin** [comment]
Just the github user ids of your contributors.

**Comment by isaacrlevin** [comment]
@tomasherceg 
FYI staging site to review
https://jolly-grass-05beb181e-725.westus2.azurestaticapps.net/projects/spotlight?project=DotVVM

**Comment by tomasherceg** [comment]
@isaacrlevin Thanks, the site looks nice!
I can see that you already found the IDs of the contributors - only the alias of Milan Mikuš is Mylan719. The rest is correct.

**Comment by tomasherceg** [comment]
@isaacrlevin Btw is it possible to select another frame as the thumbnail of the video? I look even more weird than usual on the current one. :-)

**Comment by isaacrlevin** [comment]
How does this look?

https://jolly-grass-05beb181e-725.westus2.azurestaticapps.net/projects/spotlight

**Comment by tomasherceg** [comment]
@isaacrlevin Awesome, many thanks!

**Comment by isaacrlevin** [comment]
@tomasherceg this will be published on Monday FYI

**Comment by isaacrlevin** [comment]
@clairernovotny can you please close this issue or give me more repo power :)

**Comment by devlead** [comment]
This is now completed
https://dotnetfoundation.org/projects/spotlight?project=DNN%20Platform%20(Formerly%20DotNetNuke)
