### ISSUE TITLE
Code Signing Certificate Request: Kerberos.NET

### ISSUE THREAD

**Issue by SteveSyfuhs** [dotnet-foundation/projects#101]
### Please fill in the information below

- **Project Name:** Kerberos.NET
- **LastPass Email (or send offline):** steve@syfuhs.net

Certificate onboarding checklist:

- [x] Register trade name @ChrisSfanos
- [x] Create organization with DigiCert
- [x] Create configuration in Code Signing Service
- [x] Provide credentials in shared folder in LastPass
- [x] Request certificate from DigiCert
- [x] Received certificate and finalize sign service configuration

**Comment by ChrisSfanos** [comment]
Trade Name registration submitted

**Comment by SteveSyfuhs** [comment]
Friendly status check?

**Comment by clairernovotny** [comment]
Waiting on DigiCert validation. Sometimes it's fast, sometimes it's....not, sadly.

**Comment by clairernovotny** [comment]
This took way longer than normal but it's resolved. I've shared the credentials in the LastPass. Happy to look at any PR's to add signing to your pipeline. Once the package is signed, please add `dotnetfoundation` as a co-owner on the NuGet packages.
