### ISSUE TITLE
Project Support Request: cake-build/cake

### ISSUE THREAD

**Issue by devlead** [dotnet-foundation/projects#104]
- **Project Name:** cake-build/cake
- **Due by:**
- **Description:** CLA bot not reporting back

See that webhook delivers payload for PR events to logic app and they're getting 202, but GitHub status check isn't triggered
![image](https://user-images.githubusercontent.com/1647294/94254312-e4c24b00-ff26-11ea-970d-47aa57f45aca.png)

Example PR
https://github.com/cake-build/cake/pull/2865

**Comment by clairernovotny** [comment]
I'll ping the folks who run the bot.

**Comment by devlead** [comment]
> I'll ping the folks who run the bot.

Excellent, happy to jump on a Teams call if there's any assistance needed from our part.

**Comment by clairernovotny** [comment]
It looks like dnfadmin is no longer an owner of the cake-build org? Can you please fix that? dnfadmin needs to be an owner of Foundation project orgs. That may be impacting this.

Thanks

**Comment by devlead** [comment]
Isn't @dnfclas used for CLA? It's member of a team that has maintainer access, shouldn't that be sufficient to do the status check? 
![Screenshot_20200928-183117](https://user-images.githubusercontent.com/1647294/94460478-16524500-01b9-11eb-8846-2df54cf77161.jpg)

**Comment by clairernovotny** [comment]
There are several issues, and Foundation policy requires that dnfadmin account to always be an owner on the org. Has to do with security and continuity, mostly. It's never used to interfere.

**Comment by devlead** [comment]
I see, seems to be working now.
![Screenshot_20200928-195953](https://user-images.githubusercontent.com/1647294/94468808-4c95c180-01c5-11eb-9db5-fd74a182d17f.jpg)

**Comment by clairernovotny** [comment]
Glad it's working but can you please restore dnfadmin to owner?

**Comment by devlead** [comment]
Thought dnfadmin was a high privilege break glass account, but see activity in our audit logs. 

See it's being used as a bot, with more privileges than it needs to preform those tasks. 

It also across multiple orgs/repos creates forks, commits, raises issues and merges PRs, which indicates someone's actively using it from their browser.

Which raises security concerns, what process and policies are in place for this account? Who has access to it? What's the audit process of this account? What's the policy on informing orgs when administrative tasks are executed on orgs?

**Comment by clairernovotny** [comment]
The `dnfadmin` account is protected with FIDO keys and very limited access. We're working with GitHub on overall improvements so that we don't need this kind of account in the future but it's still required today.
