### ISSUE TITLE
Project Spotlight Request: DNN Platform

### ISSUE THREAD

**Issue by mitchelsellers** [dotnet-foundation/projects#105]
## General Information

**Project Name:** DNN Platform (Formerly DotNetNuke)

**Contributor (Company, Organization or individual name(s)):** DNN Community Managed, current community leadership team: Mitchel Sellers, David Poindexter, Will Strohl, and Peter Donker

**Source Code URL:** https://github.com/dnnsoftware/Dnn.Platform

**Documentation URL:** https://dnndocs.com/

**Contribution URL:** https://github.com/dnnsoftware/Dnn.Platform/blob/develop/CONTRIBUTING.md

**Project Homepage URL (if different):** https://dnncommunity.org/

**Please provide a brief statement about your project in terms that are understandable to the target consumer of the library or project, i.e. an elevator pitch for the project:** The DNN Platform is a Content Management System (CMS) based on Microsoft's .NET Framework. Just like other CMSs such as Wordpress, Joomla or Drupal, it allows users to create and manage online content. And just like those other CMSs you can extend the application with custom addons to suit your needs. Unlike most other CMSs, however, it is built on .NET, meaning it is built on a solid foundation created by the world's most successful tech company. Microsoft invests heavily to ensure this is the most powerful and secure backbone for web-based applications. To date, DNN is the most succesful open source CMS built on this enterprise-grade infrastructure.

**Please list 5 top non-maintainer contributors to your project** 
@ahoefling - Andrew Hoefling
@thabaum - Cody
@sleupold - Sebastian Leupold
@EPTamminga - Ernst Peter Tamminga
@bogdan-litescu - Bogdan - Litescu

**Month you would prefer to be featured** Flexible September/October

**Timeline when to conduct a short interview** Flexible US Central times during the day or after 8PM.

**Comment by isaacrlevin** [comment]
This is live, @clairernovotny can you close? (or give me close rights to this repo)
