### ISSUE TITLE
New .NET Foundation Project Application: Stride Game Engine

### ISSUE THREAD

**Issue by xen2** [dotnet-foundation/projects#107]
## 1.   General Information

**Project Name:** Stride

**License:** MIT

**Contributor (Company, Organization or individual name(s)):**
Originally Silicon Studio.
The project was then open-sourced and it is now maintained by the Stride community.

**Existing OSS Project? (Yes/No):** Yes

**Source Code URL:** https://github.com/stride3d/stride

**Project Homepage URL (if different):** https://stride3d.net

**Project Transfer Signatories:**
Full legal name and __email address__ required of the individual(s) with the authority to transfer or contribute the project to the .NET Foundation. Note that if you'd prefer not to include this in the public application, it can be submitted via e-mail to contact@dotnetfoundation.org (referencing this issue number).

* [Virgile Bello](https://github.com/xen2) (virgile@stride3d.net)

## 2.   Description
**Please provide a brief statement about your project in terms that are understandable to the target consumer of the library or project, i.e. an elevator pitch for the project:**

Stride is an open-source C# game engine for realistic rendering and VR. The engine is highly modular and aims at giving game makers more flexibility in their development. Stride comes with an editor that allows you to create and manage the content of your games or applications visually and intuitively.

**Please provide a 1 sentence (<140 character) summary of your project to help users when searching the .NET Foundation projects**

Stride is an open-source C# game engine, featuring editor, VR, efficient asset pipeline and realistic rendering.

## 3.   Project Governance
Please complete this section about who will be maintaining the open source project and how it will run.
**Project Lead:**

Name:   Virgile Bello
 Email:   virgile@stride3d.net
 GitHub Profile URL: https://github.com/xen2

**Committers:**

Which individuals have commit / write access to the repository, what is their GitHub ID and who is their employer (if contributions are on behalf of an employer)

https://github.com/xen2
https://github.com/Aggror
https://github.com/Eideren
https://github.com/Kryptos-FR
https://github.com/xwellingtonx

**Governance Model:**

Please describe how new code changes are proposed to the project, how those changes are reviewed and how a decision is made to accept proposed changes. Also describe the process for identifying and appointing new committers.

Changes are proposed through github PR. It might be following a discussion on our Discord server (but this is in no mean mandatory).
We require test to pass, and at least 1 PR review from a person familiar with the module being changed (ideally 2 or 3).
Regular contributors are usually offered a committer role if they are interested in it. If the project grows bigger, we might need a more formal process for this.

**CLA**

If already an OSS project, was a Contribution License Agreement in place for contributions accepted? How does the project check who has signed one?

We use cla-assistant.io github bot.
Our CLA is based on Harmony Agreements.
https://cla-assistant.io/stride3d/stride

**CLA Notification Alias**
Provide an email address that will receive CLA related notifications from the .NET Foundation CLA automation

cla@stride3d.net (not created yet)

**Project Transfer Type**

- [ ] Assigment
- [x] Contribution (note: still not 100% decided)

**Assignment Model.**  Under the .NET Foundation assignment model, project ownership and other intellectual property is assigned to the .NET Foundation and the .NET Foundation agrees to grantback a license to the contributor(s). 

**Contribution Model.**  Under the .NET Foundation contribution model, a project retains ownership of the project, but grants the .NET Foundation a broad license to the project’s code and other intellectual property. The project also confirms that the project’s submissions to .NET Foundation are its own original work (there are also instructions for any third party materials that might be included).

## 4.   Repository Layout
**The .NET Foundation host guidance for new projects and details on recommended structure here:
[https://github.com/dotnet/home/tree/master/guidance](https://github.com/dotnet/home/tree/master/guidance)

Note that the open source repository should be the master where changes are made by the core development team using the same PR process that is used for non-committer contributions.

Please define below any changes you would want to make to your repositories as part of the process of joining the .NET Foundation**

Right now our user-facing doc is on a separate repository: https://github.com/stride3d/stride-docs
Not decided if it would be better to merge it with main repository (it's quite large so ideally I would like to wait for [VFS for Git](https://vfsforgit.org/))

## 5.  Eligibility Criteria
Please complete the following for your project
* The project is built on the .NET platform and/or creates value within the .NET ecosystem.
- [x] Yes 
- [ ] No
* The project produces source code for distribution to the public at no charge.
- [x] Yes 
- [ ] No
* The project's code is easily discoverable and publicly accessible (preferably on GitHub).
- [x] Yes 
- [ ] No
* The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).
- [x] Yes 
- [ ] No
* When applicable, project must use reproducible build settings in its toolchain.
- [x] Yes (need to double check)
- [ ] No
* The project uses [Source Link.](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
- [x] Yes 
- [ ] No
* The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).
- [x] Yes 
- [ ] No
* The project code signs their artifacts as appropriate.
- [x] Yes 
- [ ] No
* Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).
- [x] Yes  (need to double check accepted license, here is [list of what we use](https://github.com/stride3d/stride/blob/master/THIRD%20PARTY.md)
- [ ] No
* Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.
- [x] Yes 
- [ ] No
* The copyright ownership of everything that the project produces is clearly defined and documented.
- [x] Yes 
- [ ] No
* The project has a public issue tracker where the status of any defect can be easily obtained.
- [x] Yes 
- [ ] No
* The project has a published Security Policy.
- [ ] Yes 
- [x] No
* The project has a home page which provides high level information about its status and purpose.
- [x] Yes 
- [ ] No
* The project has a public communication channel where community members can engage with maintainers.
- [x] Yes (Discord, Twitter, forums, etc.)
- [ ] No
* The project has a publicly available location where members can review and contribute to documentation.
- [x] Yes (separate repository: [stride-docs](https://github.com/stride3d/stride-docs))
- [ ] No

## 6.   PR Plan
**Please summarize the public relations plan for the announcement when joining the foundation (and releasing as open source if appropriate). What is the main story we wish to promote, through what channels, what issues should we be aware of?  For significant news events then please also work with your .NET Foundation contact to ensure a [full PR plan](https://dotnetfoundation.sharepoint.com/Shared%20Documents/PR/Communications%20Plan%20TEMPLATE.docx?web=1) is developed.**

**Twitterpost**
> *Stride has joined the .NET Foundation! Read about it here <link to Stride blogpost below>*

**Blogpost on main website**
> **Stride has joined the .NET Foundation**
> *It’s our pleasure to announce that as of today, Stride is officially part of the .NET Foundation! Stride is joining an elite group of projects such as Roslyn, NuGet, .NET Core, ASP.NET Core, and others. Many of these technologies are at the core of the Stride game engine, so being united or this banner just feels right*
> .NET Foundation Logo

> **What Does This Mean for Stride?**
> *Open source foundations have been a mainstay of OSS projects across many different platforms for years. Ultimately what they provide to OSS projects are legal support, marketing help, and general project guidance. This includes protecting the project’s copyrights and ensuring that the intellectual property is in good standing and is properly assigned.*

> *In general the goal of the .NET Foundation is to help ensure that all of its projects follow OSS best practices in order to increase adoption of OSS across the entire .NET ecosystem.*

> *We’re joining the .NET Foundation in order to help broaden the awareness of the Stride game engine and send a signal to potential users everywhere that Stride is the best opensource C# game engine to use. Joining the .NET Foundation will enable us to keep community standards in good hands*.

## 7.   Infrastructure Requirements
**Please describe any infrastructure requirements for the project. For example, how will build servers be operated? Any web hosting or service hosting requirements? Do we need to set up SSL certificates or provide Authenticode Code Signing arrangement for releases?**

- Website and build agent on Azure
- Build server & forum on Digital Ocean (ideally it would be better on Azure, if it wasn't for costs)
- CDN with StackPath (same, it would be better on Azure)
- SSL certificates are all free & auto-renewed (Let's Encrypt or equivalent)
- Code signing certificate would need to be provided by .NET Foundation (they need to be installed on the build agent)

## 8.   Additional Notes

We recently migrated our project to work with .NET Core 3.1 (both runtime and editor), and hope to switch to .NET 5 sooner or later.

**Comment by ChrisSfanos** [comment]
Hi everyone
I'll be driving the on-boarding process for Stride Game Engine to the .NET Foundation.  We will be working through the following checklist

## CLA
- [ ] Project Agreement Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)
- [ ] Enable two-factor authentication (2FA) for GitHub

**Comment by ChrisSfanos** [comment]
Project agreement is out for signing

**Comment by ChrisSfanos** [comment]
Agreement is signed off - CLA onboarding instructions sent

**Comment by ChrisSfanos** [comment]
CLA bot is configured
Sending the remaining onboarding steps shortly

**Comment by tebjan** [comment]
Looking so forward to this!!!

**Comment by ChrisSfanos** [comment]
All on-boarding steps are complete - closing this out :-)
