### ISSUE TITLE
Code Signing Certificate Request: DataGridExtensions

### ISSUE THREAD

**Issue by tom-englert** [dotnet-foundation/projects#108]
### Please fill in the information below

- **Project Name:** DataGridExtensions
- **LastPass Email (or send offline):** -offline-

Certificate onboarding checklist:

- [x] Register trade name @ChrisSfanos
- [x] Create organization with DigiCert
- [x] Create configuration in Code Signing Service
- [x] Provide credentials in shared folder in LastPass
- [x] Request certificate from DigiCert
- [x] Received certificate and finalize sign service configuration

**Comment by ChrisSfanos** [comment]
Trade name registration submitted

**Comment by clairernovotny** [comment]
Completed from digicert. Sorry it took so long on this.

**Comment by clairernovotny** [comment]
I just invited you to the shared LastPass where the cert is setup and configured.

Few things:
1. Here's a template of how to add code signing to the build pipeline: https://github.com/novotnyllc/CodeSigningDemo
2. Once signing is configured, please add `dotnetfoundation` as a co-owner in NuGet. 
3. If you have any 3rd party binaries in your packages, you'll need a whitelist.txt to include on your binaries and not the other ones in the nupkg.

I'm happy to review any PR's/pipelines

**Comment by tom-englert** [comment]
Starting with version 2.4.7 packages are now signed.
https://github.com/dotnet/DataGridExtensions/commit/71406b90aa5377e3dc38b28f6b0992344cf93f37
