### ISSUE TITLE
Project Support Request: Steeltoe

### ISSUE THREAD

**Issue by TimHess** [dotnet-foundation/projects#109]
- **Project Name:** Steeltoe
- **Due by:** This week, if possible
- **Description:** I/We need access to the node resource group(s) that are automatically created when using AKS. I thought we might be able to get by without this access, but we need it in order to configure network resources. The group name for the current cluster is `MC_Steeltoe_steeltoe-staging_eastus2`. We are planning to add a production cluster in the future after we've validated everything in this cluster, so there will likely be a follow-up request

**Comment by clairernovotny** [comment]
Should be all set now.

**Comment by TimHess** [comment]
Thanks for getting back to me so fast, sorry it took me so long to get back around to validating this update, but it did work. Unfortunately, we weren't able to setup an ingress controller with that cluster due to some apparent bug with the Kubernetes version used, so I ended up deleting that cluster and starting over.

If you could, when you have a chance, I would like access to the new secondary group named `MC_Steeltoe_staging_eastus2.`

Thanks

**Comment by clairernovotny** [comment]
Is there anything left to do for this issue, can we close it out?

**Comment by TimHess** [comment]
Can you provide resource group access to `MC_Steeltoe_staging_eastus2` and `MC_Steeltoe_production_eastus2`? Then I think we'll be all set with this.

**Comment by clairernovotny** [comment]
> Can you provide resource group access to `MC_Steeltoe_staging_eastus2` and `MC_Steeltoe_production_eastus2`? Then I think we'll be all set with this.

Should be all set now.

**Comment by TimHess** [comment]
Excellent, thank you!
