### ISSUE TITLE
New Project Application of Ant Design Blazor

### ISSUE THREAD

**Issue by ElderJames** [dotnet-foundation/projects#114]
## 1.   General Information

**Project Name:** 

Ant Design Blazor

**License:** 

MIT

**Contributor (Company, Organization or individual name(s)):** 

@ElderJames 
@mutouzdl  
@TimChen44 
@zxyao145 
@Brian-Ding 
@Epictek

**Existing OSS Project? (Yes/No):** 

Yes

**Source Code URL:** 

https://github.com/ant-design-blazor/ant-design-blazor

**Project Homepage URL (if different):** 

https://ant-design-blazor.github.io/

**Project Transfer Signatories:**

Will be submitted via e-mail to contact@dotnetfoundation.org.

## 2.   Description

Ant Design Blazor is a set of enterprise-class UI components based on Ant Design and Blazor.

## 3.   Project Governance

**Project Lead:**

Name:   James Yeung
Email:   shunjiey@hotmail.com
GitHub Profile URL: https://github.com/ElderJames

**Committers:**

@ElderJames 
@mutouzdl  
@TimChen44 
@zxyao145 
@Brian-Ding 
@Epictek

**Governance Model:**

Changes are proposed in GitHub Issues, Pull Requests and by discussion in [Discord](https://discord.com/invite/jqu3Xeq) and [DingTalk](https://h5.dingtalk.com/circle/healthCheckin.html?corpId=dingccf128388c3ea40eda055e4784d35b88&2f46=c9b80ba5&origin=11). Changes are reviewed by the core contributors and the community.

New committers are proposed for inclusion in the core team by one of the core members and are subject to votes from existing core members.

**CLA**

No

**CLA Notification Alias**

n/a

**Project Transfer Type**

 Contribution

## 4.   Repository Layout

We already follow the guidelines here.

## 5.  Eligibility Criteria
Please complete the following for your project
* The project is built on the .NET platform and/or creates value within the .NET ecosystem.
- [x] Yes 
- [ ] No
* The project produces source code for distribution to the public at no charge.
- [x] Yes 
- [ ] No
* The project's code is easily discoverable and publicly accessible (preferably on GitHub).
- [x] Yes 
- [ ] No
* The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).
- [x] Yes 
- [ ] No
* When applicable, project must use reproducible build settings in its toolchain.
- [x] Yes 
- [ ] No
* The project uses [Source Link.](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
- [x] Yes 
- [ ] No
* The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).
- [x] Yes 
- [ ] No
* The project code signs their artifacts as appropriate.
- [ ] Yes 
- [ ] No
* The project organization has 2FA enabled. Requiring 2FA must be done as part of onboarding if not already enabled.
- [x] Yes
- [ ] No
* Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).
- [x] Yes 
- [ ] No
* Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.
- [x] Yes 
- [ ] No
* The copyright ownership of everything that the project produces is clearly defined and documented.
- [x] Yes 
- [ ] No
* The project has a public issue tracker where the status of any defect can be easily obtained.
- [x] Yes 
- [ ] No
* The project has a published Security Policy.
- [ ] Yes 
- [x] No
* The project has a home page which provides high level information about its status and purpose.
- [x] Yes 
- [ ] No
* The project has a public communication channel where community members can engage with maintainers.
- [x] Yes 
- [ ] No
* The project has a publicly available location where members can review and contribute to documentation.
- [x] Yes 
- [ ] No

## 6.   PR Plan

That .NET has a set of enterprise-class UI components based on Ant Design and Blazor WebAssembly.

## 7.   Infrastructure Requirements

Hosting space for our website and community would be useful.

## 8.   Additional Notes

We hope to get more support from the ASP.NET team.

**Comment by ChrisSfanos** [comment]
Hi folks - I'll be starting the onboarding process for this project now.  For reference, we will be following the checklist below:

## CLA
- [ ] Project Agreement Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)
- [ ] Enable two-factor authentication (2FA) for GitHub

**Comment by ElderJames** [comment]
OK, Please.

**Comment by ChrisSfanos** [comment]
CLA is out for signing

**Comment by ElderJames** [comment]
How do I do that?

**Comment by ChrisSfanos** [comment]
You should have received an email from DocuSign today. If you didn’t I’ll resend it on monday

________________________________

**Comment by ChrisSfanos** [comment]
CLA Signed
CLA Bot instructions sent

**Comment by ChrisSfanos** [comment]
CLA bot onboard complete - sending the follow up checklist shortly

**Comment by ChrisSfanos** [comment]
Added the project to the next newsletter.  Looks like all onboarding items are complete so closing this down.  Welcome to the .NET Foundation!

**Comment by ElderJames** [comment]
Thank you!
