### ISSUE TITLE
Application for Finbuckle.MultiTenant

### ISSUE THREAD

**Issue by AndrewTriesToCode** [dotnet-foundation/projects#121]
## 1.   General Information

**Project Name:** Finbuckle.MultiTenant

**License:** Apache 2.0

**Contributor (Company, Organization or individual name(s)):** Finbuckle LLC, Andrew White (me), ~10 minor (<100 lines) contributors

**Existing OSS Project? (Yes/No):** Yes

**Source Code URL:** https://github.com/Finbuckle/Finbuckle.MultiTenant

**Project Homepage URL (if different):** https://www.finbuckle.com/MultiTenant

**Project Transfer Signatories:**

Andrew Chandler White, andrew@finbuckle.com

## 2.   Description
**Please provide a brief statement about your project in terms that are understandable to the target consumer of the library or project, i.e. an elevator pitch for the project:**

Finbuckle.MultiTenant is a open source multitenancy library for .NET providing tenant resolution, per-tenant app behavior, and per-tenant data isolation. It includes a variety of "strategies" and other out-of-the-box components, and is highly extendable. Getting started is easy with detailed documentation and sample projects. It supports .NET 5, .NET Core 3.1, and .NET Core 2.1.

**Please provide a 1 sentence (<140 character) summary of your project to help users when searching the .NET Foundation projects**

Finbuckle.MultiTenant is a open source multitenancy library for .NET providing tenant resolution, per-tenant app behavior, and per-tenant data isolation.

## 3.   Project Governance

**Project Lead:**
(Who is the primary contact point for the community and the .NET Foundation when discussing governance of the project.)

Name: Andrew White
 Email: andrew@finbuckle.com
 GitHub Profile URL: https://github.com/AndrewTriesToCode

**Committers:**

Andrew White, @AndrewTriesToCode

**Governance Model:**

A github template for contributions is used. Simple PRs for quick fixes or minor issues are welcomed. Conversations for larger items are encouraged before submitting a PR.

Currently only I have commit access because the bulk of activity is just my own contributions. For any PR I check to ensure 3 things are in place: code, docs, and tests.

**CLA**

No CLA in place except the terms in Apache 2.0 for contributors.

**CLA Notification Alias**
cla@finbuckle.com

**Assignment Model.**  Under the .NET Foundation assignment model, project ownership and other intellectual property is assigned to the .NET Foundation and the .NET Foundation agrees to grantback a license to the contributor(s). 

## 4.   Repository Layout

I don't believe any are needed, but am open to doing so if required.

## 5.  Eligibility Criteria
Please complete the following for your project
* The project is built on the .NET platform and/or creates value within the .NET ecosystem.
- [x] Yes 
- [ ] No
* The project produces source code for distribution to the public at no charge.
- [x] Yes 
- [ ] No
* The project's code is easily discoverable and publicly accessible (preferably on GitHub).
- [x] Yes 
- [ ] No
* The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).
- [x] Yes (dotnet build is all that is needed)
- [ ] No
* When applicable, project must use reproducible build settings in its toolchain.
- [x] Yes 
- [ ] No
* The project uses [Source Link.](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
- [x] Yes (currently prepped for the next release)
- [ ] No
* The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).
- [x] Yes 
- [ ] No
* The project code signs their artifacts as appropriate.
- [ ] Yes 
- [x] No (Need support getting a code signing cert)
* The project organization has 2FA enabled. Requiring 2FA must be done as part of onboarding if not already enabled.
- [x] Yes
- [ ] No
* Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).
- [x] Yes 
- [ ] No
* Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.
- [x] Yes 
- [ ] No
* The copyright ownership of everything that the project produces is clearly defined and documented.
- [x] Yes 
- [ ] No
* The project has a public issue tracker where the status of any defect can be easily obtained.
- [x] Yes 
- [ ] No
* The project has a published Security Policy.
- [x] Yes 
- [ ] No
* The project has a home page which provides high level information about its status and purpose.
- [x] Yes 
- [ ] No
* The project has a public communication channel where community members can engage with maintainers.
- [x] Yes 
- [ ] No
* The project has a publicly available location where members can review and contribute to documentation.
- [x] Yes 
- [ ] No

## 6.   PR Plan

This is an area I could use assistance with. I do have good engagement with my users on GitHub, but I do not have any PR contacts or media connections.

## 7.   Infrastructure Requirements

No major requirements. I would love assistance getting code signing up and running in addition to CI/CD workflows.

## 8.   Additional Notes

I have created an LLC in order to receive GitHub organization sponsorships. I don't think that causes any issues but I want to be fully transparent.

**Comment by ChrisSfanos** [comment]
Hello!  I will be driving the on-boarding process for this project - we will be following the checklist below

## CLA
- [ ] Project Agreement Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)
- [ ] Enable two-factor authentication (2FA) for GitHub

**Comment by ChrisSfanos** [comment]
CLA is out for signing via DocuSign

**Comment by AndrewTriesToCode** [comment]
Hello @ChrisSfanos 

Sorry for the slow response -- my day job has me busy with the new year. I will review the CLA shortly. Is the copyright assignment model the only option used for projects at this point?

**Comment by ChrisSfanos** [comment]
Hey @AndrewTriesToCode  - no worries 👍 
Yes it is the only model at this point

**Comment by ChrisSfanos** [comment]
Hi @AndrewTriesToCode - have you had an opportunity to review the CLA? - thanks!

**Comment by AndrewTriesToCode** [comment]
Hi Cheia, thanks for checking up. I’ll admit I’ve hesitated in part due to the copyright assignment but I’ve come to terms with that and am ready to sign. I’ve also been working in parallel to incorporate CI/CD for the project and a blog section for the website. I felt like I wanted to get those I. Order before moving forward and I think I’m there. I will sign the CLA later today. 

I have a few people with pending PRs that we will want to also sign it.

Question, at what point are things official? The CLA or a subsequent step?

Thanks,
Drew

**Comment by ChrisSfanos** [comment]
Hi Drew
Once the CLA is signed, it's basically official at that point.  There is remaining steps to wrap up, but I'd consider it official after the CLA

**Comment by AndrewTriesToCode** [comment]
@ChrisSfanos
As you saw there's a discussion going on in another thread about the copyright model -- sorry to get you dragged in over there. Claire indicated there is upcoming guidance on this issue so I'm going to wait on that. Thanks for your help with everything so far!

**Comment by ChrisSfanos** [comment]
Sounds good 👍

________________________________

**Comment by AndrewTriesToCode** [comment]
@ChrisSfanos

Can you please modify the CLA pending my signature to use the contribution model instead of the assignment model?

**Comment by ChrisSfanos** [comment]
Yes - I can revoke the existing agreement and resend.  Not that @clairernovotny may not be available promptly due to some time away

**Comment by ChrisSfanos** [comment]
Update CLA is now out for signing

**Comment by AndrewTriesToCode** [comment]
@ChrisSfanos thanks I have signed the document. What's next?

**Comment by ChrisSfanos** [comment]
Claire is out on leave, so I need to see if I can get her to sign.  In the meantime, I'll go ahead and send you the on-boarding CLA bot steps and other work items in a bit

**Comment by ChrisSfanos** [comment]
CLA bot instructions sent

**Comment by ChrisSfanos** [comment]
CLA bot onboarding is complete - I've sent the remaining work items to complete the process

**Comment by AndrewTriesToCode** [comment]
Thanks!

**Comment by AndrewTriesToCode** [comment]
@ChrisSfanos I took a little longer to figure some things out. At this point I believe I have everything done except for adding the copyright headers. Since I used the contribution model and didn't assign the copyright to the .NET Foundation is seems that this step is not needed?

I just submitted a PR to the dotnet foundation website to add the project: [PR-927](https://github.com/dotnet-foundation/website/pull/927)

Also I am not sure if I am on the project-leader mailing list -- how can I check that?

**Comment by ChrisSfanos** [comment]
Thanks for submitting the PR - marking it off as complete as it looks correct.  As for the mailing list, just trying adding yourself (again) just in case.  Looks like the README updates for the .NET Foundation aren't there yet.  As for the headers you are ok

**Comment by AndrewTriesToCode** [comment]
Thank you @ChrisSfanos 

Is this the guidance on additions needed in the readme file? I couldn't find anything else
https://github.com/dotnet-foundation/foundation/blob/master/guidance/readme-guide.md

Those guidance documents don't appear to be linked to from anywhere and are located in an archived repo. Or is there another document I should be looking at?

**Comment by AndrewTriesToCode** [comment]
Ok I just found the original email you provided with the details... I'll get the readme updated later today and I think that is our last checklist item.

**Comment by ChrisSfanos** [comment]
last action item is wrapped up - closing this work item out :-)
