### ISSUE TITLE
Code Signing Certificate Request: .NET nanoFramework

### ISSUE THREAD

**Issue by josesimoes** [dotnet-foundation/projects#123]
### Please fill in the information below

- **Project Name:** .NET nanoFramework
- **LastPass Email (or send offline):** nanoframework@outlook.com

Would like to provide signed packages for our VS extensions and NuGet packages.
(not 100% sure that this is the correct issue template...)

Certificate onboarding checklist:

- [x] Register trade name @ChrisSfanos
- [x] Create configuration in Code Signing Service
- [x] Create organization with DigiCert
- [x] Request certificate from DigiCert
- [x] Received certificate and finalize sign service configuration
- [x] Provide credentials in shared folder in LastPass

**Comment by ChrisSfanos** [comment]
Trade Name registration has been submitted

**Comment by clairernovotny** [comment]
I just invited you to the shared LastPass where the cert is setup and configured.

Few things:
1. Here's a template of how to add code signing to the build pipeline: https://github.com/novotnyllc/CodeSigningDemo
2. Once signing is configured, please add `dotnetfoundation` as a co-owner in NuGet. 
3. If you have any 3rd party binaries in your packages, you'll need a whitelist.txt to include on your binaries and not the other ones in the nupkg.

I'm happy to review any PR's/pipelines

**Comment by josesimoes** [comment]
Thanks!

We have this setup now. 
As the project publishes a bunch of NuGet I'm adding the signing to each one as the repo is touched.

@clairernovotny as a side note: I had to grab the certificate from the signed nupkg and upload it to NuGet.org, otherwise NuGet was refusing to accept the signed packages being published through the command line.

**Comment by clairernovotny** [comment]
Hi @josesimoes the solution to this is to add `dotnetfoundation` as a co-owner to the NuGet packages. This is required for continuity reasons too. Can you please take care of that? We have all of the public certs attached to our NuGet org.

Thanks!

**Comment by josesimoes** [comment]
> Hi @josesimoes the solution to this is to add `dotnetfoundation` as a co-owner to the NuGet packages. This is required for continuity reasons too. Can you please take care of that? We have all of the public certs attached to our NuGet org.
> 
I did that... still it complained about it...

**Comment by clairernovotny** [comment]
I don't see the package ownership request. I have to accept it on my end too. On NuGet.org, if you go to Manage Package 
![image](https://user-images.githubusercontent.com/1427284/102547999-03e4fa80-4088-11eb-86c5-9ee40419d19f.png)
 Under owners, you can add
![image](https://user-images.githubusercontent.com/1427284/102548030-0e06f900-4088-11eb-93fc-a688a0e2aa14.png)

You do need to do it for each package as NuGet doesn't have bulk operations, but you only need to do it once per package.

**Comment by josesimoes** [comment]
🤔  I was under the impression that that co-ownership would happen automatically when adding the dotnetfoundation user to the package metadata...

**Comment by clairernovotny** [comment]
Unfortunately that's not secure.... because it's not authenticated. Package ownership stuff has to be done on the website. I just accepted the one for `nanoFramework.Networking.Sntp`

**Comment by josesimoes** [comment]
Got you! 
I'll go ahead and do that to the other packages too.

PS: maybe it's a lack of understanding from my end, but it wasn't clear to me that the package co-ownership had to be handled on the NuGet website. Suggest that this is made clearer on the instructions. 😉

**Comment by josesimoes** [comment]
OK just did that for all our packages. You now have a long queue of requests! 😄

**Comment by clairernovotny** [comment]
All set now. And the UX for approving them isn't any better 😅
