### ISSUE TITLE
Project Spotlight Request: ResX Resource Manager

### ISSUE THREAD

**Issue by tom-englert** [dotnet-foundation/projects#126]
## General Information

**Project Name:**
```
ResX Resource Manager
```
**Contributor (Company, Organization or individual name(s)):**
```
Tom Englert
```
**Source Code URL:**
```
https://github.com/dotnet/ResXResourceManager
```
**Documentation URL:**
```
https://github.com/dotnet/ResXResourceManager/tree/master/Documentation
```
**Contribution URL:**
```
https://github.com/dotnet/ResXResourceManager/issues
```
**Project Homepage URL (if different):**
```
```
**Please provide a brief statement about your project in terms that are understandable to the target consumer of the library or project, i.e. an elevator pitch for the project:**
```
The most popular tool to manage localization of all kind of applications with resx-based resources; 
one of the highest rated extensions on the Visual Studio Marketplace.
```
**Please list 5 top non-maintainer contributors to your project**
```
yinyue200
mkaring
solomon-okolie
DominickM324
DJmRek
```
**Month you would prefer to be featured**
```
No preference
```
**Timeline when to conduct a short interview**
```
No preference
```

**Comment by isaacrlevin** [comment]
@tom-englert we would love for ResX Resource Manager to be the featured project for April. Can you please let me know of some date/times you would be available for a 10-15 minute interview?

**Comment by tom-englert** [comment]
@isaacrlevin since I'm in the UTC+1 time zone 5pm-8pm would probably the best time slot. Except for Thursday 15. any day should be fine.

**Comment by isaacrlevin** [comment]
How about this Friday (16/4/2021) at 6 PM your time?

**Comment by tom-englert** [comment]
@isaacrlevin Friday will be fine. Do I have to prepare something?

**Comment by isaacrlevin** [comment]
No prep, just going to talk about the project, no demo. Can I have an email I can send the meeting invite to.

**Comment by tom-englert** [comment]
mail@tom-englert.de

**Comment by tom-englert** [comment]
@isaacrlevin what about the state of this? 
Just published ResXManager with VS2022 support, so might be a good time for a spotlight.

**Comment by isaacrlevin** [comment]
@BethMassi can we have the .NET Foundation Twitter Handle promote this? Maybe something like

"ResXManager now supports @VisualStudio 2022. Learn more from Marketing Comittee member @isaacrlevin chat with Tom Englert, creator of ResXManager about his project
https://dotnetfoundation.org/projects/spotlight?project=ResX%20Resource%20Manager"

**Comment by BethMassi** [comment]
Yep. @ddskier can you queue this up?

**Comment by ddskier** [comment]
Posted it just now on all channels (Twitter, LinkedIn, FB) and repeating it on Aug 3.
