### ISSUE TITLE
Project Support Request: [NuGet Trends] - Sentry GitHub App access to repository

### ISSUE THREAD

**Issue by bruno-garcia** [dotnet-foundation/projects#128]
### Please fill in the information below:
- **Project Name:** NuGet Trends
- **Due by:** Eventually please.
- **Description:** 

[NuGet Trends](https://github.com/dotnet/nuget-trends) uses [Sentry](http://sentry.io/) to monitor errors. [Sentry has a GitHub app](https://github.com/apps/sentry-io) to connect to the repo to get commit data and releases. It uses that to show what commit likely caused the bug among other features.

Could we please give access to the GitHub app for this repo? `dotnet/nuget-trends`:

I've made the request through GitHub:
![image](https://user-images.githubusercontent.com/1633368/100147957-104fac00-2e6a-11eb-87b5-e9e2e8f82a82.png)

**Comment by clairernovotny** [comment]
I installed it and granted it permission to your repo

**Comment by bruno-garcia** [comment]
@clairernovotny I could see the repo was allowed but somehow it didn't go through.
Do you mind removing the repo and adding it back again please?

I tried to do that but I can't:

![image](https://user-images.githubusercontent.com/1633368/100171805-fd060600-2e94-11eb-8eae-c70f40d6004a.png)

**Comment by clairernovotny** [comment]
I removed and re-added it to your repo.

**Comment by bruno-garcia** [comment]
Thank you again @clairernovotny !

**Comment by bruno-garcia** [comment]
@clairernovotny I'm sorry but I didn't know that to add an integration you must be a member of both the the GitHub org and the Sentry org when you go through the add integration flow.

Here there's a video that shows how it's done (takes 30 seconds):
https://drive.google.com/file/d/1znxllMqSmJRuCC0bNys-aXERMTQfduWK/view?usp=sharing

I would send invite you in to the sentry.io NuGet Trends org. 
Would that be OK with you?

**Comment by ChrisSfanos** [comment]
Issue cleanup - I'm guessing this is no longer an issue?  If so, please create a new issue or re-open - thanks!
