### ISSUE TITLE
Project Support Request: [Cake] LastPass Subscription

### ISSUE THREAD

**Issue by gep13** [dotnet-foundation/projects#129]
# Please fill in the information below:
- **Project Name:** Cake
- **Due by:** No immediate rush
- **Description:**

When the Cake Team joined the .Net Foundation, we were offered LastPass Subscriptions for all team members.  This is used to share login details across the team.

The core team has expanded, and we are in need of 2 additional LastPass subscriptions, so that everyone on the team can have access to the shared details.

Is this something that can be helped with?  Thanks

**Comment by gep13** [comment]
@clairernovotny just wanted to follow up with regard to this request.  Do you require any additional information? Thanks

**Comment by pascalberger** [comment]
In the meantime we have additional maintainers and are in need of 4 additional subscriptions.

**Comment by gep13** [comment]
@clairernovotny would it be possible to get some feedback on whether this is going to be possible?

If it isn't, we can start looking into an alternative to ensure that all Cake Team members have access to all team related credentials.

**Comment by clairernovotny** [comment]
Hi, apologies for the delay, this got caught up in the holiday chaos. Please email me the addresses of the people you'd like to add.

**Comment by gep13** [comment]
@clairernovotny I have sent an email as requested.  Let me know if you have any questions, thanks.

**Comment by gep13** [comment]
@clairernovotny thank you very much for your help here, appreciate it.
