### ISSUE TITLE
Creation of Resource Group in Azure Sponsorship

### ISSUE THREAD

**Issue by mitchelsellers** [dotnet-foundation/projects#13]
As we are working on resources inside of the Sponsorship Azure account we would like to create two resource groups to help group/manage assets, however, I don't have permission to create resource groups for the DNN Platform Project.  Could we get the following two Resource Groups added

DNN-UpdateService
DNN-Community

**Comment by mitchelsellers** [comment]
Just checking back in on this

**Comment by jongalloway** [comment]
Added both, with you as owner. Closing as fixed, re-open if there's a problem.
