### ISSUE TITLE
OpenMod Project Application

### ISSUE THREAD

**Issue by Trojaner** [dotnet-foundation/projects#132]
## 1.   General Information

**Project Name:** OpenMod

**[License](https://github.com/openmod/openmod/blob/main/LICENSE):**
- OpenMod Framework: MIT
- OpenMod Documentation: **Creative Commons Attribution 4.0 International** (CC BY 4.0)

**Contributor:** Enes Sadık Özbek (@Trojaner)

**Existing OSS Project? (Yes/No):** Yes

**Source Code URL:** https://github.com/openmod/openmod

**Project Homepage URL (if different):** https://openmod.github.io/openmod-docs

**Project Transfer Signatories:**
Enes Sadık Özbek - es.ozbek@outlook.com

## 2.   Description
**Please provide a brief statement about your project in terms that are understandable to the target consumer of the library or project, i.e. an elevator pitch for the project:**
OpenMod is a .NET based plugin framework. It supports authorization, hotreloading, plugin configurations, internalization, command handling and much more. OpenMod can be used for games, bot frameworks, web servers or anything else that needs plugin functionality.

**Please provide a 1 sentence (<140 character) summary of your project to help users when searching the .NET Foundation projects**
OpenMod .NET plugin framework. 

## 3.   Project Governance
**Project Lead:**
Name:   Enes Sadık Özbek
 Email:   es.ozbek@outlook.com
 GitHub Profile URL: @Trojaner

**Committers:**
@DiFFoZ @IAmSilK @rube200 @CyberAndrii are part of the team. We also have [some external contributors](https://github.com/openmod/openmod/graphs/contributors). 

**Governance Model:**
We have a [contributing guideline](https://github.com/openmod/openmod/blob/main/CONTRIBUTING.md). New changes should be proposed and discussed on our issue tracker first. Acceptance depends on if the proposed changes are within the scope of the project and if the implementation meets the criteria in our guidelines. Aside CLA, builds and tests, all PR's must pass manual code review, [LGTM analysis](https://lgtm.com/projects/g/openmod/openmod/) and not introduce new CodeQL alerts.

**CLA**
[cla-assistant](https://cla-assistant.io/) is used since day one with its standard SAP Individual Contributor License Agreement.

**CLA Notification Alias**
Provide an email address that will receive CLA related notifications from the .NET Foundation CLA automation
es.ozbek@outlook.com

**Project Transfer Type**
[ ] Assignment
[x] Contribution

## 4.   Repository Layout
[Our repository](https://github.com/openmod/openmod) is well structured and using the mono repository pattern. [Documentation](https://openmod.github.io/openmod-docs/) resides in [its owns own repository](https://github.com/openmod/openmod-docs).  We also maintain a list of plugins [here](https://github.com/openmod/openmod-plugins).

## 5.  Eligibility Criteria
Please complete the following for your project
* The project is built on the .NET platform and/or creates value within the .NET ecosystem.
- [x] Yes 
- [ ] No
* The project produces source code for distribution to the public at no charge.
- [x] Yes 
- [ ] No
* The project's code is easily discoverable and publicly accessible (preferably on GitHub).
- [x] Yes 
- [ ] No
* The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).
- [x] Yes - The GitHub workflow files are public and describe the build process.
- [ ] No 
* When applicable, project must use reproducible build settings in its toolchain.
- [x] Yes - Builds are published via GitHub actions, there is no manual publishing process
- [ ] No
* The project uses [Source Link.](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
- [x] Yes - It is added but currently broken due to [a bug in RuntimeNullables](https://github.com/Singulink/RuntimeNullables/issues/5)
- [ ] No
* The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).
- [x] Yes
- [ ] No
* The project code signs their artifacts as appropriate.
- [ ] Yes 
- [x] No - needs to be arranged.
* The project organization has 2FA enabled. Requiring 2FA must be done as part of onboarding if not already enabled.
- [x] Yes
- [ ] No 
* Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).
- [x] Yes - Some exceptions such as game binaries exist
- [ ] No
* Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.
- [x] Yes 
- [ ] No
* The copyright ownership of everything that the project produces is clearly defined and documented.
- [x] [Yes](https://github.com/openmod/openmod/blob/main/LICENSE)
- [ ] No
* The project has a public issue tracker where the status of any defect can be easily obtained.
- [x] [Yes](https://github.com/openmod/openmod/issues)
- [ ] No
* The project has a published Security Policy.
- [x] [Yes](https://github.com/openmod/openmod/blob/main/SECURITY.md)
- [ ] No
* The project has a home page which provides high level information about its status and purpose.
- [x] [Yes](https://github.com/openmod/openmod) 
- [ ] No
* The project has a public communication channel where community members can engage with maintainers.
- [x] Yes - Discord and the issue tracker
- [ ] No
* The project has a publicly available location where members can review and contribute to documentation.
- [x] [Yes](https://github.com/openmod/openmod/tree/main/docs) 
- [ ] No

## 6.   PR Plan
There is not much PR wise. The first thing we would do is publish an announcement on our Discord server and repository.

## 7.   Infrastructure Requirements
Please describe any infrastructure requirements for the project. For example, how will build servers be operated? Any web hosting or service hosting requirements? Do we need to set up SSL certificates or provide Authenticode Code Signing arrangement for releases?
- At the moment we are using GitHub Actions for our build and deployment processes. We may switch to Azure Pipelines. 
- A code signing certificate.
- A public NuGet feed for nightly builds (e.g. Azure Artifacts)

## 8.   Additional Notes
OpenMod's main goal is to provide a unviversal plugin API especially targeting .NET based game servers such as Unity games. However, through abstractions and clean separation it is also a generic framework that can be used for other purposes such as web servers or bot frameworks. It provides a user system, hotreloading, permissions, plugin configurations, i18n, commands, eventing, NuGet integration, IoC  & DI, and a lot of other boilerplate code.

**Comment by Trojaner** [comment]
Hello, what's the latest status of our application?

**Comment by sbwalker** [comment]
@Trojaner The Project Committee reviewed the application in February and there were concerns about the licensing. Although the license is permissive, it is not a standard OSI license and has a specific jurisdiction clause which would be challenging for the .NET Foundation to support. As a result the application was placed in the "On Hold" category. Please feel free to share any additional information you may have related to this topic. Note that the Project Committee meeting notes are all posted publicly here: https://github.com/orgs/dotnet-foundation/teams/projects

**Comment by Trojaner** [comment]
Thank you for your quick answer. 

Although the EUPL is a less known license, it is a license that is both listed on [OSI](https://opensource.org/licenses/alphabetical) and also (acknowledged as free license by the Free Software Foundation)[https://www.fsf.org/blogs/licensing/european-union-public-license-v-1-2-added-to-license-list]. However, it is a copyleft license similar to the GPL license. We could change the license to a less restrictive license like MIT or Apache if this is an issue.

Sadly I cannot access the link you have posted, it redirects to a 404 page.

**Comment by sbwalker** [comment]
Currently the .NET Foundation does not accept projects licensed under copy-left restrictions. In addition, the clause in the EUPL I was referring to was "this licence shall be governed by Belgian law if the Licensor has no seat, residence or registered office inside a European Union Member State." - which would be very challenging for the .NET Foundation to support. If you are willing/able to transition the project to a more standard permissive license it would address the concerns of the Foundation. I am not sure why you cannot access the link above - if you are a member of the .NET Foundation you are supposed to be able to view it. The meeting notes are also posted here: https://github.com/dotnet-foundation/projects/tree/master/meetings

**Comment by Trojaner** [comment]
I am currently not a member of the .NET Foundation. We are willing to change the license and will let you know when it is done. Thank you.

**Comment by Trojaner** [comment]
Hello,
We have changed the license to MIT.
https://github.com/openmod/openmod/blob/main/LICENSE

**Comment by sbwalker** [comment]
Yesterday the .NET Foundation BOD voted to approve this project for Membership in the .NET Foundation. @ChrisSfanos will reach out to you shortly to initiate the onboarding process.

**Comment by ChrisSfanos** [comment]
Hello!  We will be following the following checklist to onboard your project to the .NET Foundation.  I'll post updates here as we move along

## CLA
- [ ] Project Agreement Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)
- [ ] Enable two-factor authentication (2FA) for GitHub organization and all users

**Comment by ChrisSfanos** [comment]
Project transfer agreement is out for signing

**Comment by ChrisSfanos** [comment]
Thanks - I'll send instructions on the CLA process tomorrow

**Comment by ChrisSfanos** [comment]
CLA onboarding step sent out via email

**Comment by ChrisSfanos** [comment]
Onboarding is complete - welcome OpenMod to the .NET Foundation!
