### ISSUE TITLE
Project Support Request: Accessibility help for Avalonia

### ISSUE THREAD

**Issue by grokys** [dotnet-foundation/projects#138]
### Please fill in the information below:
- **Project Name:** Avalonia
- **Due by:** n/a
- **Description:** The Avalonia UI framework is currently trying to add support for Accessibility using the MS UI Automation API. This API is ahem... quirky... and we're experiencing problems getting stuff to work. Would it be possible to put us in touch with someone from the Windows Accessibility team who could give us some pointers?

**Comment by ChrisSfanos** [comment]
Issue cleanup - please create a new issue or re-open as needed - thanks!
