### ISSUE TITLE
New .NET Foundation Project Application: .NEXT

### ISSUE THREAD

**Issue by sakno** [dotnet-foundation/projects#139]
## 1.   General Information

**Project Name:** .NEXT Raft

**License:** MIT

**Contributor (Company, Organization or individual name(s)):** Roman Sakno (rvsakno@outlook.com)

**Existing OSS Project? (Yes/No):** Yes

**Source Code URL:** https://github.com/sakno/dotNext

**Project Homepage URL (if different):** https://sakno.github.io/dotNext/index.html

**Project Transfer Signatories:** Roman Sakno (rvsakno@outlook.com)

## 2.   Description
A framework for building clustered and replicated microservices in .NET on top of Raft consensus algorithm.

## 3.   Project Governance
**Project Lead:**

Name:   Roman Sakno
 Email:   rvsakno@outlook.com
 GitHub Profile URL: https://github.com/sakno

**Governance Model:**
* Community members submit pull requests which are reviewed by the core committers
* Anyone can become a contributor if he doing PRs and reviews on regular basis

**CLA**

This project would like to utilize the .NET Foundation CLA system

**CLA Notification Alias**
rvsakno@outlook.com

**Assignment Model.**  Under the .NET Foundation assignment model, project ownership and other intellectual property is assigned to the .NET Foundation and the .NET Foundation agrees to grantback a license to the contributor(s). 

**Contribution Model.**  Under the .NET Foundation contribution model, a project retains ownership of the project, but grants the .NET Foundation a broad license to the project’s code and other intellectual property. The project also confirms that the project’s submissions to .NET Foundation are its own original work (there are also instructions for any third party materials that might be included).

## 4.   Repository Layout
Partially satisfies to [https://github.com/dotnet/home/tree/master/guidance](https://github.com/dotnet/home/tree/master/guidance). 

TODO:
* Code of Conduct
* File headers

## 5.  Eligibility Criteria
Please complete the following for your project
* The project is built on the .NET platform and/or creates value within the .NET ecosystem.
- [X] Yes 
- [ ] No
* The project produces source code for distribution to the public at no charge.
- [X] Yes 
- [ ] No
* The project's code is easily discoverable and publicly accessible (preferably on GitHub).
- [X] Yes 
- [ ] No
* The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).
- [X] Yes 
- [ ] No
* When applicable, project must use reproducible build settings in its toolchain.
- [X] Yes 
- [ ] No
* The project uses [Source Link.](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
- [X] Yes 
- [ ] No
* The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).
- [X] Yes 
- [ ] No
* The project code signs their artifacts as appropriate.
- [X] Yes 
- [ ] No
* The project organization has 2FA enabled. Requiring 2FA must be done as part of onboarding if not already enabled.
- [ ] Yes
- [X] No
* Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).
- [X] Yes 
- [ ] No
* Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.
- [X] Yes 
- [ ] No
* The copyright ownership of everything that the project produces is clearly defined and documented.
- [X] Yes 
- [ ] No
* The project has a public issue tracker where the status of any defect can be easily obtained.
- [X] Yes 
- [ ] No
* The project has a published Security Policy.
- [ ] Yes 
- [X] No
* The project has a home page which provides high level information about its status and purpose.
- [X] Yes 
- [ ] No
* The project has a public communication channel where community members can engage with maintainers.
- [X] Yes 
- [ ] No
* The project has a publicly available location where members can review and contribute to documentation.
- [X] Yes 
- [ ] No

## 6.   PR Plan
Need assistance with this. 

## 7.   Infrastructure Requirements
No special requirements. Currently, project uses Azure Pipelines for running tests on Windows and Linux.

## 8.   Additional Notes
Currently, .NEXT Raft is a part of .NEXT family of libraries and located in the same repository with other libraries. Should I move .NEXT Raft to dedicated repository? Or it's reasonable to submit entire .NEXT project which provides additional value to .NET developers besides development of clustered microservices.

**Comment by ChrisSfanos** [comment]
Hello everyone - I will be working to onboard the project - we will use the following checklist

## CLA
- [ ] Project Agreement Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)
- [ ] Enable two-factor authentication (2FA) for GitHub

**Comment by sakno** [comment]
@ChrisSfanos , is there any direct involvement expected from my side?

**Comment by ChrisSfanos** [comment]
Hi @sakno - yes, definitely.  I emailed you about which model you'll bring the project to the .NET Foundation under.  With that, I'll generate a CLA which you will need to sign
After that, there is work for the CLA bot and then the majority of Project Onboarding steps listed above are for you to follow (I'll be sending a mail on extra details for those steps when it's time to work on those)

**Comment by ChrisSfanos** [comment]
Transfer agreement is out for signing via DocuSign

**Comment by sakno** [comment]
@ChrisSfanos , I have signed document via DocuSign, what's next?

**Comment by ChrisSfanos** [comment]
Email will be coming out shortly with the next steps - thanks!

**Comment by ChrisSfanos** [comment]
PR submitted for the project entry, which was the last open item.  Closing this work item out :-)
