### ISSUE TITLE
Creation of an Email Distribution List

### ISSUE THREAD

**Issue by mitchelsellers** [dotnet-foundation/projects#14]
If we could get an email distribution list setup for the DNN Platform project.

The immediate need is for security@dnncommunity.org that sends all received email to security@dnnsecurity.atlassian.net it would be great.

We have control of DNS to help support any changes here

**Comment by mitchelsellers** [comment]
Checkin gon this one as well

**Comment by jongalloway** [comment]
Started setup, need a TXT record added to verify domain ownership to create e-mail addresses for dnncommunity.org:

TXT name: | @ or skip if not supported by provider.
TXT value: | MS=ms20755896
TTL: | 36003600 or your provider default.

[docs link on domain verification](https://docs.microsoft.com/en-us/office365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider?redirectSourcePath=%252farticle%252f7b7b075d-79f9-4e37-8a9e-fb60c1d95166&view=o365-worldwide#BKMK_verify)

**Comment by mitchelsellers** [comment]
@jongalloway Record added

**Comment by jongalloway** [comment]
@mitchelsellers Okay, hopefully the last step - it says you need to add the following MX, CNAME, and TXT record to DNS to finish setup. Zip contains a CSV file with info and a zone file if your DNS provider has support to import that. 

After that's set up, O365 will have dnncommunity.org set up as a supported domain so we can add any DL's you want very quickly going forward.

[dnncommunity.org.zone.zip](https://github.com/dotnet-foundation/projects/files/3708503/dnncommunity.org.zone.zip)

**Comment by david-poindexter** [comment]
@jongalloway and @mitchelsellers - I'll get these added as soon as possible.  Thanks!

**Comment by jongalloway** [comment]
I've set up security@dnncommunity.org that forwards to security@dnnsecurity.atlassian.net

@david-poindexter & @mitchelsellers: I think the main reason for the additional DNS settings are to make sure e-mails aren't flagged as spam. So it should probably work already if you want to test it.

**Comment by david-poindexter** [comment]
@jongalloway thanks!  All DNS records have now been added.

**Comment by jongalloway** [comment]
@david-poindexter @mitchelsellers Can one of you send an e-mail to security@dnncommunity.org and verify that it is delivered to security@dnnsecurity.atlassian.net. Once that's verified we can close this out.

**Comment by david-poindexter** [comment]
@jongalloway I sent a test email and received a confirmation of receipt.

**Comment by mitchelsellers** [comment]
Looks good for now!  Thanks, everyone!
