### ISSUE TITLE
Project Support Request: Avalonia

### ISSUE THREAD

**Issue by grokys** [dotnet-foundation/projects#140]
### Please fill in the information below:
- **Project Name:** Avalonia
- **Due by:** N/A
- **Description:** As suggested [here](https://github.com/dotnet-foundation/projects/issues/1#issuecomment-663937413), could you add dependabot as an allowed user for the cla bot in the AvaloniaUI org please?

**Comment by grokys** [comment]
ping: any chance of getting this resolved?

**Comment by worldbeater** [comment]
@jongalloway wouldn't it be too much to ask you for help with adding dependabot to the allowlist here? 🥺
Also probably worth adding that bot to the global allow list, according to the `cla-assistant` docs https://github.com/cla-assistant/cla-assistant/blob/master/src/client/modals/templates/allowlist_info.html#L11-L18

**Comment by clairernovotny** [comment]
I thought we fixed the CLA bot to allow all bots. I've updated the entry to fix it for Avalonia explicitly.
