### ISSUE TITLE
Code Signing Certificate Request: Silk.NET

### ISSUE THREAD

**Issue by Perksey** [dotnet-foundation/projects#147]
Follow up from #115:

### Please fill in the information below

- **Project Name:** Silk.NET
- **LastPass Email (or send offline):** dylan@ultz.co.uk (note: currently not setup with LastPass)

Certificate onboarding checklist:

- [x] Register trade name @ChrisSfanos
- [x] Create configuration in Code Signing Service
- [x] Create organization with DigiCert
- [x] Request certificate from DigiCert
- [x] Received certificate and finalize sign service configuration
- [x] Provide credentials in shared folder in LastPass

**Comment by ChrisSfanos** [comment]
Trade name registration submitted this morning

**Comment by clairernovotny** [comment]
Hi @Perksey Sorry for the long delay. There were some hiccups with DigiCert due to some baseline requirements changing. We have the certificate up and configured. Can you please set up with LastPass and I can share the credentials with you?

**Comment by Perksey** [comment]
No worries! LastPass account created, let me know if you need me to do anything else.

**Comment by clairernovotny** [comment]
Just shared the folder with the credentials.

![image](https://user-images.githubusercontent.com/1427284/124651841-6efdef00-de69-11eb-8975-52d0fc785deb.png)

There's a sample pipeline here: https://github.com/novotnyllc/CodeSigningDemo

**Comment by Perksey** [comment]
Brill, thanks!

**Comment by clairernovotny** [comment]
Once you have your Pipeline configured, please add `dotnetfoundation` as a co-owner to any NuGet packages. The certificate will be recognized by NuGet then.

**Comment by Perksey** [comment]
Hi Claire,

Is there any way to achieve this without adding `dotnetfoundation` as an owner?

Currently we use an organisation API key to push our packages which has rights to use our reserved prefix, and there's no NuGet REST API to add an owner to a package programmatically. Given that our library sources are mostly generated, it would mean that we'd have to manually go through our packages (in case the generator has created new ones) and add the org as an owner - something that could be time consuming given it can't be automated.

Could we add the certificate to our own organisation, and perhaps add a .NET Foundation account as one of the owners of the `Silk.NET` organisation? Another option would be contacting NuGet support to add `dotnetfoundation` as an organisation permitted to use our prefix, and then using a `dotnetfoundation` API key to push our packages. Still some manual package owner modification involved, but at least then it's only once.

**Comment by Perksey** [comment]
Will reopen until the above is resolved.

**Comment by clairernovotny** [comment]
The foundation requires co-ownership in NuGet regardless. Once a package has dotnetfoundation as a co-owner, subsequent updates are automatically carried forward.

**Comment by Perksey** [comment]
More than happy with the foundation having ownership of the packages, but from a practicality standpoint we have 163 NuGet packages so any ownership modification would ideally be at the organisation level (i.e. giving a foundation-owned account ownership of the `Silk.NET` organisation)

Given that NuGet has no public API endpoints for modifying package ownership, any individual package-level ownership modifications would take a very long time given we have 163 of them!

I'm fine with having to update the certificate on our organisation too (less seamless of course) but I understand that the foundation needs ownership for administration purposes as well. Is there an equivalent of the `dnfadmin` GitHub account for NuGet i.e. an individual non-organisation account we can grant ownership of the organisation to?

**Comment by clairernovotny** [comment]
I agree that 163 packages is a lot, and it's equally painful on the accepting side....  I can start an email thread with the NuGet team to see what they can do. 

We don't have individual accounts like that as that's generally an anti-pattern and not the best for security.

**Comment by Perksey** [comment]
That'd be great, thanks!

**Comment by clairernovotny** [comment]
As a short term workaround (as per the email thread), you can save the cert as a DER-encoded .cer file and then register that on the account you're currently using. That'll let you publish the signed packages.

**Comment by Perksey** [comment]
Will keep this issue open until we do manage to get the package ownership transferred, but will use that workaround in the meantime. Thanks!

**Comment by clairernovotny** [comment]
Hi, @Perksey I know it took much longer than expected to address the package ownership issues on NuGet. Now that it's resolved, how is this coming; are you all set here, can we close this issue?

**Comment by Perksey** [comment]
Yep, now that’s solved this can be closed off - forgot to update this issue, sorry!

Thanks for all of your help :)
