### ISSUE TITLE
AspNet Boilerplate

### ISSUE THREAD

**Issue by ismcagdas** [dotnet-foundation/projects#150]
## 1.   General Information

**Project Name:**

AspNet Boilerplate

**License:**

MIT

**Contributor (Company, Organization or individual name(s)):**

* [Halil İbrahim KALKAN](https://github.com/hikalkan)
* [Ismail CAGDAS](https://github.com/ismcagdas)
* [Aaron Chong](https://github.com/acjh)
* [Ryan Chang](https://github.com/ryancyq)
* [Musa Demir](https://github.com/demirmusa)
* [Ali Rıza Adıyahşi](https://github.com/alirizaadiyahsi)
* [Li Ming Ma](https://github.com/maliming)
* [Alper Ebicoglu](https://github.com/ebicoglu)

**Existing OSS Project? (Yes/No):**

Yes

**Source Code URL:**

https://github.com/aspnetboilerplate/aspnetboilerplate

**Project Homepage URL (if different):**

https://aspnetboilerplate.com/

**Project Transfer Signatories:**

Will be shared with contact@dotnetfoundation.org

## 2.   Description
ASP.NET Boilerplate is a general purpose application framework specially designed for new modern web applications. It uses already familiar tools and implements best practices around them to provide you a SOLID development experience. ASP.NET Boilerplate works with the latest ASP.NET Core & EF Core but also supports ASP.NET MVC 5.x & EF 6.x as well.

Web application framework with a strong infrastructure for modern web applications

## 3.   Project Governance
Please complete this section about who will be maintaining the open source project and how it will run.
**Project Lead:**

Name:   Halil İbrahim KALKAN
 Email:   will be shared via email
 GitHub Profile URL: https://github.com/hikalkan

**Committers:**

* [Halil İbrahim KALKAN](https://github.com/hikalkan)
* [Ismail CAGDAS](https://github.com/ismcagdas)
* [Musa Demir](https://github.com/demirmusa)
* [Li Ming Ma](https://github.com/maliming)
* [Alper Ebicoglu](https://github.com/ebicoglu)

**Governance Model:**

Direct commit to the repository is closed for all developers. Because of that, new code changes must be introduced with pull requests. When a PR is opened, one of the developers in Committers section can approve the PR and merge changes to the dev branch. The reviewer checks the code quality, unit tests and evaluates the PR according to these criterias.

**CLA**

There is no CLA at the moment.

**CLA Notification Alias**
aspnetboilerplate@volosoft.com

**Assignment Model.**  Under the .NET Foundation assignment model, project ownership and other intellectual property is assigned to the .NET Foundation and the .NET Foundation agrees to grantback a license to the contributor(s). 

**Contribution Model.**  Under the .NET Foundation contribution model, a project retains ownership of the project, but grants the .NET Foundation a broad license to the project’s code and other intellectual property. The project also confirms that the project’s submissions to .NET Foundation are its own original work (there are also instructions for any third party materials that might be included).

## 4.   Repository Layout
The .NET Foundation host guidance for new projects and details on recommended structure here:
[https://github.com/dotnet/home/tree/master/guidance](https://github.com/dotnet/home/tree/master/guidance)

Note that the open source repository should be the master where changes are made by the core development team using the same PR process that is used for non-committer contributions.

Please define below any changes you would want to make to your repositories as part of the process of joining the .NET Foundation

## 5.  Eligibility Criteria
Please complete the following for your project
* The project is built on the .NET platform and/or creates value within the .NET ecosystem.
- [x] Yes 
- [ ] No
* The project produces source code for distribution to the public at no charge.
- [x] Yes 
- [ ] No
* The project's code is easily discoverable and publicly accessible (preferably on GitHub).
- [x] Yes 
- [ ] No
* The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).
- [x] Yes 
- [ ] No
* When applicable, project must use reproducible build settings in its toolchain.
- [x] Yes 
- [ ] No
* The project uses [Source Link.](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
- [x] Yes 
- [ ] No
* The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).
- [x] Yes 
- [ ] No
* The project code signs their artifacts as appropriate.
- [ ] Yes 
- [x] No
* The project organization has 2FA enabled. Requiring 2FA must be done as part of onboarding if not already enabled.
- [ ] Yes
- [x] No
* Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).
- [x] Yes 
- [ ] No
* Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.
- [x] Yes 
- [ ] No
* The copyright ownership of everything that the project produces is clearly defined and documented.
- [ ] Yes 
- [x] No
* The project has a public issue tracker where the status of any defect can be easily obtained.
- [x] Yes 
- [ ] No
* The project has a published Security Policy.
- [ ] Yes 
- [x] No
* The project has a home page which provides high level information about its status and purpose.
- [x] Yes 
- [ ] No
* The project has a public communication channel where community members can engage with maintainers.
- [x] Yes 
- [ ] No
* The project has a publicly available location where members can review and contribute to documentation.
- [x] Yes 
- [ ] No

## 6.   PR Plan
Please summarize the public relations plan for the announcement when joining the foundation (and releasing as open source if appropriate). What is the main story we wish to promote, through what channels, what issues should we be aware of?  For significant news events then please also work with your .NET Foundation contact to ensure a [full PR plan](https://dotnetfoundation.sharepoint.com/Shared%20Documents/PR/Communications%20Plan%20TEMPLATE.docx?web=1) is developed.

We will be writing a blog post and promote it on our social media channels.

## 7.   Infrastructure Requirements
Please describe any infrastructure requirements for the project. For example, how will build servers be operated? Any web hosting or service hosting requirements? Do we need to set up SSL certificates or provide Authenticode Code Signing arrangement for releases?

Project is build with Jenkins and it is possible to generate NuGet packages using a PowerShell script and [Nuke](https://nuke.build/).

## 8.   Additional Notes

ASP.NET Boilerplate is a general purpose application framework specially designed for new modern web applications. It uses already familiar tools and implements best practices around them to provide you a SOLID development experience.
ASP.NET Boilerplate works with the latest ASP.NET Core & EF Core but also supports ASP.NET MVC 5.x & EF 6.x as well. 
ASP.NET Boilerplate is created in August 2013 and it is maintained since then.

**Comment by ChrisSfanos** [comment]
Hi @ismcagdas - please email me (chris dot sfanos @ dotnetfoundation dot com the complete list of signers full names and email addresses so I can process the Project Agreement - thanks

**Comment by ChrisSfanos** [comment]
For the onboarding process to the .NET Foundation, we will be working through this checklist:

## CLA
- [ ] Project Agreement Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)
- [ ] Enable two-factor authentication (2FA) for GitHub

**Comment by ChrisSfanos** [comment]
Project agreement doc is now out for signing

**Comment by ChrisSfanos** [comment]
Sorry, lost track of this one.  Agreement is signed.  I'll send our CLA onboarding instructions in a few

**Comment by ChrisSfanos** [comment]
CLA onboarding is complete - sending the final steps next

**Comment by ChrisSfanos** [comment]
I've added the project to the next newsletter and the rest of the work items have been completed - this is now closed out :-)
