### ISSUE TITLE
New Core Cake Team Member

### ISSUE THREAD

**Issue by gep13** [dotnet-foundation/projects#16]
We have recently brought on a new Core Cake Team Member (@jericho) https://github.com/jericho who has been doing an amazing amount of work in the Cake Community, and we felt it was time to bring him on as a full team member.

What information is required in order to get him access to the benefits offered by the .Net Foundation.

**Comment by jongalloway** [comment]
What would you like us to set up? Some options:

- Add to Cake DLs
- Invite to project leader slack
- Request MSDN subscription (disclaimer, not a guaranteed benefit, just something we request)
- Anything else?

I looked up e-mail from a git commit; generally that's also something we'd need in the future.

**Comment by gep13** [comment]
The Cake Team also uses our LastPass Subscription to share Cale account details, so it would be good to be able to have them access for that.

Having a jericho@cakebuild.net email address would be good as well.

**Comment by gep13** [comment]
@jongalloway just wanted to touch base with this to see how it is progressing, thanks.

**Comment by jongalloway** [comment]
Just pinged you via Slack to verify name and e-mail before LastPass and MSDN steps. Other parts are done, updated on checklist above.

**Comment by jongalloway** [comment]
Added to LastPass, requested MSDN.

Last step remaining is to add him to the CakeTeam in LastPass once the invite is accepted. I think everyone on CakeTeam is an admin for that group and should be able to add him, can you test that?

Will wait to close until that's done.

**Comment by Jericho** [comment]
@jongalloway thanks for doing all this. I accepted LastPass invitation and MSDN subscription.

I also accepted Office365 invite which you sent a little while ago but it appears I haven't been assigned a license. Here's the message I get when I login: `You don't have a license to use Office 365 with the user ID assigned to you by your work or school. Ask your admin to assign one to you. If you're an admin, you can assign one to your account.`

**Comment by jongalloway** [comment]
@Jericho I didn't know if you'd need a license, and we pay for them so I'm cheap. ;)

Assigned.

All set?

**Comment by Jericho** [comment]
I understand, and also I don’t want to be a financial burden on the foundation! 

In case it makes a difference: I don’t need access to the office suite (already have a paid subscription) and unless I’m mistaken the Cake team doesn’t use the various communication apps such as Skype or Kaizala. So feel free to take away those licenses. 

As far as I know, I only need a “@cakebuild.net” email address so whatever license is required for that...

Other than that, yes I’m all set.

**Comment by gep13** [comment]
@jongalloway thank you for taking the time to do this!  Appreciate it!
