### ISSUE TITLE
Project Spotlight Request: Verify

### ISSUE THREAD

**Issue by SimonCropp** [dotnet-foundation/projects#160]
## General Information

**Project Name:** 

Verify

**Contributor (Company, Organization or individual name(s)):**

Simon Cropp

**URL:**

https://github.com/VerifyTests/Verify

**Please provide a brief statement about your project in terms that are understandable to the target consumer of the library or project, i.e. an elevator pitch for the project:** 

Simplified .net snapshot testing with Verify.

Verify is a snapshot tool that enables the assertion of complex data models and documents.

Verify is called on the test result during the assertion phase. It serializes that result and stores it in a file that matches the test name. On the next test execution, the result is again serialized and compared to the existing file. The test will fail if the two snapshots do not match: either the change is unexpected, or the reference snapshot needs to be updated to the new result.

xUnit, NUnit and MsTest are support. Utilities are provided to streamline compatibility with variety of libraries and technologies including Blazor, SqlServer, EntityFramework, and asp core.

**Please list 5 top non-maintainer contributors to your project**

Not really any of note so far

**Month you would prefer to be featured** 

Any

**Timeline when to conduct a short interview**

Any. i work from home Thur+Fri in AEST, so those would work. but could also do weekends

**Comment by isaacrlevin** [comment]
hey there! thanks for submitting your project to be spotlighted. Currently we have you tacked for September. I am OOO for a large part of the summer. Are you free this week to get the interview done so there won't be a delay in publishing?

**Comment by isaacrlevin** [comment]
Hey there, sorry for delay on this (and the push back). Can you please provide your availability next week Thursday in your timezone?

**Comment by SimonCropp** [comment]
> Hey there, sorry for delay on this (and the push back

no worries at all. 

How about 7 am my time. which i think is 3pm your time?  If thats ok, shoot me an invite to simon.cropp@gmail.com

**Comment by isaacrlevin** [comment]
Invite sent!

**Comment by SimonCropp** [comment]
i just realized the invite you sent is for my friday. I can do my thursday or friday.

**Comment by isaacrlevin** [comment]
If the current timeslot works we can keep that... I hope that is ok

**Comment by isaacrlevin** [comment]
Are we still set for today?

**Comment by SimonCropp** [comment]
yep. cal entry is in 30min

**Comment by devlead** [comment]
This has now been completed
https://dotnetfoundation.org/projects/spotlight?project=Verify
