### ISSUE TITLE
Project Spotlight Request: NuGet Package Explorer

### ISSUE THREAD

**Issue by clairernovotny** [dotnet-foundation/projects#162]
## General Information

**Project Name:** NuGet Packaget Explorer

**Contributor (Company, Organization or individual name(s)):**
Claire Novotny

**Source Code URL:**
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer

**Documentation URL:**

**Contribution URL:**

**Project Homepage URL (if different):**

**Please provide a brief statement about your project in terms that are understandable to the target consumer of the library or project, i.e. an elevator pitch for the project:**
NuGet Package Explorer (NPE) is an application that makes it easy to create and explore NuGet packages. You can load a .nupkg or .snupkg file from disk or directly from a feed such as nuget.org.

**Please list 5 top non-maintainer contributors to your project**
https://github.com/304NotModified
https://github.com/campersau

**Month you would prefer to be featured**
ASAP

**Timeline when to conduct a short interview**
ASAP

**Comment by isaacrlevin** [comment]
@clairernovotny are you available this week to do a 15-20 minute interview?

**Comment by clairernovotny** [comment]
Sure, when? My work calendar is up to date.

**Comment by ChrisSfanos** [comment]
Issue cleanup - this is an old issue and was time-sensitive
