### ISSUE TITLE
Project Support Request: ReactiveUI

### ISSUE THREAD

**Issue by glennawatson** [dotnet-foundation/projects#165]
### Please fill in the information below:
- **Project Name:** ReactiveUI
- **Due by:** ASAP
- **Description:** Our code signing is failing so we can't release. Seems to be invalid "CodeSign" app credentials. If you can update https://github.com/organizations/reactiveui/settings/secrets/actions here that would be great.

**Comment by glennawatson** [comment]
The error we get explicitly is `Error: Did not specify valid secret.`

**Comment by clairernovotny** [comment]
As per the Twitter/Slack conversations, this seems to be working now, correct?

**Comment by glennawatson** [comment]
Confirmed fix. Thanks for the help.
