### ISSUE TITLE
New GitHub Issues Beta - Project Support Request: Silk.NET

### ISSUE THREAD

**Issue by Perksey** [dotnet-foundation/projects#166]
### Please fill in the information below:
- **Project Name:** Silk.NET
- **Due by:** Ideally an answer on whether this is possible within the next few weeks so we can plan our project planning.
- **Description:** GitHub have launched [a new Issues experience](https://github.com/features/issues) and we'd love to enrol in the beta to aid our project planning for the upcoming rewrite, but given we're in the dotnet org we can't enable it, only an org owner can enable it. Would it be possible to enrol dotnet in the beta?

**Comment by Perksey** [comment]
FYI @HurricanKai @ThomasMiz

**Comment by clairernovotny** [comment]
We have already put the `dotnet` org on the waiting list. I don't have any more information about when we'll have it enabled from GitHub than anyone else.

**Comment by Perksey** [comment]
Brill, confirmation that we're on the list is all we were after! Thanks.
