### ISSUE TITLE
Code Signing Certificate Request: Stride

### ISSUE THREAD

**Issue by xen2** [dotnet-foundation/projects#168]
### Please fill in the information below

- **Project Name:** Stride (alternatively: Stride Game Engine)
- **LastPass Email (or send offline):** virgile@stride3d.net (not created yet, does it need a business account or personal is enough?)

Certificate onboarding checklist:

- [x] Register trade name @ChrisSfanos
- [x] Create configuration in Code Signing Service
- [x] Create organization with DigiCert
- [x] Request certificate from DigiCert
- [x] Received certificate and finalize sign service configuration
- [x] Provide credentials in shared folder in LastPass

**Comment by xen2** [comment]
Quick update: our previous signing certificate expired a few weeks ago and it looks like it will be difficult to renew.
It would be great if this was solved quickly.

**Comment by ChrisSfanos** [comment]
Trade name registration submitted

**Comment by clairernovotny** [comment]
The cert is in the service and configurd. @xen2 you need to sign up for LastPass and sign in for the sharing keys. A personal account is fine for this.

**Comment by xen2** [comment]
@clairernovotny thanks!
I have just created an account with virgile@stride3d.net

**Comment by clairernovotny** [comment]
Should be all set now.

**Comment by xen2** [comment]
> Should be all set now.

Thank you very much!

**Comment by xen2** [comment]
Another issue: I attached a zip with 2 exe.
One can be signed, the other not: `Server returned non Ok response: 500 Internal Server Error`

The only thing different is some installer parameters (about what UI to display when uninstalling).

[StrideSetup.SignTest.zip](https://github.com/dotnet-foundation/projects/files/9088690/StrideSetup.SignTest.zip)
 
Any reason for this error 500? Is it a problem with the signing service or is something wrong with the file?

**Comment by ChrisSfanos** [comment]
Issue cleanup - if you are still having signing issues @xen2 , please create a new issue as we are moving to a new [CLI Signing](https://github.com/dotnet/sign) service that I will onboard you with
