### ISSUE TITLE
Assistance with Azure Marketplace

### ISSUE THREAD

**Issue by mitchelsellers** [dotnet-foundation/projects#17]
For the DNN Platform project there is currently a published WebDeploy package (https://azuremarketplace.microsoft.com/en-us/marketplace/apps/DNNCorp.DNNPlatform?tab=Overview) but this package is VERY old, and there is no-one that has any access to the account associated with this.

We need some assistance to get this at a minimum unlisted, as it is a version with security issues.  But ldeally we need the ability to update this.

**Comment by jongalloway** [comment]
Will ask around, but with two disclaimers:
- I've had very low success rate getting help with Azure Marketplace issues in the past
- I and some other people in .NET Foundation work at Microsoft, but there's no official relationship or support for .NET Foundation from Azure Marketplace

**Comment by jongalloway** [comment]
Found the support alias and e-mailed about both de-listing current insecure release and getting access to push new releases. Again, I've had very low success rate getting engagement from that team in the past, but fingers crossed.

**Comment by clairernovotny** [comment]
Closing due to age. Please reopen if there's still an issue.
