### ISSUE TITLE
Moving TorchSharp to .NET Foundation

### ISSUE THREAD

**Issue by NiklasGustafsson** [dotnet-foundation/projects#176]
## 1.   General Information

**Project Name:** TorchSharp

**License:** MIT

**Contributor (Company, Organization or individual name(s)):** Microsoft Corporation

**Existing OSS Project? (Yes/No):** Yes.

**Source Code URL:** https://github.com/xamarin/TorchSharp

**Project Homepage URL (if different):**

**Project Transfer Signatories:**
Full legal name and __email address__ required of the individual(s) with the authority to transfer or contribute the project to the .NET Foundation. Note that if you'd prefer not to include this in the public application, it can be submitted via e-mail to contact@dotnetfoundation.org (referencing this issue number).

## 2.   Description
TorchSharp provides .NET bindings to LibTorch, which is the deep learning and tensor math engine powering  Pytorch. It mainly consists of a thin interop layer to the native library, which supports CPU and CUDA-based arithmetic. There is also a small set of utility functions implemented in .NET on top of the interop layer, most significantly for vision primitives.

Short description:

TorchSharp provides .NET bindings to LibTorch, the deep learning and tensor math engine powering Pytorch.

## 3.   Project Governance
Please complete this section about who will be maintaining the open source project and how it will run.
**Project Lead:**

Name:   Niklas Gustafsson
 Email:   niklas.gustafsson@microsoft.com
 GitHub Profile URL: https://github.com/NiklasGustafsson

**Committers:**

Don Syme, Microsoft
Niklas Gustafsson, Microsoft
Miguel de Icaza, Microsoft

**Governance Model:**

Code changes are proposed and reviewed using the GitHub Pull Request (PR) system. PRs are reviewed and approved by the project committers in conference.

**CLA**

There has been no CLA in place for the existing OSS project, but all code currently in the master branch of the existing repository was written by Microsoft full-time employees.

**CLA Notification Alias**
niklas.gustafsson@microsoft.com

**Assignment Model.**  Under the .NET Foundation assignment model, project ownership and other intellectual property is assigned to the .NET Foundation and the .NET Foundation agrees to grant back a license to the contributor(s). 

**Contribution Model.**  Under the .NET Foundation contribution model, a project retains ownership of the copyright, but grants the .NET Foundation a broad license to the project’s code and other intellectual property. The project also confirms that the project’s submissions to .NET Foundation are its own original work (there are also instructions for any third party materials that might be included).

## 4.   Repository Layout
The .NET Foundation host guidance for new projects and details on recommended structure here:
[https://github.com/dotnet/home/tree/master/guidance](https://github.com/dotnet/home/tree/master/guidance)

Note that the open source repository should be the master where changes are made by the core development team using the same PR process that is used for non-committer contributions.

Please define below any changes you would want to make to your repositories as part of the process of joining the .NET Foundation

## 5.  Eligibility Criteria
Please complete the following for your project
* The project is built on the .NET platform and/or creates value within the .NET ecosystem.
- [x] Yes 
- [ ] No
* The project produces source code for distribution to the public at no charge.
- [x] Yes 
- [ ] No
* The project's code is easily discoverable and publicly accessible (preferably on GitHub).
- [x] Yes 
- [ ] No
* The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).
- [x] Yes 
- [ ] No
* When applicable, project must use reproducible build settings in its toolchain.
- [x] Yes 
- [ ] No
* The project uses [Source Link.](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
- [ ] Yes 
- [x] No
* The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).
- [ ] Yes 
- [x] No
* The project code signs their artifacts as appropriate.
- [ ] Yes 
- [x] No
* The project organization has 2FA enabled. Requiring 2FA must be done as part of onboarding if not already enabled.
- [x] Yes
- [ ] No
* Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).
- [x] Yes 
- [ ] No
* Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.
- [x] Yes 
- [ ] No
* The copyright ownership of everything that the project produces is clearly defined and documented.
- [x] Yes 
- [ ] No
* The project has a public issue tracker where the status of any defect can be easily obtained.
- [x] Yes 
- [ ] No
* The project has a published Security Policy.
- [ ] Yes 
- [x] No
* The project has a home page which provides high level information about its status and purpose.
- [x] Yes 
- [ ] No
* The project has a public communication channel where community members can engage with maintainers.
- [x] Yes 
- [ ] No
* The project has a publicly available location where members can review and contribute to documentation.
- [x] Yes 
- [ ] No

## 6.   PR Plan

We are currently not ready for any kind of PR efforts around this library, and will continue to develop it and grow its community through word-of-mouth.

## 7.   Infrastructure Requirements
We will use standard Microsoft Azure DevOps CI as the build infrastructure. There are no web hosting or service hosting requirements. We would like advice about the standard practices for .NET Foundation projects with majority Microsoft contributions, and the simplest path to arranging appropriate code signing.

## 8.   Additional Notes
This project is conceptually related to ML.NET, but stands on its own. It is also similar to Tensorflow.NET under the SciSharp GitHub organization, which provides similar bindings to Tensorflow.
TorchSharp is currently < v1.0. In other words, it is still a pre-release.
We do currently **not** embed PDBs, but can enable it if required.
A small amount of code as well as the overall API design, is inspired by Pytorch. Since the implementation languages are different, there are no instances of copied code, but some functions in the torch.vision namespace are directly inspired by the corresponding Python implementations, which are covered by a BSD-3 license.

**Comment by ChrisSfanos** [comment]
Hi everyone
We will be following this checklist to onboard the project. Since it's a MSFT transfer, I'll work on the first two items in parallel to handing off the rest of the list

## CLA
- [ ] Project Agreement Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)
- [ ] Enable two-factor authentication (2FA) for GitHub

**Comment by ChrisSfanos** [comment]
Agreement is out for signing

**Comment by NiklasGustafsson** [comment]
## Project Onboarding
* [ ]  Public Announcement via the .NET Foundation site/etc
* [x]  Joining the Project leader mailing list
* [x]  Joining the Project leader Slack channel
* [x]  Updating license/copyright in the repo + updating file headers
* [x]  Reviewing the .NET Foundation Code of Conduct
* [ ]  Add Project to the .NET Foundation project list
* [x]  Project layout cleanup (as appropriate)
* [x]  README Guidance updates
* [ ]  ~~Project website updates (outside of GitHub)~~
* [ ]  Enable two-factor authentication (2FA) for GitHub

**Comment by ChrisSfanos** [comment]
Project agreement is signed
CLA bot is already enabled by default for all projects in the dotnet organization

**Comment by ChrisSfanos** [comment]
Once the code signing is wrapped up, we can close this item out - all other onboarding tasks are complete

**Comment by NiklasGustafsson** [comment]
Speaking of that, @ChrisSfanos, how is the code signing task proceeding? Do you need anything from me?

**Comment by ChrisSfanos** [comment]
I’m out of the process loop once the Trade Name is registered. Claire handles the remaining steps

Chris
________________________________

**Comment by clairernovotny** [comment]
@NiklasGustafsson It can take 1-3 weeks to get a cert from DigiCert depending on how long they take. We're working on getting it done ASAP.

**Comment by NiklasGustafsson** [comment]
@clairernovotny: Thanks for the heads up about the timeline!

**Comment by NiklasGustafsson** [comment]
Just so that we can prepare for when the cert is ready -- is there documentation or examples of how the code-signing service is used within a Azure DevOps pipeline?

**Comment by ChrisSfanos** [comment]
Hi folks
I'm working to clean up the onboarding projects still listed as open.  Looks like the cert was the last item.  What is the latest status?

Thanks!

**Comment by NiklasGustafsson** [comment]
@ChrisSfanos  -- yes, we're done. Code signing has been working for a while. Thanks for the reminder.

**Comment by ChrisSfanos** [comment]
Awesome - that was the last item, so I'm closing this one out - thanks!
