### ISSUE TITLE
AutoFixture

### ISSUE THREAD

**Issue by ecampidoglio** [dotnet-foundation/projects#178]
## 1.   General Information

**Project Name:** AutoFixture

**License:** MIT

**Contributors:** Mark Seemann, Nikos Baxevanis, Enrico Campidoglio, Adam Chester, Oleksandr Povar, Andrei Ivascu

**Existing OSS Project? (Yes/No):** Yes

**Source Code URL:** https://github.com/AutoFixture/AutoFixture

**Project Homepage URL (if different):** https://autofixture.github.io

**Project Transfer Signatories:** Submitted via e-mail

## 2.   Description

AutoFixture is an open source library for .NET designed to minimize the 'Arrange' phase of your unit tests in order to maximize maintainability. Its primary goal is to allow developers to focus on what is being tested rather than how to setup the test scenario, by making it easier to create object graphs containing test data.

**Please provide a 1 sentence (<140 character) summary of your project to help users when searching the .NET Foundation projects**: Easily create test data for your unit tests.

## 3.   Project Governance

**Project Lead:**

Name: Andrei Ivascu
Email: andrew.ivascu@gmail.com
GitHub Profile URL: https://github.com/aivascu

**Committers:**

* Mark Seemann @ploeh
* Nikos Baxevanis @moodmosaic
* Enrico Campidoglio @ecampidoglio
* Adam Chester @adamchester
* Oleksandr Povar @zvirja
* Andrei Ivascu @aivascu

**Governance Model:**

Changes are proposed by starting a thread on GitHub Discussions. Members of the [@AutoFixture/Core](https://github.com/orgs/AutoFixture/teams/core) team are asked for their opinions. If a consensus is reached within the Core team, a GitHub issue is created to track work on the change.

**CLA**

If already an OSS project, was a Contribution License Agreement in place for contributions accepted? How does the project check who has signed one? No.

**CLA Notification Alias**

Provide an email address that will receive CLA related notifications from the .NET Foundation CLA automation: autofixture1@protonmail.com

**Assignment Model.**  Under the .NET Foundation assignment model, project ownership and other intellectual property is assigned to the .NET Foundation and the .NET Foundation agrees to grantback a license to the contributor(s). 

**Contribution Model.**  Under the .NET Foundation contribution model, a project retains ownership of the copyright, but grants the .NET Foundation a broad license to the project’s code and other intellectual property. The project also confirms that the project’s submissions to .NET Foundation are its own original work (there are also instructions for any third party materials that might be included).

## 4.   Repository Layout
The .NET Foundation host guidance for new projects and details on recommended structure here:
[https://github.com/dotnet/home/tree/master/guidance](https://github.com/dotnet/home/tree/master/guidance)

Note that the open source repository should be the master where changes are made by the core development team using the same PR process that is used for non-committer contributions.

Please define below any changes you would want to make to your repositories as part of the process of joining the .NET Foundation.

## 5.  Eligibility Criteria

Please complete the following for your project.

* The project is built on the .NET platform and/or creates value within the .NET ecosystem.
- [x] Yes 
- [ ] No
* The project produces source code for distribution to the public at no charge.
- [x] Yes 
- [ ] No
* The project's code is easily discoverable and publicly accessible (preferably on GitHub).
- [x] Yes 
- [ ] No
* The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).
- [x] Yes 
- [ ] No
* When applicable, project must use reproducible build settings in its toolchain.
- [x] Yes 
- [ ] No
* The project uses [Source Link.](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
- [x] Yes 
- [ ] No
* The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).
- [x] Yes 
- [ ] No
* The project code signs their artifacts as appropriate.
- [x] Yes 
- [ ] No
* The project organization has 2FA enabled. Requiring 2FA must be done as part of onboarding if not already enabled.
- [x] Yes
- [ ] No
* Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).
- [x] Yes 
- [ ] No
* Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.
- [x] Yes 
- [ ] No
* The copyright ownership of everything that the project produces is clearly defined and documented.
- [x] Yes 
- [ ] No
* The project has a public issue tracker where the status of any defect can be easily obtained.
- [x] Yes 
- [ ] No
* The project has a published Security Policy.
- [ ] Yes 
- [x] No
* The project has a home page which provides high level information about its status and purpose.
- [x] Yes 
- [ ] No
* The project has a public communication channel where community members can engage with maintainers.
- [x] Yes 
- [ ] No
* The project has a publicly available location where members can review and contribute to documentation.
- [x] Yes 
- [ ] No

## 6.   PR Plan

Please summarize the public relations plan for the announcement when joining the foundation (and releasing as open source if appropriate). What is the main story we wish to promote, through what channels, what issues should we be aware of?  For significant news events then please also work with your .NET Foundation contact to ensure a [full PR plan](https://dotnetfoundation.sharepoint.com/Shared%20Documents/PR/Communications%20Plan%20TEMPLATE.docx?web=1) is developed.

The plan is to announce the joining to the .NET Foundation on [AutoFixture's Twitter account](https://twitter.com/AutoFixture).

## 7.   Infrastructure Requirements

Please describe any infrastructure requirements for the project. For example, how will build servers be operated? Any web hosting or service hosting requirements? Do we need to set up SSL certificates or provide Authenticode Code Signing arrangement for releases?

The builds are run on AppVeyor. Web hosting is provided by GitHub Pages. The project has its own code signing key. We would like to transfer the autofixture.org domain to the .NET Foundation.

## 8.   Additional Notes

Please provide any additional information required or use this area for notes during the onboarding process. If this open source project has similarities with any other projects in this space then please detail them and why this project is different. If there are any potential issues that you feel the project might need help with early on then also state them here and discuss with your .NET Foundation Contact.

**Comment by ploeh** [comment]
> We would like to transfer the autofixture.org domain to the .NET Foundation.

I'm the one who currently owns that domain. In fact, I own these relevant domains:

- autofixture.com
- autofixture.org
- autofixture.net
- autofixture.dk

You may not be interested in the `.dk` domain, but I strongly suggest that we transfer ownership of the other three.

To be clear, I'm happy to donate them all to the foundation, so the only cost associated with these domains is the renewal fees when they lapse.

**Comment by Kralizek** [comment]
@aivascu also owns autofixture.io, IIRC

**Comment by aivascu** [comment]
That is correct, I own [autofixture.io](https://autofixture.io). The website currently hosts the AutoFixture API Reference.
I will be glad to donate the domain name as well.

**Comment by ploeh** [comment]
BTW, given that this is the _.NET_ foundation, I think that the 'official' domain name ought to be `autofixture.net` 😉

**Comment by aivascu** [comment]
Classy! I like this idea. 🙂

**Comment by ChrisSfanos** [comment]
Hello!  The .NET Foundation is ready to pick back up with onboarding - we will be following the checklist below

## CLA
- [ ] Project Agreement Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)
- [ ] Enable two-factor authentication (2FA) for GitHub organization and all users

**Comment by ChrisSfanos** [comment]
agreement is out for signing

**Comment by ChrisSfanos** [comment]
Looks like we lost track of this one - CLA was signed a long while back.  My apologies.  The CLA bot process is changing, so I'll work on an update and reach out again.

**Comment by ChrisSfanos** [comment]
We are ready to move this project to the new CLA service and tackle the rest of the onboarding steps.  Email was sent this morning with the details

**Comment by ChrisSfanos** [comment]
Emailed @aivascu for an update - thanks!

**Comment by ChrisSfanos** [comment]
CLA work is complete - this was the last step in onboarding, so wrapping up and closing this work item :-)
