### ISSUE TITLE
Code Signing Certificate Request: AutoMapper

### ISSUE THREAD

**Issue by jbogard** [dotnet-foundation/projects#181]
### Please fill in the information below

- **Project Name: AutoMapper**
- **LastPass Email (or send offline): jimmy.bogard@gmail.com**

Certificate onboarding checklist:

- [x] Register trade name @ChrisSfanos
- [x] Create configuration in Code Signing Service
- [x] Create organization with DigiCert
- [x] Request certificate from DigiCert
- [x] Received certificate and finalize sign service configuration
- [x] Provide credentials in shared folder in LastPass

**Comment by ChrisSfanos** [comment]
Trade name registration submitted

**Comment by clairernovotny** [comment]
Sorry for the delay, DigiCert had some issues on their end. Should be forthcoming.

**Comment by clairernovotny** [comment]
Looks like you may need to sign into last pass to generate sharing keys.

I just invited you to the shared LastPass where the cert is setup and configured.

Few things:
1. Here's a template of how to add code signing to the build pipeline: https://github.com/novotnyllc/CodeSigningDemo
2. Once signing is configured, please add `dotnetfoundation` as a co-owner to the AutoMapper packages in NuGet. 
3. If you have any 3rd party binaries in your packages, you'll need a whitelist.txt to include on your binaries and not the other ones in the nupkg.

I'm happy to review any PR's/pipelines

**Comment by clairernovotny** [comment]
Hi,

Just checking in here to see if we can close out this issue?

**Comment by ChrisSfanos** [comment]
Issue cleanup - closing this out.  We are moving to the new [CLI Signing](https://github.com/dotnet/sign) tool shortly
