### ISSUE TITLE
Code Signing Certificate Request: TorchSharp

### ISSUE THREAD

**Issue by NiklasGustafsson** [dotnet-foundation/projects#182]
### Please fill in the information below

- **Project Name:** TorchSharp
- **LastPass Email (or send offline):** will send offline

Certificate onboarding checklist:

- [x] Register trade name @ChrisSfanos
- [x] Create configuration in Code Signing Service
- [x] Create organization with DigiCert
- [x] Request certificate from DigiCert
- [x] Received certificate and finalize sign service configuration
- [x] Provide credentials in shared folder in LastPass

**Comment by ChrisSfanos** [comment]
Trade name has been registered

**Comment by clairernovotny** [comment]
Sorry for the delay, DigiCert had some issues on their end. Should be forthcoming.

**Comment by clairernovotny** [comment]
I just invited you to the shared LastPass where the cert is setup and configured.

Few things:
1. Here's a template of how to add code signing to the build pipeline: https://github.com/novotnyllc/CodeSigningDemo
2. Once signing is configured, please add `dotnetfoundation` as a co-owner to the packages in NuGet. 
3. If you have any 3rd party binaries in your packages, you'll need a whitelist.txt to include on your binaries and not the other ones in the nupkg.

I'm happy to review any PR's/pipelines

**Comment by clairernovotny** [comment]
Hi,

Just wanted to see if you're all set here and we can close the issue?

**Comment by NiklasGustafsson** [comment]
Yes. Closing.
