### ISSUE TITLE
ClangSharp and LLVMSharp

### ISSUE THREAD

**Issue by tannergooding** [dotnet-foundation/projects#184]
## 1.   General Information

**Project Names:** ClangSharp and LLVMSharp

**License:** University of Illinois/NCSA Open Source License

**Contributor (Company, Organization or individual name(s)):** Microsoft

**Existing OSS Project? (Yes/No):** Yes

**Source Code URL:** https://github.com/microsoft/ClangSharp

**Project Transfer Signatories:**

This has approval for transfer on the Microsoft side, the exact signatory may need to be confirmed if this is accepted by the .NET Foundation.

## 2.   Description

ClangSharp and LLVMSharp are .NET interop bindings for the Clang and LLVM projects. ClangSharp provides an additional P/Invoke generator which is used to bootstrap itself and LLVMSharp. The P/Inveok generator is a general purpose utility that can be used to generate .NET bindings for many kinds of C and some C++ header files. It is used to power microsoft/win32metadata as well as various other projects.

## 3.   Project Governance
Please complete this section about who will be maintaining the open source project and how it will run.
**Project Lead:**

Name: Tanner Gooding
 Email: tagoo@outlook.com or tagoo@microsoft.com
 GitHub Profile URL: http://github.com/tannergooding

**Committers:**

No other committers at this time. Finding additional committers is desired.

**Governance Model:**

Code changes are proposed via issues on GitHub. For the raw interop bindings, these are generally taken "as-is" from each new version of Clang/LLVM.
For the P/Invoke generator, changes are proposed, discussed, and often taken after reaching an agreement on the best direction.

**CLA**

All contributions have been made under https://cla.opensource.microsoft.com/microsoft/ClangSharp and https://cla.opensource.microsoft.com/microsoft/LLVMSharp

**CLA Notification Alias**
Project maintainer(s)

**Assignment Model.**  Under the .NET Foundation assignment model, project ownership and other intellectual property is assigned to the .NET Foundation and the .NET Foundation agrees to grantback a license to the contributor(s). 

## 4.   Repository Layout

The repo largely follows existing best practices and the general layout of other Microsoft maintained repositories. Changes can be made as appropriate to fit the needs/expectations of the .NET Foundation.

## 5.  Eligibility Criteria
Please complete the following for your project
* The project is built on the .NET platform and/or creates value within the .NET ecosystem.
- [x] Yes 
- [ ] No
* The project produces source code for distribution to the public at no charge.
- [x] Yes 
- [ ] No
* The project's code is easily discoverable and publicly accessible (preferably on GitHub).
- [x] Yes 
- [ ] No
* The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).
- [x] Yes 
- [ ] No
* When applicable, project must use reproducible build settings in its toolchain.
- [x] Yes 
- [ ] No
* The project uses [Source Link.](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
- [x] Yes 
- [ ] No
* The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).
- [x] Yes 
- [ ] No
* The project code signs their artifacts as appropriate.
- [ ] Yes 
- [x] No
* The project organization has 2FA enabled. Requiring 2FA must be done as part of onboarding if not already enabled.
- [x] Yes
- [ ] No
* Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).
- [ ] Yes 
- [ ] No
* Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.
- [x] Yes 
- [ ] No
* The copyright ownership of everything that the project produces is clearly defined and documented.
- [x] Yes 
- [ ] No
* The project has a public issue tracker where the status of any defect can be easily obtained.
- [x] Yes 
- [ ] No
* The project has a published Security Policy.
- [ ] Yes 
- [x] No
* The project has a home page which provides high level information about its status and purpose.
- [x] Yes 
- [ ] No
* The project has a public communication channel where community members can engage with maintainers.
- [ ] Yes 
- [x] No
* The project has a publicly available location where members can review and contribute to documentation.
- [ ] Yes 
- [x] No

## 6.   PR Plan

No known requirements. Simply announcing the project is joining the foundation and detailing what it provides should be sufficient.

## 7.   Infrastructure Requirements

Authenticode signing will be required.

**Comment by ChrisSfanos** [comment]
Hi folks - we will be following the checklist below for onboarding the project

## CLA
- [ ] Project Agreement Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)
- [ ] Enable two-factor authentication (2FA) for GitHub organization and all users

**Comment by ChrisSfanos** [comment]
Onboarding agreement is out for signing

**Comment by ChrisSfanos** [comment]
Project agreement is signed

**Comment by ChrisSfanos** [comment]
Both repos have moved to the dotnet-foundation org so the CLA should be working automagically

Project names sent over to the newsletter team for inclusion

Tanner has submitted the PR for the
