### ISSUE TITLE
Code Signing Certificate Request: BrightChain

### ISSUE THREAD

**Issue by JessicaMulein** [dotnet-foundation/projects#185]
### Please fill in the information below

- **Project Name:** BrightChain
- **LastPass Email (or send offline):** offline?

Certificate onboarding checklist:

- [ ] Register trade name @ChrisSfanos
  - BrightChain has been registered as a Trade Name of Mulein Studios in Washington State
- [ ] Create configuration in Code Signing Service
- [ ] Create organization with DigiCert
- [ ] Request certificate from DigiCert
- [ ] Received certificate and finalize sign service configuration
- [ ] Provide credentials in shared folder in LastPass

**Comment by ChrisSfanos** [comment]
Hi @JessicaMulein  - As part of this, I need to register BrightChain as a Trade Name of the .NET Foundation in Washington State.  But I'm not sure if something can registered as a Trade Name in two places or not.  Do you know?  Adding @clairernovotny  also for input

**Comment by JessicaMulein** [comment]
Maybe the state website will let us move it?

**Comment by JessicaMulein** [comment]
Removed

Washington State Department of Revenue

Your request has been submitted and your confirmation number is 0-022-310-493
Please allow up to 10 business days for processing. Your change will not be effective until processing is completed.

Give us your feedback

**Comment by JessicaMulein** [comment]
Previously:
<html>
<body>
<div class="FastPageWrapper" style="margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; line-height: 1.4; vertical-align: baseline; transition-property: visibility, opacity; transition-duration: 0.2s; transition-timing-function: ease; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="FastContentWrapper" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline;"><div id="FAST_ROOT_MANAGER__" class="ManagerWrapper" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline; position: relative;"><div id="MANAGER_CONTAINER__0" class="ManagerContainer ManagerBase ManagerContainer_Fast_TAP MC_Default LoggedOn HasNavigation NoSidebar SidebarPinned SidebarLeft NoActions SidebarVisible AboveFold" data-manager-container="0" data-fast-language="ENG" data-tabindex="0" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline; position: relative; transition-property: opacity, transform; transition-duration: 0.2s; transition-timing-function: ease; background-color: rgb(255, 255, 255);"><div id="MANAGER_CW__0" class="ManagerContentWrapper" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline;"><main id="MANAGER_CC__0" class="ManagerContentContainer" style="display: block; position: relative; margin-top: 0px;"><div id="MANAGER_CONTENT__0" tabindex="-1" class="ManagerControlsContainer" style="margin: 0px auto; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline; max-width: 90rem;"><div id="MANAGER_CONTROL__0" class="ManagerControlContainer" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline; position: relative; min-width: 0px; max-width: 90rem;"><div id="CONTROL_CONTAINER__0" class="ControlContainer" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline;"><div id="Dc-1" data-docid="Dc" data-idprefix="Dc-" class="DocumentContainer  DocumentEnabled DocTypeWA_XLTRD0" data-document-container="[0,0]" tabindex="-1" data-manager-modal="0" data-doc-modal="0" data-fast-language="ENG" data-tabindex="0" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline; position: relative; transition-property: opacity, transform; transition-duration: 0.2s; transition-timing-function: ease; background-color: rgb(255, 255, 255); outline: none;"><form id="Dc-2" class="FastForm DocumentForm StandardDocumentForm " action="https://secure.dor.wa.gov/atlaseservices/wtp/_/" method="post" onsubmit="return false;" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline; display: block;"><div class="DocumentContentWrapper" style="margin: 0px; padding: 0px 20px 20px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline;"><div id="ddc_Dc-" class="DocLayout DocViewClean" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline;"><div id="vc_Dc-3" class="DocViewLayout DocViewEnabled ViewStackLayout VSResponsive VSHasAutoMargins VSAutoMargin StackVSMedium" data-automargin-class="VSAutoMargin" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline; flex: 1 0 auto; box-sizing: border-box; clear: both;"><div id="fc_Dc-4" class="VSViewRow VSView" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline;"><div id="ddc_Dd-" class="DocLayout DocViewClean" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline;"><div id="dvc_Dd-1" class="ViewContainer ViewContainerVS_Context ViewEnabled" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline;"><div id="vc_Dd-1" class="DocViewLayout DocViewEnabled ViewStackLayout VSResponsive VSHasAutoMargins VSAutoMargin StackVSMedium" data-automargin-class="VSAutoMargin" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline; flex: 1 0 auto; box-sizing: border-box; clear: both;"><div id="fc_Dd-2" class="VSViewRow VSView" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline;"><div class="DocViewLayout DocViewEnabled TableContainer DTCGLNone DTCGLNoneNoHeaders WebContext  NoColumnHeaders" id="fc_Dd-4" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline; position: relative; transition-property: opacity, transform; transition-duration: 0.2s; transition-timing-function: ease; flex: 1 0 auto; box-sizing: border-box; clear: both; background: inherit;"><div class="DocTableHeader" style="margin: 0px 0px 0px -20px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline; background-image: inherit; background-position: inherit; background-size: inherit; background-repeat: inherit; background-attachment: inherit; background-origin: inherit; background-clip: inherit; background-color: rgb(255, 255, 255); position: relative; display: flex; flex-flow: row wrap; align-items: flex-end;"><div class="TableTitlebar NonHeaderedTableTitlebar WebDocTitlebar FastTitlebarContainer " style="margin: 0px 0px 0px 20px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline; text-align: inherit; flex: 100 1 auto;"><div class="FastTitlebar WebDocTitlebar FastTitlebarContainer " style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline; white-space: normal; height: auto; display: flex; flex-flow: row wrap; align-items: center; box-sizing: border-box; position: relative;"><div class="FastTitlebarCaptionWrapper" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline; flex: 0 1 auto; display: flex; align-items: center;"><h3 id="caption2_Dd-5" class=" FastTitlebarCaption" style="margin: 0px auto 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 600; font-stretch: inherit; font-size: 24px; font-family: inherit; line-height: 1.4; vertical-align: baseline; flex: 0 0 auto; display: block; white-space: normal; max-width: 100%; overflow: hidden;">Trade Names</h3></div><ul class="HeaderLinkContainer" style="margin: 0px 0px 0px auto; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline; list-style: none; display: flex; flex-flow: row wrap; align-items: center;"></ul></div></div></div><div class="DocTableWrapper" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline; position: relative;">

License
--
604746813-001-0001
MULEIN STUDIOS

</div></div></div></div></div></div></div></div></form></div></div><a href="https://secure.dor.wa.gov/atlaseservices/wtp/_/#" class="ScrollForMoreLink FRC FastEvt" data-event="ScrollForMore" title="Scroll for More" style="margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant: inherit; font-weight: normal; font-stretch: inherit; font-size: 1.5rem; font-family: &quot;Material Icons&quot;; line-height: 1; vertical-align: baseline; text-decoration: none; color: rgb(255, 255, 255); display: block; text-transform: none; letter-spacing: normal; overflow-wrap: normal; white-space: nowrap; direction: ltr; -webkit-font-smoothing: antialiased; text-rendering: optimizelegibility; font-feature-settings: &quot;liga&quot;; position: fixed; overflow: hidden; z-index: 61; bottom: 14px; left: 928px; transform: translateX(-0.75rem); float: left; opacity: 0; visibility: hidden; border-radius: 1.5rem; box-shadow: none; transition-property: opacity, box-shadow, background-color; transition-duration: 0.2s; transition-timing-function: ease; text-indent: -100000px; height: 1em; width: 1em; background-color: rgb(22, 74, 124);"></a></div></div></main></div></div></div><div class="clearer" style="margin: 0px !important; padding: 0px !important; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline; content: &quot; &quot;; visibility: hidden !important; display: block !important; height: 0px !important; clear: both !important;"></div><div class="clearer" style="margin: 0px !important; padding: 0px !important; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline; content: &quot; &quot;; visibility: hidden !important; display: block !important; height: 0px !important; clear: both !important;"></div></div></div><div class="FastPageFooter" style="margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; line-height: 1.4; vertical-align: baseline; background-color: rgb(255, 255, 255); color: rgb(0, 92, 153); transition-property: visibility, opacity; transition-duration: 0.2s; transition-timing-function: ease; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="FastPageFooterContent" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline; max-width: 100%; box-sizing: border-box;"><div class="FastSiteSection FastSiteFooter" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline;"><div class="main-footer" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; font-family: inherit; line-height: 1.4; vertical-align: baseline;"><br class="Apple-interchange-newline">
</body>
</html>

**Comment by ChrisSfanos** [comment]
Thanks!  I'll probably process this tomorrow - thanks!

**Comment by JessicaMulein** [comment]
Should we register with and without spaces? I've never considered it with spaces.

**Comment by ChrisSfanos** [comment]
From what I recall, it doesn't matter.  I don't think it allows spaces actually (I planned no spaces anyway)

**Comment by clairernovotny** [comment]
Hi @JessicaMulein. Due to budget constraints, Code Signing certificates are only available to .NET Foundation member projects at this time.

**Comment by JessicaMulein** [comment]
Didn't I get voted in?
What is Seed?

**Comment by JessicaMulein** [comment]
I guess I'll take my trademark back!

**Comment by JessicaMulein** [comment]
Well that was $25 well spent
