### ISSUE TITLE
RestSharp

### ISSUE THREAD

**Issue by alexeyzimarev** [dotnet-foundation/projects#198]
## 1.   General Information

**Project Name:** RestSharp

**License:** Apache 2.0

**Contributor (Company, Organization or individual name(s)):** Alexey Zimarev

**Existing OSS Project? (Yes/No):** Yes

**Source Code URL:** https://github.com/restsharp/RestSharp

**Project Homepage URL (if different):** https://restsharp.dev

**Project Transfer Signatories:** alex@zimarev.com

## 2.   Description

RestSharp is one of the most popular REST clients for .NET with 107+ million downloads on NuGet.

## 3.   Project Governance

**Project Lead:**

Name: Alexey Zimarev   
Email: alex@zimarev.com
GitHub Profile URL: https://github.com/alexeyzimarev

**Committers:**

Alexey Zimarev

**Governance Model:**

There's no strong community behind this project, I am maintaining it alone.

**CLA**

There's no CLA in place

**CLA Notification Alias**
Provide an email address that will receive CLA related notifications from the .NET Foundation CLA automation

Same as above

**Assignment Model.**  Under the .NET Foundation assignment model, project ownership and other intellectual property is assigned to the .NET Foundation and the .NET Foundation agrees to grantback a license to the contributor(s). 

**Contribution Model.**  Under the .NET Foundation contribution model, a project retains ownership of the copyright, but grants the .NET Foundation a broad license to the project’s code and other intellectual property. The project also confirms that the project’s submissions to .NET Foundation are its own original work (there are also instructions for any third party materials that might be included).

## 4.   Repository Layout

I believe the repository structure is good enough.

## 5.  Eligibility Criteria
Please complete the following for your project
* The project is built on the .NET platform and/or creates value within the .NET ecosystem.
- [X] Yes 
- [ ] No
* The project produces source code for distribution to the public at no charge.
- [X] Yes 
- [ ] No
* The project's code is easily discoverable and publicly accessible (preferably on GitHub).
- [X] Yes 
- [ ] No
* The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).
- [X] Yes 
- [ ] No
* When applicable, project must use reproducible build settings in its toolchain.
- [X] Yes 
- [ ] No
* The project uses [Source Link.](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
- [X] Yes 
- [ ] No
* The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).
- [X] Yes 
- [ ] No
* The project code signs their artifacts as appropriate.
- [ ] Yes 
- [X] No
* The project organization has 2FA enabled. Requiring 2FA must be done as part of onboarding if not already enabled.
- [X] Yes
- [ ] No
* Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).
- [X] Yes 
- [ ] No
* Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.
- [X] Yes 
- [ ] No
* The copyright ownership of everything that the project produces is clearly defined and documented.
- [X] Yes 
- [ ] No
* The project has a public issue tracker where the status of any defect can be easily obtained.
- [X] Yes 
- [ ] No
* The project has a published Security Policy.
- [X] Yes 
- [ ] No
* The project has a home page which provides high level information about its status and purpose.
- [X] Yes 
- [ ] No
* The project has a public communication channel where community members can engage with maintainers.
- [X] Yes 
- [ ] No
* The project has a publicly available location where members can review and contribute to documentation.
- [X] Yes 
- [ ] No

## 6.   PR Plan
I don't have a PR plan in place.

## 7.   Infrastructure Requirements
We use GitHub Actions only

## 8.   Additional Notes
N/A

**Comment by alexeyzimarev** [comment]
Could I get an update on the onboarding progress? I never heard from the Foundation since I opened this issue back in December 2021.

**Comment by sbwalker** [comment]
@alexeyzimarev the Project Committee reviewed the application in January and made a recommendation to the BOD that RestSharp be added to the .NET Foundation as a Member Project. At the next board meeting the BOD voted and approved the project. The project then moved to the onboarding stage and that is where it currently resides as the .NET Foundation is currently in the process of updating its onboarding procedures. I hope this provides some better clarity.

**Comment by alexeyzimarev** [comment]
Thank you for the update  👍

**Comment by alexeyzimarev** [comment]
Is there any update for RestSharp as it's been more than three months since my last question?

**Comment by sbwalker** [comment]
Within the past few weeks the new onboarding steps have been finalized so I would expect your project to move through the process soon.

**Comment by ChrisSfanos** [comment]
Hi everyone - the Foundation is ready to re-start the onboarding process!  We will follow the checklist below

## CLA
- [ ] Project Agreement Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)
- [ ] Enable two-factor authentication (2FA) for GitHub

**Comment by ChrisSfanos** [comment]
agreement is out for signing

**Comment by ChrisSfanos** [comment]
Agreement is signed - instructions for DNFAdmin config sent for CLA onboarding to Alex

**Comment by ChrisSfanos** [comment]
CLA bot is configured - I'll send out the notes for the remaining on-boarding work

**Comment by alexeyzimarev** [comment]
[x] Joining the Project leader mailing list
[x] Joining the Project leader Slack channel
[x] Updating license/copyright in the repo + updating file headers
[x] Reviewing the .NET Foundation Code of Conduct
[x] README Guidance updates
[x] Project website updates (outside of GitHub)
[x] Enable two-factor authentication (2FA) for GitHub

**Comment by ChrisSfanos** [comment]
Thanks @alexeyzimarev  for the offline updates - I will work on the newsletter post with the partner team.  If you have trouble with the .NET Project page PR, let me know - thanks!

**Comment by alexeyzimarev** [comment]
@ChrisSfanos the PR for the website is already merged :)

**Comment by ChrisSfanos** [comment]
Oh ok!  I've notified the team about the newsletter line item, so that wraps up the on-boarding process - thanks for all your timely help in getting this done!
