### ISSUE TITLE
NuGet Trends

### ISSUE THREAD

**Issue by bruno-garcia** [dotnet-foundation/projects#20]
## 1.   General Information

**Project Name:** NuGet Trends

**License:** MIT

**Contributor (Company, Organization or individual name(s)):** Bruno Garcia, João Grassi

**Existing OSS Project? (Yes/No):** Yes

**Source Code URL:** https://github.com/NuGetTrends/nuget-trends/

**Project Homepage URL (if different):** https://nugettrends.com/

**Project Transfer Signatories:**
Full legal name and email address required of the individual(s) with the authority to transfer or contribute the project to the .NET Foundation. Note that if you'd prefer not to include this in the public application, it can be submitted via e-mail to contact@dotnetfoundation.org (referencing this issue number).

Bruno Garcia - bruno@nugettrends.com

## 2.   Description
**Please provide a brief statement about your project in terms that are understandable to the target consumer of the library or project, i.e. an elevator pitch for the project:**
NuGet Trends holds historical data of NuGet packages download numbers.

For example, [here's the download number graph of Newtonsoft.Json for the last 7.5 years.](https://nugettrends.com/packages?months=90&ids=Newtonsoft.Json).

It's a useful tool for package maintainers to see the download rate of their packages and also for people interested in packages popularity over time.

The database has the complete nuget.org catalog which include target framework information. That means that there's a lot more features we can add like TFM adoption overtime, dependency graphs etc.

**Please provide a 1 sentence (<140 character) summary of your to help users when searching the .NET Foundation projects**

Check out NuGet packages adoption and what's trending on NuGet. 

## 3.   Project Governance
Please complete this section about who will be maintaining the open source project and how it will run.
**Project Lead:**
(Who is the primary contact point for the community and the .NET Foundation when discussing governance of the project.)

Name:   Bruno Garcia
 Email:   bruno@nugettrends.com
 GitHub Profile URL: https://github.com/bruno-garcia

**Committers:**
https://github.com/bruno-garcia
https://github.com/joaopgrassi/
https://github.com/loic-sharma

**Governance Model:**

Please describe how new code changes are proposed to the project, how those changes are reviewed and how a decision is made to accept proposed changes. Also describe the process for identifying and appointing new committers.

The repo has a [CONTRIBUTING](https://github.com/NuGetTrends/nuget-trends/blob/master/CONTRIBUTING.md). There's no process defined yet. [Loic](https://github.com/loic-sharma) got commit rights after helping via PR code reviews.

**CLA**

If already an OSS project, was a Contribution License Agreement in place for contributions accepted? How does the project check who has signed one?

None yet.

**CLA Notification Alias**
Provide an email address that will receive CLA related notifications from the .NET Foundation CLA automation

cla@nugettrends.com

**Project Transfer Type**

Projects may join the .NET Foundation in one of two ways and you should chat with your .NET Foundation contact to discuss the best mechanism for your project. You can either a) assign the copyright of the project's source code to the .NET Foundation or b) contribute the project source code to the .NET Foundation under an open source license. Assignment is the preferred approach, but licensing a project to the Foundation may be more appropriate for longer running open source projects that have not previously had a contribution license agreement and have accepted contributions from many different sources.
a) Assignment
b) Contribution

Assignment

## 4.   Repository Layout
The .NET Foundation host guidance for new projects and details on recommended structure here:
[https://github.com/dotnet/home/tree/master/guidance](https://github.com/dotnet/home/tree/master/guidance)

Note that the open source repository should be the master where changes are made by the core development team using the same PR process that is used for non-committer contributions.

Please define below any changes you would want to make to your repositories as part of the process of joining the .NET Foundation

Current structure already matches the guidance.

## 5.   PR Plan
Please summarize the public relations plan for the announcement when joining the foundation (and releasing as open source if appropriate). What is the main story we wish to promote, through what channels, what issues should we be aware of?  For significant news events then please also work with your .NET Foundation contact to ensure a [full PR plan](https://dotnetfoundation.sharepoint.com/Shared%20Documents/PR/Communications%20Plan%20TEMPLATE.docx?web=1) is developed.

[NuGetTrends has a twitter account](https://twitter.com/NuGetTrends). We plan to announce via twitter and also change the website to include the .NET Foundation logo.

## 6.   Infrastructure Requirements
Please describe any infrastructure requirements for the project. For example, how will build servers be operated? Any web hosting or service hosting requirements? Do we need to set up SSL certificates or provide Authenticode Code Signing arrangement for releases?

There are no special hosting requirements. Currently the project runs on docker on Linux. Infra is setup with DB backup jobs shipped to remote host, etc. Cloudflare terminates the TLS connection. The system at this time has no PII data.
At the time no artifacts are publish nor NuGet packages are published to nuget.org so I believe no need for authenticode.

## 7.   Additional Notes
Please provide any additional information required or use this area for notes during the onboarding process. If this open source project has similarities with any other projects in this space then please detail them and why this project is different. If there are any potential issues that you feel the project might need help with early on then also state them here and discuss with your .NET Foundation Contact.

The checklist in the NuGet Trends repository is [here](https://github.com/NuGetTrends/nuget-trends/issues/67).

**Comment by ChrisSfanos** [comment]
@bruno-garcia  - I need an email address please for @joaopgrassi to include the signing (since he has a large # of contributions) - you can email me at chris.sfanos @ dotnetfoundation.org is you don't want to include it here

**Comment by ChrisSfanos** [comment]
CLA is out for signatures

**Comment by ChrisSfanos** [comment]
CLA signoff is complete - kicked off CLA GitHub onboarding

**Comment by ChrisSfanos** [comment]
CLA onboarding is complete

**Comment by ChrisSfanos** [comment]
We will track the remaining onboarding work via this checklist:

## Onboarding
- [ ] CLA Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Post Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Enable CLA automation for future contributors
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)

**Comment by bruno-garcia** [comment]
@ChrisSfanos Thanks for driving this! Happy we're moving forward. 
Also, would it be possible to transfer the project to github.com/dotnet or github.com/dotnet-foundation so we don't need to keep that github.com/nugettrends org around? It's a single project: github.com/nugettrends/nuget-trends

**Comment by ChrisSfanos** [comment]
Seems reasonable, but @onovotny gets to make those calls

The next step is to configure the CLA bot - but if you are going to move the org, the steps vary slightly, so let's get that answered before I move forward with that

**Comment by bruno-garcia** [comment]
Hi @onovotny , would it be possible to transfer the repo?

**Comment by onovotny** [comment]
@bruno-garcia yes, will do

**Comment by bruno-garcia** [comment]
@onovotny Invite sent. Thanks!

**Comment by ChrisSfanos** [comment]
Looks like the repo is still under NugetTrends org right?  If we are moving it to dotnet-foundation org, I'll wait on the CLA config

**Comment by bruno-garcia** [comment]
I opened the [onboarding PR](https://github.com/dotnet/foundation/pull/168/files#diff-04c6e90faac2675aa89e2176d2eec7d8R126) with the org `NuGetTrends` not to block anything. But I will open a follow up PR to change once @clairernovotny makes the a new org.

Thanks again folks to help phasing out that org.

**Comment by clairernovotny** [comment]
Hi @bruno-garcia I'm not seeing the invite?

**Comment by bruno-garcia** [comment]
@clairernovotny  This is odd, I even double checked yesterday before writing that message.

I see this: 
<img width="741" alt="image" src="https://user-images.githubusercontent.com/1633368/76990788-4d50bf80-6927-11ea-8a65-a13e6760bfc0.png">

On https://github.com/NuGetTrends/nuget-trends/invitations

**Comment by clairernovotny** [comment]
Looks like I can't transfer it without being either an org owner or unless you change the org setting to let members transfer repos:

![image](https://user-images.githubusercontent.com/1427284/77016880-52c20000-694f-11ea-8e91-44c362430bc3.png)

**Comment by bruno-garcia** [comment]
TIL. Done:

<img width="736" alt="image" src="https://user-images.githubusercontent.com/1633368/77017019-0c24d380-6958-11ea-947b-a1a8e03ab00b.png">

**Comment by clairernovotny** [comment]
Should be all set now! https://github.com/dotnet/nuget-trends

**Comment by bruno-garcia** [comment]
Thanks a lot @clairernovotny !!
Do we stay admins then even outside of the org?

**Comment by clairernovotny** [comment]
Yes, you should still be admins of your repo. If you run into any issues, please lmk!

**Comment by bruno-garcia** [comment]
Awesome. Just [pushed to master](https://github.com/dotnet/nuget-trends/commit/5b42e553d9ee79262131713e4525750c11f19c5f) and it worked 👀

**Comment by ChrisSfanos** [comment]
Excellent - I've gone in and configured the CLA for dotnet/NuGetTrends!  I'll do a quick review, but I believe the onboarding process is now complete :-)

**Comment by ChrisSfanos** [comment]
Onboarding complete - closing this out

**Comment by joaopgrassi** [comment]
Oh, now I'm "org-less" 😅. I liked having NuGet Trends there ☹

**Comment by bruno-garcia** [comment]
@joaopgrassi you can still have it, but the project isn't part of that org anymore so makes little sense.
I think the github.com/dotnet is for Microsoft employees only. @clairernovotny or @ChrisSfanos can probably help clarify.

I'm a member of the github.com/dotnet-foundation which I believe anyone member of the foundation are part of.
