### ISSUE TITLE
Code Signing Certificate Request: ClangSharp and LLVMSharp

### ISSUE THREAD

**Issue by tannergooding** [dotnet-foundation/projects#204]
ClangSharp and LLVMSharp need code signing support. This would require new certificate(s) as well as assistance in properly setting up CI.

### Please fill in the information below:

- **Project Name:** ClangSharp (http://github.com/dotnet/clangsharp) and LLVMSharp (http://github.com/dotnet/llvmsharp)
- **LastPass Email (or send offline):** What is the preferred way to setup an e-mail here? The code is assigned to the foundation, but maintained by me and I'd rather this not be attached to my "personal" e-mail.

Certificate onboarding checklist:

- [x] Register trade name @ChrisSfanos
- [x] Create configuration in Code Signing Service
- [x] Create organization with DigiCert
- [x] Request certificate from DigiCert
- [x] Received certificate and finalize sign service configuration
- [x] Provide credentials in shared folder in LastPass

**Comment by clairernovotny** [comment]
@ChrisSfanos can you please handle the trade name components?

**Comment by ChrisSfanos** [comment]
So this is temporarily blocked - to log into the State website, I had to get an authorization letter mailed (yep, actual mail) - I'm going to campus on Friday to check the mailbox.  Then I'll be able to log in and register the trade name

**Comment by ChrisSfanos** [comment]
Ok, I got a digital copy of the letter, was able to register myself and completed the trade name registrations for ClangSharp and LLVMSharp

**Comment by clairernovotny** [comment]
@tannergooding The email is for lastpass so we can share the credentials, it can be a personal email.

**Comment by tannergooding** [comment]
We can use `admin <at> clangsharp <dot> dev` then.

**Comment by clairernovotny** [comment]
This is all complete now and the credentials are in the vault. Apologies for the time this took; we were waiting on DigiCert to complete things.

**Comment by tannergooding** [comment]
No worries, there isn't a particular rush on this from my end at the moment; I understand it can take time <3

**Comment by tannergooding** [comment]
Has there been any update on this front? Not seen any update on whether the certs are available now.

**Comment by tannergooding** [comment]
Thought there was more special setup required here, but was able to get everything working after talking with some people.
