### ISSUE TITLE
Spectre.Console

### ISSUE THREAD

**Issue by patriksvensson** [dotnet-foundation/projects#210]
## 1.   General Information

**Project Name:**
Spectre.Console

**License:**
MIT

**Contributor (Company, Organization or individual name(s)):**
Patrik Svensson, Phil Scott, Nils Andresen

**Existing OSS Project? (Yes/No):**
Yes

**Source Code URL:**
https://github.com/spectreconsole/spectre.console

**Project Homepage URL (if different):**
https://spectreconsole.net

**Project Transfer Signatories:**
Patrik Svensson, patrik@patriksvensson.se
Phil Scott, phil.scott@gmail.com
Nils Andresen, nils@nils-andresen.de

## 2.   Description
**Please provide a brief statement about your project in terms that are understandable to the target consumer of the library or project, i.e. an elevator pitch for the project:**

Spectre.Console is a .NET library that makes it easier to create beautiful console applications with .NET.

**Please provide a 1 sentence (<140 character) summary of your project to help users when searching the .NET Foundation projects**

Spectre.Console is a .NET library that makes it easier to create beautiful console applications with .NET.

## 3.   Project Governance

**Project Lead:**
(Who is the primary contact point for the community and the .NET Foundation when discussing governance of the project.)

Name: Patrik Svensson
Email: patrik@patriksvensson.se
GitHub Profile URL: https://github.com/patriksvensson

**Committers:**

Which individuals have commit / write access to the repository, what is their GitHub ID and who is their employer (if contributions are on behalf of an employer)

Patrik Svensson, @patriksvensson
Phil Scott, @phil-scott-78
Nils Andresen, @nils-a

**Governance Model:**

Please describe how new code changes are proposed to the project, how those changes are reviewed and how a decision is made to accept proposed changes. Also describe the process for identifying and appointing new committers.

Our contribution process can be found here: https://github.com/spectreconsole/spectre.console/blob/main/CONTRIBUTING.md#contributing-process

To boil it down, the maintainer team drives the vision of the project, but we accept suggestions for new features and bug reports via GitHub issues. If someone want to create a pull request for something, they will need to create an issue and get sign off.

**CLA**

If already an OSS project, was a Contribution License Agreement in place for contributions accepted? How does the project check who has signed one?

We use CLA-bot. A PR cannot be merged until the user have signed the CLA.

**CLA Notification Alias**
Provide an email address that will receive CLA related notifications from the .NET Foundation CLA automation

patrik@patriksvensson.se

**Contribution Model.**  Under the .NET Foundation contribution model, a project retains ownership of the copyright, but grants the .NET Foundation a broad license to the project’s code and other intellectual property. The project also confirms that the project’s submissions to .NET Foundation are its own original work (there are also instructions for any third party materials that might be included).

## 4.   Repository Layout
The .NET Foundation host guidance for new projects and details on recommended structure here:
[https://github.com/dotnet/home/tree/master/guidance](https://github.com/dotnet/home/tree/master/guidance)

Note that the open source repository should be the master where changes are made by the core development team using the same PR process that is used for non-committer contributions.

Please define below any changes you would want to make to your repositories as part of the process of joining the .NET Foundation

We will need to add a `NOTICE.md` but apart from that we should be compliant with the recommended structure. Our documentation is however under `docs` and not `Documentation` and this is not something we wish to change due to technical reasons.

## 5.  Eligibility Criteria
Please complete the following for your project
* The project is built on the .NET platform and/or creates value within the .NET ecosystem.
- [x] Yes 
- [ ] No
* The project produces source code for distribution to the public at no charge.
- [ ] Yes 
- [x] No
* The project's code is easily discoverable and publicly accessible (preferably on GitHub).
- [x] Yes 
- [ ] No
* The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).
- [x] Yes 
- [ ] No
* When applicable, project must use reproducible build settings in its toolchain.
- [x] Yes 
- [ ] No
* The project uses [Source Link.](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
- [x] Yes 
- [ ] No
* The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).
- [x] Yes 
- [ ] No
* The project code signs their artifacts as appropriate.
- [ ] Yes 
- [x] No
* The project organization has 2FA enabled. Requiring 2FA must be done as part of onboarding if not already enabled.
- [x] Yes
- [ ] No
* Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).
- [x] Yes 
- [ ] No
* Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.
- [x] Yes 
- [ ] No
* The copyright ownership of everything that the project produces is clearly defined and documented.
- [x] Yes 
- [ ] No
* The project has a public issue tracker where the status of any defect can be easily obtained.
- [x] Yes 
- [ ] No
* The project has a published Security Policy.
- [ ] Yes 
- [x] No
* The project has a home page which provides high level information about its status and purpose.
- [x] Yes 
- [ ] No
* The project has a public communication channel where community members can engage with maintainers.
- [x] Yes 
- [ ] No
* The project has a publicly available location where members can review and contribute to documentation.
- [x] Yes 
- [ ] No

## 6.   PR Plan

Need to get back to you about this.

## 7.   Infrastructure Requirements

We would need Authenticode Code signing for releases.

## 8.   Additional Notes

Nothing we can think about at the moment.

**Comment by patriksvensson** [comment]
Hello! I just wanted to see what the status of this is. Thanks!

**Comment by ChrisSfanos** [comment]
Hi @patriksvensson - the project was accepted by the Board this week (congrats!), but the onboarding team is working on changes to the legal agreements, so we can't start the formal on-boarding process until those who wrapped up.  Sorry for the delays!

**Comment by patriksvensson** [comment]
@ChrisSfanos Thank you! No worries, I was just curious!

**Comment by ChrisSfanos** [comment]
Hi everyone!  We are ready (finally!) to begin the onboarding process.  The following checklist will track the work

## CLA
- [ ] Project Agreement Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)
- [ ] Enable two-factor authentication (2FA) for GitHub organization and all users

**Comment by ChrisSfanos** [comment]
Agreement is out for signing

**Comment by patriksvensson** [comment]
@ChrisSfanos Regarding `Updating license/copyright in the repo + updating file headers`, we've opted in for the "Contribution Model" is this still applicable?

**Comment by ChrisSfanos** [comment]
Hi @patriksvensson  - we have had all projects, regardless of model, make that change.  If there are concerns with it, we can definitely discuss it offline.  For the items in the Project Onboarding bottom half, I'll send out an email later once we complete the top two with a few more details for each one

**Comment by ChrisSfanos** [comment]
Hi @patriksvensson  - mistake on my part.  Copyright change is only for Assignment model.  As a favor, can you check the FAQ I included in my mail to you about a week ago?  We are trying to put a section in their that helps cover this and wanted you/your project's feedback on it

**Comment by patriksvensson** [comment]
@ChrisSfanos The FAQ is good! Perhaps a table row under the "Contribution License Agreement" part (Q10) could be added:

`Will I have to update the copyright and file headers` => `No`

**Comment by patriksvensson** [comment]
@ChrisSfanos

`Project Agreement Signing via DocuSign` is completed, so I guess we should continue enabling the CLA bot for the project. Will we need to export the existing signed CLAs?

`Enable two-factor authentication (2FA) for GitHub organization and all users`: All team members have 2FA enabled

What does `README Guidance updates` mean?
What

**Comment by patriksvensson** [comment]
Pinging in @phil-scott-78 and @nils-a as well

**Comment by ChrisSfanos** [comment]
Hey @patriksvensson  - I'm going to email you the details for both the CLA bot and the remaining work items - I'll do that shortly - thanks!

**Comment by ChrisSfanos** [comment]
Project is fully onboarded :-)
