### ISSUE TITLE
Review and Update Issue Templates

### ISSUE THREAD

**Issue by rprouse** [dotnet-foundation/projects#212]
It was raised that clairernovotny is still the assignee on most of the issue templates. We should review and update assignees and processes as appropriate.

**Comment by sbwalker** [comment]
@rprouse Agreed. I do not believe I have the permissions to make these types of changes to the repo... I will raise this to the new ED in our meeting this week.

**Comment by sbwalker** [comment]
@rprouse Chris Sfanos was able to modify the issue template for this repo - he removed Claire and added myself.

**Comment by nicoleabuhakmeh** [comment]
Tom/ED will be doing an audit of our templates in Github and within the organization to update some of these individuals in the documents.
