### ISSUE TITLE
Project Support Request: Stride game engine

### ISSUE THREAD

**Issue by tebjan** [dotnet-foundation/projects#216]
### Please fill in the information below:
- Stride
- 5th August 2022
- GitHub Enterprise support

We currently pay 40$ a month for GitHub, which is one of our biggest expenses. This is quite a lot for us, as we only have a budget from individual supporters who donate amounts in the lower $ range.

Is it possible to get a repository upgrade for our project so we can direct the money toward open-source developers instead?
https://github.com/stride3d/stride

See our expenses here:
https://opencollective.com/stride3d/expenses

Thanks a lot!

**Comment by VaclavElias** [comment]
I wonder if we could get also refund for the last x months if this is going to be approved? Thanks for any help with this ☺.

**Comment by nicoleabuhakmeh** [comment]
I've added in the DNF board to review this request.

**Comment by tebjan** [comment]
Is someone still working on this? We just had to pay another 40$ bill to GitHub, see: https://opencollective.com/stride3d/expenses

**Comment by tebjan** [comment]
This becomes a serious problem, we got a bill from GitHub of over 300$ last month! https://opencollective.com/stride3d/expenses

Can this please be returned, these are primarily small donations from the open-source gaming community. We cannot afford these kinds of GitHub bills from what we get in donations.

<img width="607" alt="image" src="https://user-images.githubusercontent.com/1094716/203819612-94612f69-ea2b-40bf-8405-eba4674b9cd4.png">

**Comment by VaclavElias** [comment]
Please, can we get any update or advice on who we should speak with to help us?

**Comment by tebjan** [comment]
Asking again, can we get someone working on this, please?

**Comment by rprouse** [comment]
@ChrisSfanos can we move the project into the .NET Foundation Enterprise account so that we can cover their build minutes? The GitHub Enterprise includes 50,000 build minutes vs the Team account which is only 3,000, so it will likely be no additional cost for us.

@tebjan and @VaclavElias would moving into the Enterprise organization be acceptable?

**Comment by tebjan** [comment]
Yes, this would be a good solution, thanks for looking into it.

**Comment by VaclavElias** [comment]
Thank you.

@tebjan, do we need to ask for any refund, or that is sorted?

![image](https://github.com/dotnet-foundation/projects/assets/4528464/8c925e77-b3fd-4629-9ef0-27f504e1fe28)

**Comment by ChrisSfanos** [comment]
> @ChrisSfanos can we move the project into the .NET Foundation Enterprise account so that we can cover their build minutes? The GitHub Enterprise includes 50,000 build minutes vs the Team account which is only 3,000, so it will likely be no additional cost for us.
> 
> @tebjan and @VaclavElias would moving into the Enterprise organization be acceptable?

Yep, we are going to move forward with the move to the GHE.  I'll sync internally on the next steps to move it

**Comment by ChrisSfanos** [comment]
An invitation has been sent to invite Stride3D to the DNF GHE

**Comment by ChrisSfanos** [comment]
The invite was accepted and approved and Stride3d is now a member of the .NET Foundation GHE.

**Comment by tebjan** [comment]
Fantastic, thanks a lot!

**Comment by VaclavElias** [comment]
Thank you very much 🙂
