### ISSUE TITLE
Silk.NET - Add member to a dotnet team

### ISSUE THREAD

**Issue by Perksey** [dotnet-foundation/projects#217]
### Please fill in the information below:
- **Project Name:** Silk.NET
- **Due by:** ASAP
- **Description:** We are currently onboarding a new maintainer to Silk.NET and need to grant them access to the org-level dev tracker. Obviously we don't have access to the dotnet-policy-bot being external, would it be possible for @Beyley to be granted access to @dotnet/silk-dotnet

**Comment by Perksey** [comment]
cc @richlander @terrajobst iirc you can add people to dotnet teams?

Many thanks in advance :)

**Comment by richlander** [comment]
NP. @Beyley has been invited to the org. I upgraded you to a maintainer of your team. Wants the invitation is accepted, you should be able to do the rest yourself. Tell me if someone doesn't work.

**Comment by Perksey** [comment]
Awesome, thank you so much. I'll check on whether I can do this myself herein tomorrow before closing this issue, but in any case we're sorted now. Thanks again :)

**Comment by Perksey** [comment]
Okay couldn't help myself this evening... Yep looks like I can do the team member adding myself now (obviously new org members will still need your help!)

Closing, thanks :)
