### ISSUE TITLE
Project Support Request: NUnit - Code Signing Certificate and Service

### ISSUE THREAD

**Issue by rprouse** [dotnet-foundation/projects#22]
- **Project Name:** NUnit
- **Due by:** N/A
- **Description:** The NUnit project would like to start signing our NuGet release packages in Azure DevOps. @onovotny has given me the information I need to complete the process once we have a cert. He asked me to create this issue here for tracking and to kick off the process.

The related NUnit issue is https://github.com/nunit/nunit/issues/3393

**Comment by jongalloway** [comment]
- [ ] Register trade name
- [ ] Request code signing certificate
- [ ] Configure signing service

**Comment by jongalloway** [comment]
@ChrisSfanos Can you please do the NUnit d/b/a setup?

**Comment by rprouse** [comment]
@jongalloway just "NUnit" is fine for the trade name.

**Comment by onovotny** [comment]
@ChrisSfanos Please lmk when the d/b/a is in the system and then I can take care of the DigiCert bits.

**Comment by onovotny** [comment]
The cert has been requested from DigiCert. Might take a few days.

**Comment by onovotny** [comment]
Closing as completed. Instructions have been communicated offline.
