### ISSUE TITLE
Nerdbank.Streams

### ISSUE THREAD

**Issue by AArnott** [dotnet-foundation/projects#224]
## 1.   General Information

**Project Name:** Nerdbank.Streams

**License:** MIT

**Contributor (Company, Organization or individual name(s)):** Andrew Arnott (@aarnott), Frederik Carlier (@qmfrederik), Gerd Katzenbeisser (@hakito), @asmichi, Rasmus Melchior Jacobsen (@rmja)

**Existing OSS Project? (Yes/No):** Yes

**Source Code URL:** https://github.com/AArnott/Nerdbank.Streams

**Project Homepage URL (if different):**

**Project Transfer Signatories:**
- Andrew Layne Arnott (andrewarnott@live.com)
The rest of the contributors listed earlier contributed very small code changes relative to the overall project. 

## 2.   Description

Specialized .NET Streams, pipes, and extensions for full duplex in-proc communication, web sockets, and multiplexing.

## 3.   Project Governance

**Project Lead:**

Name:   Andrew Arnott
 Email:   andrewarnott@live.com
 GitHub Profile URL: https://github.com/aarnott

**Committers:**

@aarnott (Microsoft employee, but this is an independent project)

**Governance Model:**

[Benevolent dictator](https://producingoss.com/html-chunk/benevolent-dictator.html)

**CLA**

If already an OSS project, was a Contribution License Agreement in place for contributions accepted? How does the project check who has signed one?

It does not already require a CLA. Several external folks have contributed via PR, but these have been relatively small (bug fix level).

**CLA Notification Alias**

andrewarnott@live.com

**Contribution Model.**  Under the .NET Foundation contribution model, a project retains ownership of the copyright, but grants the .NET Foundation a broad license to the project’s code and other intellectual property. The project also confirms that the project’s submissions to .NET Foundation are its own original work (there are also instructions for any third party materials that might be included).

**Project Trademarks - Licensed.**

## 4.   Repository Layout

No layout changes are planned. This repo already follows the same pattern that many of my other repos follow, including some that are already in the .NET Foundation.

## 5.  Eligibility Criteria
Please complete the following for your project
* The project is built on the .NET platform and/or creates value within the .NET ecosystem.
- [x] Yes 
- [ ] No
* The project produces source code for distribution to the public at no charge.
- [x] Yes 
- [ ] No
* The project's code is easily discoverable and publicly accessible (preferably on GitHub).
- [x] Yes 
- [ ] No
* The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).
- [x] Yes 
- [ ] No
* When applicable, project must use reproducible build settings in its toolchain.
- [x] Yes 
- [ ] No
* The project uses [Source Link.](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
- [x] Yes 
- [ ] No
* The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).
- [x] Yes 
- [ ] No
* The project code signs their artifacts as appropriate.
- [x] Yes 
- [ ] No
* The project organization has 2FA enabled. Requiring 2FA must be done as part of onboarding if not already enabled.
- [x] Yes
- [ ] No
* Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).
- [x] Yes 
- [ ] No
* Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.
- [x] Yes 
- [ ] No
* The copyright ownership of everything that the project produces is clearly defined and documented.
- [x] Yes 
- [ ] No
* The project has a public issue tracker where the status of any defect can be easily obtained.
- [x] Yes 
- [ ] No
* The project has a published Security Policy.
- [x] Yes 
- [ ] No
* The project has a home page which provides high level information about its status and purpose.
- [x] Yes 
- [ ] No
* The project has a public communication channel where community members can engage with maintainers.
- [x] Yes 
- [ ] No
* The project has a publicly available location where members can review and contribute to documentation.
- [x] Yes 
- [ ] No

## 6.   PR Plan

No plan necessary.

## 7.   Infrastructure Requirements

We can start authenticode signing the binary with the nerdbank cert created by the .NET Foundation when it inducted the Nerdbank.GitVersioning project.

## 8.   Additional Notes
None.

**Comment by samsp-msft** [comment]
This library has nearly 3M downloads on Nuget. I had reached out to @AArnott about it being a foundation project because we have a PR for CoreWCF that depends on it. I don't want to take dependencies on something without the seal of governance that a foundation project has.
It then turns out that a ton of other projects already depend on it, like JsonRPC, roslyn and dotnet interactive, so we are probably remis in not already having included it in the foundation.

**Comment by AArnott** [comment]
> The project has a published Security Policy.

I checked 'no' here. What might a security policy for an independent OSS repo look like? Any samples?

**Comment by mconnew** [comment]
@AArnott, I believe something like CoreWCF has [here](https://github.com/CoreWCF/CoreWCF/blob/main/SECURITY.md) is sufficient.

**Comment by AArnott** [comment]
Thank you. Security policy [published](https://github.com/AArnott/Nerdbank.Streams/commit/0a6a40fbb814ad69094639b64052bc941e4e70e5).

**Comment by samsp-msft** [comment]
Actually, I think that security reporting could be another area that the DNF could provide more support for projects - in acting as the point of initial contact and ensuring that the issues get looked into in a timely manner. A security bug is the main scenario where you need to quickly find out if the repo maintainers are still active, and if not find somebody who can investigate and patch.

**Comment by sbwalker** [comment]
This project was approved at the Sept 22 BOD meeting

**Comment by samsp-msft** [comment]
Sweet.

**Comment by AArnott** [comment]
Exciting. So what are the next steps? I can start signing the binaries with the authenticode key I already have. Who can help me move the repo to the `dotnet` org on github?

**Comment by ChrisSfanos** [comment]
Hey @AArnott  - I will get the transfer agreement out shortly and we will follow the steps below to on-board the project

## CLA
- [ ] Project Agreement Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)
- [ ] Enable two-factor authentication (2FA) for GitHub organization and all users

**Comment by ChrisSfanos** [comment]
Agreement is out for signing

**Comment by ChrisSfanos** [comment]
And we will need to get the repo moved to the dotnet org - that is required for the CLA bot (which will be automatically enabled once the move happens)

**Comment by AArnott** [comment]
I've enabled authenticode signing in the project pipeline. How can we move the repo to the dotnet org?

**Comment by ChrisSfanos** [comment]
It looks like the steps are here - https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository - I should be able to accept it from the dotnet org side

**Comment by ChrisSfanos** [comment]
Agreement is signed
@AArnott - did you get a chance to look at the transfer process in that github article?  Does it look like that will work?

**Comment by AArnott** [comment]
It didn't work. I got an access denied error. And the link you provided explains why:

> To transfer a repository that you own to an organization, you must have permission to create a repository in the target organization.

**Comment by AArnott** [comment]
@ChrisSfanos I can't push an update to nerdbank.streams to nuget.org now that the package is signed. nuget.org demands I upload a .cer file that matches the cert used to sign the package. Where can I get that file?

**Comment by ChrisSfanos** [comment]
I'll ping you in email and we can work to figure it out

**Comment by ChrisSfanos** [comment]
Hey Andrew - we are ready to onboard Nerdbank.Streams to the new CLA service and wrap up the onboarding checklist - will email you in a few

**Comment by ChrisSfanos** [comment]
@AArnott - looks like I lost track of this one - emailed you just now

**Comment by AArnott** [comment]
I'm ready to transfer the repo to the dotnet org, if I can be temporarily granted Create repo permission in the org.

**Comment by ChrisSfanos** [comment]
Hey Andrew - typically we do it the other way and grant DNFAdmin temporary perms to your org and I can do the transfer from there

**Comment by AArnott** [comment]
I don't have an org. nerdbank.streams is in my github user account.

**Comment by ChrisSfanos** [comment]
So I can't really give perms to the /dotnet org.  We've had other projects just create a temporary org, move the repo there and grant dnfadmin perms and then do the move - does that work?

**Comment by ChrisSfanos** [comment]
We moved the project to the /dotnet/ org so now it's covered automatically with the CLA.  That wraps up the last of the work items for onboarding and we can close out the issue - thanks!

**Comment by AArnott** [comment]
@ChrisSfanos I've lost admin access to the repo in the move. Can you please re-establish that?

**Comment by AArnott** [comment]
Thanks. The last issue seems to be that my Azure Pipelines no longer build PRs, even though I've updated them to point at the new repo location. Any idea why that might be?

**Comment by ChrisSfanos** [comment]
Hmm - that one I don't know anything about.  Let me ask and see
