### ISSUE TITLE
Arad Portal

### ISSUE THREAD

**Issue by ammarheidari** [dotnet-foundation/projects#226]
[Arad Portal](https://github.com/araditc/Arad.Portal)
### Arad Portal CMS
- Fully open Source
- multi tenant
- multilingual
- .net CMS
AradPortalCMS is a .net core fully open source, responsive, multitenant and multilingual 
Content management system Which allows site admin user to create a customized website based on his requirements.
This website can contain two parts. First part is products that can be added by site admin and sell them if he want.
Second part is data to exposure to end user as blog or content or news.
Admin user can create homepage , product List page, or content List page of the site dynamically as will be described on this document later.
AradPortalCMS is a web application based on .net 5 and mongo db as its database.
Bootstrap 5.1 and its classes is used In UI of project  as long as it satisfied our requirements, some other external UI plugins also used in some pages that will be described on packages and plugins of project and developer guide section.

This documentation has two main Part First Part (Site Admin Guide) is for a site admin who is not a developer and supposed to use this application for creating a website and don’t suppose to extend and develop the application source code.

Second Part (Developer Guide) is for developer who supposed to extend and develop source ode of the application, this part should also be read more than First part by developer.

**Comment by sbwalker** [comment]
The Project Committee Charter (https://github.com/dotnet-foundation/projects) contains eligibility criteria which is used to evaluate project applications. In regards to licensing the criteria is "The code is offered under a standard, permissive open source license which has been approved by the .NET Foundation". Arad.Portal is currently licensed under a non-permissive GPL license, so this project application cannot be approved.

**Comment by ammarheidari** [comment]
Hello
The license updated. Please check again.

**Comment by sbwalker** [comment]
Now that the project meets the Eligibility criteria, the Project Committee will review your application at its next scheduled meeting in November. Based on the fact that you were able to immediately change the license from GPL to MIT, it would seem to indicate that the project has very limited adoption. This will likely be evident in the Activity metrics which the Project Committee will review next month. In general, the .NET Foundation only accepts projects which have achieved a critical mass and established a viable community of users and contributors.

**Comment by ammarheidari** [comment]
Please let me know which license I should use for accept this request?

**Comment by ammarheidari** [comment]
Please let me know which license I should use for accept this request?

**Comment by sbwalker** [comment]
The Open Source Initiative (https://opensource.org/licenses) provides a good explanation of "permissive" licenses:

What is a "permissive" Open Source license?

A "permissive" license is simply a non-copyleft open source license — one that guarantees the freedoms to use, modify, and redistribute, but that permits proprietary derivative works. 

The most common permissive licenses used in .NET Foundation are:

MIT
Apache 2.0
BSD

**Comment by ammarheidari** [comment]
We use MIT license. Please accept this project

**Comment by sbwalker** [comment]
The project will be reviewed by the Project Committee at its next scheduled meeting in November. As mentioned earlier in this thread this will include a review of the project's Activity metrics which are usually an effective method of determining if a project has achieved a critical mass of adoption and established a viable community of users and contributors.

**Comment by sbwalker** [comment]
The Project Committee reviewed this application at the November meeting and the general consensus was that the project's activity metrics are not yet at a level where it could be considered an official Member Project. As a result, the project was not referred to the BOD but will be added to the Seed category (a category reserved for projects which are relatively new or have not attracted a critical mass of users or contributors).

**Comment by sbwalker** [comment]
This project appears to no longer exist

**Comment by ammarheidari** [comment]
Please check again

**Comment by sbwalker** [comment]
Ok thank you - is there a reason it was offline?

**Comment by ammarheidari** [comment]
Just for some maintenance
