### ISSUE TITLE
Kerberos.NET

### ISSUE THREAD

**Issue by SteveSyfuhs** [dotnet-foundation/projects#23]
## 1.   General Information

**Project Name:** Kerberos.NET

**License:** MIT

**Contributor (Company, Organization or individual name(s)):** Steve Syfuhs

**Existing OSS Project? (Yes/No):** https://github.com/SteveSyfuhs/Kerberos.NET

**Source Code URL:** https://github.com/SteveSyfuhs/Kerberos.NET

**Project Homepage URL (if different):**

**Project Transfer Signatories:** Steve Syfuhs steve@syfuhs.net
Full legal name and email address required of the individual(s) with the authority to transfer or contribute the project to the .NET Foundation. Note that if you'd prefer not to include this in the public application, it can be submitted via e-mail to contact@dotnetfoundation.org (referencing this issue number).

## 2.   Description
**Please provide a brief statement about your project in terms that are understandable to the target consumer of the library or project, i.e. an elevator pitch for the project:**

Kerberos.NET is a managed implementation of the Kerberos authentication protocol used by the majority of production enterprise platforms. Hundreds of millions of enterprise Windows clients authenticate using Kerberos every day but there are noticeable gaps in how these clients seamlessly authenticate to cloud services. This library is intended to bridge those gaps between Windows on-premises model with hybrid cloud services without taking a dependency on any platform.

**Please provide a 1 sentence (<140 character) summary of your to help users when searching the .NET Foundation projects**

(What?)

## 3.   Project Governance
Please complete this section about who will be maintaining the open source project and how it will run.
**Project Lead:**
(Who is the primary contact point for the community and the .NET Foundation when discussing governance of the project.)

Name:   Steve Syfuhs
 Email:   steve@syfuhs.net
 GitHub Profile URL: https://github.com/SteveSyfuhs

**Committers:**

Which individuals have commit / write access to the repository, what is their GitHub ID and who is their employer (if contributions are on behalf of an employer)

No one besides myself has write access to the repo. All changes flow through forked PRs.

**Governance Model:**

Please describe how new code changes are proposed to the project, how those changes are reviewed and how a decision is made to accept proposed changes. Also describe the process for identifying and appointing new committers.

Changes (features, bugs) are proposed as GitHub issues with a general intent to describe what the problem is, how it should be tackled, potentially what workarounds there are, and how it should be validated. These issues are open to anyone to take on, and the changes themselves are submitted through PRs. Each committed change is automatically built through CI with unit and E2E tests run. Only passing builds can be merged into the main branch. Most changes, unless trivial, are required to include test coverage. Whether a change is accepted or not does not follow a strong process, but is more of a review against intent, style, security promises, and actual implementation.

**CLA**

If already an OSS project, was a Contribution License Agreement in place for contributions accepted? How does the project check who has signed one?

It is an existing OSS project, but a CLA has not been introduced yet.

**CLA Notification Alias**
Provide an email address that will receive CLA related notifications from the .NET Foundation CLA automation

steve@syfuhs.net

**Project Transfer Type**

Projects may join the .NET Foundation in one of two ways and you should chat with your .NET Foundation contact to discuss the best mechanism for your project. You can either a) assign the copyright of the project's source code to the .NET Foundation or b) contribute the project source code to the .NET Foundation under an open source license. Assignment is the preferred approach, but licensing a project to the Foundation may be more appropriate for longer running open source projects that have not previously had a contribution license agreement and have accepted contributions from many different sources.
a) Assignment
b) Contribution

**Assignment** is chosen.

## 4.   Repository Layout
The .NET Foundation host guidance for new projects and details on recommended structure here:
[https://github.com/dotnet/home/tree/master/guidance](https://github.com/dotnet/home/tree/master/guidance)

Note that the open source repository should be the master where changes are made by the core development team using the same PR process that is used for non-committer contributions.

Please define below any changes you would want to make to your repositories as part of the process of joining the .NET Foundation

Optionally it might make sense to migrate the repo under the dotnet org.

## 5.   PR Plan
Please summarize the public relations plan for the announcement when joining the foundation (and releasing as open source if appropriate). What is the main story we wish to promote, through what channels, what issues should we be aware of?  For significant news events then please also work with your .NET Foundation contact to ensure a [full PR plan](https://dotnetfoundation.sharepoint.com/Shared%20Documents/PR/Communications%20Plan%20TEMPLATE.docx?web=1) is developed.

The project is starting to get enough attention that it requires more than just my oversight. Bringing it to the .NET Foundation will provide a more cohesive governance model and clear long term intent to contribute and keep the project running.

## 6.   Infrastructure Requirements
Please describe any infrastructure requirements for the project. For example, how will build servers be operated? Any web hosting or service hosting requirements? Do we need to set up SSL certificates or provide Authenticode Code Signing arrangement for releases?

Build: It would be preferable to move away from my personal builds accounts. It doesn't require much: https://github.com/SteveSyfuhs/Kerberos.NET/blob/master/build.yaml
Signing: Code signing and Nuget Package signing

## 7.   Additional Notes
Please provide any additional information required or use this area for notes during the onboarding process. If this open source project has similarities with any other projects in this space then please detail them and why this project is different. If there are any potential issues that you feel the project might need help with early on then also state them here and discuss with your .NET Foundation Contact.

One notable reason for transitioning this to the .NET Foundation is that certain Microsoft teams have intentions of using this library for a handful of projects and it is a good way to keep the correct boundaries.

**Comment by SteveSyfuhs** [comment]
Ping 🙂

**Comment by ChrisSfanos** [comment]
CLA out for signing

**Comment by ChrisSfanos** [comment]
CLA signoff is complete - kicked off CLA GitHub onboarding

**Comment by ChrisSfanos** [comment]
We will track the remaining onboarding work via this checklist:

## Onboarding
- [ ] CLA Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Post Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Enable CLA automation for future contributors
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)

**Comment by ChrisSfanos** [comment]
CLA onboarding complete - post onboarding email sent

**Comment by ChrisSfanos** [comment]
Onboarding complete - closing
