### ISSUE TITLE
Code Signing Certificate Request: TerraFX

### ISSUE THREAD

**Issue by tannergooding** [dotnet-foundation/projects#230]
The projects in the TerraFX organization need code signing support. This would require a new certificate.

### Please fill in the information below

- **Project Name:** TerraFX (http://github.com/terrafx)
- **LastPass Email (or send offline):** `admin <at> terrafx <dot> dev`

Certificate onboarding checklist:

- [x] Register trade name @ChrisSfanos
- [x] Create configuration in Code Signing Service
- [x] Create organization with DigiCert
- [x] Request certificate from DigiCert
- [ ] Received certificate and finalize sign service configuration
- [ ] Provide credentials in shared folder in LastPass

**Comment by ChrisSfanos** [comment]
Trade name registration submitted

**Comment by ChrisSfanos** [comment]
Looks like I got the signing service config working - now onto Digicert :-)

**Comment by ChrisSfanos** [comment]
Sorry for the delay - progress on this.  Created CodeSign entry and generated metadata.  Certificate request submitted

**Comment by ChrisSfanos** [comment]
DigiCert is doing some validation today - I expect to make more progress in the next day or two and get the cert in-hand

**Comment by tannergooding** [comment]
Any further update here and anything I can help with on my end?

**Comment by ChrisSfanos** [comment]
Hey Tanner - sorry I lost track of this one.  The cert is ready.  We are moving off the old signing service into a new one.  I'm going to start a thread with you and Claire on it in a minute

**Comment by tannergooding** [comment]
This was all resolved
