### ISSUE TITLE
dotnet-console-games

### ISSUE THREAD

**Issue by ZacharyPatten** [dotnet-foundation/projects#233]
## 1.   General Information

- **Project Name:** [`dotnet-console-games`](https://github.com/ZacharyPatten/dotnet-console-games)
- **License:** [`MIT`](https://github.com/ZacharyPatten/dotnet-console-games/blob/main/LICENSE)
- **Contributor(s):** [`see contributors on GitHub`](https://github.com/ZacharyPatten/dotnet-console-games/graphs/contributors)
- **Existing OSS Project? (Yes/No):** `Yes`
- **Source Code URL:** [`https://github.com/ZacharyPatten/dotnet-console-games`](https://github.com/ZacharyPatten/dotnet-console-games)
- **Project Homepage URL (if different):** _`(same as above)`_
- **Project Transfer Signatories:** [`Zachary Patten`](https://github.com/ZacharyPatten) - <a href="mailto:sevenix.zp@gmail.com">`sevenix.zp@gmail.com`</a>

## 2.   Description

- **Please provide a brief statement about your project in terms that are understandable to the target consumer of the library or project, i.e. an elevator pitch for the project:**
  `Game examples implemented as .NET console applications primarily for providing education and inspiration. :)`
  <br />
  > **Note**
  > - dotnet-console-games is not a library. It does not have a NuGet package. It is intended to be a resource for developers.
  > - Aside from being a resource, it would also make a great entry point for new developers wanting to contribute to a repo under the .NET Foundation.
- **Please provide a 1 sentence (<140 character) summary of your project to help users when searching the .NET Foundation projects:** <em>`(same as above)`</em>

## 3.   Project Governance

- **Project Lead:** [`Zachary Patten`](https://github.com/ZacharyPatten)
- **Committers:** `N/A (pull requests to the main branch currently require lead's approval)`
- **Governance Model:** `(standard pull request process in GitHub)`
- **CLA - If already an OSS project, was a Contribution License Agreement in place for contributions accepted? How does the project check who has signed one?** `N/A`

## 4.   Repository Layout

- `The project already has an established general layout, but changes can be made if needed/desired (ex. a code of conduct is not currently included but can be added).`

## 5.  Eligibility Criteria

- `✅ Yes` **The project is built on the .NET platform and/or creates value within the .NET ecosystem.**
- `✅ Yes` **The project produces source code for distribution to the public at no charge.**
- `✅ Yes` **The project's code is easily discoverable and publicly accessible (preferably on GitHub).**
- `🔳 N/A` **The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).**
- `🔳 N/A` **When applicable, project must use reproducible build settings in its toolchain.**
- `❌ No` **The project uses [Source Link.](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)**
- `🔳 N/A` **The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).**
- `🔳 N/A` **The project code signs their artifacts as appropriate.**
- `✅ Yes` **The project organization has 2FA enabled. Requiring 2FA must be done as part of onboarding if not already enabled.**
- `✅ Yes` **Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).**
- `✅ Yes` **Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.**
- `✅ Yes` **The copyright ownership of everything that the project produces is clearly defined and documented.**
- `✅ Yes` **The project has a public issue tracker where the status of any defect can be easily obtained.**
- `❌ No` **The project has a published Security Policy.**
- `✅ Yes` **The project has a home page which provides high level information about its status and purpose.**
- `✅ Yes` **The project has a public communication channel where community members can engage with maintainers.**
- `✅ Yes` **The project has a publicly available location where members can review and contribute to documentation.**

## 6.   PR Plan

- `Just adopting the project. I am willing to migrate the repo into the dotnet GitHub organization if desired. `

## 7.   Infrastructure Requirements

- `None`

## 8.   Additional Notes

- `None`

**Comment by sbwalker** [comment]
This project was approved by the BOD in the December meeting.

**Comment by ChrisSfanos** [comment]
Hello!  We will start the onboarding process now this project and follow this checklist

## CLA
- [ ] Project Agreement Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)
- [ ] Enable two-factor authentication (2FA) for GitHub organization and all users

**Comment by ChrisSfanos** [comment]
agreement is out for signing

**Comment by ZacharyPatten** [comment]
> [ ] Project Agreement Signing via DocuSign

> agreement is out for signing

👍

I have signed the agreement via Docusign.

**Comment by ChrisSfanos** [comment]
Agreement is signed - putting the project in the CLA onboarding queue.  Emailing coming with onboarding steps

**Comment by ChrisSfanos** [comment]
We moved the repo to the /dotnet org so the CLA is now enabled - sending the list of remaining work items now

**Comment by ZacharyPatten** [comment]
As for the onboarding checklist, I believe I have completed everything that was pending on repo/code side. Let me know if otherwise.

**Comment by ChrisSfanos** [comment]
onboarding complete - closing the tracking issue
