### ISSUE TITLE
Application for decoding Starcraft II Direct Strike Replays and generating statistics to join the .NET Foundation

### ISSUE THREAD

**Issue by ipax77** [dotnet-foundation/projects#239]
## 1.   General Information

**Project Name:** dsstats - Direct Strike Fan Project

**License:** [AGPL-3.0 license](https://github.com/ipax77/dsstats/blob/master/LICENSE)

**Contributor (Company, Organization or individual name(s)):** Philipp Hetzner ([ipax77](https://github.com/ipax77)), [Firestorm-253](https://github.com/Firestorm-253)

**Existing OSS Project? (Yes/No):** Yes

**Source Code URL:** https://github.com/ipax77/dsstats

**Project Homepage URL (if different):** https://dsstats.pax77.org/

**Project Transfer Signatories:**
Philipp Hetzner - ph.ilipp@web.de

## 2.   Description
Direct Strike Fan Project
Fan Project for analyzing [Starcraft II](https://starcraft2.com/) [Direct Strike](https://www.patreon.com/Tya) Replays

## 3.   Project Governance
**Project Lead:**
Name:   Philipp Hetzner
 Email:   ph.ilipp@web.de
 GitHub Profile URL: https://github.com/ipax77

**Committers:**
[GitHub contributors list](https://github.com/ipax77/dsstats/graphs/contributors)

**Governance Model:**
[CODE_OF_CONDUCT](https://github.com/ipax77/dsstats/blob/master/CODE_OF_CONDUCT.md)
[CONTRIBUTING](https://github.com/ipax77/dsstats/blob/master/CONTRIBUTING.md)

**CLA**

If already an OSS project, was a Contribution License Agreement in place for contributions accepted? How does the project check who has signed one? ```N/A```

## 4.   Repository Layout
GitHub default

## 5.  Eligibility Criteria

* The project is built on the .NET platform and/or creates value within the .NET ecosystem.
- [x] Yes 
- [ ] No
* The project produces source code for distribution to the public at no charge.
- [x] Yes 
- [ ] No
* The project's code is easily discoverable and publicly accessible (preferably on GitHub).
- [x] Yes 
- [ ] No
* The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).
- [x] Yes 
- [ ] No
* When applicable, project must use reproducible build settings in its toolchain.
- [x] Yes 
- [ ] No
* The project uses [Source Link.](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
- [x] Yes 
- [ ] No
* The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).
- [ ] Yes 
- [x] No
* The project code signs their artifacts as appropriate.
- [x] Yes 
- [ ] No
* The project organization has 2FA enabled. Requiring 2FA must be done as part of onboarding if not already enabled.
- [x] Yes
- [ ] No
* Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).
- [x] Yes 
- [ ] No
* Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.
- [x] Yes 
- [ ] No
* The copyright ownership of everything that the project produces is clearly defined and documented.
- [x] Yes 
- [ ] No
* The project has a public issue tracker where the status of any defect can be easily obtained.
- [x] Yes 
- [ ] No
* The project has a published Security Policy.
- [x] Yes 
- [ ] No
* The project has a home page which provides high level information about its status and purpose.
- [x] Yes 
- [ ] No
* The project has a public communication channel where community members can engage with maintainers.
- [x] Yes 
- [ ] No
* The project has a publicly available location where members can review and contribute to documentation.
- [x] Yes 
- [ ] No

## 6.   PR Plan
We are trying to get the .NET MAUI Blazor app into the Microsoft Store

## 7.   Infrastructure Requirements
The .NET MAUI Blazor app needs a [signing certificate](https://learn.microsoft.com/en-us/dotnet/maui/windows/deployment/publish-cli?view=net-maui-7.0#installing-the-app) 
The Website/API part is currently running in a docker container and is using a MySQL Server

## 8.   Additional Notes
The Project is using the nuget packages [pax.BlazorChartJs](https://www.nuget.org/packages/pax.BlazorChartJs/) and [s2protocol.NET](https://www.nuget.org/packages/s2protocol.NET/) developed by the Project Lead (both MIT licensed) and currently has ~30 active users. On [reddit](https://www.reddit.com/r/dotnetcore/comments/dap9dj/my_way_to_net_core_30/) is a story of how the project started over three years ago.

**Comment by sbwalker** [comment]
Currently the .NET Foundation only accepts projects which are licensed under permissive open source licenses (this is documented as part of the Project Charter - https://github.com/dotnet-foundation/projects ). This project is available under a GPLV3 license which is a non-permissive license.

**Comment by ipax77** [comment]
Thank you for the information
