### ISSUE TITLE
Project Support Request: DotVVM - Code Signing Certificate and Service

### ISSUE THREAD

**Issue by tomasherceg** [dotnet-foundation/projects#24]
- **Project Name:** DotVVM
- **Due by:** N/A
- **Description:** We'd like to start signing our NuGet packages.

**Comment by onovotny** [comment]
@ChrisSfanos can you please register a d/b/a for DotVVM?

**Comment by ChrisSfanos** [comment]
Request submitted - Request ID: 0-011-055-433

**Comment by onovotny** [comment]
@tomasherceg what email address should we use for sharing a LastPass folder? Do you have a lastpass account already? Feel free to send it to me offline.

**Comment by onovotny** [comment]
@tomasherceg 

Certificate requested from CA and client configuration created and shared via LastPass.

Please treat both the username and passwords as secrets.

If you're using Azure Pipelines, I have a recommended template here that splits build from signing into separate stages to minimize secret exposure. I'm happy to help review your configuration as needed.

https://github.com/onovotny/CodeSigningDemo/blob/master/azure-pipelines.yml

**Comment by onovotny** [comment]
Closing as completed. The certificate has been issued and setup in the signing service. Please reach out with any questions getting your pipeline configured.
