### ISSUE TITLE
Project Support Request: Polly - Code Signing Certificate and Service

### ISSUE THREAD

**Issue by joelhulen** [dotnet-foundation/projects#25]
Project Name: Polly
Due by: N/A
Description: The Polly project would like to start signing our NuGet release packages. @onovotny has given me the information I need to complete the process once we have a cert. He asked me to create this issue here for tracking and to kick off the process.

Please set the certificate subject to: **Polly (.NET Foundation)**

**Comment by onovotny** [comment]
@ChrisSfanos can you please register a d/b/a for Polly?

**Comment by ChrisSfanos** [comment]
Submitted - request ID: 0-011-055-433

**Comment by onovotny** [comment]
@joelhulen what email address should we use for sharing a LastPass folder? Do you have a lastpass account already? Feel free to send it to me offline.

**Comment by joelhulen** [comment]
Answered LastPass question offline.

**Comment by onovotny** [comment]
@joelhulen 

Certificate requested from CA and client configuration created and shared via LastPass.

Please treat both the username and passwords as secrets.

If you're using Azure Pipelines, I have a recommended template here that splits build from signing into separate stages to minimize secret exposure. I'm happy to help review your configuration as needed.

https://github.com/onovotny/CodeSigningDemo/blob/master/azure-pipelines.yml

**Comment by onovotny** [comment]
Closing as completed. The certificate has been issued and setup in the signing service. Please reach out with any questions getting your pipeline configured.
