### ISSUE TITLE
Unity Container

### ISSUE THREAD

**Issue by ENikS** [dotnet-foundation/projects#26]
## 1.   General Information

**Project Name:** Unity Container

**License:** Apache 2.0

**Contributor (Company, Organization or individual name(s)):** ENikS

**Existing OSS Project? (Yes/No):** Yes

**Source Code URL:** https://github.com/unitycontainer

**Project Homepage URL (if different):**

**Project Transfer Signatories:** Evgueni Sadovoi esadovoi@eniks.com

## 2.   Description
 The Unity Container (Unity) is a full featured, extensible dependency injection (DI/IoC) container.

## 3.   Project Governance
Project is maintained by ENikS and it will remain open source in eternity. 

**Project Lead:** ENikS 

Name:   Evgueni Sadovoi
 Email:   esadovoi@eniks.com
 GitHub Profile URL: https://github.com/ENikS

**Committers:**
No one is committing to the project except ENikS

**Governance Model:**

ENikS makes all the decisions about project development.

**CLA**

There is no CLA implemented for the project at the moment. 

**CLA Notification Alias**

none

**Project Transfer Type** 

Contribution

## 4.   Repository Layout

[Unity Organization](https://github.com/unitycontainer) contains individual repositories designated to each distributed package. Central [Unity](https://github.com/unitycontainer/unity) repository references other repositories as sub-modules and hosts development environments for current and feature versions.

All repositories in the organization are open source.

## 5.   PR Plan

Unity will announce membership in the foundation. It should assure continuity and support for OSS.

## 6.   Infrastructure Requirements

I am working on converting CI/CD integration to Azure DevOps pipelines.
Code signing certificate will be required to sign distributed packages

## 7.   Additional Notes

Unity Container organization is one of the oldest IoC implementations with 16+ distributed packages and total number of downloads in 60+ millions. 

The project requires significant effort for modernization and could use any help it could get. 

The main goal of joining the foundation is securing assistance in creating sustainable support from users and consumers of the project.

**Comment by onovotny** [comment]
Hi @ENikS, thanks for your application. Can you please complete the remaining sections (all are required), and then we can take it to the advisory council and board? Happy to answer questions/clarify things as needed.

**Comment by ENikS** [comment]
@onovotny 
I need some help with PR part.

**Comment by ChrisSfanos** [comment]
CLA out for signing

**Comment by ENikS** [comment]
@ChrisSfanos  @onovotny 

The CLA you sent requires transfer of trademark (Exhibit A). I would like to keep the ownership and just license it. Could you please change it to Licensed Marks (Exhibit B)?

**Comment by ChrisSfanos** [comment]
I'll need @onovotny to sign off on that, and then I'll void the old document and resend

**Comment by ENikS** [comment]
Thank you

**Comment by onovotny** [comment]
I've reached out to our lawyer for input.

**Comment by ENikS** [comment]
@ChrisSfanos 

Could you please delete old agreement, the one with transferred trademark? It floods my inbox with reminders.

@onovotny  
Any word from your legal department?

**Comment by ChrisSfanos** [comment]
We will track the remaining onboarding work via this checklist:

## Onboarding
- [ ] CLA Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Post Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Enable CLA automation for future contributors
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)

**Comment by ENikS** [comment]
I have a question:

I am planning to develop Unity full time. Obviously it would need to generate some kind of income for me to do so. Are there any restrictions on what I can and can't do?

**Comment by onovotny** [comment]
The eligibility criteria for member projects, new and ongoing, is listed here: https://github.com/dotnet-foundation/projects#eligibility-criteria

Beyond that, you can do whatever you want with it.

**Comment by ChrisSfanos** [comment]
I've updated the CLA and it's out for signing - please review/sign at your first opportunity so we can move forward with the onboarding

**Comment by ChrisSfanos** [comment]
CLA is signed.  CLA bot config email sent

**Comment by ChrisSfanos** [comment]
CLA bot complete - post onboarding supplemental email sent

**Comment by ENikS** [comment]
Might take some time to complete the rest, trying to survive this new, glamorous virus

**Comment by ChrisSfanos** [comment]
Completely understand - I'll check in in about a week and see how it's going

**Comment by ChrisSfanos** [comment]
Hey @ENikS  - just checking in - have you made any progress with the onboarding?

**Comment by ENikS** [comment]
Not much progress, sorry. Still don't feel too well.

**Comment by ChrisSfanos** [comment]
Hey @ENikS - hoping you are feeling better.  Have you had an opportunity to make progress?

**Comment by ENikS** [comment]
I've completed the following:
- Joining the Project leader mailing list
- Joining the Project leader Slack channel
- Reviewing the .NET Foundation Code of Conduct
-  Add Project to the .NET Foundation project list

**Comment by ENikS** [comment]
I've updated license in repositories and projects to be:
```
Copyright © .NET Foundation and Contributors. 
All Rights Reserved
```

**Comment by ChrisSfanos** [comment]
Thanks for the update @ENikS !  Looks like the README updates and the changes to the external website are all that is left to complete the on-board steps!

**Comment by ENikS** [comment]
Updated [external site](http://unitycontainer.org). (See footer)

**Comment by ChrisSfanos** [comment]
Verified - thanks!

**Comment by ENikS** [comment]
I've completed the rest of steps:
* Project layout cleanup (as appropriate)
* README Guidance updates

**Comment by ChrisSfanos** [comment]
Verified all item - marking this as closed - thanks!!

**Comment by ENikS** [comment]
So, what is happening now, once all the todos are done?

**Comment by ChrisSfanos** [comment]
The project has completed the full on-boarding to the .NET Foundation :-)

**Comment by ENikS** [comment]
Excellent!

@clairernovotny 
Now that the project is part of the Foundation, how would I apply for the certificate and other benefits we discussed earlier?

**Comment by ENikS** [comment]
@ChrisSfanos 

I do not see myself as a member of [foundation](https://github.com/dotnet), am I not accepted?

**Comment by ChrisSfanos** [comment]
Actually I don't have any control over that - adding @clairernovotny  for input

**Comment by ENikS** [comment]
@ChrisSfanos 

I been trying to ask @clairernovotny  questions above but she is ignoring this thread. Could you please contact her in some other way and bring this to her attention?

**Comment by clairernovotny** [comment]
Sorry, not intentionally filtering anything, just get a lot of GitHub notifications and it's easy to miss them. The membership committee takes care of member related things, did you submit an application to be a member? I can follow up with the committee in that case, they're usually pretty fast about processing things.

**Comment by ENikS** [comment]
@clairernovotny 

I was under assumption that being part of foundation automatically makes me a member. Could you please point me to the relevant info how to apply?

In emails with Oren Novotny we discussed certain benefits the project could apply for. This was the original motivation to became a member of the foundation. Could you provide me with some info on what could be done in this regard?

**Comment by clairernovotny** [comment]
There's a form to fill out here: https://dotnetfoundation.org/member/become-a-member to become a member. Onboarding a project doesn't automatically make its maintainers members (two different systems/processes), but all maintainers automatically qualify. Just put it in the notes section of the form.
