### ISSUE TITLE
Docker.DotNet is not represented on the website

### ISSUE THREAD

**Issue by mikeblas** [dotnet-foundation/projects#265]
Per issue #52 here, Docker.DotNet is a DotNet foundation project.

However, the project can't be found anywhere on the site. 

1. Start at https://dotnetfoundation.org/projects/project-search
2. Search for "Docker"
3. No results

or

1. Start at https://dotnetfoundation.org/projects/project-search
2. Click "D" in the thumb tabs
3. No results (at all!)

or 

1. Start at the Docker.DotNet README at https://www.nuget.org/packages/Docker.DotNet/
2. Scroll to the penultimate section, which links to the DotNet foundation and claims membership
3. Click on the link in the sentence "Docker.DotNet is a [.NET Foundation](https://www.dotnetfoundation.org/projects) project."
4. It's 404

**Comment by galvesribeiro** [comment]
I was about to open an issue on this as well. Will follow up with the DNF folks to see what would it takes.

**Comment by ChrisSfanos** [comment]
I checked today and this has been fixed - we have been making website cleanups recently and this one was picked up then.
