### ISSUE TITLE
FluentValidation

### ISSUE THREAD

**Issue by JeremySkinner** [dotnet-foundation/projects#27]
## 1.   General Information

**Project Name:** FluentValidation

**License:** Apache2

**Contributor (Company, Organization or individual name(s)):** Jeremy Skinner

**Existing OSS Project? (Yes/No):** Yes

**Source Code URL:** https://github.com/jeremyskinner/fluentvalidation

**Project Homepage URL (if different):** https://fluentvalidation.net

**Project Transfer Signatories:** Jeremy Skinner jeremy@jeremyskinner.co.uk

## 2.   Description
**Please provide a brief statement about your project in terms that are understandable to the target consumer of the library or project, i.e. an elevator pitch for the project:**

FluentValidation is a .NET library for building strongly-typed validation rules for objects. Additionally it provides integration for automatic validation within ASP.NET-based projects. 

**Please provide a 1 sentence (<140 character) summary of your to help users when searching the .NET Foundation projects**
luentValidation is a .NET library for building strongly-typed validation rules for objects.

## 3.   Project Governance
Please complete this section about who will be maintaining the open source project and how it will run.
**Project Lead:**
(Who is the primary contact point for the community and the .NET Foundation when discussing governance of the project.)

Name:   Jeremy Skinner
 Email:   jeremy@jeremyskinner.co.uk
 GitHub Profile URL: http://github.com/jeremyskinner

**Committers:**

Which individuals have commit / write access to the repository, what is their GitHub ID and who is their employer (if contributions are on behalf of an employer)

Just me at present (@JeremySkinner)

**Governance Model:**

Please describe how new code changes are proposed to the project, how those changes are reviewed and how a decision is made to accept proposed changes. Also describe the process for identifying and appointing new committers.

Feature requests/chnages are proposed via new issues on the github project page. Discussion twill take place to ensure the proposed change makes sense, is within scope of the project, is beneficial/useful to the community and will not have a negative impact on maintainability. Once discussed, the contributor will send a PR which I will review and propose any necessary changes, and go through CI before being merged for the next release. 

I have not yet had to go through a process for identifying new committers. 

**CLA**

If already an OSS project, was a Contribution License Agreement in place for contributions accepted? How does the project check who has signed one?

No, not yet, although I would like to start doing this going forward. 

**CLA Notification Alias**
Provide an email address that will receive CLA related notifications from the .NET Foundation CLA automation

jeremy@jeremyskinner.co.uk

**Project Transfer Type**

Projects may join the .NET Foundation in one of two ways and you should chat with your .NET Foundation contact to discuss the best mechanism for your project. You can either a) assign the copyright of the project's source code to the .NET Foundation or b) contribute the project source code to the .NET Foundation under an open source license. Assignment is the preferred approach, but licensing a project to the Foundation may be more appropriate for longer running open source projects that have not previously had a contribution license agreement and have accepted contributions from many different sources.
a) Assignment
b) Contribution

I think contribution would make more sense as FluentValidation has been around for over 10 years and has a lot of contributions without a CLA. Happy to discuss this. 

## 4.   Repository Layout
The .NET Foundation host guidance for new projects and details on recommended structure here:
[https://github.com/dotnet/home/tree/master/guidance](https://github.com/dotnet/home/tree/master/guidance)

Note that the open source repository should be the master where changes are made by the core development team using the same PR process that is used for non-committer contributions.

Please define below any changes you would want to make to your repositories as part of the process of joining the .NET Foundation

## 5.   PR Plan
Please summarize the public relations plan for the announcement when joining the foundation (and releasing as open source if appropriate). What is the main story we wish to promote, through what channels, what issues should we be aware of?  For significant news events then please also work with your .NET Foundation contact to ensure a [full PR plan](https://dotnetfoundation.sharepoint.com/Shared%20Documents/PR/Communications%20Plan%20TEMPLATE.docx?web=1) is developed.

Blog post, twitter announcement & updated website. 

## 6.   Infrastructure Requirements
Please describe any infrastructure requirements for the project. For example, how will build servers be operated? Any web hosting or service hosting requirements? Do we need to set up SSL certificates or provide Authenticode Code Signing arrangement for releases?

Already in place. Website is hosted on GH pages and I own the domain. CI is on azure pipelines. 

## 7.   Additional Notes
Please provide any additional information required or use this area for notes during the onboarding process. If this open source project has similarities with any other projects in this space then please detail them and why this project is different. If there are any potential issues that you feel the project might need help with early on then also state them here and discuss with your .NET Foundation Contact.

**Comment by JeremySkinner** [comment]
Just wondering if there was any news on this? :smiley:

**Comment by jogibear9988** [comment]
@JeremySkinner 
see my ticket here: https://github.com/dotnet-foundation/projects/issues/46

**Comment by onovotny** [comment]
First, sorry for the delays. Things got caught up with the winter holidays and then the Executive Director transition. We're working to clear the various backlogs as fast as we can.

@ChrisSfanos is taking lead on processing the accepted projects and we should get through them shortly. 

Thank you for your patience.

**Comment by JeremySkinner** [comment]
Thanks @onovotny that's great to hear. Hope things are going well for you in the new role

**Comment by ChrisSfanos** [comment]
DocuSign with the agreement is out for signatures.  Since it's my first go at it, don't be shocked if we have to have a 2nd pass at it :-)

**Comment by JeremySkinner** [comment]
Thanks @ChrisSfanos. 

Just one thing I wanted to query - in the "Project Trademarks" section of the document "Disclaimed" is pre-ticked. Is that definitely correct? Just wanted to double check how Disclaimed/Licensed relates to the project transfer types of Assignment/Contribution, and make sure we're definitely going with the right one (Contribution). 

(Very possible i'm just misunderstanding the terminology!)  

Thanks!

**Comment by ChrisSfanos** [comment]
I checked a few previous ones and that was the option selected, so I went with it - @onovotny  should review to confirm this is correct for this entry

**Comment by JeremySkinner** [comment]
Thanks for clarifying - I've signed the document

**Comment by ChrisSfanos** [comment]
Document has been signed - closing this issue

Closes #27

**Comment by JeremySkinner** [comment]
What’s the next step?

**Comment by ChrisSfanos** [comment]
I'll let @onovotny chime in on that - my understanding was this issue just tracked the DocuSign work.  If we want to use it track additional steps, that's great and we can do that.

**Comment by onovotny** [comment]
We should have it track the complete steps in the process. 

Thanks!

**Comment by ChrisSfanos** [comment]
CLA signoff is complete - kicked off CLA GitHub onboarding

**Comment by ChrisSfanos** [comment]
CLA onboarding is complete

**Comment by JeremySkinner** [comment]
Hi @ChrisSfanos & @onovotny just a quick question about copyright notices. 

As we're going with Contribution rather than Assignment, I assume the copyright notices for the project will stay as "(c) Jeremy Skinner & contributors" rather than needing to be changed to "(c) .NET Foundation & contributors"? (Or does .NET Foundation become a copyright holder for Contribution too?)

Thanks!

**Comment by onovotny** [comment]
I'll follow up with the lawyer and get back to you.

**Comment by ChrisSfanos** [comment]
In an effort to be clear and transparent on the on-boarding/post onboarding processes, I'd like to track the steps via this checklist and update as we go until it's signed off.  First go at it:

## Onboarding
- [X ] CLA Signing via DocuSign
- [X ] CLA Onboarding via GitHub

## Post Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Enable CLA automation for future contributors
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)

**Comment by JeremySkinner** [comment]
Hi @ChrisSfanos the following are done and can be ticked off:

- Joining the Project leader mailing list (I've requested to join)
- Join slack channel
-  Enable CLA automation for future contributors (these are working nicely)
-  Reviewing the .NET Foundation Code of Conduct
-  Project layout cleanup (except for copyright)
- README updates
- PR to add to project list (https://github.com/dotnet/foundation/pull/166) 

>  Public Announcement via the .NET Foundation site/etc

I think this should be unticked, as there isn't an announcement yet

>  Updating license/copyright in the repo + updating file headers

Awaiting confirmation re copyright for contribution (vs assignment) before I change this.

**Comment by ChrisSfanos** [comment]
Re: announcement: it's going to be in this month's newsletter, which I've submitted the PR for.  So technically it's not public, but the work is done for it :-)

Updating the rest of the boxes - big thanks!

**Comment by ChrisSfanos** [comment]
We are going with .NET Foundation and contributors for the copyright - synced with Jeremy and he's going to make these changes by EOW

**Comment by JeremySkinner** [comment]
I've made the copyright changes, and also updated the project list PR with missing files. Let me know if there's anything else you need from me

**Comment by ChrisSfanos** [comment]
Thanks Jeremy!  Nope, looking at the list, that wraps up the onboarding process ... marking this one as closed out :-)

**Comment by JeremySkinner** [comment]
That’s great, thanks for all your help getting this sorted 😊
