### ISSUE TITLE
Project Support Request: FluentValidation (CLA bot no longer working)

### ISSUE THREAD

**Issue by JeremySkinner** [dotnet-foundation/projects#270]
It looks like the CLA bot is no longer working on the FluentValidation/FluentValidation repository - is there something that I need to do to re-enable it?

Thanks!

**Comment by ChrisSfanos** [comment]
We need to move to the new CLA service, but to enable our team to install it, I'll need you to (temporarily) elevate DNFAdmin to Owner.  Once we complete the install, you can revert the account back to member.  Drop me a note (chris.sfanos at dotnetfoundation.org) when you've made the change - thanks!

**Comment by JeremySkinner** [comment]
Thanks, that's done (and I've sent you an email)

**Comment by ChrisSfanos** [comment]
We migrated the project to the new CLA - I see PRs are properly getting processed.  Closing this
