### ISSUE TITLE
.


### ISSUE THREAD

**Issue by Somekabk** [dotnet-foundation/projects#273]
https://www.oracle.com/downloads/licenses/no-fee-license.html

**Comment by CAM-Gerlach** [comment]
Just FYI, this account has spammed this repo multiple times with spam issues (e.g. #272 , #276 ) as well as others (the CPython devguide) over the past month with no sign of genuine activity. As it has also spammed the CPython devguide with the same, we will be org-banning and reporting it, and you might want to consider doing the same. Thanks.
