### ISSUE TITLE
ASP.NET API Versioning Is Not Represented on the Website

### ISSUE THREAD

**Issue by commonsensesoftware** [dotnet-foundation/projects#274]
[ASP.NET API Versioning](https://github.com/dotnet/aspnet-api-versioning) is not represented on the updated website, but it is on the old website:

https://old.dotnetfoundation.org/projects/aspnet-api-versioning

To my knowledge, there is no pending action on the maintainer side to make this transition happen. It's been close to 6+ months since the _new_ website went live. When will the site be updated? Please advise.

**Comment by sbwalker** [comment]
The Project Committee was not involved in the site migration, but I will make sure your message gets routed to the appropriate location.

**Comment by commonsensesoftware** [comment]
Thank you. I've seen this issue come up for other projects as well. It's unclear why some projects have been migrated and others _still_ has not. The incomplete migration makes documentation and discovery painful.

**Comment by ChrisSfanos** [comment]
I should be able to add this as I have permissions to the website editor

Chris
________________________________

**Comment by sbwalker** [comment]
API Versioning is represented on the .NET Foundation Trends site which the Project Committee maintains:

https://www.dnfprojects.com/*/27/View/!/105/Mar-05-2023/Apr-04-2023

**Comment by ChrisSfanos** [comment]
This is fixed - ASP.NET API Versioning now appears on the Current projects list

**Comment by commonsensesoftware** [comment]
Confirmed fixed. Big thanks @ChrisSfanos. This issue is resolved.

**Comment by commonsensesoftware** [comment]
@ChrisSfanos  Quick question. Is there something else I need to do in order to bring all the other details like the logo and project info into the new site from the old site? Just having the project listed is a plus, but if there is something else for me to do in order to retain parity, I'll do it. I've noticed that some projects have it and some don't.

**Comment by ChrisSfanos** [comment]
Drop me a note at chris.sfanos @ dotnetfoundation.org and I'll chat with you about it
