### ISSUE TITLE
Project Support Request: [.NET MAUI Community Toolkit] Add .NET MAUI Community Toolkit to `Current Projects` Page on Website

### ISSUE THREAD

**Issue by brminnick** [dotnet-foundation/projects#286]
### Please fill in the information below:
- **Project Name:** .NET MAUI Community Toolkit
- **Due by:** NA
- **Description:** Add .NET MAUI Community Toolkit to [`Current Projects` page on .NET Foundation Website](https://dotnetfoundation.org/projects/current-projects)

Hi Friends! 

Could we add the .NET MAUI Community Toolkit to the [`Current Projects` page on the .NET Foundation Website](https://dotnetfoundation.org/projects/current-projects)?

- **Title:** .NET MAUI Community Toolkit
- **Description:** The .NET MAUI Community Toolkit is a collection of reusable elements for application development with .NET MAUI, including animations, behaviors, converters, effects, and helpers. It simplifies and demonstrates common developer tasks when building iOS, Android, macOS and WinUI applications using .NET MAUI.
- **Image Logo:** https://github.com/CommunityToolkit/Maui/blob/main/build/nuget.png
- **Project Website:** https://learn.microsoft.com/dotnet/communitytoolkit/maui/

👇 Currently, the .NET MAUI Community Toolkit isn't featured in the Current Projects page

<img width="1428" alt="image" src="https://github.com/dotnet-foundation/projects/assets/13558917/73ed536d-095c-48c8-9c7f-5c6a171c1d91">

**Comment by sbwalker** [comment]
@brminnick The .NET Foundation website only includes official .NET Foundation Member Projects. Please submit an application to have the .NET MAUI Community Toolkit considered as an official .NET Foundation project. You can find more information about the process here: https://github.com/dotnet-foundation/projects.

**Comment by brminnick** [comment]
Hi @sbwalker! I'm a bit confused. We are members of the .NET Foundation.

The .NET MAUI Community Toolkits have been an official .NET Foundation Project since its inception in 2021. 

👇 Here's some examples demonstrating our membership

## NuGet Package Ownership

The .NET Foundation is an official `Owner` on NuGet of all of our NuGet Packages:
- [`CommunityToolkit.Maui`](https://www.nuget.org/packages/CommunityToolkit.Maui/)
- [`CommunityToolkit.Maui.Core`](https://www.nuget.org/packages/CommunityToolkit.Maui.Core/)
- [`CommunityToolkit.Maui.Markup`](https://www.nuget.org/packages/CommunityToolkit.Maui.Markup/)
- [`CommunityToolkit.Maui.MediaElement`](https://www.nuget.org/packages/CommunityToolkit.Maui.MediaElement/)
<img width="300" alt="image" src="https://github.com/dotnet-foundation/projects/assets/13558917/2c53e23c-d899-479d-9882-2c7f11977521">

## Monthly Standups Stream to .NET Foundation YouTube Channel

We livestream every Monthly Standup to the .NET Foundation YouTube channel
- [.NET MAUI Community Toolkit Monthly Standup, May 2023](https://www.youtube.com/watch?v=mRxA-roTPt8)
- [.NET MAUI Community Toolkit Monthly Standup, April 2023](https://www.youtube.com/watch?v=3pJh1eYcYPg&t=2s&pp=ygUULm5ldCBmb3VuZGF0aW9uIG1hdWk%3D)
- [.NET MAUI Community Toolkit Monthly Standup, March 2023](https://www.youtube.com/watch?v=_O4u9gL5oOc&t=72s&pp=ygUULm5ldCBmb3VuZGF0aW9uIG1hdWk%3D)
- [(and every month in between)](https://www.youtube.com/@NETFoundation/search?query=maui%20community%20toolkit)
- [.NET MAUI Community Toolkit Monthly Standup, August 2021](https://www.youtube.com/watch?v=b7wVk4Udi_U)

## Previous .NET Foundation Work Tickets

I've worked with @ChrisSfanos to help resolve previous work tickets:
- https://github.com/dotnet-foundation/projects/issues/264

## .NET Foundation in our README

Each of READMEs highlight that we are members of the .NET MAUI Community Toolkit
- [`CommunityToolkit.Maui` README](https://github.com/CommunityToolkit/Maui/blob/main/README.md#net-foundation)
- [`CommunityToolkit.Maui.Markup` README](https://github.com/CommunityToolkit/Maui.Markup/blob/main/README.md#net-foundation)

**Comment by sbwalker** [comment]
@brminnick My apologies... the reason for my confusion is that I do not recall the Project Committee reviewing a Project Application for .NET MAUI Community Toolkit, nor can I locate a project application in the .NET Foundation issues - https://github.com/dotnet-foundation/projects/issues). The .NET MAUI Community Toolkit is also not represented on the .NET Foundation Project Trends site: https://www.dnfprojects.com/ where the Project Committee monitors ongoing activity of .NET Foundation projects.  I will sync up with @ChrisSfanos to get more clarity.

**Comment by brminnick** [comment]
No worries - thanks! 

I believe we were grandfathered into the .NET Foundation as members of the [.NET Community Toolkit org on GitHub](https://github.com/CommunityToolkit). It was previous "Windows Community Toolkit" until 2021 when @michael-hawker and I teamed to rebrand to the ".NET Community Toolkit" so that we could add more toolkits outside of the Windows ecosystem.

**Comment by sbwalker** [comment]
Ahh.... this makes sense now, as the Windows Community Toolkit is an official member of the .NET Foundation. I just noticed that Windows Community Toolkit is represented on https://www.dnfprojects.com and points to https://github.com/CommunityToolkit/WindowsCommunityToolkit - should it be replaced with the .NET MAUI Community Toolkit?

**Comment by sbwalker** [comment]
Also the Windows Community Toolkit is listed on the .NET Foundation website: https://dotnetfoundation.org/projects/project-detail/windows-community-toolkit

**Comment by brminnick** [comment]
Right on! We wouldn't want to replace "Windows Community Toolkit" with ".NET MAUI Community Toolkit" because the Windows toolkit it still exists: [`CommunityToolkit.WinUI`](https://www.nuget.org/packages/CommunityToolkit.WinUI) for example.

I see two paths forward:
1. Keep Windows Community Toolkit on the Official Projects page and add .NET MAUI Community Toolkit
2. 👇 Rename "Windows Community Toolkit" to ".NET Community Toolkits", and update its logo, description and project link 

**.NET Community Toolkits**
- **Image Logo:** https://github.com/CommunityToolkit/Maui/blob/main/build/nuget.png
- **Project Website:** https://learn.microsoft.com/dotnet/communitytoolkit/
- **Description:** The .NET Community Toolkits offer a collection of reusable implementations that aim to simplify common development tasks for a variety of .NET frameworks. The toolkits are a collaboration with the community, Microsoft engineers, Microsoft MVPs, and the teams working on .NET technologies

**Comment by ChrisSfanos** [comment]
Hey @michael-hawker - I don't think there is a hard and fast rule - I think it's really what's better from a community perspective.  If having a separate entry for each project because they are distinct from a developer's perspective we can go that route.  If it helps drive cross-traffic to both by having a single entry pointing to multiple items, then we should go that route

**Comment by brminnick** [comment]
That makes sense. 

From a community perspective, the .NET MAUI community (mobile) and the Windows community (desktop) don't have a huge overlap, so I agree that it'd make sense to highlight both projects separately on the Current Projects page, despite both projects being in the same CommunityToolkit org.

**Comment by ChrisSfanos** [comment]
The works for me - so let's go with adding a .NET MAUI community toolkit entry

Please take a look at some existing Project entries and then drop in here your:
1) Project description
2) GitHub repo link
3) Any other site landing page you want to directly developers to

I'll grab the license and license link and add that

**Comment by michael-hawker** [comment]
@brminnick you have a typo in your GitHub Repo link it should be https://github.com/CommunityToolkit/Maui

**Comment by brminnick** [comment]
Good catch - thanks! Fixed ✅

**Comment by AlexRadch** [comment]
I would suggest keeping `Windows Community Toolkit ` and will add both the `.NET Community Toolkit` and the `.NET MAUI Community Toolkit`.

**Comment by michael-hawker** [comment]
@ChrisSfanos is there action on us here? Do you need us to open a PR somewhere to add these two extra projects to the list?

I also noticed that our Windows Community Toolkit listing doesn't have a 'Project Website' button like the others.

We're also migrating our repository to https://github.com/CommunityToolkit/Windows, so we'll want to update the link ourselves for that:

- **Title**: Windows Community Toolkit
- **Description**: The Windows Community Toolkit is a collection of controls for WinUI 2, WinUI 3, and Uno Platform developers. It simplifies and demonstrates common developer tasks building experiences for Windows with .NET.
- **Image Logo**: https://github.com/CommunityToolkit/Windows/blob/main/icon.png
- **GitHub Repo**: https://github.com/CommunityToolkit/Windows
- **Project Website**: https://aka.ms/windowstoolkitdocs

**Comment by 1kevgriff** [comment]
Hey all - I'm trying to help clean some of these issues up.  How's this look for everyone? 

https://dotnetfoundation.org/projects/project-detail/.net-maui-community-toolkit

**Comment by glennawatson** [comment]
Thanks again @michael-hawker for your patience. Closing this one but please open a new issue if there are any more issues with the content.
