### ISSUE TITLE
Add the .NET Community Toolkit to .NET Foundation projects list

### ISSUE THREAD

**Issue by AlexRadch** [dotnet-foundation/projects#289]
[.NET Foundation projects list](https://dotnetfoundation.org/projects/current-projects) contains [Windows Community Toolkit](https://dotnetfoundation.org/projects/project-detail/windows-community-toolkit) but does not contains the [.NET Community Toolkit](https://github.com/CommunityToolkit/dotnet) project.

I would suggest adding the .NET Community Toolkit to the .NET Foundation projects list also.

**Comment by michael-hawker** [comment]
👍 FYI @Sergio0694, discussed in #286 as well.

**Comment by AlexRadch** [comment]
* **Title:** .NET Community Toolkit
* **Description:** .NET Community Toolkit is a collection of helpers and APIs that work for all .NET developers and are agnostic of any specific UI platform. The toolkit is maintained and published by Microsoft, and part of the .NET Foundation.
* **Image Logo:** https://github.com/CommunityToolkit/Maui/blob/main/build/nuget.png
* **Project Website:** https://learn.microsoft.com/dotnet/communitytoolkit/introduction
* **GitHub Repo:** https://github.com/CommunityToolkit/dotnet

**Comment by michael-hawker** [comment]
Perfect, thanks @AlexRadch!

**Comment by 1kevgriff** [comment]
How's this look? https://dotnetfoundation.org/projects/project-detail/.net-community-toolkit

**Comment by michael-hawker** [comment]
FYI @Sergio0694

**Comment by Sergio0694** [comment]
This is great, thank you everyone for the help with this! 🙂
