### ISSUE TITLE
Code Signing Certificate Request: docfx

### ISSUE THREAD

**Issue by yufeih** [dotnet-foundation/projects#293]
### Please fill in the information below

- **docfx**
- **LastPass Email (or send offline):**

Certificate onboarding checklist:

- [x] Register trade name @ChrisSfanos
- [x] Create configuration in Code Signing Service
- [x] Create organization with DigiCert
- [x] Request certificate from DigiCert
- [x] Received certificate and finalize sign service configuration
- [x] Provide credentials in shared folder in LastPass

**Comment by ChrisSfanos** [comment]
Cert is back and loaded into AKV and handed off all the Sign CLI info

**Comment by yufeih** [comment]
Thank you @ChrisSfanos !
