### ISSUE TITLE
Ant Design Blazor was forgotten in the website project list

### ISSUE THREAD

**Issue by ElderJames** [dotnet-foundation/projects#297]
I noticed that some people said that they could not see our project on the official website and questioned our authenticity. I went to see it today and it was. 

May I ask what the situation is? Am I missing something?

https://dotnetfoundation.org/projects/current-projects

**Comment by glennawatson** [comment]
@nicoleabuhakmeh  handles a lot of the website features maybe she'll know.

**Comment by nicoleabuhakmeh** [comment]
It's been published and if there is anything that needs to be changed, please let me know.
