### ISSUE TITLE
Request to Join dotnet-foundation projects committee

### ISSUE THREAD

**Issue by aguluman** [dotnet-foundation/projects#304]
## Your name: 
Chukwuma Akunyili

## Your Email: 
chukwuma.akunyili.233279@unn.edu.ng

## Notes (OPTIONAL):
I would love to leave something behind while I lived here on earth.

**Comment by nicoleabuhakmeh** [comment]
Hi there, please apply on our [Membership Form.](https://dnf-forms.azurewebsites.net/)
