### ISSUE TITLE
Request to Add Spargine to Your List of Projects

### ISSUE THREAD

**Issue by RealDotNetDave** [dotnet-foundation/projects#307]
I'd like to submit the projects that make up my OSS Spargine to your list of projects. Spargine, my open-source assemblies, and NuGet packages are designed for .NET 6 & 7! These assemblies encapsulate the foundational code I have been developing since the early days of .NET 2. I am not only a devoted user of these assemblies in _all of my projects_, but they are also currently in production at many companies that I have worked for.

Complete information can be found at this link along with documentation: https://dotnettips.wordpress.com/spargine/

**GitHub**: https://realdotnetdave.github.io/dotNetTips.Spargine/
**NuGet**: http://bit.ly/dotNetDaveNuGet

**Comment by sbwalker** [comment]
@RealDotNetDave Is it possible for you to submit an application using the New Project Application Issue Template:

https://github.com/dotnet-foundation/projects/issues/new?assignees=sbwalker%2CChrisSfanos&labels=project+application%2Cproject+support&projects=&template=application.yml&title=Issue%3A+New+.NET+Foundation+Project+Application

The template captures a variety of information which the Project Committee uses to evaluate applications

**Comment by RealDotNetDave** [comment]
Yes, I will do that.

**Comment by RealDotNetDave** [comment]
Done. Please let me know if there is anything missing.
