### ISSUE TITLE
Issue: New .NET Foundation Project Application - Roslynator

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet-foundation/projects#308]
### Project Name

Roslynator

### License

Apache 2.0

### Contributor

Josef Pihrt

### Existing OSS Project?

Yes

### Source Code URL

https://github.com/josefpihrt/roslynator

### Project Homepage URL

https://josefpihrt.github.io/docs/roslynator

### Project Transfer Signatories

* James Hargreaves <jamesHargreaves12@gmail.com>

### Description

Roslynator is a set of code analysis tools for .NET/C#, such as extensions for Visual Studio and VS Code, code analyzers packages, testing framework and CLI. Roslynator is powered with [Roslyn](https://github.com/dotnet/roslyn).

### Name

Josef Pihrt

### Email

josef@pihrt.net

### GitHub Profile URL

https://github.com/josefpihrt

### Committers

There are contributors but none of then has commit/write access.

### Governance Model

Changes are proposed by creating a PR (standard model). I'm the only developer that approves PR.

CONTRIBUTING.md and [documentation](https://josefpihrt.github.io/docs/roslynator/developers) contain instructions how to proceed when someone wants to contribute.

### CLA

- [ ] If already an OSS project, was a Contribution License Agreement in place for contributions accepted?

### How does the project check who has signed one?

Currently, CLA is not required.

### Assignment and Contribution Models

- [ ] Assignment Model
> Under the .NET Foundation assignment model, project ownership and other intellectual property is assigned to the .NET Foundation and the .NET Foundation agrees to grantback a license to the contributor(s).

- [x] Contribution Model
> Under the .NET Foundation contribution model, a project retains ownership of the copyright, but grants the .NET Foundation a broad license to the project’s code and other intellectual property. The project also confirms that the project’s submissions to .NET Foundation are its own original work (there are also instructions for any third party materials that might be included).

### Repository Layout

I have already made significant changes as a part of effort of joining .NET Foundation:

- Add CI/CD pipeline
- Add web page with documentation.
- Add SECURITY.md file

In case of joining .NET foundation it would be necessary to update file headers.

### Eligibility Criteria

- [X] The project is built on the .NET platform and/or creates value within the .NET ecosystem.
- [X] The project produces source code for distribution to the public at no charge.
- [X] The project's code is easily discoverable and publicly accessible (preferably on GitHub).
- [X] The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).
- [X] When applicable, project must use reproducible build settings in its toolchain.
- [X] The project uses [Source Link.](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
- [X] The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).
- [ ] The project code signs their artifacts as appropriate.
- [X] The project organization has 2FA enabled. Requiring 2FA must be done as part of onboarding if not already enabled.
- [X] Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).
- [ ] Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.
- [X] The copyright ownership of everything that the project produces is clearly defined and documented.
- [X] The project has a public issue tracker where the status of any defect can be easily obtained.
- [X] The project has a published Security Policy.
- [X] The project has a home page which provides high level information about its status and purpose.
- [ ] The project has a public communication channel where community members can engage with maintainers.
- [X] The project has a publicly available location where members can review and contribute to documentation.

### PR Plan Summary

- Publish post on twitter (https://twitter.com/roslynator).
- Publish post on LinkedIn.
- Add section to README.md and main documentation page.

### Infrastructure Requirements Summary

Currently, artifacts are not digitally signed.

### Additional Notes

Hi,

I would like to join .NET Foundation with project Roslynator. I feel that it would be an appreciation that the project is good enough to be part of the foundation. It could also help the project to be more popular and thus attract more contributors.

Thanks in advance for your help,
Josef

**Comment by glennawatson** [comment]
Roslynator is a great tool. Use it all the time.

**Comment by Inerska** [comment]
Great tool, using it all the time as well!

**Comment by sbwalker** [comment]
@JosefPihrt your project application will be reviewed this week by the Project Committee. It will be evaluated based on the criteria outlined in the Charter - https://github.com/dotnet-foundation/projects

**Comment by JosefPihrt** [comment]
@sbwalker Thanks for letting me know.

**Comment by sbwalker** [comment]
The Project Committee has evaluated the project and will recommend this project for Member status at the next BOD meeting (Aug 23)

**Comment by JosefPihrt** [comment]
That's great! Thanks for the recommendation!

**Comment by JosefPihrt** [comment]
Thanks again for letting me know.

I'm really glad that Roslynator was approved for the membership in the .NET Foundation! 🎉 🥳 🚀

**Comment by ChrisSfanos** [comment]
Hello!  We will be following the following checklist to onboard your project to the .NET Foundation.  I'll post updates here as we move along

## CLA
- [ ] Project Agreement Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)
- [ ] Enable two-factor authentication (2FA) for GitHub organization and all users

**Comment by ChrisSfanos** [comment]
Hello!  The new submission form is missing a section for you to select your onboard agreement type - please review the description of Assignment and Contribution model under the Project Application and Review section [here](https://dotnetfoundation.org/projects/submit-a-project) and let me know which you want to move forward with.  I'll send out the form via DocuSign after you've selected - thanks!

**Comment by JosefPihrt** [comment]
Hi, I chose "Contribution Model". I've update the first post to include section "Assignment and Contribution Models".

**Comment by JosefPihrt** [comment]
So this agreement will be sent to my mailbox or how does it work? Thank you for the help.

**Comment by ChrisSfanos** [comment]
James Hargreaves was listed as the Project Transfer Signer in the application, so the agreement was sent via DocuSign to James

**Comment by JosefPihrt** [comment]
I see 👍

**Comment by ChrisSfanos** [comment]
Hi @jamesHargreaves12 - let me know if you did not receive the DocuSign request to transfer Roslynator to the .NET Foundation - thanks!

**Comment by jamesHargreaves12** [comment]
Sorry for the delay - I have signed the request.

**Comment by JosefPihrt** [comment]
@ChrisSfanos I'm ready to sign the agreement.

**Comment by ChrisSfanos** [comment]
Hi @JosefPihrt - you only listed James as the signer, so you don't need to sign.  I pinged the DNF signer to sign on the Foundation's behalf.  I'll send you the CLA onboarding steps in a minute

**Comment by ChrisSfanos** [comment]
Agreement is signed - CLA onboarding email went out also

**Comment by glennawatson** [comment]
@ChrisSfanos I believe Josef is the main developer so this may be in error. We might want to change this to dual signers

**Comment by glennawatson** [comment]
We don't want to have a wall of information getting in the way of the main maintainer signing the document. Eg the initial application has a lot of fields, so we should step back from this.

**Comment by ChrisSfanos** [comment]
Hey @glennawatson  - we allow multiple signers, so that's not a problem.  I've been working with Josef offline and we are moving forward with the onboarding.

**Comment by ChrisSfanos** [comment]
We just transferred the project to /dotnet/ so the CLA is automatically configured.  I'll send the remaining onboarding steps today

**Comment by ChrisSfanos** [comment]
Onboarding process is wrapped up - Welcome Roslynator to the .NET Foundation!
