### ISSUE TITLE
Issue: New .NET Foundation Project Application - WatsonTcp

### ISSUE THREAD

**Issue by jchristn** [dotnet-foundation/projects#309]
### Project Name

WatsonTcp

### License

MIT

### Contributor

Joel Christner

### Existing OSS Project?

Yes

### Source Code URL

https://github.com/jchristn/WatsonTcp

### Project Homepage URL

https://github.com/jchristn/WatsonTcp

### Project Transfer Signatories

Joel Christner, joel.christner@gmail.com

### Description

WatsonTcp is a lightweight, easy to use library that enables developers to quickly integrate TCP sockets communication capabilities into their apps.

### Name

Joel Christner

### Email

joel.christner@gmail.com

### GitHub Profile URL

https://github.com/jchristn

### Committers

jchristn

### Governance Model

Currently made at my sole discretion; generally I focus on improvements that improve stability, performance, or core capability of the library.  In terms of core capability, I generally focus only on including items that are horizontally applicable to a broad base of users.

### CLA

- [ ] If already an OSS project, was a Contribution License Agreement in place for contributions accepted?

### How does the project check who has signed one?

NA

### CLA Notification Alias

joel.christner@gmail.com

### Repository Layout

NA

### Eligibility Criteria

- [X] The project is built on the .NET platform and/or creates value within the .NET ecosystem.
- [X] The project produces source code for distribution to the public at no charge.
- [X] The project's code is easily discoverable and publicly accessible (preferably on GitHub).
- [ ] The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).
- [ ] When applicable, project must use reproducible build settings in its toolchain.
- [ ] The project uses [Source Link.](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
- [ ] The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).
- [X] The project code signs their artifacts as appropriate.
- [X] The project organization has 2FA enabled. Requiring 2FA must be done as part of onboarding if not already enabled.
- [ ] Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).
- [ ] Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.
- [X] The copyright ownership of everything that the project produces is clearly defined and documented.
- [X] The project has a public issue tracker where the status of any defect can be easily obtained.
- [ ] The project has a published Security Policy.
- [X] The project has a home page which provides high level information about its status and purpose.
- [X] The project has a public communication channel where community members can engage with maintainers.
- [X] The project has a publicly available location where members can review and contribute to documentation.

### PR Plan Summary

I haven't thought about PR, but would love to have a conversation to discuss.

### Infrastructure Requirements Summary

NA

### Additional Notes

NA

**Comment by sbwalker** [comment]
@jchristn  your project application will be reviewed this week by the Project Committee. It will be evaluated based on the criteria outlined in the Charter - https://github.com/dotnet-foundation/projects

**Comment by sbwalker** [comment]
The Project Committee has evaluated the project and will recommend this project for Member status at the next BOD meeting (Aug 23)

**Comment by ChrisSfanos** [comment]
Hello!  We will be following the following checklist to onboard your project to the .NET Foundation.  I'll post updates here as we move along

## CLA
- [ ] Project Agreement Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)
- [ ] Enable two-factor authentication (2FA) for GitHub organization and all users

**Comment by ChrisSfanos** [comment]
Hi @jchristn - same for this project - thanks!

**Comment by jchristn** [comment]
Licensed, please :)

**Comment by ChrisSfanos** [comment]
Thanks!  But I also need the top section (I can see it's not super clear on the website - I need to get that fixed)  - Contribution vs Assignment (need this for both projects)

Assignment and Contribution Models. The .NET Foundation uses either an assignment model or a contribution model for on-boarding new projects. Under the assignment model, a project transfers ownership of the copyright to the .NET Foundation. Under the contribution model, a project retains ownership of the copyright, but grants the .NET Foundation a broad license to the project's code and other intellectual property. The project also confirms that the project's submissions to .NET Foundation are its own original work (there are also instructions for any third party materials that might be included).

**Comment by jchristn** [comment]
Hi @ChrisSfanos I'm indifferent; thanks for explaining the difference.  If the choice is mine, I'd select Contribution model for both.  Copying/pasting into the other issue as well (I'm happy to be convinced that the assignment model is preferred, too)

**Comment by ChrisSfanos** [comment]
Happy to help - I do you need to pick, so we will go with Contribution for both.  I'll work to get a single agreement that covers both projects out to you tomorrow

**Comment by ChrisSfanos** [comment]
Agreement is out for signing

**Comment by ChrisSfanos** [comment]
CLA instructions emailed out - we will need to either move these projects to the /dotnet/ org or a new one will need to be created and move your projects there

**Comment by ChrisSfanos** [comment]
We moved this to the /dotnet/ org, so CLA is now automatically covered.  I'll be sending out the remaining onboarding steps (same for both projects) in a mail shortly

**Comment by ChrisSfanos** [comment]
Looks like just updates to the README to reference the .NET Foundation are missing

**Comment by jchristn** [comment]
How would you like them to be referenced?  Happy to make whatever changes are needed to the README.

**Comment by ChrisSfanos** [comment]
Just a reference/link to the DNF website - a basic example is https://github.com/dotnet/roslyn

**Comment by jchristn** [comment]
This is done for both projects.

**Comment by ChrisSfanos** [comment]
Project on-boarding is complete!  (we will cover the public announcement)
