### ISSUE TITLE
Issue: New .NET Foundation Project Application - WatsonWebserver

### ISSUE THREAD

**Issue by jchristn** [dotnet-foundation/projects#310]
### Project Name

WatsonWebserver

### License

MIT

### Contributor

Joel Christner

### Existing OSS Project?

Yes

### Source Code URL

https://github.com/jchristn/WatsonWebserver

### Project Homepage URL

https://github.com/jchristn/WatsonWebserver

### Project Transfer Signatories

Joel Christner, joel.christner@gmail.com

### Description

WatsonWebserver is a simple, standalone RESTful server platform enabling developers to rapidly build HTTP-based applications.

### Name

Joel Christner

### Email

joel.christner@gmail.com

### GitHub Profile URL

https://github.com/jchristn

### Committers

Joel Christner

### Governance Model

Generally I only amend the library with fixes or net-new capabilities that are horizontal and broad in nature.

### CLA

- [ ] If already an OSS project, was a Contribution License Agreement in place for contributions accepted?

### How does the project check who has signed one?

NA

### CLA Notification Alias

joel.christner@gmail.com

### Repository Layout

NA

### Eligibility Criteria

- [X] The project is built on the .NET platform and/or creates value within the .NET ecosystem.
- [X] The project produces source code for distribution to the public at no charge.
- [X] The project's code is easily discoverable and publicly accessible (preferably on GitHub).
- [ ] The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).
- [ ] When applicable, project must use reproducible build settings in its toolchain.
- [ ] The project uses [Source Link.](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
- [ ] The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).
- [X] The project code signs their artifacts as appropriate.
- [X] The project organization has 2FA enabled. Requiring 2FA must be done as part of onboarding if not already enabled.
- [X] Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).
- [ ] Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.
- [X] The copyright ownership of everything that the project produces is clearly defined and documented.
- [X] The project has a public issue tracker where the status of any defect can be easily obtained.
- [ ] The project has a published Security Policy.
- [X] The project has a home page which provides high level information about its status and purpose.
- [X] The project has a public communication channel where community members can engage with maintainers.
- [X] The project has a publicly available location where members can review and contribute to documentation.

### PR Plan Summary

I haven't thought about PR but would love to have a discussion on this.

### Infrastructure Requirements Summary

NA

### Additional Notes

NA

**Comment by sbwalker** [comment]
@jchristn your project application will be reviewed this week by the Project Committee. It will be evaluated based on the criteria outlined in the Charter - https://github.com/dotnet-foundation/projects

**Comment by sbwalker** [comment]
The Project Committee has evaluated the project and will recommend this project for Member status at the next BOD meeting (Aug 23)

**Comment by sbwalker** [comment]
Yesterday the .NET Foundation BOD voted to approve this project for Membership in the .NET Foundation. @ChrisSfanos will reach out to you shortly to initiate the onboarding process.

**Comment by jchristn** [comment]
Thank you @sbwalker - looking forward to the chat with @ChrisSfanos

**Comment by ChrisSfanos** [comment]
Hello!  The new submission form is missing a section for you to select your onboard agreement type - please review the description of Assignment and Contribution model under the Project Application and Review section [here](https://dotnetfoundation.org/projects/submit-a-project) and let me know which you want to move forward with.  I'll send out the form via DocuSign after you've selected - thanks!

**Comment by ChrisSfanos** [comment]
Hi @jchristn - let me know which agreement you want to proceed with - thanks!

**Comment by jchristn** [comment]
Very sorry @ChrisSfanos looking now for both.

**Comment by jchristn** [comment]
Licensed, please!

**Comment by jchristn** [comment]
Hi @ChrisSfanos I'm indifferent; thanks for explaining the difference.  If the choice is mine, I'd select Contribution model for both.  Copying/pasting into the other issue as well (I'm happy to be convinced that the assignment model is preferred, too)

**Comment by ChrisSfanos** [comment]
Agreement is out for signing

**Comment by ChrisSfanos** [comment]
We moved this to the /dotnet/ org, so CLA is now automatically covered.  I'll be sending out the remaining onboarding steps (same for both projects) in a mail shortly

**Comment by ChrisSfanos** [comment]
Project on-boarding is complete!  (we will cover the public announcement)
