### ISSUE TITLE
Simon Cropp: join the project committee 

### ISSUE THREAD

**Issue by SimonCropp** [dotnet-foundation/projects#320]
## Your name: 

Simon Cropp

## Your Email: 

simon.cropp@gmail.com

**Comment by glennawatson** [comment]
Attempted to make the meeting times a little nicer @SimonCropp for us Aussies, 7am but not better than nothing :)

**Comment by sbwalker** [comment]
Your application has been received and is under official consideration

**Comment by nicoleabuhakmeh** [comment]
Simon has been invited to the committee on Discord.
