### ISSUE TITLE
Membership Request

### ISSUE THREAD

**Issue by MJHeijster** [dotnet-foundation/projects#321]
## Your name: 
Jeroen Heijster

## Your Email: 
mjheijster@gmail.com

## Notes (OPTIONAL):
I work in .NET for over 10 years now. I wish to help in the .NET ecosystem and gain knowledge in the process.

**Comment by sbwalker** [comment]
Your application has been received and is under official consideration

**Comment by nicoleabuhakmeh** [comment]
Hi @MJHeijster  - I invite you to join the other community members here on [Discord.](https://discord.gg/Q9WngNSK) Introduce yourself and follow a committee's conversation you're interested in.

Our [README.md](https://github.com/dotnet-foundation/.github/tree/main/profile/README.md) has a listing of the different areas we have working groups currently in. Add a comment to the upcoming agenda if you have an idea or group you'd like to join. If you're looking for outreach in your community, get started by submitting a [proposal.](https://github.com/dotnet-foundation/wg-outreach/blob/main/proposals.md) The Proposal will be reviewed by the Chair, Committee and if needed, Board. Please submit items for events, at least 90 days prior to the event.

We're always open to helping promote events and related items in our [Content Repo](https://github.com/dotnet-foundation/content). Subscribe to the [newsletter](https://dotnetfoundation.us12.list-manage.com/subscribe?u=9d9421a5cbd70d03dc69dc918&id=0d416ef7e3)to get an update on the monthly goings on, upcoming events or things you might have missed within the .NET Community.

We also welcome authored blog posts on our blog, Submitted Via email to [Contact@DotnetFoundation.org](https://github.com/dotnet-foundation/wg-membership/issues/Contact@DotnetFoundation.org) for review by the volunteer publishing team.

We have a great Meetup Network with Worldwide Events: [meetups](https://www.meetup.com/pro/dotnet/) and [speakers.](https://dotnetfoundation.org/community/speakers)

If you're looking to help out a specific [Project](https://dotnetfoundation.org/projects/current-projects), the best way is directly on their project's link under the description. Check their issues and looking for ways they have asked for help from the community.

We are committed to fostering a welcoming and inclusive environment where all members feel valued and respected. We believe that the strength of our community lies in the diversity of its members, and we are committed to creating an inclusive and welcoming environment for all. Please review our [Privacy Policy](https://dotnetfoundation.org/about/policies/privacy-policy) and [Code of Conduct](https://dotnetfoundation.org/about/policies/code-of-conduct) as a community member.

**Comment by MJHeijster** [comment]
> Hi @MJHeijster - I invite you to join the other community members here on [Discord.](https://discord.gg/Q9WngNSK) Introduce yourself and follow a committee's conversation you're interested in.
> 
> Our [README.md](https://github.com/dotnet-foundation/.github/tree/main/profile/README.md) has a listing of the different areas we have working groups currently in. Add a comment to the upcoming agenda if you have an idea or group you'd like to join. If you're looking for outreach in your community, get started by submitting a [proposal.](https://github.com/dotnet-foundation/wg-outreach/blob/main/proposals.md) The Proposal will be reviewed by the Chair, Committee and if needed, Board. Please submit items for events, at least 90 days prior to the event.
> 
> We're always open to helping promote events and related items in our [Content Repo](https://github.com/dotnet-foundation/content). Subscribe to the [newsletter](https://dotnetfoundation.us12.list-manage.com/subscribe?u=9d9421a5cbd70d03dc69dc918&id=0d416ef7e3)to get an update on the monthly goings on, upcoming events or things you might have missed within the .NET Community.
> 
> We also welcome authored blog posts on our blog, Submitted Via email to [Contact@DotnetFoundation.org](https://github.com/dotnet-foundation/wg-membership/issues/Contact@DotnetFoundation.org) for review by the volunteer publishing team.
> 
> We have a great Meetup Network with Worldwide Events: [meetups](https://www.meetup.com/pro/dotnet/) and [speakers.](https://dotnetfoundation.org/community/speakers)
> 
> If you're looking to help out a specific [Project](https://dotnetfoundation.org/projects/current-projects), the best way is directly on their project's link under the description. Check their issues and looking for ways they have asked for help from the community.
> 
> We are committed to fostering a welcoming and inclusive environment where all members feel valued and respected. We believe that the strength of our community lies in the diversity of its members, and we are committed to creating an inclusive and welcoming environment for all. Please review our [Privacy Policy](https://dotnetfoundation.org/about/policies/privacy-policy) and [Code of Conduct](https://dotnetfoundation.org/about/policies/code-of-conduct) as a community member.

Thanks, joined the server, glad to be a part of the group.
