### ISSUE TITLE
Issue: New .NET Foundation Project Application

### ISSUE THREAD

**Issue by CypherPotato** [dotnet-foundation/projects#328]
### Project Name

Sisk Framework

### License

MIT

### Contributor

Project Principium, CypherPotato

### Existing OSS Project?

Yes

### Source Code URL

https://github.com/sisk-http/core

### Project Homepage URL

https://sisk.project-principium.dev/

### Project Transfer Signatories

- Gabriel Scatolin da Silva (gab [at] proj.pw)

### Description

Sisk is an lightweight web framework designed for fast and robust development, which allows you to take the full control of what you want to do.

Sisk can do web development the way you want. Create MVC, MVVC, SOLID applications, or any other design pattern you're interested in.

Main features:

- Lightweight: robust projects tested in small, low-cost, low-performance environments and got good results. The entire Sisk ecosystem is less than 500kb in size!
- Open-source: the entire Sisk ecosystem is open source, and all the libraries and technologies we use must be open source as well. Sisk is entirely distributed under the MIT License, which allows the commercial development.
- Sustainable: you are the one who makes the project, Sisk gives you the tools. Because it is open source, the community (including you) can maintain, fix bugs and improve Sisk over time.

### Name

Gabriel Scatolin

### Email

gscatolin [at] outlook.com

### GitHub Profile URL

https://github.com/CypherPotato

### Committers

- CypherPotato

### Governance Model

Any commit/change that follows the project philosophy, maintains code quality, and is honest about the change it makes, should be accepted.

### CLA

- [ ] If already an OSS project, was a Contribution License Agreement in place for contributions accepted?

### Select the Project Transfer Agreement model

Contribution

### Repository Layout

Create a code of conduct to hold the community to a uniform standard and add text that the project is supported by the .NET Foundation, in repo and website.

### Eligibility Criteria

- [X] The project is built on the .NET platform and/or creates value within the .NET ecosystem.
- [X] The project produces source code for distribution to the public at no charge.
- [X] The project's code is easily discoverable and publicly accessible (preferably on GitHub).
- [X] The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).
- [X] When applicable, project must use reproducible build settings in its toolchain.
- [ ] The project uses [Source Link.](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
- [X] The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).
- [X] The project code signs their artifacts as appropriate.
- [X] Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).
- [X] The project organization has 2FA enabled. Requiring 2FA must be done as part of onboarding if not already enabled.
- [X] Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.
- [X] The copyright ownership of everything that the project produces is clearly defined and documented.
- [X] The project has a public issue tracker where the status of any defect can be easily obtained.
- [X] The project has a published Security Policy.
- [X] The project has a home page which provides high level information about its status and purpose.
- [X] The project has a public communication channel where community members can engage with maintainers.
- [X] The project has a publicly available location where members can review and contribute to documentation.

### PR Plan Summary

The focus is for the .NET Foundation application to spread the project to other .NET contributors to improve the project, create tests, improve and keep the project stable, secure and sustainable.

### Infrastructure Requirements Summary

The project website runs on a simple nginx server with PHP, currently owned by Project Principium. There's no another hosting requeriments. The website must provide an SSL certificate, and download updates directly from the github repository, through `git pull`.

### Additional Notes

I would like to better understand how the shared license between the main maintainer (Project Principium) and the .NET Foundation would work, today and in the long term. Even though it is not a project that requires a license, it still belongs to an entity.

Source link is planned to be released within version [0.16](https://github.com/orgs/sisk-http/projects/1?pane=issue&itemId=41589558).

**Comment by CypherPotato** [comment]
For other reasons, I gave up on the application.

**Comment by sbwalker** [comment]
@CypherPotato just to confirm - you are no longer interested in having the Sisk Framework project join the .NET Foundation - correct?

**Comment by CypherPotato** [comment]
@sbwalker I'm inclined to make the project part of the .NET Foundation, but I don't know if fits the foundation's interest yet. I thought about canceling the request to refine the project before trying to submit again. If you have a suggestion or recommendation, I would be happy to receive it.

**Comment by sbwalker** [comment]
@CypherPotato the Project Committee only reviews projects which have a serious interest in joining the .NET Foundation - which is why I reached out to confirm if you have withdrawn your application.

**Comment by CypherPotato** [comment]
@sbwalker So, at the moment, I have no interest in submitting the project on the .NET Foundation. I'm interested in the future, but the project still needs to be more refined to be able to take this step.

thank you.

**Comment by glennawatson** [comment]
@CypherPotato we have a couple categories with projects. One is seed project of the project committee agrees which helps guides projects to become full grown member projects. If the application was still open that'd be likely where we would place the project.

**Comment by CypherPotato** [comment]
I see. Thank you for your response. Did the comitee already reunited about the open project submissions? If not, I can reopen this issue and submit it again to .NET Foundation.

I apologize for my inexperience and confusion while trying to submit Sisk. I'd be pleased to have .NET Foundation support on it.

Thank you.

**Comment by glennawatson** [comment]
We have met for December already but we do have a January meeting.

**Comment by CypherPotato** [comment]
Sure. I'll reopen this issue and submit it again to the comitee. Thank you.

If theres something I can do for now, please, keep me informed.

**Comment by sbwalker** [comment]
This application was not in the correct project application workflow category so it was not discussed in our last Project Committee meeting. It will be reviewed at the March meeting.

**Comment by sbwalker** [comment]
@CypherPotato the Project Committee was not able to vote on any of the new project applications in the last meeting, as it had not collected the activity metrics or eligibility criteria in time to review. The next meeting is April 11 and it will review 6 projects (and any other submitted between now and then). Our apologies for the delay.

**Comment by CypherPotato** [comment]
Well, that was 3 months without any response from .NET Foundation. I would like to help with the process, but I don't think I can help deciding for the project committee.

**Comment by sbwalker** [comment]
@CypherPotato the Project Committee met on April 11 and discussed the 6 project applications (based on activity metrics and eligibility criteria). I was personally not able to attend the meeting due to a work conflict. It is my understanding that no decisions were made in that meeting in regards to recommending projects for Member or Seed status. The next meeting is May 9.

**Comment by CypherPotato** [comment]
> @CypherPotato the Project Committee met on April 11 and discussed the 6 project applications (based on activity metrics and eligibility criteria). I was personally not able to attend the meeting due to a work conflict. It is my understanding that no decisions were made in that meeting in regards to recommending projects for Member or Seed status. The next meeting is May 9. 

Just let me know if I can help with something. I would be happy if I could.

**Comment by sbwalker** [comment]
Thank you for your application. The Project Committee reviewed the application at a recent meeting based on the criteria outlined in the Charter (https://github.com/dotnet-foundation/projects?tab=readme-ov-file#criteria). Based on the current Activity metrics, the project does not yet meet the Activity requirements for becoming a Member project. However, the Project Committee is interested in getting a better understanding of the specific benefits or services you were hoping to receive by joining the .NET Foundation. If you are able to provide this additional context, we will be able to provide guidance on next steps.

**Comment by CypherPotato** [comment]
Hello, thank you for your response.

Today the entire Sisk project is only maintained by me, and has been a viable alternative to ASP.NET. Sisk's documentation clearly explains [its purpose](https://docs.sisk-framework.org/) and why it does exists. It has been actively maintained for two years and I intend for more as long as there are commercial projects that use Sisk, so they can pay my time and give me a reason to keep the project alive.

The idea of putting it on the .NET foundation was to attract the attention of .NET developers more experienced than me and to be able to further improve the project, with optimizations, refactorings or constructive criticism. Furthermore, being able to build a sustainable community to keep Sisk an active project for a longer period of time, which doesn't just rely on me.
