### ISSUE TITLE
New Membership Request

### ISSUE THREAD

**Issue by WeihanLi** [dotnet-foundation/projects#332]
## Your name: 
_Weihan Li_

## Your Email: 
_weihanli@outlook.com_

## Notes (OPTIONAL):
_I'd like to make some contributions on dotnet && also learn from the process_

**Comment by nicoleabuhakmeh** [comment]
Hi @WeihanLi  - I'd like to invite you to join our Discord Server where these discussions are taking place. Please Introduce yourself in the #introductions channel and Let us know some of your favorite projects. https://discord.gg/f4cP7fST

**Comment by WeihanLi** [comment]
@nicoleabuhakmeh accepted, thanks very much, is this done? should I close this issue?
