### ISSUE TITLE
Project Support Request: NuGet Trends

### ISSUE THREAD

**Issue by bruno-garcia** [dotnet-foundation/projects#336]
### Please fill in the information below:
- **Project Name:** [NuGet Trends](https://github.com/dotnet/nuget-trends)
- **Due by:** Within 3 months
- **Description:** Azure credits to run the site

A few months ago the Azure team offered credits to get NuGet Trends over to Azure. A few months ago we finally made the switch.
It got renewed a few times but they let me know recently that these credits are not supposed to be renewed indefinitely. So I'm looking for support to cover the server costs.

Things are under an Azure account with email `@nugettrends.com`.
It involves: 
1. 2 App Services, single instances, Basic (B3)
2. 1 Postgres DB, General Purpose, D2ds_v4, 2 vCores, 8 GiB RAM, 128 GiB storage
3. 1 RabbitMQ (container instance)

On https://www.microsoftazuresponsorships.com/Usage I see 1800 USD used in the current subscription which was renewed last month. (600 spent on the DB alone)

Before this ran on a single box on Hezner for 70 USD though. Plus backup pushed daily through a script to another box that costs 5.

**Comment by ChrisSfanos** [comment]
Hi @bruno-garcia  - with the holidays, I won't get an opportunity to put this in front of the board until January

**Comment by bruno-garcia** [comment]
Thanks for the update @ChrisSfanos 
Looking forward to any further news once you have it.

**Comment by bruno-garcia** [comment]
Any updates on this matter @ChrisSfanos ? I'm still paying for a box in case I run out of Azure credits but I'd like to cut that expense and stay on Azure if possible.

**Comment by ChrisSfanos** [comment]
Hi @bruno-garcia - sorry for the delay - the team didn't meet until last week.  Unfortunately at this point the Foundation is unable to extend an Azure credit support.  I'm going to follow up with some additional folks this week, but wanted to give you an update

**Comment by bruno-garcia** [comment]
Not gonna lie, that's a bummer. Thanks for the update though.

> I'm going to follow up with some additional folks this week
Still have hope, wouldn't want to shut down the site. Thank yuo

**Comment by glennawatson** [comment]
Hey @bruno-garcia 

Just curious if you'd be okay to some help to reduce the costs of the project?

One thing we could explore at looking at the source code of the project is using serverless both with data and functions. 

We are thinking we could help out with board people like myself to provide some PRs

Then when we adopted some cheaper technologies we can look at getting hosting for you, either through azure credits again or just through the DNF.

**Comment by glennawatson** [comment]
Like if you're agreeable I'm thinking of starting the work today btw, not in some distant future. Kevin Griffith has also agreed he could help out.

**Comment by bruno-garcia** [comment]
I purposely used open source technology only so it could be easily hosted anyone. From a single VM and docker and I originally hosted. 

So going with serverless is an option but we'd be locking in to Azure and it involves work to change things. Appreciate y'all offering to contribute it btw, but I'll maintain the code after that so before agreeing let's think this through. 

More than 50% of the cost is the Postgres database. We have more cost reduction opportunities there. 
Today we store every single day in the DB but only show weekly aggregates. The amount of data stored would be greatly reduced. 

Though the tweet I got in touch with two potential sponsors so before making changes to the code base let me check if either of those work out. 

I really appreciate you all offering to help with code changes as well as potentially also hosting .

**Comment by glennawatson** [comment]
I've done both AWS/Azure combined front ends before today, you can keep all your existing logic segmented away and just have presentation 'heads'. I can definitely help with your goal of keeping multiple heads including supporting postgres (considering you're already using entity framework) along with the serverless option.

I think a big issue you're facing at least with the DNF and Azure, they see you hosting VMs (a much more costly solution) for your database and server instances.

**Comment by glennawatson** [comment]
Since you got funding from sentry should we close this issue @bruno-garcia ?

**Comment by bruno-garcia** [comment]
Yeah, thanks Glenn! @getsentry will sponsor NuGet Trends so I'll just keep in containers as-is for now.

Folks keen to contribute, all the TFM data is in there, all of catalog's is in the DB. Lots we can do :)

Cheers
