### ISSUE TITLE
Project Support Request: AAS WorldWide Telescope — Azure Active Directory admin

### ISSUE THREAD

**Issue by pkgw** [dotnet-foundation/projects#34]
### Please fill in the information below:

- **Project Name:** AAS WorldWide Telescope
- **Due by:** End of calendar year would be ideal (before next major release)
- **Description:** Our project's Azure subscription is associated with an Azure Active Directory instance, `wwtadmindotnetfoundation.onmicrosoft.com`. We can't figure out if anyone still affiliated with the project actually has administration rights over this AAD instance. As the project leader, I'm hoping that someone might be able to set up my account, `Pwilliams@cfa.harvard.edu`, as an admin/owner of this AAD instance.

Note that I have admin oversight of our *subscription* for Azure services, but as best I understand it the admin of the AAD instance used for project IAM is a separate thing.

**Comment by jongalloway** [comment]
@pkgw I'd start by opening a ticket with Azure support. Unless I'm reading this wrong, this doesn't seem like something .NET Foundation can really help with, since this is on your Azure account.

**Comment by pkgw** [comment]
@jongalloway Thanks, I'll try that too. I believe the AAD instance is somehow tied to the Foundation since it is called `wwtadmindotnetfoundation` after all (there exists an email address `wwtadmin@dotnetfoundation.net`) but I am very unclear on how all of these pieces fit together (obviously).

**Comment by jongalloway** [comment]
@pkgw I verified we don't have that AAD instance in any of our subscriptions. Maybe the foundation helped get an Azure Sponsorship when this was set up? With anything Azure, my first step is to file a support ticket. We don't have any secret handshake Azure support for .NET Foundation.

**Comment by pkgw** [comment]
OK, if there's nothing in any of the Foundation subscriptions, then I think the issue here can be closed.
