### ISSUE TITLE
Committee Meeting - January 2024 Minutes

### ISSUE THREAD

**Issue by nicoleabuhakmeh** [dotnet-foundation/projects#343]
The Project Committee had their monthly meeting on January 11th, 2024 at 5pm Eastern.

Discord link is open to current members of the Project Committee to meeting: https://discord.com/events/966483029830824008/1185240341675261962

### Attendees:
Shawn Walker
Vincent Biret
Andrea Peruffo
Johan (az4der)
Eriawan Kusum
Ken (honest_lynx_15868)
Glenn Watson
Parham Gholami
Rob Mensching
Jeremy Sinclair
Michael Hawker
Nicole Miller 

## Agenda Items

1. Review of Application: [Jinget](https://github.com/dotnet-foundation/projects/issues/345) The committee decided to review the project stats before next month's meeting. **Project to be reviewed next month** 

2. Review of 2023 DNF Projects as posted by Shawn Walker
![image](https://github.com/dotnet-foundation/projects/assets/95773119/e674ca48-a630-4f12-907b-4ad9c6ec9683)

3. Question from a maintainer regarding project criteria from [andreaTP](https://github.com/andreaTP) & [baywet](https://github.com/baywet) 
The maintainers would like to submit their project to the Foundation but only want to submit a specific repo. The committee asked the maintainer to submit an application and will defer to Chris Sfanos to answer any questions that may come up during onboarding after they submit their project. [std.uritemplate](https://github.com/dotnet-foundation/projects/issues/349) 
**Project to be reviewed next month**

4. Project Application Criteria- Discussion
There is concern that some projects are too small for the Foundation, suggestion has been made to add criteria that makes sure the project meets the requirements before the committee takes the time to review. 

5. Ideas for 2024
- Hackathon for DNF Projects by DNF Members (submitted by Jeremy Sinclair)

The NEXT Project Committee meeting will be on February 8th, 2024 at 5pm Eastern in Discord.

**Comment by andreaTP** [comment]
- DotNet Foundation and projects using a monorepo structure (e.g.: https://github.com/std-uritemplate/std-uritemplate)

**Comment by eriawan** [comment]
@nicoleabuhakmeh 

hi, I'm part of .NET Foundation Project committee and I could not join that link of 
https://discord.com/events/966483029830824008/1185240341675261962 and that link is always redirected to this link:
https://discord.com/channels/966483029830824008
and It says that I don't have access to that event:

![image](https://github.com/dotnet-foundation/projects/assets/8773147/eea5d49e-eb52-4fa2-b0d2-fec29f14efc7)

Could you verify my access?

**Comment by eriawan** [comment]
@nicoleabuhakmeh 
Hang on, now it seems working after I reinstall my discord client.
Apologize for inconvenience!

Eriawan

**Comment by glennawatson** [comment]
The project committee periodically checks seeds project every 6 months or so to check status.
