### ISSUE TITLE
Code Signing Certificate Request: CoreWCF

### ISSUE THREAD

**Issue by mconnew** [dotnet-foundation/projects#35]
### Please fill in the information below

- **Project Name:** CoreWCF
- **LastPass Email (or send offline):** sending offline

Certificate onboarding checklist:

- [x] Register trade name @ChrisSfanos
- [x] Create organization with DigiCert
- [x] Create configuration in Code Signing Service
- [x] Provide credentials in shared folder in LastPass
- [x] Request certificate from DigiCert
- [x] Recieved certificate and finalize sign service configuration

**Comment by onovotny** [comment]
@ChrisSfanos can you please register a trade name for `CoreWCF`?

**Comment by ChrisSfanos** [comment]
I just completed the registration process for the Trade Name

**Comment by onovotny** [comment]
Certificate has been requested from DigiCert

**Comment by onovotny** [comment]
Sorry for the delay, DigiCert had to revalidate a few additional things. We have the certificate configured in the service, just need to know what email address to add to the LastPass shared folder to share the credentials.

**Comment by mconnew** [comment]
@onovotny, I sent the email address offline. Do I need to send it again?

**Comment by onovotny** [comment]
My apologies, I can't seem to locate it, what address did you send it to?

**Comment by mconnew** [comment]
I sent it to project-support@dotnetfoundation.org on Dec 17th like the template said to do 😄

**Comment by onovotny** [comment]
I just invited you to the shared LastPass where the cert is setup and configured.

Few things:
1. Here's a template of how to add code signing to the build pipeline: https://github.com/novotnyllc/CodeSigningDemo
2. Once signing is configured, please add `dotnetfoundation` as a co-owner in NuGet. 
3. If you have any 3rd party binaries in your packages, you'll need a whitelist.txt to include on your binaries and not the other ones in the nupkg.

I'm happy to review any PR's/pipelines

**Comment by clairernovotny** [comment]
Just following up to see if we can close this out? Are you all set?

**Comment by mconnew** [comment]
@clairernovotny, sorry it's taken so long to get to this. I got swamped with other things. I'm trying to work out what's needed to do the code signing. I'm going through the demo and have got to the code signing part. I'm not sure if I'm understanding what's needed correctly, but it seems like I need to have my own Azure AD instance, and need to configure and deploy my own implementation of the signing service for my packages? Am I understanding that correctly? Or is there a dotnetfoundation provided shared instance of these components?

**Comment by clairernovotny** [comment]
There is a shared instance.... the config is in the lastpass along with the username/password. (the config itself is public).

**Comment by mconnew** [comment]
Is there any best practices around when to sign? I publish packages after every build to the devops artifacts nuget feed but the example is set to only sign when a manual build is kicked off. Is it normal that CI builds are not signed and only hand picked builds get signed and then pushed to nuget?

**Comment by clairernovotny** [comment]
the example signs every non-PR build and it uses a different stage to ensure that secrets aren't exposed to any build scripts.

**Comment by mconnew** [comment]
How do the SignClientUser and SignClientSecret get to the pipeline? I'm having difficulty working out where they would be configured in Azure Devops?

**Comment by clairernovotny** [comment]
I have them as a variable group in Pipelines. Then I can reference it from the yaml: 

![image](https://user-images.githubusercontent.com/1427284/94633307-e2e7e700-029a-11eb-9401-ac4587468152.png)

**Comment by mconnew** [comment]
I'm getting this error when attempting to sign the packages:
```
Submitting 'D:\a\1\BuildPackages\CoreWCF.Http.0.1.0-alpha.204.nupkg' for signing.
Submitting 'D:\a\1\BuildPackages\CoreWCF.NetTcp.0.1.0-alpha.204.nupkg' for signing.
Submitting 'D:\a\1\BuildPackages\CoreWCF.Primitives.0.1.0-alpha.204.nupkg' for signing.
Exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (AADSTS50126: Error validating credentials due to invalid username or password.
Trace ID: e404b77d-e38c-4617-a74a-f16ad4a32801
Correlation ID: 322e50fb-930d-4062-9b49-3c2c01efa963
Timestamp: 2020-10-01 00:05:02Z)) (One or more errors occurred. (AADSTS50126: Error validating credentials due to invalid username or password.
```
I've validated that the username and password are entered exactly as is in lastpass.
This is the details of the HTTP request from the logs:
```
StatusCode: 400 
ResponseBody: {"error":"invalid_grant","error_description":"AADSTS50126: Error validating credentials due to invalid username or password.\r\nTrace ID: e404b77d-e38c-4617-a74a-f16ad4a32801\r\nCorrelation ID: 322e50fb-930d-4062-9b49-3c2c01efa963\r\nTimestamp: 2020-10-01 00:05:02Z","error_codes":[50126],"timestamp":"2020-10-01 00:05:02Z","trace_id":"e404b77d-e38c-4617-a74a-f16ad4a32801","correlation_id":"322e50fb-930d-4062-9b49-3c2c01efa963","error_uri":"https://login.microsoftonline.com/error?code=50126"} 
Headers: 
Cache-Control: no-store, no-cache
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
client-request-id: 322e50fb-930d-4062-9b49-3c2c01efa963
x-ms-request-id: e404b77d-e38c-4617-a74a-f16ad4a32801
x-ms-ests-server: 2.1.11086.7 - WUS2 ProdSlices
x-ms-clitelem: 1,50126,0,,
Set-Cookie: fpc=Agx-8dNVgzdJvFqdwGKWP5u2HPdPAQAAAC0UB9cOAAAA; expires=Sat, 31-Oct-2020 00:05:02 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=prod; path=/; secure; httponly, stsservicecookie=ests; path=/; secure; samesite=none; httponly
Date: Thu, 01 Oct 2020 00:05:02 GMT
```

**Comment by clairernovotny** [comment]
When you created the variable group with the secrets, did you call it the same thing that's in the template? `Sign Client Credentials` 

https://github.com/CoreWCF/CoreWCF/blob/master/templates/CodeSignStage.yml#L13

Those should match. Also, the two variable names should match (and be marked as secrets). https://github.com/CoreWCF/CoreWCF/blob/master/templates/CodeSignStage.yml#L38-L39

**Comment by mconnew** [comment]
I had done all that, I'm super paranoid about extra spaces to the point that I always check for zero width unicode characters too (because the Windows certificate manager tool used to add a zero width unicode character at the end of the thumbprint and I got hit by that one too many times so am paranoid now!!).  
I'm now beginning to suspect a bug in devops. I added a step which takes each of the username and password and creates a SHA512 hash of each of them and writes it to the console so I can see the hash in the output. The username field hash matches what I calculate locally, but the secret hash is different. I think there might be a character or character combo which is getting messed up by Azure Devops. I'm going to do some more experimenting to see if I can work out what's causing it.

**Comment by mconnew** [comment]
I've worked out what the problem is. There's a subtle bug in the demo project which will only manifest with some secrets. The problem is [here](https://github.com/novotnyllc/CodeSigningDemo/blob/master/azure-pipelines.yml#L81). This way of using variables does substitution into the script. The problem is PowerShell does variable expansion inside of double quotes and if the secret contains a dollar sign, from that dollar sign until the first invalid parameter name symbol in the contents of the string is treated like a variable substitution of a really bizarrely named PowerShell variable which resolves to a zero length string.  
The solution is to either use single quotes which makes PowerShell treat the string as a literal, or to inject the variable as an environment variable and use $env:VARIABLE_NAME.

**Comment by mconnew** [comment]
@clairernovotny, when you say to make dotnetfoundation as a co-owner in nuget, is this a property in the nuget package itself or metadata that I set once the package has been uploaded to nuget.org?

**Comment by mconnew** [comment]
Closing this issue as everything has been resolved.
