### ISSUE TITLE
Committee Meeting - February 2024 Minutes

### ISSUE THREAD

**Issue by nicoleabuhakmeh** [dotnet-foundation/projects#351]
The Project Committee held their monthly meeting on February 8th at 5pm Eastern on Discord.  

Discord link is open to current members of the Project Committee to meeting: https://discord.com/events/966483029830824008/1185240341675261962

## Agenda Items

1. Review of Project Applications
* [Jinget](https://github.com/dotnet-foundation/projects/issues/345)
2/8/24 – include in Seed category
* [Emik.SourceGenerators.Choices](https://github.com/dotnet-foundation/projects/issues/350)
2/8/24 - inform maintainer to submit application in the future once the project is more established and has more adoption
* [std.uritemplate](https://github.com/dotnet-foundation/projects/issues/353) 
2/8/24 - submit to BOD for consideration as a Member project (need to provide clarification that the repo does not include only .NET code… and clarify the intent to join via Assignment rather than Contribution).

2. Review of Member Applications in the Project Repo - Nicole to follow up will the requests. Transfer the applications to the Project Committee as needed. 
* [Vahid Farahmandian](https://github.com/dotnet-foundation/projects/issues/348)
* [Dmitrii Slabko](https://github.com/dotnet-foundation/projects/issues/347)
* [Saeed Rezaei](https://github.com/dotnet-foundation/projects/issues/342)
* [Saeed Mohammadiaghdam](https://github.com/dotnet-foundation/projects/issues/341)
* [Hennie Francis](https://github.com/dotnet-foundation/projects/issues/330)

3. Open Discussion items for Members of the Project Committee
Avalonia – provide feedback to BOD that a project of this stature leaving the .NET Foundation does not send a positive message to the .NET community. If we are trying to improve the reputation of the .NET Foundation this will represent another step backward. Ask if there is any way to retain the project in the .NET Foundation, as there are very few reasons that a project should feel the need to leave (ie. a license change to a non-OS license, etc…).

**Comment by baywet** [comment]
@nicoleabuhakmeh for std.uritemplate, do you need the maintainers to be present on the call? (@andreaTP and I) or is this more of a discussion between foundation committee members?

**Comment by andreaTP** [comment]
@baywet do we need to submit also the "Project Application"?

**Comment by sbwalker** [comment]
@andreaTP you should use the standard issue template to submit your Project Application:

Select Create Issue in the Projects repo and then choose the appropriate option:

![image](https://github.com/dotnet-foundation/projects/assets/4840590/127972a7-ed29-4984-8bc5-2806654c2d83)

This ensures the applications follows the workflow.

**Comment by sbwalker** [comment]
@baywet if new project applications are being reviewed by the Project Committee, then only the Project Committee members should be present in the meeting.

**Comment by baywet** [comment]
@sbwalker thanks for the additional context here. 
@adnreaTP FYI we've already filed the project application https://github.com/dotnet-foundation/projects/issues/349

**Comment by sbwalker** [comment]
@baywet issue #349 is not in the correct form - it is missing the majority of key project information which is reviewed by the Project Committee. Please re-resubmit using the Project Application template I included above in the screen shot.

**Comment by baywet** [comment]
Thanks for pointing this out @sbwalker !! I indeed filed a "Membership request" which I believe was the link I was given during the January call. I'll go ahead I file a Project Application as well (unless we need to wait for the membership request to be approved first?)

**Comment by sbwalker** [comment]
@baywet the Membership request serves a different purpose in the .NET Foundation - it is for individuals, not projects. So you do not need to wait for the Membership request to be approved.

**Comment by baywet** [comment]
created the project application issue #353
