### ISSUE TITLE
[Project Support]: Steeltoe

### ISSUE THREAD

**Issue by TimHess** [dotnet-foundation/projects#357]
### Project

Steeltoe

### Project Url

https://github.com/SteeltoeOSS

### Description

Can you please create a service principal in the .NET Foundation's Azure account for Steeltoe to use with GitHub Actions?

We are investigating moving from AKS to App Service and I don't have permissions to run this command (with the actual subscription id of course):

```
az ad sp create-for-rbac --name "sp-steeltoe" --sdk-auth --role contributor --scopes /subscriptions/<subscriptionId>/resourceGroups/steeltoe
```

### Due By

This week if possible

**Comment by ChrisSfanos** [comment]
Hi @TimHess - I can help you with this.  Did you want me to create the SP using the name above?  Or was that an example?  You can also email me directly (chris.sfanos @ dotnetfoundation . org) to chat offline - thanks!

**Comment by ChrisSfanos** [comment]
Created the SP and executed the command for Tim - this is resolved - @TimHess : please close it out once you've completed verification

**Comment by TimHess** [comment]
The new credentials are working, thank you!
