### ISSUE TITLE
can i become a maintainer of Humanizr

### ISSUE THREAD

**Issue by SimonCropp** [dotnet-foundation/projects#358]
### Project

Humanizer

### Project Url

https://github.com/Humanizr/Humanizer/

### Description

https://github.com/Humanizr/Humanizer/issues/1303

### Due By

now

**Comment by ChrisSfanos** [comment]
Pinged the maintainers and will have some offline chats with the .NET Foundation team on options here - thanks for raising this

**Comment by nicoleabuhakmeh** [comment]
Closing this issue as part of the Project Committee Agenda. Task is complete.
