### ISSUE TITLE
[Minutes]: <March 21, 2024>

### ISSUE THREAD

**Issue by nicoleabuhakmeh** [dotnet-foundation/projects#359]
### Minutes from March 21, 2024

The Project Committee had their monthly meeting on March 21st at 5pm Eastern on Discord. 

Discord link is open to current members of the Project Committee for the meeting: https://discord.com/events/966483029830824008/1185240341675261962

Agenda Items
Review of Project Applications - **Tabled until April's meeting**
- [TypeScript CodeDOM](https://github.com/dotnet-foundation/projects/issues/360)
- [RConfig](https://github.com/dotnet-foundation/projects/issues/361)
- [Flowtide.NET](https://github.com/dotnet-foundation/projects/issues/363)
- [json-everything](https://github.com/dotnet-foundation/projects/issues/367)
- [Live Health Checks](https://github.com/dotnet-foundation/projects/issues/368)

Review of Seed Projects - **Not Reviewed at this time.** 

Follow up on previous agenda items:

https://github.com/dotnet-foundation/projects/issues/358 - In Process. Chris Sfanos is coordinating a discussion between the current maintainers and Simon Cropp.
https://github.com/dotnet-foundation/projects/issues/353 - Submitted to BOD, Voting will take place by email. The email vote is being conducted by current President Joe Guadagno, results should be available by next board meeting.
[Avalonia](https://github.com/AvaloniaUI/Avalonia) - Offboarding as a Foundation Project. Kevin Griffin is currently working with Chris Sfanos and the Project Maintainers to finish the DocuSign paperwork. Kevin has been asked to provide a statement for the next newsletter as part of the process.

Project Support Request: NuGet Trends [#336]([url](https://github.com/dotnet-foundation/projects/issues/336))
Chris Sfanos is checking for resources for this project. 

Proposed: Board Mentorship program – Projects
Board Members will become the primary contact for new & current projects.​
Check in with each project every few weeks. Offering support, mentorship and community.

Open Discussion items for Members of the Project Committee

**Comment by bruno-garcia** [comment]
I don't have experience in meetings but if it helps me attending to pitch this https://github.com/dotnet-foundation/projects/issues/336 I'm happy to join.

Thanks

**Comment by andreaTP** [comment]
> https://github.com/dotnet-foundation/projects/issues/353 - Submitted to BOD, Voting will take place by email.

To clarify, the voting already happened and you are going to disclose the results? Or am I getting it wrong?

Thanks in advance.
cc. @baywet

**Comment by CypherPotato** [comment]
So, this [project](https://github.com/dotnet-foundation/projects/issues/328) was commited to be discussed in this meeting, but got no feedback from the committee. Am I missing something ?

**Comment by bruno-garcia** [comment]
Hey @nicoleabuhakmeh any chance https://github.com/dotnet-foundation/projects/issues/336 was discussed (it was on the issue description). Thanks
