### ISSUE TITLE
Python.NET

### ISSUE THREAD

**Issue by filmor** [dotnet-foundation/projects#36]
## 1.   General Information

**Project Name:**
Python.NET

**License:**
MIT

**Contributor (Company, Organization or individual name(s)):**
Recently:
- filmor
- lostmsu
- amos402
- s4v4g3
- slide
- benoithudson
- koubaa
- mjmvisser

In general, we have many drive-by contributors that stick around for a while.

**Existing OSS Project? (Yes/No):**
Yes

**Source Code URL:**
https://github.com/pythonnet/pythonnet/

**Project Homepage URL (if different):**
http://pythonnet.github.io/

**Project Transfer Signatories:**
Will be submitted via e-mail to contact@dotnetfoundation.org.

## 2.   Description

Python.NET implements embedding of .NET runtime in CPython and CPython in .NET.

In both cases, objects, classes and functions of the respective other environment can be used via reasonable and straightforward to use abstractions.

## 3.   Project Governance

**Project Lead:**

Name:   Benedikt Reinartz
 Email:   filmor+net@gmail.com
 GitHub Profile URL: https://github.com/filmor

**Committers:**

- https://github.com/filmor
- https://github.com/vmuriart (mainly as a backup)
- https://github.com/lostmsu

**Governance Model:**

The general direction of the project is discussed and decided in an open, bi-weekly call. Changes are implemented by individuals and discussed directly on the respective pull-requests, were the listed commiters retain the merge rights.

**CLA**

No.

**CLA Notification Alias**
-/-

**Project Transfer Type**

Contribution

## 4.   Repository Layout
- A `.gitattributes` file will be added
- We will discuss whether to move the current documentation out of the Github Wiki into the code

## 5.   PR Plan
There is no plan for this.

## 6.   Infrastructure Requirements
We currently don't need any additional infrastructure apart from access to the better AppVeyor plan for the project.

## 7.   Additional Notes
-/-

**Comment by filmor** [comment]
Is this missing anything in particular?

**Comment by ChrisSfanos** [comment]
Hi everyone - I'll be handling the onboarding of your project.  To get started, I'll need the email addresses of
@vmuriart 
@tonyroberts 
Can you send (or forward) them to chris.sfanos (at) dotnetfoundation.org  - thanks!

**Comment by ChrisSfanos** [comment]
Update - swapping in @lostmsu . I need both an email address and a last name - thanks!

**Comment by ChrisSfanos** [comment]
Hi @vmuriart 
I still need your email address so I can send out the CLA for signing - thanks!

**Comment by ChrisSfanos** [comment]
Last call for @vmuriart - if no reply, I'll remove and send the CLA as-is

**Comment by ChrisSfanos** [comment]
Hi everyone - we will be using the following checklist to track all the CLA and onboarding tasks to bring the project over to the .NET Foundation

## CLA
- [ ] CLA Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)

**Comment by ChrisSfanos** [comment]
CLA is signed - CLA bot onboarding email sent

**Comment by ChrisSfanos** [comment]
CLA bot config complete - emailed supplemental notes for the onboarding items

**Comment by ChrisSfanos** [comment]
Checking on the status of the task list - thanks!

**Comment by ChrisSfanos** [comment]
Website updates are complete - all items are done - marking this as Closed!  Thanks for all your efforts :-)
