### ISSUE TITLE
[Project Support]: Chem4Word

### ISSUE THREAD

**Issue by MikeWilliams-UK** [dotnet-foundation/projects#365]
### Project

Chem4Word

### Project Url

https://www.chem4word.co.uk

### Description

At the end of 2022 we were setup with access to three resource groups in the DNF Azure subscription.
See https://github.com/dotnet-foundation/projects/issues/219
This was handled by @ChrisSfanos.

I seem to have lost access to them.
If I log in to the Azure Portal and try to switch directories the DNF subscription is no longer showing for me.

If I use a direct link to one of the resources I get this error message
![image](https://github.com/dotnet-foundation/projects/assets/13162784/a59ab7d2-06da-4537-8f7b-82b3f11e89c7)

Please can it be fixed so that I can access our DNF resources?
Without this I will not be able to deploy any updates to our Azure Functions which run in the DNF subscription.

### Due By

12-Mar-2024

**Comment by MikeWilliams-UK** [comment]
@ChrisSfanos (or whoever actions this request) please can you also ensure that Clyde Davies ([clyde.davies@gmail.com](mailto:clyde.davies@gmail.com)) also is set up as owner/administrator of the Chem4Word resource group(s)

**Comment by MikeWilliams-UK** [comment]
@deadlyvices - Ping to include you Clyde

**Comment by deadlyvices** [comment]
I'm experiencing exactly the same issue as Mike: I can't see the DNF Azure Subscription

**Comment by nicoleabuhakmeh** [comment]
Both of your passwords have been reset and an email should have been generated to log in. The resource will be added to the list so it's not an issue in the future. Sorry to have caused you both an issue.

**Comment by deadlyvices** [comment]
No problems, thanks for sorting this out so quickly!

Clyde
________________________________

**Comment by MikeWilliams-UK** [comment]
I have just tried to log on and it does not recognise my email address as mike@doublewide.co.uk

**Comment by deadlyvices** [comment]
Use the account in the banner message that was sent you.

Mine was ***@***.***

________________________________

**Comment by MikeWilliams-UK** [comment]
Just worked out that I had to use the FULL string sent in the email, not my old login details :-)

**Comment by deadlyvices** [comment]
I confess I'm not sure what this new account ***@***.*** actually is for!
I can log in with it, but our present resources and subscriptions are managed in Azure under our old credentials, in my case ***@***.***
So what does this new account do?

Thanks
Clyde
________________________________

**Comment by MikeWilliams-UK** [comment]
Thanks @nicoleabuhakmeh I can now get to our resources in the DNF Azure Subscription
@deadlyvices please confirm that you can access them by logging on to the azure portal with your regular account then switching directory to the ".NET Foundation"

**Comment by deadlyvices** [comment]
I can see them all now, thanks
________________________________

**Comment by MikeWilliams-UK** [comment]
Thanks @nicoleabuhakmeh - All is working as it used to.
