### ISSUE TITLE
"fill out a new project application" link seems out of date

### ISSUE THREAD

**Issue by gregsdennis** [dotnet-foundation/projects#366]
The "fill out a new project application" link on https://old.dotnetfoundation.org/projects/submit appears to be out of date.  The link is

```
https://github.com/dotnet-foundation/projects/issues/new?assignees=&labels=project+application&template=application.md&title=
```

It appears the template has been updated to a YAML file.  (This issue was created using the link and has no template.)

**Comment by gregsdennis** [comment]
Looks like the "join" link in the readme is also out of date for the same reason: new YAML template.

```
https://github.com/dotnet-foundation/projects/issues/new?assignees=sbwalker&labels=membership&template=membership.md
```

**Comment by glennawatson** [comment]
The join is being actively worked on the monent. It's seen re developed and in testing right now

**Comment by nicoleabuhakmeh** [comment]
Hi there, It looks like you're on the old website. The link on our website is: [https://dotnetfoundation.org/projects/submit-a-project](https://dotnetfoundation.org/projects/submit-a-project
)

**Comment by gregsdennis** [comment]
Strange. That's just where I was directed. I didn't even notice the URL.
