### ISSUE TITLE
Project Support Request: AAS WorldWide Telescope — domain name transfer

### ISSUE THREAD

**Issue by pkgw** [dotnet-foundation/projects#37]
### Please fill in the information below:
- **Project Name:** AAS WorldWide Telescope
- **Due by:** 1/31/2020
- **Description:** Transfer `openwwt.{org,com}` to project control

After the successful handling of #2, the next domains that I'd like to bring under the project umbrella are `openwwt.org` and `openwwt.com`, registered by project founder @astrojonathan. I presume Jonathan needs to kick the process off — would you be able to give him the steps he needs to follow? Thanks.

**Comment by onovotny** [comment]
The domains would need to be unlocked for transfer and the unlock code sent to me (oren at dotnetfoundation dot org). I can then initiate the transfer to our registrar. 

Where is the DNS currently served from? Do you need us to create a new DNS Zone or are you able to handle that yourselves in the azure subscription similar to how the other one is done?

**Comment by pkgw** [comment]
Looks like the DNS is coming from EasyDNS at the moment. We could handle the DNS in our Azure subscription ourselves, I think. AFAIK these domains just act as aliases for worldwidetelescope.org.

**Comment by astrojonathan** [comment]
Ok. I will get that and send it...

**Comment by astrojonathan** [comment]
I send Oren the unlock codes for both domains.

**Comment by onovotny** [comment]
I just initiated the transfer.

**Comment by onovotny** [comment]
Looks like there's a hiccup as the domains are still marked as locked. They need to be unlocked with easyDNS and then we can try again.

**Comment by onovotny** [comment]
Gentle ping on this, we're blocked on the transfer until the domains are unlocked from easyDNS.

**Comment by astrojonathan** [comment]
Try now

**Comment by astrojonathan** [comment]
They love making it hard to leave..

**Comment by pkgw** [comment]
@onovotny Did you get a chance to try again? Do the unlock codes have an expiration date or anything?

**Comment by clairernovotny** [comment]
Closing as completed
