### ISSUE TITLE
MiniExcel .NET Foundation Project Application

### ISSUE THREAD

**Issue by shps951023** [dotnet-foundation/projects#371]
### Project Name

MiniExcel

### License

Apache-2.0

### Contributor

Wei Lin, mini-software team

### Existing OSS Project?

Yes

### Source Code URL

https://github.com/mini-software/MiniExcel

### Project Transfer Signatories

Wei Lin shps951002@gmail.com

### Description

MiniExcel is simple and efficient to avoid OOM's .NET processing Excel tool.

At present, most popular frameworks need to load all the data into the memory to facilitate operation, but it will cause memory consumption problems. MiniExcel tries to use algorithm from a stream to reduce the original 1000 MB occupation to a few MB to avoid OOM(out of memory).

### Name

Wei Lin

### Email

shps951002@gmail.com

### GitHub Profile URL

https://github.com/shps951023

### Maintainers
- Responsible for one or more components within the project.
- Review and merge pull requests related to their components.
- Address issues and bugs related to their components.

### Pull Requests
- All changes to the project must be made through PRs.
- PRs must be reviewed by at least one core contributor before merging.
- Contributors should follow the project's coding standards and guidelines.

### Issue Tracking
- All bugs, feature requests, and enhancements must be tracked using Issues.
- Community members are encouraged to report issues and suggest improvements.

### CLA

- [ ] If already an OSS project, was a Contribution License Agreement in place for contributions accepted?

### Select the Project Transfer Agreement model

Assignment

### Eligibility Criteria

- [X] The project is built on the .NET platform and/or creates value within the .NET ecosystem.
- [X] The project produces source code for distribution to the public at no charge.
- [X] The project's code is easily discoverable and publicly accessible (preferably on GitHub).
- [X] The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).
- [X] When applicable, project must use reproducible build settings in its toolchain.
- [X] The project uses [Source Link.](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
- [X] The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).
- [X] The project code signs their artifacts as appropriate.
- [X] The project organization has 2FA enabled. Requiring 2FA must be done as part of onboarding if not already enabled.
- [X] Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).
- [X] Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.
- [X] The copyright ownership of everything that the project produces is clearly defined and documented.
- [X] The project has a public issue tracker where the status of any defect can be easily obtained.
- [X] The project has a published Security Policy.
- [X] The project has a home page which provides high level information about its status and purpose.
- [X] The project has a public communication channel where community members can engage with maintainers.
- [X] The project has a publicly available location where members can review and contribute to documentation.

### PR Plan Summary

Open source project to make better .NET community.

**Comment by sbwalker** [comment]
The Project Committee reviewed your application and will recommend the project for consideration of Member status at the next Board of Directors meeting. The project will require a majority Board vote to proceed.

**Comment by ChrisSfanos** [comment]
The project was approved by the Board to join the .NET Foundation - congratulations

**Comment by ChrisSfanos** [comment]
For the onboarding process, we will be using this tracking checklist - I'll be starting on this project on monday

## CLA
- [ ] Project Agreement Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)
- [ ] Enable two-factor authentication (2FA) for GitHub organization and all users

**Comment by ChrisSfanos** [comment]
Agreement is signed - CLA onboarding instructions coming out shortly

**Comment by ChrisSfanos** [comment]
CLA onboarding is complete - I'll be sending the remaining onboarding steps tomorrow

**Comment by ChrisSfanos** [comment]
onboarding complete
