### ISSUE TITLE
[Code Signing Certificate]: std.uritemplate

### ISSUE THREAD

**Issue by baywet** [dotnet-foundation/projects#378]
### Project Name

std.uritemplate

### LastPass Email

andrea.peruffo1982@gmail.com, vincentbiret@hotmail.com

### Onboarding Checklist

- [x] Register trade name @ChrisSfanos
- [x] Create configuration in Code Signing Service
- [x] Create organization with DigiCert
- [x] Request certificate from DigiCert
- [x] Received certificate and finalize sign service configuration
- [x] Provide credentials in shared folder in LastPass

CC @andreaTP

**Comment by yihezkel** [comment]
Sorry to bother, but I don't see any updates here. Is this progressing?

**Comment by andreaTP** [comment]
Thanks for checking on us @yihezkel , yes, this is progressing, waiting on @ChrisSfanos to get it to the next step.

**Comment by ChrisSfanos** [comment]
Completed certificate registration work and handed all the config details over to @andreaTP

**Comment by andreaTP** [comment]
Implemented and working, this can be closed 🎉

**Comment by ChrisSfanos** [comment]
closing :-)
