### ISSUE TITLE
xUnit.net Code Signing Certificate needs to be renewed

### ISSUE THREAD

**Issue by bradwilson** [dotnet-foundation/projects#379]
Builds for xUnit.net are currently broken because the code signing certificate is expired:

```
warn: Sign.Core.ICertificateVerifier[0]
      The certificate is expired.
fail: Sign.Core.ISignatureProvider[0]
      Signing failed with error -2146762486.
```

**Comment by bradwilson** [comment]
cc: @ChrisSfanos

**Comment by ChrisSfanos** [comment]
A new cert was generated and uploaded to the sign service

**Comment by bradwilson** [comment]
Still not working, same problem:

```
 warn: Sign.Core.ICertificateVerifier[0]
      The certificate is expired.
fail: Sign.Core.ISignatureProvider[0]
      Signing failed with error -2146762486.
```

Sample run: https://github.com/xunit/xunit/actions/runs/9424328378/job/25977267549

**Comment by bradwilson** [comment]
I can also repro this from home, so it doesn't appear to be an Actions issue:

![image](https://github.com/dotnet-foundation/projects/assets/16944/7b74fce6-0e29-480f-a3d3-bf658e5338f5)

**Comment by bradwilson** [comment]
All good now! Thanks!
