### ISSUE TITLE
CoreWF

### ISSUE THREAD

**Issue by clairernovotny** [dotnet-foundation/projects#38]
## 1.   General Information

**Project Name:**
CoreWF
**License:**
MIT
**Contributor (Company, Organization or individual name(s)):**
UiPath
**Existing OSS Project? (Yes/No):**
Yes
**Source Code URL:**
https://github.com/UiPath/corewf
**Project Homepage URL (if different):**

**Project Transfer Signatories:**
Full legal name and email address required of the individual(s) with the authority to transfer or contribute the project to the .NET Foundation. Note that if you'd prefer not to include this in the public application, it can be submitted via e-mail to contact@dotnetfoundation.org (referencing this issue number).
Marius Tirca

## 2.   Description
**Please provide a brief statement about your project in terms that are understandable to the target consumer of the library or project, i.e. an elevator pitch for the project:**

The Windows Workflow Foundation (WF) handles the long-running work of many companies. It powers many applications in all types of businesses. As more developers look into adopting .NET Core, some are asking if WF will be officially ported. This project only ports the WF runtime and ETW tracking provider to the .NET Standard. But much more work is needed before it can substitute for the .NET Framework version.

**Please provide a 1 sentence (<140 character) summary of your to help users when searching the .NET Foundation projects**

A port of the Windows Workflow Foundation (WF) runtime to the .NET Standard.

## 3.   Project Governance
Please complete this section about who will be maintaining the open source project and how it will run.
**Project Lead:** 
(Who is the primary contact point for the community and the .NET Foundation when discussing governance of the project.)

Name:   Marius Tirca 
 Email:   
 GitHub Profile URL: @marivs

**Committers:**

Which individuals have commit / write access to the repository, what is their GitHub ID and who is their employer (if contributions are on behalf of an employer)

@lbargaoanu 
@dmetzgar 
@ewinnington 

**Governance Model:**

Please describe how new code changes are proposed to the project, how those changes are reviewed and how a decision is made to accept proposed changes. Also describe the process for identifying and appointing new committers.

@lbargaoanu (UiPath employee) is the current maintainer of the repo

**CLA**
No

If already an OSS project, was a Contribution License Agreement in place for contributions accepted? How does the project check who has signed one?

**CLA Notification Alias**
Provide an email address that will receive CLA related notifications from the .NET Foundation CLA automation

**Project Transfer Type**

Projects may join the .NET Foundation in one of two ways and you should chat with your .NET Foundation contact to discuss the best mechanism for your project. You can either a) assign the copyright of the project's source code to the .NET Foundation or b) contribute the project source code to the .NET Foundation under an open source license. Assignment is the preferred approach, but licensing a project to the Foundation may be more appropriate for longer running open source projects that have not previously had a contribution license agreement and have accepted contributions from many different sources.
a) Assignment
b) Contribution

Assignment

## 4.   Repository Layout
The .NET Foundation host guidance for new projects and details on recommended structure here:
[https://github.com/dotnet/home/tree/master/guidance](https://github.com/dotnet/home/tree/master/guidance)

Note that the open source repository should be the master where changes are made by the core development team using the same PR process that is used for non-committer contributions.

Please define below any changes you would want to make to your repositories as part of the process of joining the .NET Foundation

I don’t think any repo changes are required as part of this process.

## 5.   PR Plan
Please summarize the public relations plan for the announcement when joining the foundation (and releasing as open source if appropriate). What is the main story we wish to promote, through what channels, what issues should we be aware of?  For significant news events then please also work with your .NET Foundation contact to ensure a [full PR plan](https://dotnetfoundation.sharepoint.com/Shared%20Documents/PR/Communications%20Plan%20TEMPLATE.docx?web=1) is developed.

We’ll have to follow up for a full PR plan, but the main idea is that UiPath is committed to support this project going forward.

## 6.   Infrastructure Requirements
Please describe any infrastructure requirements for the project. For example, how will build servers be operated? Any web hosting or service hosting requirements? Do we need to set up SSL certificates or provide Authenticode Code Signing arrangement for releases?

It’s just a library. Azure DevOps Pipeline hosted agent is already configured as a build server, no special requirements.

## 7.   Additional Notes
Please provide any additional information required or use this area for notes during the onboarding process. If this open source project has similarities with any other projects in this space then please detail them and why this project is different. If there are any potential issues that you feel the project might need help with early on then also state them here and discuss with your .NET Foundation Contact.

**Comment by ChrisSfanos** [comment]
Hi everyone
I'll be working on the backend to on-board/post-onboarding to bring the project to the .NET Foundation.  The on-boarding consists of:

1) CLA signing via DocuSign
2) CLA onboarding via GitHub

to complete #1, I need the email addresses of the following contributors:
@lbargaoanu
@dmetzgar
@marivs

If you don't want to post your email address here, please send it to me at chris.sfanos@dotnetfoundation.org

**Comment by ChrisSfanos** [comment]
CLA is out for signing

**Comment by ChrisSfanos** [comment]
CLA is signed - moving to CLA onboarding via GitHub

**Comment by ChrisSfanos** [comment]
We will track the remaining onboarding work via this checklist:

## Onboarding
- [ ] CLA Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Post Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Enable CLA automation for future contributors
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)

**Comment by ChrisSfanos** [comment]
CLA Bot onboarding complete - I've sent @marivs the post on-boarding work

**Comment by ChrisSfanos** [comment]
Pinging @marivs on the latest status

**Comment by dmetzgar** [comment]
Project list PR: https://github.com/dotnet/foundation/pull/174

Readme update: https://github.com/UiPath-Open/corewf/pull/103

**Comment by ChrisSfanos** [comment]
Onboarding is complete - closing this out
