### ISSUE TITLE
xUnit.net Code Signing Certificate not valid on NuGet.org

### ISSUE THREAD

**Issue by bradwilson** [dotnet-foundation/projects#383]
I got my [certificate renewed](https://github.com/dotnet-foundation/projects/issues/379) last month, and now when I try to upload packages signed with the new certificate to NuGet, it no longer allows them because the certificate is unknown.

The organization certificate settings show this (and it's expired, though I was able to upload packages right up until the last certificate renewal):

![image](https://github.com/dotnet-foundation/projects/assets/16944/34fcfa88-21ae-4d56-a81c-7e54deeef47f)

In order to fix this issue, I apparently need the .cer file of the certificate. Since this certificate is presumably stored in Azure without me having direct access to it, either someone there with access to my NuGet organziation needs to upload this, or you need to provide me with the .cer file so that I can do it.

Note that the package is verifiably signed:

![image](https://github.com/dotnet-foundation/projects/assets/16944/cebde093-c373-40f5-9f69-1c3b55372dd5)

(tagging @ChrisSfanos as I'm pretty sure that's who would be able to do this for me)

**Comment by bradwilson** [comment]
FYI, this is the e-mail that NuGet sent me:

> The package [xunit 2.9.0](https://www.nuget.org/packages/xunit/2.9.0) failed validation because of the following reason(s):
>
>    The package was signed, but the signing certificate (SHA-1 thumbprint `e49a663526bcc40878466be4f49f9833b3302c0a`) is not associated with your account. You must register this certificate to publish signed packages. [Read more...](https://aka.ms/nuget-signed-ref)
>
> Your package was not published on NuGet Gallery and is not available for consumption.
>
> You can reupload your package once you've fixed the issue with it.

**Comment by bradwilson** [comment]
I opened one of my signed packages in NuGet Package Explorer, and clicked on the certificate.

First, I exported this:

![image](https://github.com/dotnet-foundation/projects/assets/16944/ca863e51-4d86-4201-84ee-992d857320ae)

And then uploaded that to NuGet, but that still failed verification.

Then I tried uploading this:

![image](https://github.com/dotnet-foundation/projects/assets/16944/ddd0ba2a-d492-4d8b-b359-341fef1f636f)

That also failed to verify when I uploaded the package.

Note that when I uploaded both of those, they did not show any subject or expiration information in the NuGet UI:

![image](https://github.com/dotnet-foundation/projects/assets/16944/1a072c61-eb83-4ad2-9c65-a031d08209ed)

(0d766 is the xUnit.net key, d60d2 is the parent certificate)

NuGet makes it exceptionally confusing by showing SHA256 in the UI, but showing me SHA1 when the packages failed to upload. However, I did verify that the SHA1 from my e-mail matched the xUnit.net key:

![image](https://github.com/dotnet-foundation/projects/assets/16944/dc760a72-3d0c-44a1-b616-ee65fd86106a)

I'm not sure what the problem is, but I have a couple ideas:

(a) I'm just not uploading the right thing, though it is accepting them;
(b) There is a lag between the time you upload a certificate and when it becomes available for verification.

`¯\_(ツ)_/¯`

**Comment by bradwilson** [comment]
I should point out that I wrote the previous reply several hours ago but didn't hit the Go button. I re-tried uploading one of the packages (testing the time lag hypothesis) and it still fails validation.

At this point I'm 90% sure that the NuGet team is going to need to get involved, so I'm going to go open an issue there.

**Comment by bradwilson** [comment]
Here's the NuGet issue I opened: https://github.com/NuGet/NuGetGallery/issues/10058

**Comment by ChrisSfanos** [comment]
Yep this is a task for me - hang on and let me take a look

**Comment by ChrisSfanos** [comment]
I uploaded the certificate to NuGet - can you take a look?

**Comment by bradwilson** [comment]
Did you delete one before uploading? Because it looks identical to what I had before. (Also, have you read the whole thread? I've already extracted the .CER file from a signed package, and now believe that NuGet is bugged.)

**Comment by bradwilson** [comment]
Okay, this time the package upload worked. I would really like to know what you did different than I did because this *should* have been a (pain in the butt, admittedly) self-service item.

**Comment by bradwilson** [comment]
Ah, okay, that went to the wrong place, which means my self-extracted certificate did finally just start working. xUnit.net is not in the dotnetfoundation organization on NuGet, it has its own organization.

**Comment by bradwilson** [comment]
Aha! Someone just posted this into Discord:

> FWIW silk.net is the same and I think there’s more projects out there as well. We do have dotnetfoundation as an owner on some packages, and that does indeed lock up the certificate changes - it’s hardcoded somewhere that if “dotnetfoundation” is an owner, they’re the only ones that can manage certificate settings.

That's why it suddenly started working. I don't know it for sure but the coincidence level is just too high for it to not be true. I'm going to leave my NuGet issue open just for 100% verification. That _also_ explains why I've been able to upload packages even though the only other certificate in my list is waaaaaaay expired: someone must've uploaded it to `dotnetfoundation` last time, presumably Claire.

Sounds like one of the standard steps for certificate renewal needs to be to make sure it gets added to `dotnetfoundation`. 👍🏼

**Comment by ChrisSfanos** [comment]
Depending on when it was, it was either myself or Claire

I don't believe every .NET Foundation project distributes through NuGet (I may be wrong - just speculating), so we don't always upload the new cert to NuGet unless the project owner specifically requests it
