### ISSUE TITLE
[Code Signing Certificate]: json-everything

### ISSUE THREAD

**Issue by gregsdennis** [dotnet-foundation/projects#384]
### Project Name

json-everything

### LastPass Email

emailed

### Onboarding Checklist

- [x] Register trade name @ChrisSfanos
- [ ] Create configuration in Code Signing Service
- [ ] Create organization with DigiCert
- [ ] Request certificate from DigiCert
- [ ] Received certificate and finalize sign service configuration
- [ ] Provide credentials in shared folder in LastPass

**Comment by gregsdennis** [comment]
There are currently multiple packages that come out of this project, and it's likely that new ones will come eventually.  Will the cert be able to apply to all of them?

**Comment by ChrisSfanos** [comment]
Trade name submitted - it'll take a few days or so for it to process

**Comment by gregsdennis** [comment]
Hey @ChrisSfanos.  How's this progressing?

**Comment by ChrisSfanos** [comment]
There were some processing delays - I'm working with DigiCert right now on getting it moving

**Comment by ChrisSfanos** [comment]
certificate generated and details emailed out today

**Comment by gregsdennis** [comment]
I have all the details.  Thank you @ChrisSfanos.  I think this can be closed out.  I suppose I contact you again when this secret expires?  Or is renewal something I can do?

**Comment by ChrisSfanos** [comment]
Ok great - I'll close it up.  As for the secret - we will want to move to the managed identities option sooner than that, and I'll reach out at that time
