### ISSUE TITLE
Issue: New .NET Foundation Project Application

### ISSUE THREAD

**Issue by ArgoZhang** [dotnet-foundation/projects#386]
### Project Name

BootstrapBlazor

### License

Apache-2.0

### Contributor

Argo, azlis, densen2014, YSMC-W, j4587698

### Existing OSS Project?

Yes

### Source Code URL

https://github.com/dotnetcore/BootstrapBlazor?wt.mc_id=DT-MVP-5004174

### Project Homepage URL

https://www.blazor.zone

### Project Transfer Signatories

argo@live.ca

### Description

BootstrapBlazor is an enterprise-grade library that fuses Bootstrap with Blazor, offering developers a powerful toolkit for building responsive and interactive web applications effortlessly.

### Name

Argo Zhang

### Email

argo@live.ca

### GitHub Profile URL

https://github.com/ArgoZhang?wt.mc_id=DT-MVP-5004174

### Committers

- [Old Li](https://github.com/azlis?wt.mc_id=DT-MVP-5004174)
- [Alex chow](https://github.com/densen2014?wt.mc_id=DT-MVP-5004174)
- [YSMC](https://github.com/YSMC-W?wt.mc_id=DT-MVP-5004174)
- [j4587698](https://github.com/j4587698?wt.mc_id=DT-MVP-5004174)
- [zhangpeihang](https://github.com/Vision-Zhang?wt.mc_id=DT-MVP-5004174)

### Governance Model

New requirements and bugs start with community discussions, and then issues are created on GitHub to track progress, or discussions are created to discuss and find the best possible solutions. The maintenance team or creator then creates branches and submits the code. Finally, team members review the code and check unit tests to ensure that no new problems will arise.

### CLA

- [X] If already an OSS project, was a Contribution License Agreement in place for contributions accepted?

### How does the project check who has signed one?

the project uses [https://cla-assistant.io](https://cla-assistant.io) for CLA management, and 26 people have signed it.

### CLA Notification Alias

argo@live.ca

### Select the Project Transfer Agreement model

Contribution

### Eligibility Criteria

- [X] The project is built on the .NET platform and/or creates value within the .NET ecosystem.
- [X] The project produces source code for distribution to the public at no charge.
- [X] The project's code is easily discoverable and publicly accessible (preferably on GitHub).
- [X] The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).
- [X] When applicable, project must use reproducible build settings in its toolchain.
- [X] The project uses [Source Link.](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
- [X] The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).
- [X] The project code signs their artifacts as appropriate.
- [X] The project organization has 2FA enabled. Requiring 2FA must be done as part of onboarding if not already enabled.
- [X] Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).
- [X] Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.
- [X] The copyright ownership of everything that the project produces is clearly defined and documented.
- [X] The project has a public issue tracker where the status of any defect can be easily obtained.
- [X] The project has a published Security Policy.
- [X] The project has a home page which provides high level information about its status and purpose.
- [X] The project has a public communication channel where community members can engage with maintainers.
- [X] The project has a publicly available location where members can review and contribute to documentation.

### PR Plan Summary

This component library currently has nearly 200 components with 100% unit testing, which can greatly enrich the ecological environment in the Blazor field and provide more Blazor enthusiasts with an alternative.

### Infrastructure Requirements Summary

 follow the documentation https://www.blazor.zone/install-server

**Comment by sbwalker** [comment]
Project will be reviewed today at the Project Committee Monthly Meeting

**Comment by sbwalker** [comment]
The project will be recommended for approval as a Member Project at the next BOD meeting

**Comment by ArgoZhang** [comment]
🎉 Great! Just Signed!

**Comment by ChrisSfanos** [comment]
Thanks - we will use the following checklist as we onboard - I will email you soon with details on the list

## CLA
- [ ] Project Agreement Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)
- [ ] Enable two-factor authentication (2FA) for GitHub organization and all users

**Comment by ChrisSfanos** [comment]
email sent for CLA onboarding

**Comment by ChrisSfanos** [comment]
just got back to review - closing
