### ISSUE TITLE
Meeting Agenda - August 8th, 2024

### ISSUE THREAD

**Issue by nicoleabuhakmeh** [dotnet-foundation/projects#390]
### Agenda Items

Agenda Items
The Project Committee will have their monthly meeting on August 8th at 5pm Eastern on Discord.

Discord link is open to current members of the Project Committee for the meeting: https://discord.com/events/966483029830824008/1185240341675261962

Agenda Items

Review of Project Applications:
386 [BootstrapBlazor](https://github.com/dotnetcore/BootstrapBlazor)

388 [FluentCMS](https://github.com/fluentcms/FluentCMS)

Update on the previous agenda items:
@glennawatson - Signing Certificate Change
[Shotgun.API](https://github.com/dotnet-foundation/projects/issues/382) - Needs license

Board Approved and Onboarded Projects from the previous month:

Community Updates

Next Meeting: September 12th, 5pm Eastern. 
September Agenda:  Emma Irwin from the Microsoft Open Source Program Office will be joining us to talk about their initiatives.

**Comment by Freysi21** [comment]
@nicoleabuhakmeh do I need to do something regarding license to get this further?

**Comment by Freysi21** [comment]
@nicoleabuhakmeh a license has been added to the repo

**Comment by Freysi21** [comment]
@glennawatson this is the project https://github.com/dotnet-foundation/projects/issues/382
