### ISSUE TITLE
[Project Support]: Datasync Toolkit Projects page Link Update

### ISSUE THREAD

**Issue by michael-hawker** [dotnet-foundation/projects#392]
### Project

Datasync Toolkit

### Project Url

https://github.com/CommunityToolkit/Datasync

### Description

Looks like [this listing](https://dotnetfoundation.org/projects/project-detail/community-datasync-toolkit) was updated but not the link to the new repo for that one: https://github.com/CommunityToolkit/Datasync

Related to still pending #289 and #286

### Due By

8/12/2024

**Comment by 1kevgriff** [comment]
@ChrisSfanos I've been playing around on the website, and I updated the repo link.

https://dotnetfoundation.org/projects/project-detail/community-datasync-toolkit

**Comment by michael-hawker** [comment]
FYI @adrianhall

**Comment by adrianhall** [comment]
Ack - thanks Michael.
