### ISSUE TITLE
Project Support Request: [Windows Community Toolkit] Update Projects website listing

### ISSUE THREAD

**Issue by michael-hawker** [dotnet-foundation/projects#393]
Need this listing updated: https://dotnetfoundation.org/projects/project-detail/windows-community-toolkit

> I also noticed that our Windows Community Toolkit listing doesn't have a 'Project Website' button like the others.

We're also migrating our repository to https://github.com/CommunityToolkit/Windows, so we'll want to update the link ourselves for that:

- **Title**: Windows Community Toolkit
- **Description**: The Windows Community Toolkit is a collection of controls for WinUI 2, WinUI 3, and Uno Platform developers. It simplifies and demonstrates common developer tasks building experiences for Windows with .NET.
- **Image Logo**: https://github.com/CommunityToolkit/Windows/blob/main/icon.png
- **GitHub Repo**: https://github.com/CommunityToolkit/Windows
- **Project Website**: https://aka.ms/windowstoolkitdocs

_Originally posted by @michael-hawker in https://github.com/dotnet-foundation/projects/issues/286#issuecomment-1694033889_

**Comment by 1kevgriff** [comment]
I've updated the DNF website for this project: https://learn.microsoft.com/en-us/dotnet/communitytoolkit/windows/
