### ISSUE TITLE
Issue: New .NET Foundation Project Application - MessagePack-CSharp

### ISSUE THREAD

**Issue by AArnott** [dotnet-foundation/projects#396]
### Project Name

MessagePack

### License

MIT and BSD 2-Clause License

### Contributor

Andrew Arnott, Yoshifumi Kawai

### Existing OSS Project?

Yes

### Source Code URL

https://github.com/MessagePack-CSharp/MessagePack-CSharp

### Project Transfer Signatories

* Yoshifumi Kawai <ils@neue.cc>
* Andrew Arnott <andrewarnott@live.com>

### Description

Extremely Fast MessagePack Serializer for C#(.NET, .NET Core, Unity, Xamarin). / msgpack.org[C#]

### Name

Yoshifumi Kawai

### Email

ils@neue.cc

### GitHub Profile URL

https://github.com/neuecc

### Committers

neuecc
aarnott

### Discord Ids

- `aarnott.` (yes, the trailing period is part of the username)

### Governance Model

TODO

### CLA

- [ ] If already an OSS project, was a Contribution License Agreement in place for contributions accepted?

### CLA Notification Alias

andrewarnott@live.com

### Select the Project Transfer Agreement model

Contribution

### Repository Layout

.gitattributes
.gitignore
README.md - a very long document explaining how to use the library
doc/ - a directory of a few satellite docs linked to from the README file.
src/ - The source code for the several libraries/packages built from this repo
tests/ - All tests
sandbox/ - test data/projects used to verify MessagePack functionality either on their own, or used by the projects under `tests/`
.github - GitHub Actions
azure-pipelines - Azure Pipelines workflows

### Eligibility Criteria

- [X] The project is built on the .NET platform and/or creates value within the .NET ecosystem.
- [X] The project produces source code for distribution to the public at no charge.
- [X] The project's code is easily discoverable and publicly accessible (preferably on GitHub).
- [X] The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).
- [X] When applicable, project must use reproducible build settings in its toolchain.
- [X] The project uses [Source Link.](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
- [X] The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).
- [ ] The project code signs their artifacts as appropriate.
- [ ] The project organization has 2FA enabled. Requiring 2FA must be done as part of onboarding if not already enabled.
- [X] Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).
- [x] Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.
- [X] The copyright ownership of everything that the project produces is clearly defined and documented.
- [X] The project has a public issue tracker where the status of any defect can be easily obtained.
- [x] The project has a published Security Policy.
- [X] The project has a home page which provides high level information about its status and purpose.
- [X] The project has a public communication channel where community members can engage with maintainers.
- [X] The project has a publicly available location where members can review and contribute to documentation.

### PR Plan Summary

.NET 9 is removing the BinaryFormatter and has documented to customers a few alternatives for existing users to switch to. These alternatives include MessagePack. Some customers have expressed hesitancy to switch to MessagePack unless it's part of the .NET Foundation.

### Infrastructure Requirements Summary

A code signing certificate would be appreciated, as we don't already have one.

**Comment by AArnott** [comment]
> Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.

I am willing to embrace the .NET Foundation's CLA.

@neuecc can you indicate the same?

**Comment by neuecc** [comment]
> @neuecc can you indicate the same?

Yes.

**Comment by sbwalker** [comment]
The Project Committee will review the application at the Sept 12 meeting

**Comment by ChrisSfanos** [comment]
Hello!  This project has been approved to join the .NET Foundation!   The transfer agreement is now out for signing - thanks!

**Comment by AArnott** [comment]
I'm glad you said that, @ChrisSfanos because I had to dig through my Junk mail to find the docusign email.

**Comment by ChrisSfanos** [comment]
Thanks - we will use the following checklist as we onboard - I will email you soon with details on the list

## CLA
- [ ] Project Agreement Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)
- [ ] Enable two-factor authentication (2FA) for GitHub organization and all users

**Comment by ChrisSfanos** [comment]
email sent for CLA onboarding

**Comment by ChrisSfanos** [comment]
CLA onboarding complete - I'll send the remaining work items in email in a few

**Comment by ChrisSfanos** [comment]
Just got to checking the list - closing
