### ISSUE TITLE
Project Support Request: ImageSharp

### ISSUE THREAD

**Issue by JimBobSquarePants** [dotnet-foundation/projects#40]
### Please fill in the information below:
- **Project Name:** ImageSharp
- **Due By:**
- **Description:**
  - Set up CI/CD on Azure DevOps
  - Code Signing Certificate and Service

I'm not 100% sure on what the process is for either. 

I know I can create multiple pipelines under the one project so that would cover building ImageSharp and ImageSharp.Drawing etc. I don't know how code signing works at all. Would the certificate subject be 

- SixLabors
- SixLabors (.NET Foundation)
- Something else?

Thanks in advance!

**Comment by onovotny** [comment]
Thanks!

Can you please fill out a separate issue to track the code signing request? https://github.com/dotnet-foundation/projects/issues

The certificate would typically be the project name ImageSharp unless there's a good reason for something else?

**Comment by JimBobSquarePants** [comment]
Of course, will do thanks!

>The certificate would typically be the project name ImageSharp unless there's a good reason for something else?

This is where things are muddy. There's multiple open source libraries in our org that ImageSharp uses.

**Comment by onovotny** [comment]
I've created the project in our DevOps repo here: https://dev.azure.com/dotnet/SixLabors and invited you in as a project admin. Please let me know if there's anything else you need.

**Comment by JimBobSquarePants** [comment]
Hooray! Thanks very much!

**Comment by JimBobSquarePants** [comment]
Actually.... Was there a timeout on this? I'm getting a 401 after authorizing the NET Foundation app.

**Comment by onovotny** [comment]
No... but DevOps sometimes has trouble with B2B invites.

If you go here https://aex.dev.azure.com/me, and sign in, there's a drop down on the left side under your profile information. If you switch it to `.NET Foundation`, it should prompt to setup a new DevOps profile in that tenant. That's likely the issue.

**Comment by JimBobSquarePants** [comment]
That did the trick. Thanks!
