### ISSUE TITLE
[Project Support]: MvvmCross code signing

### ISSUE THREAD

**Issue by Cheesebaron** [dotnet-foundation/projects#409]
### Project

MvvmCross

### Project Url

https://github.com/mvvmcross/mvvmcross

### Description

Similar to this issue #406 when using SignClient we get Internal Server error trying to sign NuGet packages.

Would it be possible to get some help fixing this?

If you would like us to sign differently, I am happy to switch to something else.

See latest run here:

https://github.com/MvvmCross/MvvmCross/actions/runs/11609433969/job/32326666096

Workflow has just been moved here: https://github.com/MvvmCross/MvvmCross/blob/develop/.github/workflows/release.yml

### Due By

As soon as possible?

**Comment by ChrisSfanos** [comment]
Hi @Cheesebaron - for some reason, the 500 errors are actually mean your cert has expired (it did back in July).  I'll kick start getting you a new one

**Comment by ChrisSfanos** [comment]
new cert created and uploaded (and on NuGet).  Email me at chris dot sfanos at dotnetfoundation dot org and I'll send you the new friendly name

**Comment by JamesNK** [comment]
Hi

I have the same issue. Project: Newtonsoft.Json. Could you generate a new cert for my project?

**Comment by ChrisSfanos** [comment]
New cert created and I emailed James the info.  Once he validates it, we can close this - thanks!

**Comment by JamesNK** [comment]
My issue is fixed. Can close.
