### ISSUE TITLE
Code Signing Certificate Request: ImageSharp

### ISSUE THREAD

**Issue by JimBobSquarePants** [dotnet-foundation/projects#41]
### Please fill in the information below
- **Project Name:** ImageSharp
- **LastPass Email (or send offline):** Will send offline.

Certificate onboarding checklist:

- [x] Register trade name @ChrisSfanos
- [x] Create organization with DigiCert
- [x] Create configuration in Code Signing Service
- [ ] Provide credentials in shared folder in LastPass
- [ ] Request certificate from DigiCert
- [ ] Recieved certificate and finalize sign service configuration

Please note: We have multiple projects under the SixLabors org that would require signing due to interop between those libraries. As such it is preferable to have the certificate subject be. **SixLabors**

**Comment by glennawatson** [comment]
On the ReactiveUI project we have a similar situation where we have multiple projects with differing names but the organisation name is ReactiveUI so our signing certificate is based on the organisation name. Given your GitHub organisation name is `SixLabors` would imagine be the same situation?

**Comment by JimBobSquarePants** [comment]
Perfect! I was hopping there was precedence.

**Comment by onovotny** [comment]
Should this be "SixLabors" or "Six Labors"? What is the entity?

**Comment by ChrisSfanos** [comment]
Registered the TradeName is ImageSharp (I took all the above as dealing only with the DigiCert stuff

**Comment by onovotny** [comment]
@ChrisSfanos We need the trade name to be "Six Labors" as well, since the trade name has to match what we enter into DigiCert.

**Comment by ChrisSfanos** [comment]
Ok, no problem - I added Six Labors as a Trade Name

**Comment by JimBobSquarePants** [comment]
Sorry for the confusion. It should be Six Labors

**Comment by onovotny** [comment]
@JimBobSquarePants What email address should I invite to the shared lastpass with the credentials?

**Comment by JimBobSquarePants** [comment]
@onovotny I'll send a message offline

**Comment by onovotny** [comment]
Just an update here, we've been blocked on a DigiCert bug on their certificate request form. We've been working on getting this resolved ASAP.

**Comment by JimBobSquarePants** [comment]
No worries, thanks for the update!

**Comment by onovotny** [comment]
@JimBobSquarePants The cert request was just completed and things are ready -- I didn't see your email, what address did you send it to?

**Comment by JimBobSquarePants** [comment]
That's great news! 

I added the email address to the project leader chat in the .NET Foundation Slack workspace

**Comment by onovotny** [comment]
Are you all set, can we close this out?

**Comment by JimBobSquarePants** [comment]
Was I supposed to see something in my LastPass account?

**Comment by onovotny** [comment]
Yes, you should have an invite

I do see this though 
![image](https://user-images.githubusercontent.com/1427284/76146373-24474980-6060-11ea-8a8c-6b7baad6dfcb.png)

**Comment by JimBobSquarePants** [comment]
Ah right... I don't normally use last pass so I didn't know this. I think I've done it now.

**Comment by JimBobSquarePants** [comment]
Ok. Looks like I have everything now. Thanks for your help @onovotny !!
