### ISSUE TITLE
[Project Support]: Silk.NET - Renew Codesigning

### ISSUE THREAD

**Issue by Perksey** [dotnet-foundation/projects#410]
### Project

Silk.NET

### Project Url

https://github.com/dotnet/Silk.NET

### Description

We’re failing to upload our latest build, which has been commissioned by a sponsor (so there is some pressure in getting this released), due to a CI error pertaining to codesigning. The `sign` tool is failing to sign our packages due to our certificate having expired.

Would it be possible to renew our code signing certificate and add the renewed certificate to the dotnetfoundation NuGet?

Many thanks.

CI job: <https://github.com/dotnet/Silk.NET/actions/runs/11667817658/job/32489233387>

### Due By

ASAP, urgently

**Comment by ChrisSfanos** [comment]
New cert is uploaded to sign service - I'll email you the new friendly name

**Comment by Perksey** [comment]
New cert received with thanks, once uploaded to NuGet this can be closed off :)

**Comment by ChrisSfanos** [comment]
That's now done - closing
