### ISSUE TITLE
[Project Support]: github hosted runners failing due to billing issue

### ISSUE THREAD

**Issue by michael-hawker** [dotnet-foundation/projects#415]
### Project

Windows Community Toolkit + Silk.NET

### Project Url

https://github.com/CommunityToolkit/Windows

### Description

As also reported by @Perksey for Silk.NET on Discord: https://discord.com/channels/966483029830824008/966484831091449856/1318240178053054607

> The job was not started because recent account payments have failed or your spending limit needs to be increased. Please check the 'Billing & plans' section in your settings.

![image](https://github.com/user-attachments/assets/e2f7a467-5935-4607-8848-a9cfc3500ee6)

He mentioned they have an `xlarge`, we have a 16-core one, not sure if those are the same.

### Due By

12/16/2024

**Comment by michael-hawker** [comment]
Thanks @ChrisSfanos! I think we're all good and things are moving again.

**Comment by Perksey** [comment]
Mentioned in the discord earlier prior to issue closure, but just commenting here too to confirm that Silk.NET's runners are working now as well :)
