### ISSUE TITLE
Project Support Request: ReactiveUI LastPass 

### ISSUE THREAD

**Issue by glennawatson** [dotnet-foundation/projects#42]
### Please fill in the information below:
- **Project Name:** ReactiveUI
- **Due by:** 31st January 2020
- **Description:** Given the leadership change 18 months ago of ReactiveUI it'd be nice if @glennawatson and @RLittlesII can get access to the organisation last pass.

**Comment by onovotny** [comment]
I need your email addresses that you use for LastPass and I can add you.

**Comment by glennawatson** [comment]
glenn@glennwatson.net is the email I would like to use.

**Comment by RLittlesII** [comment]
rodney.littles@gmail.com

**Comment by onovotny** [comment]
I've just invited you two to the shared folder. @glennawatson, looks like there's an extra step you need to do.

![image](https://user-images.githubusercontent.com/1427284/72397878-2a2f4700-370f-11ea-9c36-ac2343aaa7e3.png)

Once you've confirmed this works, we can close this issue.

**Comment by glennawatson** [comment]
I've clicked the "Generate Sharing Keys" link, I think you may have to reshare though.

**Comment by glennawatson** [comment]
Confirm that both @RLittlesII and myself see the shared folder now. Thanks. 

I am closing the issue.
