### ISSUE TITLE
Project Support Request: DNN Platform - NuGet Signing

### ISSUE THREAD

**Issue by mitchelsellers** [dotnet-foundation/projects#43]
- **Project Name:** DNN Platform
- **Due by:** End of January
- **Description:** We would like to setup signing for our NuGet packages and to add dotnetfoundation as a coowner to all NuGets.

**Comment by ChrisSfanos** [comment]
I filed the Trade Name (DNN Platform) today

**Comment by mitchelsellers** [comment]
Awesome. Any timing expectations from here?

**Comment by onovotny** [comment]
The d/b/a takes a day and the rest is up to DigiCert. Probably 1-2 weeks?

**Comment by onovotny** [comment]
We have the cert, what email address do you use for LastPass?

**Comment by mitchelsellers** [comment]
I don’t use last pass but could create an account.

**Comment by onovotny** [comment]
Please do -- we use that for secure credential sharing.

**Comment by mitchelsellers** [comment]
Ok all set 
msellers@iowacomputergurus.com

**Comment by onovotny** [comment]
I just invited you to the shared LastPass where the cert is setup and configured.

Few things:
1. Here's a template of how to add code signing to the build pipeline: https://github.com/novotnyllc/CodeSigningDemo
2. Once signing is configured, please add `dotnetfoundation` as a co-owner in NuGet. 
3. If you have any 3rd party binaries in your packages, you'll need a whitelist.txt to include on your binaries and not the other ones in the nupkg.

I'm happy to review any PR's/pipelines

**Comment by clairernovotny** [comment]
@mitchelsellers are we okay to close this issue? are you all set?

**Comment by mitchelsellers** [comment]
@clairernovotny I haven't had a chance to implement due to time constraints.  But we can close for now

**Comment by clairernovotny** [comment]
Okay, just please keep in mind that code signing and deterministic source linked builds are requirements for all Foundation projects. They shouldn't take too long to get configured.

You can see a sample on how to do deterministic builds here: https://github.com/clairernovotny/DeterministicBuilds

**Comment by mitchelsellers** [comment]
Yes we are working this into our current release cycle.

**Comment by mitchelsellers** [comment]
Is this required for .net framework projects as well. The deterministic build flags you show are .net Core based. Will they work in framework projects too? @clairernovotny
