### ISSUE TITLE
Project Application's via This Repository -> nothing happens

### ISSUE THREAD

**Issue by jogibear9988** [dotnet-foundation/projects#46]
Since last year, Project Applications have to be done via this board.

I liked when this change has come, so I thought it would be a more open Process.

But since then, all I see was, that some Project's did, but nothing more happens to the most. They get a State "New Project Application", ant nothing more happens.

And also the one's wich were changed to "Accepted" like OmniSharp, Nuke,... there seems to happan nothing more.

I would like to see that this process is more open, that we could see a timeframe, and  so on.

**Comment by glennawatson** [comment]
I'm seeing activity in the Project Board 

```
 Activity
@onovotny
@onovotny added C# AST for hardware design to New Project Application
7 hours ago
@onovotny
@onovotny added https://github.com/BLUEBAYcreater/Visual-Studio-2019--Database-Management-System-Project-c-and-mysql/blob/master/README.md to New Project Application
2 days ago
@onovotny
@onovotny removed a card
16 days ago
@onovotny
@onovotny added CoreWF to New Project Application
16 days ago
@onovotny
@onovotny added Python.NET to New Project Application
on 18 Dec 2019
```

**Comment by onovotny** [comment]
First, sorry for the delays. Things got caught up with the winter holidays and then the Executive Director transition. We're working to clear the various backlogs as fast as we can.

@ChrisSfanos is taking lead on processing the accepted projects and we should get through them shortly. 

Thank you for your patience.

**Comment by jogibear9988** [comment]
Thank you for the Information.
Hopefully our project could join #10

**Comment by ChrisSfanos** [comment]
Hi everyone
I see this was Closed - does this mean I should NOT process the on-boarding application?  Or just the issue about timing was 'resolved'?  I'm happy to start processing this ASAP

**Comment by onovotny** [comment]
@ChrisSfanos Ling2db has an active issue for onboarding. We need to complete the review there and present it to the board at the next meeting for approval.

**Comment by jogibear9988** [comment]
@ChrisSfanos you should continue. I only closed this issue that we dont get any response
