### ISSUE TITLE
Elsa Workflows

### ISSUE THREAD

**Issue by sfmskywalker** [dotnet-foundation/projects#48]
## 1.   General Information

**Project Name:** 

Elsa Workflows

**License:** 

BSD-3-Clause

**Contributor (Company, Organization or individual name(s)):**

- [Antoine Griffard](https://github.com/agriffard)
- [James Doran](https://github.com/jamesdoran)
- [Jonathan Ruckert](https://github.com/jruckert)
- [Martin Amm](https://github.com/IntranetFactory)
- [Nate Hughey](https://github.com/nhughey-evo)
- [Peter Davis](https://github.com/petedavis)
- [Sipke Schoorstra](https://github.com/sfmskywalker)
- [Stefano Candori](https://github.com/cando)
- [Stephan Baltzer](https://github.com/andale-online)
- [Terry Delph](https://github.com/terry-delph)

**Existing OSS Project? (Yes/No):**

Yes

**Source Code URL:**
https://github.com/elsa-workflows/elsa-core

**Project Homepage URL (if different):**
https://elsa-workflows.github.io/elsa-core/

**Project Transfer Signatories:**

Sipke Hessel Schoorstra
sipkeschoorstra@outlook.com

## 2.   Description
Elsa Workflows is an extensible, open source .NET Standard set of libraries and tools to implement workflow capabilities in any .NET application. It includes an HTML5 web components-based workflow designer.

Implement workflow functionality directly into your own application or integrate with a workflow server.

## 3.   Project Governance

**Project Lead:**

Name:   Sipke Schoorstra
Email:   sipkeschoorstra@outlook.com
GitHub Profile URL: https://github.com/sfmskywalker

**Committers:**

- [James Doran](https://github.com/jamesdoran)
- [Peter Davis](https://github.com/petedavis)
- [Sipke Schoorstra](https://github.com/sfmskywalker)

**Governance Model:**

New code changes are proposed in the form of GitHub issues. If participants in the discussion agree that the proposed changes make sense for the project, a PR follows. If the code quality is sufficiently acceptable, in that it adheres to already established standards within the existing code base, it gets merged in by anyone who has direct write access to the repo. Sometimes changes are so small and/or obvious improvements or fixes, that a contributor decides to send a PR without creating an issue for it. This is acceptable.

If, based on online discussions with contributors and their code contributions, I feel confident they have a good understanding of the vision and architecture of the project, I reach out to these contributors and ask if they would be interested in getting direct access to the repo.

**CLA**

There is no CLA in place as of yet.

**CLA Notification Alias**

info@elsaworkflows.io

**Project Transfer Type**

Assignment

## 4.   Repository Layout

It looks like the repo is already largely in line with what is described in the [Repository Layout Guidance](https://github.com/dotnet/foundation/blob/master/guidance/repo-guide.md). I will add the CONTRIBUTING.md file, and I am open to make any additional changes that are recommended.

## 5.   PR Plan
Please summarize the public relations plan for the announcement when joining the foundation (and releasing as open source if appropriate). What is the main story we wish to promote, through what channels, what issues should we be aware of?  For significant news events then please also work with your .NET Foundation contact to ensure a [full PR plan](https://dotnetfoundation.sharepoint.com/Shared%20Documents/PR/Communications%20Plan%20TEMPLATE.docx?web=1) is developed.

(No plan as of yet, but at least a blog post + a tweet)

## 6.   Infrastructure Requirements

The project files are built with [AppVeyor](https://ci.appveyor.com/project/sfmskywalker/elsa) and released as NuGet packages to MyGet (builds from `develop` and NuGet (builds from `master`).

The Elsa Workflows [documentation site](https://elsa-workflows.github.io/elsa-core/) itself is hosted on GitHub.

No additional infrastructure is required.

## 7.   Additional Notes

The Elsa Workflows project is not the only open source .NET project providing workflow capabilities. It is similar in functionality and capabilities to Workflow Core, but there are important differences. Probably the most compelling one being that Elsa comes with an HTML5 designer web component as well as a (reference) implementation of a Dashboard application built with ASP.NET Core. 

The project is still very young. Version 1 of the library has been released, and version 2 is in the making, adding important features such as workflow server & support for multi-node hosting (web farm, kubernetes clusters etc), sagas and more. The main vision of this project is to enable workflows anywhere, easily. 

The project is the result of a lift & shift operation by taking Orchard Core's Workflow module and making it available to any .NET application without having a dependency on Orchard Core for the workflow engine and the workflow designer (which is rehostable).

Elsa is inspired on Workflow Foundation, Logic Apps, Workflow Core and Orchard Core Workflows, and attempts to combine the best of their features.

**Comment by ChrisSfanos** [comment]
Hi folks - I need the email addresses for @jamesdoran and @petedavis so I can add them as signers to the CLA paperwork.  If you don't want to post them in the issue, you can email them to me at: chris.sfanos at dotnetfoundation.org

**Comment by jamesdoran** [comment]
Hi @ChrisSfanos, I’ve emailed over mine and @petedavis emails as requested.

**Comment by ChrisSfanos** [comment]
Thanks @JamesDoran!

The CLA document is now out for signing

**Comment by jamesdoran** [comment]
No worries, I’ve signed

**Comment by ChrisSfanos** [comment]
Hello everyone - we will be using the following checklist to track tasks during onboarding

## CLA
- [ ] CLA Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)

**Comment by ChrisSfanos** [comment]
@clairernovotny  - can you sign this one when you get a chance - thanks!

**Comment by sfmskywalker** [comment]
Great! Let me know if there’s anything I can do.

**Comment by ChrisSfanos** [comment]
CLA signed and CLA bot configured.  I've sent the supplemental info to walk through the on-boarding steps

**Comment by ChrisSfanos** [comment]
Looks like all the work items are complete - closing this out
