### ISSUE TITLE
Git Extensions project

### ISSUE THREAD

**Issue by RussKie** [dotnet-foundation/projects#49]
## 1.   General Information

**Project Name:** _Git Extensions_

**License:** _original code is licensed under GPLv3, however since Jan '19 we have only been accepting contributions under the MIT licence. 
https://github.com/gitextensions/gitextensions/blob/master/contributors.txt_
_We are currently liaising with the .NET Foundation counsel in exploration of legal aspects of relicensing the whole project under the MIT licence._

**Contributor (Company, Organization or individual name(s)):**

_The original author: @spdr870_
_Key maintainers (past and present): @KindDragon @jbialobr @RussKie @gerhardol @drewnoakes @drewnoakes @mstv @pmiossec_
_Contributors: https://github.com/gitextensions/gitextensions/graphs/contributors_

**Existing OSS Project? (Yes/No):** _Yes_

**Source Code URL:** _https://github.com/gitextensions/gitextensions/_

**Project Homepage URL (if different):** _https://gitextensions.github.io/_

**Project Transfer Signatories:**
Full legal name and email address required of the individual(s) with the authority to transfer or contribute the project to the .NET Foundation. Note that if you'd prefer not to include this in the public application, it can be submitted via e-mail to contact@dotnetfoundation.org (referencing this issue number).

_All key maintainers have provided in-principal agreement to contribute the project to .NET Foundation. Further sign offs will be provided later._

## 2.   Description
**Please provide a brief statement about your project in terms that are understandable to the target consumer of the library or project, i.e. an elevator pitch for the project:**

_Git Extensions is a standalone UI tool for managing git repositories. It also integrates with Windows Explorer, Microsoft Visual Studio (2015/2017/2019), Visual Studio Code and IntelliJ.
It is one of the oldest and arguably one of the most feature-rich git UI clients out there. Built on Windows Forms .NET_

**Please provide a 1 sentence (<140 character) summary of your to help users when searching the .NET Foundation projects**

_Git Extensions is a standalone UI tool for managing git repositories that integrates with Windows Explorer, Microsoft Visual Studio (2015/2017/2019), Visual Studio Code and IntelliJ._

## 3.   Project Governance
Please complete this section about who will be maintaining the open source project and how it will run.
**Project Lead:**
(Who is the primary contact point for the community and the .NET Foundation when discussing governance of the project.)

Name:   _Igor Velikorossov_
 Email:   _igor.velikorossov (at) microsoft_
 GitHub Profile URL: _https://github.com/RussKie_

**Committers:**

Which individuals have commit / write access to the repository, what is their GitHub ID and who is their employer (if contributions are on behalf of an employer)

* _@spdr870, Henk Westhuis_
* _@RussKie, Igor Velikorossov_
* _@gerhardol, Gerhard Olsson_
* _@drewnoakes, Drew Noakes_
* _@sharwell, Sam Harwell_
* _@mstv, Michael Seibt_
* _@NikolayXHD, Nikolai Idalgo Dias_
* _@mast-eu, Martin Steinisch_
* _@pmiossec, Philippe Miossec_

**Governance Model:**

Please describe how new code changes are proposed to the project, how those changes are reviewed and how a decision is made to accept proposed changes. Also describe the process for identifying and appointing new committers.

_Any user may propose a feature to the application. Any user can pick issues from the backlog and submit a pull-request with an implementation.
Pull-requests are reviewed by key maintainers and judged for quality, meeting guidelines, and overall fitness for purpose. Pull-requests that do not meet the bar can be further worked on, or get closed._

_If a particular contributor shows above-normal effort in making the project better, i.e. reviews open pull-requests, proposes and works on features, the team will discuss and vote whether to invite the contributor to become a "collaborator". After awhile a collaborator may be invited to become part of the team._

**CLA**

If already an OSS project, was a Contribution License Agreement in place for contributions accepted? How does the project check who has signed one?

_All new submissions are accepted subject to a contributor's sign off to our CCO https://github.com/gitextensions/gitextensions/blob/master/contributors.txt
The process is manual._

**CLA Notification Alias**
Provide an email address that will receive CLA related notifications from the .NET Foundation CLA automation

_TBD_

**Project Transfer Type**

Projects may join the .NET Foundation in one of two ways and you should chat with your .NET Foundation contact to discuss the best mechanism for your project. You can either a) assign the copyright of the project's source code to the .NET Foundation or b) contribute the project source code to the .NET Foundation under an open source license. Assignment is the preferred approach, but licensing a project to the Foundation may be more appropriate for longer running open source projects that have not previously had a contribution license agreement and have accepted contributions from many different sources.
a) ~Assignment~
b) Contribution

## 4.   Repository Layout
The .NET Foundation host guidance for new projects and details on recommended structure here:
[https://github.com/dotnet/home/tree/master/guidance](https://github.com/dotnet/home/tree/master/guidance)

Note that the open source repository should be the master where changes are made by the core development team using the same PR process that is used for non-committer contributions.

Please define below any changes you would want to make to your repositories as part of the process of joining the .NET Foundation

_TBD_

## 5.   PR Plan
Please summarize the public relations plan for the announcement when joining the foundation (and releasing as open source if appropriate). What is the main story we wish to promote, through what channels, what issues should we be aware of?  For significant news events then please also work with your .NET Foundation contact to ensure a [full PR plan](https://dotnetfoundation.sharepoint.com/Shared%20Documents/PR/Communications%20Plan%20TEMPLATE.docx?web=1) is developed.

_Not quite sure what this means and/or entails. TBD_

## 6.   Infrastructure Requirements
Please describe any infrastructure requirements for the project. For example, how will build servers be operated? Any web hosting or service hosting requirements? Do we need to set up SSL certificates or provide Authenticode Code Signing arrangement for releases?

_TBD, few ideas come to mind:_
* _AzDO CI infra (may need guidance/help in migrating from AppVeyor)_
* _Authenticode Code Signing arrangement for releases_
* _Help engaging graphics/UI designers_

## 7.   Additional Notes
Please provide any additional information required or use this area for notes during the onboarding process. If this open source project has similarities with any other projects in this space then please detail them and why this project is different. If there are any potential issues that you feel the project might need help with early on then also state them here and discuss with your .NET Foundation Contact.

**Comment by onovotny** [comment]
We have a thread with the lawyers on handling the GPL to MIT license transition.

**Comment by RussKie** [comment]
I wonder if we can get traction with the onboarding. 
We could really use the CLA bot and secrets management. I also vaguely remember one of the benefits listed was help soliciting help with designs and UI, and that's something we could really benefit from too.

Thanks
