### ISSUE TITLE
NUKE

### ISSUE THREAD

**Issue by jongalloway** [dotnet-foundation/projects#5]
Submitted by @matkoch, project questionnaire [here](https://docs.google.com/document/d/1s8ww8lxL1hEluNdnYSZLDIf3WKqUF_PCc6Z9RBLc3GU/edit?usp=sharing)

**Comment by jongalloway** [comment]
Looks good to me, will submit to advisory council with July batch

**Comment by tidusjar** [comment]
We already have CAKE, NUKE achieves the same goal just in a slightly different way. 

But yeah I've used both CAKE and NUKE and they are both very good tools.

**Comment by ChrisSfanos** [comment]
CLA is out for signing

**Comment by ChrisSfanos** [comment]
We will track the remaining onboarding work via this checklist:

## Onboarding
- [ ] CLA Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Post Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Enable CLA automation for future contributors
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)

**Comment by ChrisSfanos** [comment]
CLA not signed - pinged signers

**Comment by ChrisSfanos** [comment]
Hi @matkoch and @arodus - checking in on your signatures for moving Nuke to the .NET Foundation.  Let me know if there are any issues/etc

**Comment by ChrisSfanos** [comment]
This project has moved back into the on-boarding process.  New transfer agreement is out for signing

**Comment by ChrisSfanos** [comment]
Hi @matkoch and @arodus - the transfer agreement is out for signing, but I haven't heard back from you - please take a look and complete at your first opportunity - thanks!
