### ISSUE TITLE
Piranha CMS

### ISSUE THREAD

**Issue by tidyui** [dotnet-foundation/projects#51]
## 1.   General Information

**Project Name:**
Piranha CMS

**License:**
MIT

**Contributor (Company, Organization or individual name(s)):**
Håkan Edling, Filip Jansson

**Existing OSS Project? (Yes/No):**
Yes

**Source Code URL:**
https://github.com/PiranhaCMS/piranha.core/graphs/contributors

**Project Homepage URL (if different):**
http://piranhacms.org

**Project Transfer Signatories:**
*Full legal name and email address required of the individual(s) with the authority to transfer or contribute the project to the .NET Foundation. Note that if you'd prefer not to include this in the public application, it can be submitted via e-mail to contact@dotnetfoundation.org (referencing this issue number).*

Håkan Edling, hakan@tidyui.com

## 2.   Description
**Please provide a brief statement about your project in terms that are understandable to the target consumer of the library or project, i.e. an elevator pitch for the project:**

Piranha CMS is a lightweight and unobtrusive CMS Library for .NET Core 3.1 and NetStandard 2.0.  It can be used to add CMS functionality to your existing application or to build a new website from scratch.

**Please provide a 1 sentence (<140 character) summary of your to help users when searching the .NET Foundation projects**

Lightweight, unobtrusive and cross-platform CMS library for .NET Core 3.1 and NetStandard 2.0.

## 3.   Project Governance
*Please complete this section about who will be maintaining the open source project and how it will run.*

**Project Lead:**
*(Who is the primary contact point for the community and the .NET Foundation when discussing governance of the project.)*

Name: Håkan Edling
 Email: hakan@tidyui.com
 GitHub Profile URL: https://github.com/tidyui

**Committers:**

*Which individuals have commit / write access to the repository, what is their GitHub ID and who is their employer (if contributions are on behalf of an employer)*

Håkan Edling https://github.com/tidyui
Filip Jansson https://github.com/filipjansson

**Governance Model:**

*Please describe how new code changes are proposed to the project, how those changes are reviewed and how a decision is made to accept proposed changes. Also describe the process for identifying and appointing new committers.*

Changes are proposed via GitHub issues. All issues are reviewed and labelled with the proper type and scope. Issues that are small enough to fit into the current ongoing development are assigned to the current milestone and project. Accepted issues that don't fit into the current timeline is added to the next milestone and release. Discussions regarding issues and upcoming releases are discussed in the issues.

**CLA**

*If already an OSS project, was a Contribution License Agreement in place for contributions accepted? How does the project check who has signed one?*

No. We have a simple instruction on **how** we like people to contribute to the project (https://github.com/PiranhaCMS/piranha.core/blob/master/CONTRIBUTING.md).

**CLA Notification Alias**
*Provide an email address that will receive CLA related notifications from the .NET Foundation CLA automation*

hakan@tidyui.com

**Project Transfer Type**

*Projects may join the .NET Foundation in one of two ways and you should chat with your .NET Foundation contact to discuss the best mechanism for your project. You can either a) assign the copyright of the project's source code to the .NET Foundation or b) contribute the project source code to the .NET Foundation under an open source license. Assignment is the preferred approach, but licensing a project to the Foundation may be more appropriate for longer running open source projects that have not previously had a contribution license agreement and have accepted contributions from many different sources.*
a) Assignment
b) Contribution

Contribution

## 4.   Repository Layout
The .NET Foundation host guidance for new projects and details on recommended structure here:
[https://github.com/dotnet/home/tree/master/guidance](https://github.com/dotnet/home/tree/master/guidance)

Note that the open source repository should be the master where changes are made by the core development team using the same PR process that is used for non-committer contributions.

*Please define below any changes you would want to make to your repositories as part of the process of joining the .NET Foundation*

At the moment it looks like we already fulfill the requirements on repo structure. The only difference is that our documentation is located in a separate repo (https://github.com/PiranhaCMS/piranha.core.docs).

## 5.   PR Plan
Please summarize the public relations plan for the announcement when joining the foundation (and releasing as open source if appropriate). What is the main story we wish to promote, through what channels, what issues should we be aware of?  For significant news events then please also work with your .NET Foundation contact to ensure a [full PR plan](https://dotnetfoundation.sharepoint.com/Shared%20Documents/PR/Communications%20Plan%20TEMPLATE.docx?web=1) is developed.

We would promote this through the blog on our website (http://piranhacms.org/blog), twitter (https://twitter.com/piranhacms) and our LinkedIn page which we've just set up. We are also currently working with getting sponsors through [Open Collective](https://opencollective.com/piranhacms) and Github Sponsors to get a more sustainable model.

## 6.   Infrastructure Requirements
*Please describe any infrastructure requirements for the project. For example, how will build servers be operated? Any web hosting or service hosting requirements? Do we need to set up SSL certificates or provide Authenticode Code Signing arrangement for releases?*

We're current using free plans from [AppVeyor](https://ci.appveyor.com/project/tidyui/piranha-core) for building and running tests on Windows, [Travis](https://travis-ci.org/PiranhaCMS/piranha.core) for building and running tests och Mac & Linux, [CoverAlls](https://coveralls.io/github/PiranhaCMS/piranha.core?branch=master) for test coverage and [Crowdin](https://crowdin.com/project/piranhacms) for localization. NuGet packages are built with manually defined [NuSpec](https://github.com/PiranhaCMS/piranha.core/tree/master/nuspec) files. 

Overall we're happy with our current setup.

## 7.   Additional Notes
*Please provide any additional information required or use this area for notes during the onboarding process. If this open source project has similarities with any other projects in this space then please detail them and why this project is different. If there are any potential issues that you feel the project might need help with early on then also state them here and discuss with your .NET Foundation Contact.*

To be honest there are many CMS options available for almost any platform. What makes Piranha CMS special is that it's extremely easy to learn for new developers, it's totally plug and play so that you can easily add it to existing projects and that we without a doubt have the best experience for content editors on the .NET platform. Piranha CMS is aimed towards small to medium sized applications and we have no intention of adding big enterprise features and compete with the other alternatives out there.

**Comment by ChrisSfanos** [comment]
Hi everyone - I'll be handling the onboarding of your project.  To get started, I just need the email address of
@filipjansson 
you can email it to me at chris.sfanos (at) dotnetfoundation.org

**Comment by ChrisSfanos** [comment]
We will be using the following checklist to complete the onboarding process

## CLA
- [ ] CLA Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)

**Comment by ChrisSfanos** [comment]
CLA is out for signing

**Comment by ChrisSfanos** [comment]
CLA is signed - email sent for CLA onboarding

**Comment by ChrisSfanos** [comment]
CLA bot is configured - email sent with supplemental steps for onboarding

**Comment by ChrisSfanos** [comment]
All onboarding steps are complete.  I've added Piranha CMS to the next newsletter announcement, so that wraps this up - thanks!
