### ISSUE TITLE
Move Docker.DotNet to .Net Foundation

### ISSUE THREAD

**Issue by taylorb-microsoft** [dotnet-foundation/projects#52]
## 1.   General Information

**Project Name:**  Docker.DotNet

**License:**  Apache V 2.0

**Contributor (Company, Organization or individual name(s)):**  
- Owned by Microsoft (was transferred from a former Microsoft employee)
-  Primary Contributors: @jterry75 (Microsoft employee); @ahmetb (former Microsoft employee and original maintainer); @jstarks (Microsoft employee); @swernli (Microsoft employee)

**Existing OSS Project? (Yes/No):** Yes

**Source Code URL:** https://github.com/microsoft/Docker.DotNet/

**Project Homepage URL (if different):**

**Project Transfer Signatories:** Need guidance as a Microsoft to .NET foundation transfer. 

## 2.   Description
Library to interact with Docker Remote API endpoints in your .NET applications. 

## 3.   Project Governance
**Project Lead:** 

Name:   Gutemberg Ribeiro
 Email:   
 GitHub Profile URL: https://github.com/galvesribeiro

**Committers:**
@galvesribeiro; @jterry75 (Microsoft employee);  @jstarks (Microsoft employee); @swernli (Microsoft employee)

**Governance Model:**

Please describe how new code changes are proposed to the project, how those changes are reviewed and how a decision is made to accept proposed changes. Also describe the process for identifying and appointing new committers.

**CLA**
Microsoft CLA: https://cla.microsoft.com.

**CLA Notification Alias**
I am not sure

**Project Transfer Type**
a) Assignment seems most appropriate (open to feedback)

## 4.   Repository Layout
The .NET Foundation host guidance for new projects and details on recommended structure here:
[https://github.com/dotnet/home/tree/master/guidance](https://github.com/dotnet/home/tree/master/guidance)

Note that the open source repository should be the master where changes are made by the core development team using the same PR process that is used for non-committer contributions.

Please define below any changes you would want to make to your repositories as part of the process of joining the .NET Foundation

## 5.   PR Plan
I would not anticipate significant PR as part of moving this project.  

## 6.   Infrastructure Requirements
AppVeyor is used. 

## 7.   Additional Notes
Please provide any additional information required or use this area for notes during the onboarding process. If this open source project has similarities with any other projects in this space then please detail them and why this project is different. If there are any potential issues that you feel the project might need help with early on then also state them here and discuss with your .NET Foundation Contact.

**Comment by galvesribeiro** [comment]
Hello folks!

Here are my suggestions regarding the application:

**Email**: myfirstname @ outlook.com
**License**: If possible, after the migration, we should adopt MIT like most of the other projects under the `dotnet/` org.
**Project Homepage URL (if different)**: We will probably use GitHub pages to host the documentation and samples moving forward.

**Governance Model**: 
Something around those lines (please advice with missing topics):
- The basic `Fork->PR->CI->Review->Test->Merge->Release` flow should be kept;
- The project should strictly follow SemVer 2.0; 
- Changes are merged on master. No other branch is required (unless extremely necessary);
- Tags would flag (pre-)releases, which would trigger a particular CD workflow;
- (Pre-)Releases publish to NuGet.
- Releases as much as possible aligned with both Docker and .Net Core releases;
- New committers that have good/proven background on both .Net Core and Docker, which are whiling to dedicate some time on review issues and PRs, and are playing well actively with the community should always be considered;
- The PR impact should always be reviewed looking at the following topics (not an extensive list):
1. Security implications;
2. Performance;
3. Developer experience;
4. Background compatibility;
5. Docker API compatibility;
6. Severity level;
7. Testability;
8. Documentation.

**CLA**: Currently it is under Microsoft CLA but I would suggest after the migration to to `dotnet/` org, to move to [.Net Foundation CLA](https://cla.dotnetfoundation.org/) so we can use the `dotnetbot`.

**CLA Notification Alias**:  I don't know exactly what it means but, if it is how we should notify about the need to sign the CLA before code contributions, as mentioned on the previous point, the usual channels used on other projects at `dotnet/` org like email and `dotnetbot` would suffice IMHO.

**Project Transfer Type**: I think at first, assignment would be ok so we can release all gated fixes/improvements to let the community use it. Right after the first release, we should move the project to `dotnet/` org.

**PR Plan**: If the transfer to `dotnet/` org can be made right after the the application is approved, no need for a PR. Just need to move the repo to the org. If it would take more time to setup the repo on the new org, I would first prefer to unlock the users with a new immediate release and after that we can make a PR to the new repo under `dotnet/` org in case an immediate move isn't possible.

**Infrastructure Requirements**: Currently AppVeyor is used but I would like to migrate it to GitHub Actions for the CI/CD pipeline.

The plan is to once/if the application is accepted, we release right away a package with all the pending PRs that are blocking a lot of people or requiring them to make private builds so they can leverage it. After the migration to `dotnet/`, the current codebase would be moved to a branch which will be kept in maintenance mode while we will work on rewrite the package to leverage latest .Net and Docker APIs/Frameworks at `master` and provide _preview_ releases until it is considered stable enough.

Please let me know if you guys need more info.

Thanks!

**Comment by galvesribeiro** [comment]
Ping 🏓

**Comment by IrisClasson** [comment]
We are reviewing the project, thank you for the patience!

**Comment by sbwalker** [comment]
There is no email address in this project application so I am posting a message here:

I am contacting you on behalf of the .NET Foundation Project Committee. In case you were not aware, we recently published a set of criteria for evaluating project applications:

https://github.com/dotnet-foundation/projects

There is a Board of Directors meeting this week where project applications will be reviewed and I am hoping you will be able to assist me in providing some information related to the Eligibility criteria. Most of these questions are simply Yes/No answers, and please note that items can be waived depending on the circumstances so answering No to any item is not a reason for approval being denied.

Suitability	
- The project operates within the moral and ethical standards of the .NET Foundation.	
- The project is aligned with the philosophy and guidelines for collaborative development.	
- The project is built on the .NET platform and/or creates value within the .NET ecosystem.		

Code	
- The project produces source code for distribution to the public at no charge.	
- The project's code is easily discoverable and publicly accessible (preferably on GitHub).	
- The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).	
- When applicable, project must use reproducible build settings in its toolchain.	
- The project uses Source Link.	
- The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).	
- The project code signs their artifacts as appropriate.	
	
Licenses and Copyright	
- The code is offered under an open source license which has been approved by the .NET Foundation.	GPLV2
- Libraries that are mandatory dependencies of the project are also offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).	
- Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.	
- The copyright ownership of everything that the project produces is clearly defined and documented.	
	
Quality	
- The project is open and honest about the quality of its code.	
- The project has a public issue tracker where the status of any defect can be easily obtained.	
- The project puts a very high priority on producing secure software.	
- The project has a published Security Policy.	
	
Community	
- The project has a home page which provides high level information about its status and purpose.	
- The project welcomes contributions from anyone and embraces diversity.	
- The project strives to grant more rights and responsibilities to contributors who add value to the project.	
- The project has a public communication channel where community members can engage with maintainers.	
- The project adheres to, and enforces, the .NET Foundation Code of Conduct.	
- The project has a publicly available location where members can review and contribute to documentation.	

If you are able to provide a response in the next couple days it would be greatly appreciated. You can send it to shaun.walker @ siliqon.com

**Comment by galvesribeiro** [comment]
Hello @sbwalker I added my email to my post [here](https://github.com/dotnet-foundation/projects/issues/52#issuecomment-585502912). But sure, I'll reply and send to your email right now.

Thanks!

**Comment by galvesribeiro** [comment]
@sbwalker just checking, have you got my email with the answers to your questions? Thanks

**Comment by sbwalker** [comment]
Yes, thank you!

**Comment by ChrisSfanos** [comment]
Hi folks - I'll be processing the onboarding for the project.  To get started, I'll need the email addresses (for DocuSign and the CLA signing) from 
@jterry75
@ahmetb 
@jstarks
@swernli 

You can either post them here or email them to chris.sfanos (at) dotnetfoundation.org

**Comment by ahmetb** [comment]
`ahmetb@google.com`

**Comment by ChrisSfanos** [comment]
Ping to 
@jterry75
@jstarks
@swernli

I need your email addresses so we can move forward with the CLA signing.  You can email me (see previous comment) or post them here

**Comment by jterry75** [comment]
`juterry@microsoft.com`

**Comment by jterry75** [comment]
I think we should remove @swernli as no longer works in this area.

**Comment by galvesribeiro** [comment]
I have the DNF CLA signed but if you need me to sign something else, just shoot an email to gutemberg (at) outlook.com

**Comment by ChrisSfanos** [comment]
Thanks folks - removed him.. Just need John's and then I'll send this out - thanks!

**Comment by taylorb-microsoft** [comment]
John's is his first name to last name at microsoft.com

**Comment by ChrisSfanos** [comment]
Thanks all - CLA is now out for signing

**Comment by galvesribeiro** [comment]
Done

**Comment by ahmetb** [comment]
Thanks. I'll quickly check w/ my employer to see there are no issues. BTW the CLA indicates the project name as Docker.NET which is not the name listed in the original request above. Is that potentially a problem?

**Comment by galvesribeiro** [comment]
Oh! Good catch. I didn't saw that. It is confusing indeed but I guess the original name will be kept to avoid confusion with anything Docker Inc may come out with the domain docker.net...

@ChrisSfanos do you think you should update the CLA and send it again?

**Comment by ChrisSfanos** [comment]
Yep, I will fix that - it should be Docket.DotNet.  I'm going to void the first one and create a new one with the corrected name.  Good catch!

**Comment by ChrisSfanos** [comment]
Corrected CLA is now out for signing

**Comment by ChrisSfanos** [comment]
Hi everyone - we will be using the following checklist to track out work items 

## CLA
- [ ] CLA Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)

**Comment by ChrisSfanos** [comment]
CLA signing is complete - email out on CLA bot config

**Comment by ChrisSfanos** [comment]
CLA bot complete - supplemental steps are sent

**Comment by ChrisSfanos** [comment]
onboarding steps are complete … closing the issue
