### ISSUE TITLE
Avalonia

### ISSUE THREAD

**Issue by grokys** [dotnet-foundation/projects#55]
## 1.   General Information

**Project Name:**

Avalonia

**License:**

MIT

**Contributor (Company, Organization or individual name(s)):**

We have many contributors but our top 5 are:

Steven Kirk (@grokys)
Nikita Tsukanov (@kekekeks)
Dan Walmsley (@danwalmsley)
Jeremy Koritzinsky (@jkoritzinsky)
Jumar Macato (@jmacato)

**Existing OSS Project? (Yes/No):**

Yes

**Source Code URL:**

https://github.com/AvaloniaUI/Avalonia

**Project Homepage URL (if different):**

http://avaloniaui.net/

**Project Transfer Signatories:**

Will be submitted via e-mail to contact@dotnetfoundation.org.

## 2.   Description

A cross platform XAML Framework for .NET Framework, .NET Core and Mono.

## 3.   Project Governance

**Project Lead:**

Name:   Steven Kirk
 Email:   grokys@gmail.com
 GitHub Profile URL: https://github.com/grokys

**Committers:**

@aelij
@kekekeks
@jkoritzinsky
@grokys
@wieslawsoltes
@MarchingCube
@danwalmsley
@Gillibald
@jmacato
@nc4rrillo

**Governance Model:**

Changes are proposed in GitHub Issues, Pull Requests and by discussion in https://gitter.im/AvaloniaUI/Avalonia. Changes are reviewed by the core contributors and the community.

New committers are proposed for inclusion in the core team by one of the core members and are subject to votes from existing core members.

**CLA**

No

**CLA Notification Alias**

n/a

**Project Transfer Type**

Not sure. Open to discussion here.

## 4.   Repository Layout

I believe we already follow the guidelines here.

## 5.   PR Plan

That .NET has a cross-platform, community-lead solution for building applications using XAML.

## 6.   Infrastructure Requirements

We already make use of Azure Pipelines for CI. Hosting space for our website would be useful.

## 7.   Additional Notes

Similar to https://github.com/dotnet/wpf except cross platform (though not API compatible). We reuse code from WPF and https://github.com/microsoft/microsoft-ui-xaml where possible in order to try to provide some API consistency across XAML frameworks.

**Comment by ChrisSfanos** [comment]
Hi everyone - I'll be handling the onboarding of your project.  To get started with the CLA work, I need the email addresses of:
@kekekeks
@danwalmsley
You can email them to me at: chris.sfanos (at) dotnetfoundation.org

**Comment by danwalmsley** [comment]
@ChrisSfanos Email sent, thanks. Let me know if I can help further.

**Comment by ChrisSfanos** [comment]
Thanks all

We will be using the following checklist to track the work to complete the onboarding process

## CLA
- [ ] CLA Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)

**Comment by ChrisSfanos** [comment]
CLA is out for signing

**Comment by ChrisSfanos** [comment]
CLA Signed - email sent for CLA bot config

**Comment by ChrisSfanos** [comment]
CLA bot configured - sent email with details on completing the remaining onboarding items

**Comment by ChrisSfanos** [comment]
All work items are complete - closing this out
