### ISSUE TITLE
Omnisharp

### ISSUE THREAD

**Issue by jongalloway** [dotnet-foundation/projects#6]

**Comment by MeikTranel** [comment]
I would argue that OmniSharp has had a significant impact in evangelizing a open-source and crossplatform .NET through VSCode, a ton of .NET developers use it, it is by itself an amalgamation of dotnet foundation projects and it's going to continue to be a central point in spreading dotnet in the years to come.
This should be the easiest application process ever.

**Comment by jongalloway** [comment]
Absolutely agree! We've actually had this in the works for a while, we just need to sign it off and get it done.

**Comment by MeikTranel** [comment]
Seeing as this moved around to "accepted" can this issue be closed? Or do we wait for the announcement and the listing to go up?

**Comment by david-driscoll** [comment]
@MeikTranel I haven't see anything about it yet, so we'll see what @jongalloway says.  😄

**Comment by david-driscoll** [comment]
@jongalloway let me know what, if any, additional information you need. 👍

**Comment by jongalloway** [comment]
@david-driscoll The project was accepted by the board. Next high level steps:

- [ ] **Sign contribution agreement.** I have an e-mail from you listing 14 top contributors. I'll send you a draft for a quick skim via e-mail, then send out via DocuSign if it looks good to you.
- [ ] **Announcement plan.** Up to you, can be as simple as blog post and tweets.
- [ ] **[New project checklist.](https://github.com/dotnet/foundation/blob/master/guidance/new-projects.md)**

**Comment by ChrisSfanos** [comment]
CLA is complete (in November per Jon)

**Comment by ChrisSfanos** [comment]
Next step is CLA onboarding in GitHub - email going out on this

**Comment by ChrisSfanos** [comment]
We will track the remaining onboarding work via this checklist:

## Onboarding
- [ ] CLA Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Post Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Enable CLA automation for future contributors
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)

**Comment by ChrisSfanos** [comment]
post on-boarding mail sent

**Comment by ChrisSfanos** [comment]
Pinged @david-driscoll for a status update

**Comment by ChrisSfanos** [comment]
PR is in for the project list - that's the last item, so marking this closed
