### ISSUE TITLE
Project Support Request: Prism Library

### ISSUE THREAD

**Issue by dansiegel** [dotnet-foundation/projects#62]
### Please fill in the information below:
- **Project Name:** Prism Library
- **Due by:** April 2020
- **Description:** The listed License type and secondary contact need to be updated.

1. Prism updated from the Apache to MIT License in September 2017. The DFN website still shows this as the Apache license
1. Brian Noyes is no longer with the project. Please change the secondary contact to [Dan Siegel](https://dansiegel.net)

**Comment by clairernovotny** [comment]
@dansiegel can you please submit the changes as a PR to https://github.com/dotnet/foundation/blob/master/projects/prism.md?

**Comment by clairernovotny** [comment]
Can we close this issue out?

**Comment by SimonCropp** [comment]
@clairernovotny guessing the answer is yes :)
