### ISSUE TITLE
Application for AArnott/PInvoke project

### ISSUE THREAD

**Issue by AArnott** [dotnet-foundation/projects#66]
## 1.   General Information

**Project Name:** PInvoke

**License:** MIT

**Contributor (Company, Organization or individual name(s)):** Andrew Arnott (@aarnott), Julien Roncaglia (@vbfox), Juan Manuel Elosegui (@jmelosegui), Mathias Lykkegaard Lorenzen (@ffMathy), [and others](https://github.com/AArnott/pinvoke/graphs/contributors).

**Existing OSS Project? (Yes/No):** Yes

**Source Code URL:** https://github.com/AArnott/pinvoke

**Project Homepage URL (if different):**

**Project Transfer Signatories:**
1. Andrew Layne Arnott (andrewarnott@gmail.com)
1. (perhaps the other significant contributors listed above can comment on this issue to provide the info or express agreement, if necessary).

## 2.   Description
**Please provide a brief statement about your project in terms that are understandable to the target consumer of the library or project, i.e. an elevator pitch for the project:**

A collection of libraries intended to contain all P/Invoke method signatures for popular operating systems. Think of it as https://pinvoke.net, but proven to compile and work properly, and often with sample usage in the form of unit tests.

Each library is exposed as its own NuGet package, and may include .NET Portable libraries as applicable, exposing those APIs that are available only on Desktop, or Store, or both as appropriate.

**Please provide a 1 sentence (<140 character) summary of your to help users when searching the .NET Foundation projects**

A library containing all P/Invoke code so you don't have to import it every time. Maintained and updated to support the latest Windows OS.

## 3.   Project Governance
Please complete this section about who will be maintaining the open source project and how it will run.
**Project Lead:**
(Who is the primary contact point for the community and the .NET Foundation when discussing governance of the project.)

Name:   Andrew Arnott
 Email:   andrewarnott@gmail.com
 GitHub Profile URL:  @aarnott

**Committers:**

Which individuals have commit / write access to the repository, what is their GitHub ID and who is their employer (if contributions are on behalf of an employer)

- @AArnott 
- @jmelosegui 
- @vbfox

**Governance Model:**

Design/pattern decisions are first discussed on GitHub issues until all involved feel the relevant data has been presented. We usually come to a consensus, then we document the patterns/guidance in the [CONTRIBUTING.md file of the repo itself](https://github.com/AArnott/pinvoke/blob/master/CONTRIBUTING.md).

We never say "no" to a request for added APIs, and occasionally contributors will add APIs at others' requests. But mostly we rely on users submitting PRs for the APIs they want added, then the active maintainers review the PR and work with the author until it meets the guidelines set forth in the CONTRIBUTING.md document.

**CLA**

If already an OSS project, was a Contribution License Agreement in place for contributions accepted? How does the project check who has signed one?

No CLA process was in place.

**CLA Notification Alias**
Provide an email address that will receive CLA related notifications from the .NET Foundation CLA automation

andrewarnott@gmail.com

**Project Transfer Type**

a) Assignment
**b) Contribution**

I think we'll have to go with option b) because we've had a couple dozen contributors already, without a CLA process.

## 4.   Repository Layout

Please define below any changes you would want to make to your repositories as part of the process of joining the .NET Foundation

1. We'll need to add the code of conduct.
1. Update file headers and our LICENSE file with the updated copyright notice.

## 5.   PR Plan

We'll advertise it on our README, twitter and our gitter.im forum.
Maybe we can even get the pinvoke.net site to point people to us and mention it's under the .NET Foundation umbrella.

## 6.   Infrastructure Requirements

We're fully set up already, but would **need an Authenticode Code Signing cert**, unless it's appropriate to reuse the one we're using for Nerdbank.GitVersioning. But that cert has Nerdbank in its name, and this PInvoke project isn't under the Nerdbank "brand".

**Comment by jmelosegui** [comment]
Here goes my info in case it is needed for the Project Transfer Signatories.

Juan M. Elosegui (elosegui@gmail.com)

**Comment by ffMathy** [comment]
This is a great initiative. Let me know if I can be of help, and thanks for listing me as an author.

**Comment by AArnott** [comment]
@ChrisSfanos Repo has been transferred to dotnet org. New url https://github.com/dotnet/pinvoke

**Comment by ChrisSfanos** [comment]
CLA bot work is complete - supplemental email for the remaining onboarding items was sent today

**Comment by ChrisSfanos** [comment]
Checklist is complete - project is fully on-boarded. :-)
Closing this issue

**Comment by vatsan-madhavan** [comment]
Just noticing that this got onboarded to .NET Foundation. Congrats @AArnott @vbfox & co. - this is a great move!
