### ISSUE TITLE
Code Signing Certificate Request: Docker.DotNet

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet-foundation/projects#67]
- **Project Name:** Docker.DotNet
- **LastPass Email (or send offline):** gutemberg at outlook.com

Certificate onboarding checklist:

- [x] Register trade name @galvesribeiro
- [x] Create organization with DigiCert
- [x] Create configuration in Code Signing Service
- [x] Provide credentials in shared folder in LastPass
- [x] Request certificate from DigiCert
- [x] Received certificate and finalize sign service configuration

**Comment by ChrisSfanos** [comment]
Registered docker.dotnet

**Comment by galvesribeiro** [comment]
Hello folks! Do we have an update on this? Thanks!

**Comment by clairernovotny** [comment]
I just invited you to the shared LastPass where the cert is setup and configured.

Three things:
1. Here's a template of how to add code signing to the build pipeline: https://github.com/novotnyllc/CodeSigningDemo
2. Once signing is configured, please add `dotnetfoundation` as a co-owner in NuGet. 
3. For any tool packages, you'll need a whitelist.txt to include on your binaries and not the other ones in the nupkg.

I'm happy to review any PR's/pipelines

**Comment by galvesribeiro** [comment]
Thanks @clairernovotny 

I'll implement update the pipeline and tag you there.

**Comment by galvesribeiro** [comment]
@clairernovotny the PR is out https://github.com/dotnet/Docker.DotNet/pull/454 I appreciate a pair of eyes on it :) Thanks!

**Comment by galvesribeiro** [comment]
Hey folks! 

Since the PR is merged the nuget is out, I'm going to close this issue since we're all set for now.

I appreciate all the help so far onboarding this project.

Thanks!
