### ISSUE TITLE
Project Support Request: DNN Platform - Email Distribution List/Group

### ISSUE THREAD

**Issue by mitchelsellers** [dotnet-foundation/projects#68]
We need to get a new email group setup: community@dnncommunity.org.

This should send to the following email addresses.

will@upendoventures.com
info@tjeps.com
timo@40fingers.net
dpoindexter@nvisionative.com

Other email groups have been setup for us in the past.

Let me know if you have any questions.

**Comment by clairernovotny** [comment]
Should be all set now.

**Comment by mitchelsellers** [comment]
Looks good!  Thanks!
