### ISSUE TITLE
dotnet-foundationCode Signing Certificate Request: [Servermaxx]

### ISSUE THREAD

**Issue by invictus801** [dotnet-foundation/projects#69]
### Please fill in the information below

- **Project Name:**
- **LastPass Email (or send offline):**

Certificate onboarding checklist:

- [ ] Register trade name @ChrisSfanos
- [x] Create organization with DigiCert
- [x] Create configuration in Code Signing Service
- [x] Provide credentials in shared folder in LastPass
- [x] Request certificate from DigiCert
- [x] Received certificate and finalize sign service configuration

**Comment by ChrisSfanos** [comment]
Hi @invictus801  - it's not clear from this issue what the project name is that is supposed to be registered?

**Comment by invictus801** [comment]
> Hi @invictus801 - it's not clear from this issue what the project name is that is supposed to be registered?
Chris I may need help with that.

**Comment by ChrisSfanos** [comment]
@clairernovotny  for help here - what project are we registering the Trade Name?

**Comment by clairernovotny** [comment]
What .NET Foundation project is this for?

**Comment by ChrisSfanos** [comment]
Hi @invictus801 - so I can't find Servermaxx in my list of .NET foundation projects (I actually can't find it anywhere on GitHub actually)
Can you drop me an email at chris.sfanos (at) dotnetfoundation.org and we can chat in more detail - thanks!

**Comment by clairernovotny** [comment]
Closing as we only provide code signing certificates to member projects.
