### ISSUE TITLE
Code Signing Certificate Request: [MaxxDx]

### ISSUE THREAD

**Issue by invictus801** [dotnet-foundation/projects#70]
### Please fill in the information below

- **Project Name:**
- **LastPass Email (or send offline):**

Certificate onboarding checklist:

- [ ] Register trade name @ChrisSfanos
- [x] Create organization with DigiCert
- [ ] Create configuration in Code Signing Service
- [ ] Provide credentials in shared folder in LastPass
- [x] Request certificate from DigiCert
- [ ] Received certificate and finalize sign service configuration

**Comment by ChrisSfanos** [comment]
Hi @invictus801  - What is this issue filed for?  There is no projectname listed in the title.  Is it related to the other request you filed before?

**Comment by clairernovotny** [comment]
Closing as we only provide code signing certificates to member projects.
