### ISSUE TITLE
CoreWF ReadMe says "Supported by .NET Foundation" but Foundation documents don't

### ISSUE THREAD

**Issue by bsstahl** [dotnet-foundation/projects#71]
In the CoreWF GitHub repo, the readme file (https://github.com/UiPath-Open/corewf) states "This project is supported by the .NET Foundation" however I don't see any indication of that, either on the .NET Foundation Website projects list (https://dotnetfoundation.org/projects?q=core&type=project&ps=10&pn=2&searchquery=corewf) or in the Projects Team's onboarding project (https://github.com/dotnet-foundation/projects/projects/1). Is this something that has happened or is happening and just wasn't updated in the documentation? Did somebody jump the gun on something? I'm wondering what the situation is because, as I've mentioned in other discussions, I would very much like for the Foundation to support one or more .NET Core workflow frameworks.

**Comment by clairernovotny** [comment]
CoreWF is a Foundation project. @ChrisSfanos can you please follow up with them to ensure they add their info to our website?
