### ISSUE TITLE
Code Signing Certificate Request: PInvoke

### ISSUE THREAD

**Issue by AArnott** [dotnet-foundation/projects#72]
### Please fill in the information below

- **Project Name:** [PInvoke](https://github.com/aarnott/pinvoke) (Application #66)
- **LastPass Email (or send offline):** andrewarnott@gmail.com

Certificate onboarding checklist:

- [x] Register trade name @ChrisSfanos
- [x] Create organization with DigiCert
- [x] Create configuration in Code Signing Service
- [x] Provide credentials in shared folder in LastPass
- [x] Request certificate from DigiCert
- [x] Received certificate and finalize sign service configuration

**Comment by ChrisSfanos** [comment]
Trade Name is registered

**Comment by clairernovotny** [comment]
Should be all set and you have access to the credentials in the last pass.
