### ISSUE TITLE
Code Signing Certificate Request: Coverlet

### ISSUE THREAD

**Issue by MarcoRossignoli** [dotnet-foundation/projects#73]
### Please fill in the information below

- **Project Name:** Coverlet
- **LastPass Email (or send offline):** sent offline to project-support@dotnetfoundation.org

Certificate onboarding checklist:

- [x] Register trade name @ChrisSfanos
- [x] Create organization with DigiCert
- [x] Create configuration in Code Signing Service
- [x] Provide credentials in shared folder in LastPass
- [x] Request certificate from DigiCert
- [x] Received certificate and finalize sign service configuration

**Comment by MarcoRossignoli** [comment]
cc: @tonerdo

**Comment by ChrisSfanos** [comment]
Trade name is registered

**Comment by clairernovotny** [comment]
I just invited you to the shared LastPass where the cert is setup and configured.

Three things:
1. Here's a template of how to add code signing to the build pipeline: https://github.com/novotnyllc/CodeSigningDemo
2. Once signing is configured, please add `dotnetfoundation` as a co-owner in NuGet. 
3. For the tool packages, you'll need a whitelist.txt to include on your binaries and not the other ones in the nupkg.

I'm happy to review any PR's/pipelines

**Comment by MarcoRossignoli** [comment]
Thanks!

**Comment by MarcoRossignoli** [comment]
Sorry @clairernovotny for delay, very busy summer

we've to take a decision on https://github.com/coverlet-coverage/coverlet/issues/874 and after we can complete new pipeline/signing process cc: @tonerdo @petli
