### ISSUE TITLE
I would like to bring in MahApps.Metro to the .NET Foundation

### ISSUE THREAD

**Issue by punker76** [dotnet-foundation/projects#75]
## 1.   General Information

**Project Name:** MahApps.Metro

**License:** [MIT](https://github.com/MahApps/MahApps.Metro/blob/develop/LICENSE)

**Contributor (Company, Organization or individual name(s)):** @punker76 (@MahApps)

**Existing OSS Project? (Yes/No):** Yes

**Source Code URL:** https://github.com/MahApps/MahApps.Metro

**Project Homepage URL (if different):** https://mahapps.com

**Project Transfer Signatories:** Jan Karger ([email](mailto:punkerat76@gmail.com))

## 2.   Description
**Please provide a brief statement about your project in terms that are understandable to the target consumer of the library or project, i.e. an elevator pitch for the project:**

MahApps.Metro is a free open-source framework that allows developers to cobble together a better UI for their own WPF applications with minimal effort, Supporting .NET Framework and .NET Core. It overrides the default style of all common WPF controls and gives them a modern look. MahApps.Metro also includes some custom controls based on concepts from Windows Phone, Windows 8 and Window 10 (UWP) Apps.

**Please provide a 1 sentence (<140 character) summary of your project to help users when searching the .NET Foundation projects**

A toolkit for creating modern WPF applications with the .NET Framework and .NET Core.

## 3.   Project Governance
Please complete this section about who will be maintaining the open source project and how it will run.
**Project Lead:** Jan Karger (@punker76)

Name:   Jan Karger
 Email:   [email](mailto:punkerat76@gmail.com)
 GitHub Profile URL: https://github.com/punker76

**Committers:** @punker76 , @shiftkey , @flagbug , @AzureKitsune

**Governance Model:** PRs and changed are reviewed by ourselves (mostly @punker76). Decisions made by @punker76 and discussions with the contributor.

**CLA**

If already an OSS project, was a Contribution License Agreement in place for contributions accepted? How does the project check who has signed one?

We don’t have a CLA. The contributions have never been excessively big.

**CLA Notification Alias**

[email](mailto:punkerat76@gmail.com)

**Project Transfer Type**

- [x] Assignment 
- [ ] Contribution 

**Contribution Model.**  Under the .NET Foundation contribution model, a project retains ownership of the project, but grants .NET Foundation a broad license to the project’s code and other intellectual property. The project also confirms that the project’s submissions to .NET Foundation are its own original work (there are also instructions for any third party materials that might be included).

## 4.   Repository Layout
The .NET Foundation host guidance for new projects and details on recommended structure here:
[https://github.com/dotnet/home/tree/master/guidance](https://github.com/dotnet/home/tree/master/guidance)

Note that the open source repository should be the master where changes are made by the core development team using the same PR process that is used for non-committer contributions.

Please define below any changes you would want to make to your repositories as part of the process of joining the .NET Foundation

- None, if not necessary.

## 5.  Eligibility Criteria
Please complete the following for your project
* The project is built on the .NET platform and/or creates value within the .NET ecosystem.
- [x] Yes 
- [ ] No
* The project produces source code for distribution to the public at no charge.
- [x] Yes 
- [ ] No
* The project's code is easily discoverable and publicly accessible (preferably on GitHub).
- [x] Yes 
- [ ] No
* The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).
- [x] Yes 
- [ ] No
* When applicable, project must use reproducible build settings in its toolchain.
- [x] Yes 
- [ ] No
* The project uses [Source Link.](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
- [x] Yes 
- [ ] No
* The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).
- [x] Yes 
- [ ] No
* The project code signs their artifacts as appropriate.
- [x] Yes 
- [ ] No
* Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).
- [x] Yes 
- [ ] No
* Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.
- [x] Yes (hopefully) 
- [ ] No
* The copyright ownership of everything that the project produces is clearly defined and documented.
- [x] Yes 
- [ ] No
* The project has a public issue tracker where the status of any defect can be easily obtained.
- [x] Yes 
- [ ] No
* The project has a published Security Policy.
- [ ] Yes 
- [x] No
* The project has a home page which provides high level information about its status and purpose.
- [x] Yes 
- [ ] No
* The project has a public communication channel where community members can engage with maintainers.
- [x] Yes (Gitter, GitHub) 
- [ ] No
* The project has a publicly available location where members can review and contribute to documentation.
- [x] Yes 
- [ ] No

## 6.   PR Plan
Please summarize the public relations plan for the announcement when joining the foundation (and releasing as open source if appropriate). What is the main story we wish to promote, through what channels, what issues should we be aware of?  For significant news events then please also work with your .NET Foundation contact to ensure a [full PR plan](https://dotnetfoundation.sharepoint.com/Shared%20Documents/PR/Communications%20Plan%20TEMPLATE.docx?web=1) is developed.

- Should I make a short screencast?
- The main web site is for the complete documentation (https://mahapps.com)

## 7.   Infrastructure Requirements
Please describe any infrastructure requirements for the project. For example, how will build servers be operated? Any web hosting or service hosting requirements? Do we need to set up SSL certificates or provide Authenticode Code Signing arrangement for releases?

- The repo is currently build by appveyor without any requirements (appveyor is used by @punker76).
- The web page is build and hosted by GitHub and GitHub Actions. 
- The lib is certified by MVP DigiCert
- The web hosting (CNAME for mahapps.com) is payed by @punker76.

## 8.   Additional Notes
Please provide any additional information required or use this area for notes during the onboarding process. If this open source project has similarities with any other projects in this space then please detail them and why this project is different. If there are any potential issues that you feel the project might need help with early on then also state them here and discuss with your .NET Foundation Contact.
 - ...

**Comment by ChrisSfanos** [comment]
Assignment Agreement is out for signatures

**Comment by ChrisSfanos** [comment]
Forgot to post the checklist we will use for joining and on-boarding the project
## CLA
- [ ] CLA Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)

**Comment by ChrisSfanos** [comment]
Assignment agreement complete - sending out CLA bot config mail shortly

**Comment by ChrisSfanos** [comment]
CLA bot is now configured - emailed out the details for the remaining checklist items

**Comment by punker76** [comment]
@ChrisSfanos Here is a PR which adds some items from the list https://github.com/MahApps/MahApps.Metro/pull/3877
Let me know if this ok. Thx.

**Comment by punker76** [comment]
@ChrisSfanos [PR](https://github.com/dotnet-foundation/website/pull/194) for the last item in list

**Comment by ChrisSfanos** [comment]
I did a quick eye check and it looks good - I can't merge it, but I'm going to mark the item as complete.  And that should wrap up the work list to get the project on-boarded - thanks!
