### ISSUE TITLE
Verify

### ISSUE THREAD

**Issue by SimonCropp** [dotnet-foundation/projects#78]
## 1.   General Information

**Project Name:** Verify

**License:** MIT

**Contributor (Company, Organization or individual name(s)):** Simon Cropp

**Existing OSS Project? (Yes/No):** Yes

**Source Code URL:** all projects under https://github.com/VerifyTests. main repo is https://github.com/VerifyTests/Verify

**Project Homepage URL (if different):**

**Project Transfer Signatories:**

Simon Christopher Cropp. simon.cropp@gmail.com

## 2.   Description

Verification tool to enable approval of complex models and documents. Think snapshot testing on steroids.

## 3.   Project Governance
Please complete this section about who will be maintaining the open source project and how it will run.
**Project Lead:**

Name:   Simon Cropp
 Email:   simon.cropp@gmail.com
 GitHub Profile URL: https://github.com/SimonCropp

**Committers:**

SimonCropp

**Governance Model:**

>  describe how new code changes are proposed to the project, 

via GH issue, GH pull request, twitter, zoom, email.

>  how those changes are reviewed and how a decision is made to accept proposed changes. 

Discussion with the submitter. ensure correctness, value to other consumers, and no known technical debt. 

> Also describe the process for identifying and appointing new committers.

Currently none.

TBH I have not needed an formalized Governance Model for my OSS projects. Happy to consider suggestions for recommended models.

**CLA**

No CLA. Planning on adopting the DNF one

**CLA Notification Alias**

simon.cropp@gmail.com

**Project Transfer Type**

**Contribution Model.**  Under the .NET Foundation contribution model, a project retains ownership of the project, but grants .NET Foundation a broad license to the project’s code and other intellectual property. The project also confirms that the project’s submissions to .NET Foundation are its own original work (there are also instructions for any third party materials that might be included).

## 4.   Repository Layout

Please define below any changes you would want to make to your repositories as part of the process of joining the .NET Foundation

* documentation is under `docs`
* source (including `.gitattributes`) is under `src`

## 5.  Eligibility Criteria
Please complete the following for your project
* The project is built on the .NET platform and/or creates value within the .NET ecosystem.
- [x] Yes 
- [ ] No
* The project produces source code for distribution to the public at no charge.
- [x] Yes 
- [ ] No
* The project's code is easily discoverable and publicly accessible (preferably on GitHub).
- [x] Yes 
- [ ] No
* The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).
- [x] Yes 
- [ ] No
* When applicable, project must use reproducible build settings in its toolchain.
- [x] Yes 
- [ ] No
* The project uses [Source Link.](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
- [x] Yes 
- [ ] No
* The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).
- [x] Yes 
- [ ] No
* The project code signs their artifacts as appropriate.
- [x] Yes 
- [ ] No
* Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).
- [ ] Yes 
- [x] No
* Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.
- [x] Yes 
- [ ] No
* The copyright ownership of everything that the project produces is clearly defined and documented.
- [x] Yes 
- [ ] No
* The project has a public issue tracker where the status of any defect can be easily obtained.
- [x] Yes 
- [ ] No
* The project has a published Security Policy.
- [x] Yes 
- [ ] No
* The project has a home page which provides high level information about its status and purpose.
- [x] Yes 
- [ ] No
* The project has a public communication channel where community members can engage with maintainers.
- [x] Yes 
- [ ] No
* The project has a publicly available location where members can review and contribute to documentation.
- [x] Yes 
- [ ] No

## 6.   PR Plan
> Please summarize the public relations plan for the announcement when joining the foundation

I have spoke to Scott Hanselman about the potential of doing a podcast episode

## 7.   Infrastructure Requirements
None

## 8.   Additional Notes
* Alternatives: https://github.com/VerifyTests/Verify#alternatives
* It is a genesis of the [ApprovaTests](https://github.com/approvals/ApprovalTests.Net) project which I am also a core contributor for. For comparison https://github.com/VerifyTests/Verify/blob/master/docs/compared-to-approvaltests.md.

**Comment by SimonCropp** [comment]
> Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).

amending...

 * https://github.com/VerifyTests/Verify.Aspose relies on https://www.aspose.com/ which is a commercial product

**Comment by ChrisSfanos** [comment]
Hello!  I'll be driving the project on-boarding process.  We will follow the checklist below - thanks!

## CLA
- [ ] Project Agreement Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)

**Comment by ChrisSfanos** [comment]
Project agreement is out for signing

**Comment by ChrisSfanos** [comment]
DocuSign complete - CLA onboarding email sent

**Comment by ChrisSfanos** [comment]
CLA bot is configured - remaining on-boarding steps are up next - supplemental mail sent shortly

**Comment by ChrisSfanos** [comment]
All on-boarding steps are complete!  Thanks for the quick turnaround :-)

**Comment by SimonCropp** [comment]
@ChrisSfanos thanks for all your help
