### ISSUE TITLE
Oqtane

### ISSUE THREAD

**Issue by sbwalker** [dotnet-foundation/projects#8]
## 1.   General Information

**Project Name:** Oqtane

**License:** MIT

**Contributor (Company, Organization or individual name(s)):** Shaun Walker

**Existing OSS Project? (Yes/No):** Yes

**Source Code URL:** https://github.com/oqtane/oqtane.framework

**Project Homepage URL (if different):** https://www.oqtane.org/

**Project Transfer Signatories:**
Full legal name and email address required of the individual(s) with the authority to transfer or contribute the project to the .NET Foundation. Note that if you'd prefer not to include this in the public application, it can be submitted via e-mail to contact@dotnetfoundation.org (referencing this issue number).

Shaun Walker - shaun.walker@siliqon.com

## 2.   Description
**Please provide a brief statement about your project in terms that are understandable to the target consumer of the library or project, i.e. an elevator pitch for the project:**

Oqtane is an open source modular application framework for Blazor. Oqtane was inspired by DotNetNuke and supports multi-tenancy, a fully dynamic page compositing model, designer friendly skins, extensibility via third party modules, and a familiar data model.

**Please provide a 1 sentence (<140 character) summary of your to help users when searching the .NET Foundation projects**

Oqtane is an open source modular application framework for Blazor

## 3.   Project Governance
Please complete this section about who will be maintaining the open source project and how it will run.

**Project Lead:**
(Who is the primary contact point for the community and the .NET Foundation when discussing governance of the project.)

Name:   Shaun Walker
 Email:   shaun.walker@siliqon.com
 GitHub Profile URL: https://github.com/sbwalker

**Committers:**

Which individuals have commit / write access to the repository, what is their GitHub ID and who is their employer (if contributions are on behalf of an employer)

Shaun Walker - sbwalker

**Governance Model:**

Please describe how new code changes are proposed to the project, how those changes are reviewed and how a decision is made to accept proposed changes. Also describe the process for identifying and appointing new committers.

Community members submit pull requests which are reviewed by the core committers for quality and fit. If they are approved they are committed to the project. Core committers are identified through their participation in the community as well as through pull requests they have submitted.

**CLA**

If already an OSS project, was a Contribution License Agreement in place for contributions accepted? How does the project check who has signed one?

This project would like to utilize the .NET Foundation CLA system  

**CLA Notification Alias**
Provide an email address that will receive CLA related notifications from the .NET Foundation CLA automation

support@oqtane.org

**Project Transfer Type**

Projects may join the .NET Foundation in one of two ways and you should chat with your .NET Foundation contact to discuss the best mechanism for your project. You can either a) assign the copyright of the project's source code to the .NET Foundation or b) contribute the project source code to the .NET Foundation under an open source license. Assignment is the preferred approach, but licensing a project to the Foundation may be more appropriate for longer running open source projects that have not previously had a contribution license agreement and have accepted contributions from many different sources.
a) Assignment
b) Contribution

Assignment

## 4.   Repository Layout
The .NET Foundation host guidance for new projects and details on recommended structure here:
[https://github.com/dotnet/home/tree/master/guidance](https://github.com/dotnet/home/tree/master/guidance)

Note that the open source repository should be the master where changes are made by the core development team using the same PR process that is used for non-committer contributions.

Please define below any changes you would want to make to your repositories as part of the process of joining the .NET Foundation

Project follows the .NET Foundation recommended guidelines.

## 5.   PR Plan
Please summarize the public relations plan for the announcement when joining the foundation (and releasing as open source if appropriate). What is the main story we wish to promote, through what channels, what issues should we be aware of?  For significant news events then please also work with your .NET Foundation contact to ensure a [full PR plan](https://dotnetfoundation.sharepoint.com/Shared%20Documents/PR/Communications%20Plan%20TEMPLATE.docx?web=1) is developed.

We will post a blog on our site about joining the .NET Foundation, mention it in our email newsletter, highlight it in webinars and presentations, and will heavily promote it on social media. The main storyline will be to promote Blazor and provide a potential migration path for the legacy DNN community. 

## 6.   Infrastructure Requirements
Please describe any infrastructure requirements for the project. For example, how will build servers be operated? Any web hosting or service hosting requirements? Do we need to set up SSL certificates or provide Authenticode Code Signing arrangement for releases?

The project has its own community website at https://www.oqtane.org. There aren’t any special infrastructure requirements for this project at this time.  

## 7.   Additional Notes
Please provide any additional information required or use this area for notes during the onboarding process. If this open source project has similarities with any other projects in this space then please detail them and why this project is different. If there are any potential issues that you feel the project might need help with early on then also state them hear and discuss with your .NET Foundation Contact.

This project has conceptual similarities to DotNetNuke - which is another .NET Foundation project. However, this project is a native .NET Core application which uses Blazor so it is significantly differentiated from DotNetNuke from a technical perspective.

**Comment by sbwalker** [comment]
Is there any update on the status of this application?

**Comment by ChrisSfanos** [comment]
We will be using the following checklist to track progress for onboarding the project

## CLA
- [ ] CLA Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)

**Comment by ChrisSfanos** [comment]
CLA is out for signing

**Comment by ChrisSfanos** [comment]
CLA is signed - email out for CLA bot config

**Comment by ChrisSfanos** [comment]
CLA Bot complete
onboarding steps complete.  I've added Oqtane to the next Newsletter, so the announcement part is complete and will go out with the next edition
