### ISSUE TITLE
[NuGet Trends] Hosting support

### ISSUE THREAD

**Issue by bruno-garcia** [dotnet-foundation/projects#82]
Since there's no template for this of request, taking a guess, let me know if there's a process for this.

Currently the [member project NuGet Trends](https://github.com/dotnet/nuget-trends) runs as a set of docker containers on a single machine, located in Germany. The server bill is currently paid by me.

I wonder if the foundation is able to provide some azure credits or something else in order to host it.

The project is setup to the following containers:

* nginx - serves the static files (the SPA)
* dotnet process - web api (behind nginx, no CORS)
* dotnet process - scheduler, hits nuget.org daily
* postgres
* rabbitmq

Since all of these run on the same box and I pay for the whole box, I'm unsure what the bill would like on azure or some other cloud provider.

**Comment by clairernovotny** [comment]
Thanks @bruno-garcia. The projects committee oversees project support requests like this. @sbwalker.

We can provide a resource group in our Azure subscription that can host this. The committee would want to know a proposed architecture and rough costs for running this in the "ideal" way. I.e., probably containers App Services for handling ingress, scheduled functions, and hosted database, etc. 

Overall though, this is something we can definitely take on.

**Comment by clairernovotny** [comment]
Closing due to age. We can still handle this if you need; please just let us know approximate costs of the hosting.
