### ISSUE TITLE
Code Signing Certificate Request: FluentValidation

### ISSUE THREAD

**Issue by JeremySkinner** [dotnet-foundation/projects#88]
Hi, I'd like to get nuget package signing set up for FluentValidation. Thanks!

### Please fill in the information below

- **Project Name:** FluentValidation
- **LastPass Email (or send offline):** jeremy@jeremyskinner.co.uk

Certificate onboarding checklist:

- [x] Register trade name @ChrisSfanos
- [x] Create organization with DigiCert
- [x] Create configuration in Code Signing Service
- [x] Provide credentials in shared folder in LastPass
- [x] Request certificate from DigiCert
- [x] Received certificate and finalize sign service configuration

**Comment by ChrisSfanos** [comment]
Sorry for the delay - trade name has been registered

**Comment by clairernovotny** [comment]
I just invited you to the shared LastPass where the cert is setup and configured.

Few things:
1. Here's a template of how to add code signing to the build pipeline: https://github.com/novotnyllc/CodeSigningDemo
2. Once signing is configured, please add `dotnetfoundation` as a co-owner in NuGet. 
3. If you have any 3rd party binaries in your packages, you'll need a whitelist.txt to include on your binaries and not the other ones in the nupkg.

I'm happy to review any PR's/pipelines

**Comment by JeremySkinner** [comment]
Thanks Claire, I’ll try and make a start on this over the weekend and will let you know if I run into any issues
