### ISSUE TITLE
Code Signing Certificate Request: ResXResourceManager

### ISSUE THREAD

**Issue by tom-englert** [dotnet-foundation/projects#89]
- Project Name: ResXResourceManager
- LastPass Email: Sent per mail

Certificate onboarding checklist:

- [x] Register trade name @ChrisSfanos
- [x] Create organization with DigiCert
- [x] Create configuration in Code Signing Service
- [x] Provide credentials in shared folder in LastPass
- [x] Request certificate from DigiCert
- [x] Received certificate and finalize sign service configuration

**Comment by ChrisSfanos** [comment]
Submitted Trade Name registration this morning

**Comment by clairernovotny** [comment]
I just invited you to the shared LastPass where the cert is setup and configured.

Few things:
1. Here's a template of how to add code signing to the build pipeline: https://github.com/novotnyllc/CodeSigningDemo
2. Once signing is configured, please add `dotnetfoundation` as a co-owner in NuGet. 
3. If you have any 3rd party binaries in your packages, you'll need a whitelist.txt to include on your binaries and not the other ones in the nupkg.

I'm happy to review any PR's/pipelines

**Comment by tom-englert** [comment]
@clairernovotny: how to get this running? According to https://docs.microsoft.com/en-us/azure/security/develop/security-code-analysis-overview this is a paid service.

Can I just skip this?

    # If you have MSCA: https://aka.ms/mscadocs
          - task: ms-codeanalysis.vss-microsoft-security-code-analysis-devops.build-task-antimalware.AntiMalware@3

**Comment by tom-englert** [comment]
@clairernovotny I think I found the solution, I can simply use `"%ProgramFiles%\Windows Defender\MpCmdRun.exe" -Scan -ScanType 3 -File "<path to binaries>"`

**Comment by tom-englert** [comment]
Done, finally it was very easy to use!

**Comment by tom-englert** [comment]
P.S. that's the updated pipeline:
https://github.com/dotnet/ResXResourceManager/blob/master/azure-pipelines.yml
https://dev.azure.com/tom-englert/Open%20Source/_build?definitionId=35
