### ISSUE TITLE
FlubuCore

### ISSUE THREAD

**Issue by mzorec** [dotnet-foundation/projects#9]
## 1.   General Information

**Project Name:** FlubuCore

**License:** MIT

**Contributor (Company, Organization or individual name(s)):** Marko Zorec, Zoro Zorec

**Existing OSS Project? (Yes/No):** Yes

**Source Code URL:** https://github.com/dotnetcore/FlubuCore

**Project Homepage URL (if different):** https://flubucore.dotnetcore.xyz/

**Project Transfer Signatories:**
Full legal name and email address required of the individual(s) with the authority to transfer or contribute the project to the .NET Foundation. Note that if you'd prefer not to include this in the public application, it can be submitted via e-mail to contact@dotnetfoundation.org (referencing this issue number).

Marko Zorec - mzorec@gmail.com

Zoro Zorec -  zoro.zorec@gmail.com 

## 2.   Description
**Please provide a brief statement about your project in terms that are understandable to the target consumer of the library or project, i.e. an elevator pitch for the project:**

FlubuCore - Fluent Builder Core" is a cross platform build and deployment automation system. You can define your build and deployment scripts in C# using an intuitive fluent interface. This gives you code completion, IntelliSense, debugging, FlubuCore custom analyzers, and native access to the whole .NET ecosystem inside of your scripts.

**Please provide a 1 sentence (<140 character) summary of your to help users when searching the .NET Foundation projects**

A cross platform build and deployment automation system for building projects and executing deployment scripts using C# code.

## 3.   Project Governance
Please complete this section about who will be maintaining the open source project and how it will run.
**Project Lead:**
(Who is the primary contact point for the community and the .NET Foundation when discussing governance of the project.)

Name:   Marko Zorec
 Email:   mzorec@gmail.com
 GitHub Profile URL: https://github.com/mzorec

**Committers:**

Which individuals have commit / write access to the repository, what is their GitHub ID and who is their employer (if contributions are on behalf of an employer)

Marko Zorec - mzorec
Zoro Zorec - zoroz

**Governance Model:**

Please describe how new code changes are proposed to the project, how those changes are reviewed and how a decision is made to accept proposed changes. Also describe the process for identifying and appointing new committers.

Community members submit pull requests which are reviewed by the core committers

**CLA**

If already an OSS project, was a Contribution License Agreement in place for contributions accepted? How does the project check who has signed one?

This project would like to utilize the .NET Foundation CLA system

**CLA Notification Alias**
Provide an email address that will receive CLA related notifications from the .NET Foundation CLA automation

FlubuCore@gmail.com

**Project Transfer Type**

Projects may join the .NET Foundation in one of two ways and you should chat with your .NET Foundation contact to discuss the best mechanism for your project. You can either a) assign the copyright of the project's source code to the .NET Foundation or b) contribute the project source code to the .NET Foundation under an open source license. Assignment is the preferred approach, but licensing a project to the Foundation may be more appropriate for longer running open source projects that have not previously had a contribution license agreement and have accepted contributions from many different sources.
a) Assignment
b) Contribution

Contribution

## 4.   Repository Layout
The .NET Foundation host guidance for new projects and details on recommended structure here:
[https://github.com/dotnet/home/tree/master/guidance](https://github.com/dotnet/home/tree/master/guidance)

Note that the open source repository should be the master where changes are made by the core development team using the same PR process that is used for non-committer contributions.

Please define below any changes you would want to make to your repositories as part of the process of joining the .NET Foundation

Project follows the .NET Foundation recommended guidelines.

## 5.   PR Plan
Please summarize the public relations plan for the announcement when joining the foundation (and releasing as open source if appropriate). What is the main story we wish to promote, through what channels, what issues should we be aware of?  For significant news events then please also work with your .NET Foundation contact to ensure a [full PR plan](https://dotnetfoundation.sharepoint.com/Shared%20Documents/PR/Communications%20Plan%20TEMPLATE.docx?web=1) is developed.

## 6.   Infrastructure Requirements
Please describe any infrastructure requirements for the project. For example, how will build servers be operated? Any web hosting or service hosting requirements? Do we need to set up SSL certificates or provide Authenticode Code Signing arrangement for releases?

There aren’t any special infrastructure requirements for this project at this time.

## 7.   Additional Notes
Please provide any additional information required or use this area for notes during the onboarding process. If this open source project has similarities with any other projects in this space then please detail them and why this project is different. If there are any potential issues that you feel the project might need help with early on then also state them here and discuss with your .NET Foundation Contact.

FlubuCore is Member of NCC organization.

**Comment by mzorec** [comment]
@jongalloway @onovotny Can i ask what's the status on this? There has been no response for more than 6 months.

**Comment by IrisClasson** [comment]
Hi and sorry for the delay! The project is now under review and we should be able to give an answer soon. We'll keep you posted!

**Comment by ChrisSfanos** [comment]
Hi everyone - I'll be processing the onboarding of your project.  We will use the following checklist to track the work.  

## CLA
- [ ] CLA Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)

**Comment by ChrisSfanos** [comment]
CLA is out for signing

**Comment by mzorec** [comment]
CLA is signed.

**Comment by ChrisSfanos** [comment]
Thanks!  Email sent for CLA onboarding

**Comment by ChrisSfanos** [comment]
CLA onboarding completed - supplemental details sent for remaining onboarding steps

**Comment by ChrisSfanos** [comment]
Project onboarding list is complete and verified … closing
