### ISSUE TITLE
C# standardization: ECMA TC49-TG2

### ISSUE THREAD

**Issue by BillWagner** [dotnet-foundation/projects#90]
## 1.   General Information

**Project Name:** C# language specification standardization

**License:** MIT

**Contributor (Company, Organization or individual name(s)):** ECMA TC49-TG2 (The C# language standards committee).

**Existing OSS Project? (Yes/No):** No. The committee has been working in private, with only the approved standards being public. If accepted, the committee will do its future work in public, and encourage community contributions.

**Source Code URL:**  N/A. This project is all markdown text, defining the C# standard.

**Project Homepage URL (if different):**

**Project Transfer Signatories:**
[Jon Skeet](jonskeet@google.com): Convener of TC49-TG2
[Bill Wagner](bill.wagner@dotnetfoundation.org): Member of TC49-TG2, and .NET Foundation board member.
[Mads Torgersen](mads.torgersen@microsoft.com): C# language architect.

## 2.   Description
This project produces the standard C# language specification. The ECMA committee standardizes the formal specification of the C# language. The latest standard is C# 5.0. The committee is working on C# 6 now.

**Please provide a 1 sentence (<140 character) summary of your project to help users when searching the .NET Foundation projects**
Follow the ongoing standardization work for the C# language. The committee now publishes drafts, meeting agendas and meeting minutes in public.

## 3.   Project Governance
Please complete this section about who will be maintaining the open source project and how it will run.
**Project Lead:**
(Who is the primary contact point for the community and the .NET Foundation when discussing governance of the project.)

Name:   Jon Skeet
 Email:   jonskeet@google.com
 GitHub Profile URL: https://github.com/jskeet

**Committers:**

[Jon Skeet](https://github.com/jskeet) - Google
[Bill Wagner](https://github.com/billwagner) - Microsoft
[Neal Gafter](https://github.com/gafter) - Facebook
[Nigel Perry](https://github.com/Nigel-Ecma)
[Mads Torgersen](https://github.com/MadsTorgersen) - Microsoft
[Rex Jaeschke](https://github.com/RexJaeschke)
[Eric Lippert](https://github.com/ericlippert) - Facebook

**Governance Model:**

Change may be proposed to the standard by anyone. The changes must be approved by the ECMA committee members. Committee members must be invited by the committee, and fill out an invited expert form for ECMA.

**CLA**

If already an OSS project, was a Contribution License Agreement in place for contributions accepted? How does the project check who has signed one?

N/A. If accepted, we'd use the .NET Foundation CLA.

**CLA Notification Alias**
Provide an email address that will receive CLA related notifications from the .NET Foundation CLA automation

jonskeet@google.com.

**Project Transfer Type**

- [ ] Assigment
- [X] Contribution

**Assignment Model.**  Under the .NET Foundation assignment model, project ownership and other intellectual property is assigned to the .NET Foundation and the .NET Foundation agrees to grantback a license to the contributor(s). 

**Contribution Model.**  Under the .NET Foundation contribution model, a project retains ownership of the project, but grants the .NET Foundation a broad license to the project’s code and other intellectual property. The project also confirms that the project’s submissions to .NET Foundation are its own original work (there are also instructions for any third party materials that might be included).

## 4.   Repository Layout
The .NET Foundation host guidance for new projects and details on recommended structure here:
[https://github.com/dotnet/home/tree/master/guidance](https://github.com/dotnet/home/tree/master/guidance)

Note that the open source repository should be the master where changes are made by the core development team using the same PR process that is used for non-committer contributions.

Please define below any changes you would want to make to your repositories as part of the process of joining the .NET Foundation

We'll be creating a new repository with the following folders:
- Spec
- tools
- meeting minutes
- meeting agendas
- process docs

## 5.  Eligibility Criteria
Please complete the following for your project
* The project is built on the .NET platform and/or creates value within the .NET ecosystem.
- [X] Yes 
- [ ] No
* The project produces source code for distribution to the public at no charge.
- [X] Yes 
- [ ] No
* The project's code is easily discoverable and publicly accessible (preferably on GitHub).
- [X] Yes 
- [ ] No
* The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).
- [ ] Yes 
- [ ] No
- [X] N/A
* When applicable, project must use reproducible build settings in its toolchain.
- [ ] Yes 
- [ ] No
* The project uses [Source Link.](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
- [ ] Yes 
- [ ] No
- [X] N/A
* The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).
- [ ] Yes 
- [ ] No
* The project code signs their artifacts as appropriate.
- [ ] Yes 
- [ ] No
* Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).
- [X] Yes 
- [ ] No
* Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.
- [X] Yes 
- [ ] No
* The copyright ownership of everything that the project produces is clearly defined and documented.
- [X] Yes 
- [ ] No
* The project has a public issue tracker where the status of any defect can be easily obtained.
- [x] Yes 
- [ ] No
* The project has a published Security Policy.
- [ ] Yes 
- [ ] No
* The project has a home page which provides high level information about its status and purpose.
- [X] Yes 
- [ ] No
* The project has a public communication channel where community members can engage with maintainers.
- [X] Yes 
- [ ] No
* The project has a publicly available location where members can review and contribute to documentation.
- [X] Yes 
- [ ] No

## 6.   PR Plan
Please summarize the public relations plan for the announcement when joining the foundation (and releasing as open source if appropriate). What is the main story we wish to promote, through what channels, what issues should we be aware of?  For significant news events then please also work with your .NET Foundation contact to ensure a [full PR plan](https://dotnetfoundation.sharepoint.com/Shared%20Documents/PR/Communications%20Plan%20TEMPLATE.docx?web=1) is developed.

As we go public, we'll promote that future standard work will take place in public. We'll promote that via .NET marketing channels in coordination with ECMA.

## 7.   Infrastructure Requirements
Please describe any infrastructure requirements for the project. For example, how will build servers be operated? Any web hosting or service hosting requirements? Do we need to set up SSL certificates or provide Authenticode Code Signing arrangement for releases?

We'll link the repository to the docs.microsoft.com build pipeline to publish the latest working draft on docs.microsoft.com

## 8.   Additional Notes
Please provide any additional information required or use this area for notes during the onboarding process. If this open source project has similarities with any other projects in this space then please detail them and why this project is different. If there are any potential issues that you feel the project might need help with early on then also state them here and discuss with your .NET Foundation Contact.

This project is unique in that it does not produce code. Rather, its artifacts are the standard that defined the behavior of the [roslyn](https://github.com/dotnet/roslyn] compiler.

**Comment by ChrisSfanos** [comment]
Hi everyone
I will be driving the on-boarding for C# Standardization to the .NET Foundation.  We will be following the checklist below:

## CLA
- [ ] Project Agreement Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)
- [ ] Enable two-factor authentication (2FA) for GitHub

**Comment by ChrisSfanos** [comment]
CLA is now out for signing

**Comment by ChrisSfanos** [comment]
All C# Standardization folks have signed the CLA, so while we wait for Claire, I've sent out the CLA bot onboarding instructions

**Comment by ChrisSfanos** [comment]
CLA bot is now configured after moving the repo to the dotnet org.  I'll send out the remaining onboarding steps in a few

**Comment by ChrisSfanos** [comment]
The CLA is now signed - that's the last item on the list, so I'm closing this out
