### ISSUE TITLE
New .NET Foundation Project Application (Esquio)

### ISSUE THREAD

**Issue by unaizorrilla** [dotnet-foundation/projects#94]
## 1.   General Information

**Project Name:** 
Esquio

**License:**
Apache-2.0 License

**Contributor (Company, Organization or individual name(s)):**  
Unai Zorrilla Castro (@unaizorrilla)

**Existing OSS Project? (Yes/No):**
Yes

**Source Code URL:**
https://github.com/Xabaril/Esquio/

**Project Homepage URL (if different):**

**Project Transfer Signatories:**
Full legal name and unai@plainconcepts.com required of the individual(s) with the authority to transfer or contribute the project to the .NET Foundation. Note that if you'd prefer not to include this in the public application, it can be submitted via e-mail to contact@dotnetfoundation.org (referencing this issue number).

## 2.   Description
**Please provide a brief statement about your project in terms that are understandable to the target consumer of the library or project, i.e. an elevator pitch for the project:**

Esquio is a Feature Toggles (aka Feature Flags) and A/B testing framework for .NET Core 3.0

## 3.   Project Governance
Please complete this section about who will be maintaining the open source project and how it will run.
**Project Lead:** Unai Zorrilla ( @unaizorrilla )

Name:    Unai Zorrilla Castro
 Email:   unai@plainconcepts.com
 GitHub Profile URL: https://github.com/unaizorrilla

**Committers:**

@unaizorrilla 
@lfraile
@lurumad 

**Governance Model:**

We have an ongoing policy towards community participation and we are constantly encouraging new contributors and asking for new developers to join the core team. We discuss new features using issues and allow new code with PR's.

**CLA**

**CLA Notification Alias**
unai@plainconcepts.com 

**Project Transfer Type**

- [ ] Assigment
- [X] Contribution

**Assignment Model.**  Under the .NET Foundation assignment model, project ownership and other intellectual property is assigned to the .NET Foundation and the .NET Foundation agrees to grantback a license to the contributor(s). 

**Contribution Model.**  Under the .NET Foundation contribution model, a project retains ownership of the project, but grants the .NET Foundation a broad license to the project’s code and other intellectual property. The project also confirms that the project’s submissions to .NET Foundation are its own original work (there are also instructions for any third party materials that might be included).

## 4.   Repository Layout
The .NET Foundation host guidance for new projects and details on recommended structure here:
[https://github.com/dotnet/home/tree/master/guidance](https://github.com/dotnet/home/tree/master/guidance)

Note that the open source repository should be the master where changes are made by the core development team using the same PR process that is used for non-committer contributions.

Please define below any changes you would want to make to your repositories as part of the process of joining the .NET Foundation

## 5.  Eligibility Criteria
Please complete the following for your project
* The project is built on the .NET platform and/or creates value within the .NET ecosystem.
- [X] Yes 
- [ ] No
* The project produces source code for distribution to the public at no charge.
- [X] Yes 
- [ ] No
* The project's code is easily discoverable and publicly accessible (preferably on GitHub).
- [X] Yes 
- [ ] No
* The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).
- [X] Yes 
- [ ] No
* When applicable, project must use reproducible build settings in its toolchain.
- [X] Yes 
- [ ] No
* The project uses [Source Link.](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
- [X] Yes 
- [ ] No
* The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).
- [X] Yes 
- [ ] No
* The project code signs their artifacts as appropriate.
- [X] Yes 
- [ ] No
* Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).
- [X] Yes 
- [ ] No
* Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.
- [X] Yes 
- [ ] No
* The copyright ownership of everything that the project produces is clearly defined and documented.
- [X] Yes 
- [ ] No
* The project has a public issue tracker where the status of any defect can be easily obtained.
- [X] Yes 
- [ ] No
* The project has a published Security Policy.
- [X] Yes 
- [ ] No
* The project has a home page which provides high level information about its status and purpose.
- [X] Yes 
- [ ] No
* The project has a public communication channel where community members can engage with maintainers.
- [ ] Yes 
- [X] No
* The project has a publicly available location where members can review and contribute to documentation.
- [X] Yes 
- [ ] No

## 6.   PR Plan
The plan is to shout out the milestone of joining the foundation and take advantage on the “noise” generated by the event. Posts on official blog, Twitter, Linked In.
For this last part we see the foundation as a key part of bringing “weight” to the announcement in order to make more interesting/relevant to those channels.

## 7.   Infrastructure Requirements
We are currently relying on GitHub, GitHub actions and pipelines.

**Comment by ChrisSfanos** [comment]
Hello - we will be following the checklist below to onboard the project

## CLA
- [ ] Project Agreement Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)

**Comment by ChrisSfanos** [comment]
Hi @lfraile - I need your full name and email address for the CLA agreement.  You can email it to chris.sfanos (at) dotnetfoundation.org if you'd prefer

**Comment by lfraile** [comment]
Hello @ChrisSfanos, sure, here it goes: Luis Fraile Hernández and my email lfraile@lfraile.net

**Comment by ChrisSfanos** [comment]
Thanks!
CLA is now out for signatures

**Comment by ChrisSfanos** [comment]
CLA is signed - I've sent an email detailing the steps to configure permissions for the CLA Bot

**Comment by ChrisSfanos** [comment]
CLA bot is configured / remaining steps are complete - closing this out
