### ISSUE TITLE
Xamarin Community Toolkit

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet-foundation/projects#95]
## 1.   General Information

**Project Name:** Xamarin Community Toolkit

**License:** [MIT License](https://github.com/xamarin/XamarinCommunityToolkit/blob/main/LICENSE)

**Contributor (Company, Organization or individual name(s)):** Microsoft and the Xamarin Community

**Existing OSS Project? (Yes/No):** Yes

**Source Code URL:** https://github.com/xamarin/XamarinCommunityToolkit

**Project Homepage URL (if different):**

**Project Transfer Signatories:**
[Gerald Versluis](Gerald.Versluis@@microsoft.com)
[Javier Suarez](jsuarez@microsoft.com)

## 2.   Description
**Please provide a brief statement about your project in terms that are understandable to the target consumer of the library or project, i.e. an elevator pitch for the project:**

The Xamarin Community Toolkit is a collection of common elements for mobile development with Xamarin.Forms that people tend to replicate across multiple apps. It simplifies and demonstrates common developer tasks when building apps with Xamarin.Forms.

**Please provide a 1 sentence (<140 character) summary of your project to help users when searching the .NET Foundation projects**

The Xamarin Community Toolkit is a collection of common elements for mobile development with Xamarin.Forms.

## 3.   Project Governance

**Project Leads:**

Name:   Gerald Versluis
 Email:   Gerald.Versluis@@microsoft.com
 GitHub Profile URL: https://github.com/jfversluis

Name:   Javier Suarez
 Email:   jsuarez@microsoft.com
 GitHub Profile URL: https://github.com/jsuarezruiz

**Committers:**

**Governance Model:**

We have an ongoing policy towards community participation and we are constantly encouraging new contributors and asking for new developers to join the core team. We discuss new features using issues and allow new code with PR's.

**CLA**

If already an OSS project, was a Contribution License Agreement in place for contributions accepted? How does the project check who has signed one?

**CLA Notification Alias**
Gerald.Versluis@@microsoft.com
jsuarez@microsoft.com

**Project Transfer Type**

- [ ] Assigment
- [x] Contribution

**Assignment Model.**  Under the .NET Foundation assignment model, project ownership and other intellectual property is assigned to the .NET Foundation and the .NET Foundation agrees to grantback a license to the contributor(s). 

**Contribution Model.**  Under the .NET Foundation contribution model, a project retains ownership of the project, but grants the .NET Foundation a broad license to the project’s code and other intellectual property. The project also confirms that the project’s submissions to .NET Foundation are its own original work (there are also instructions for any third party materials that might be included).

## 4.   Repository Layout
The .NET Foundation host guidance for new projects and details on recommended structure here:
[https://github.com/dotnet/home/tree/master/guidance](https://github.com/dotnet/home/tree/master/guidance)

Note that the open source repository should be the master where changes are made by the core development team using the same PR process that is used for non-committer contributions.

Please define below any changes you would want to make to your repositories as part of the process of joining the .NET Foundation

## 5.  Eligibility Criteria
Please complete the following for your project
* The project is built on the .NET platform and/or creates value within the .NET ecosystem.
- [x] Yes 
- [ ] No
* The project produces source code for distribution to the public at no charge.
- [x] Yes 
- [ ] No
* The project's code is easily discoverable and publicly accessible (preferably on GitHub).
- [x] Yes 
- [ ] No
* The project contains a build script that can produce deployable artifacts that are identical to the official deployable artifacts, with the exception of code signing (Exception may be granted for strong name keys, though strongly encouraged to be committed. Exception relies on OSS signing being in the build script for public builds).
- [x] Yes 
- [ ] No
* When applicable, project must use reproducible build settings in its toolchain.
- [x] Yes 
- [ ] No
* The project uses [Source Link.](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
- [x] Yes 
- [ ] No
* The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).
- [x] Yes 
- [ ] No
* The project code signs their artifacts as appropriate.
- [x] Yes 
- [ ] No
* Libraries that are mandatory dependencies of the project are offered under a standard, permissive open source license which has been approved by the .NET Foundation (exceptions include a dependency that is required by the target platform where no alternative open source dependency is available such as the .NET Framework or a hardware specific library).
- [x] Yes 
- [ ] No
* Committers are bound by a Contributor License Agreement (CLA) and/or are willing to embrace the .NET Foundation's CLA when the project becomes a Member.
- [x] Yes 
- [ ] No
* The copyright ownership of everything that the project produces is clearly defined and documented.
- [x] Yes 
- [ ] No
* The project has a public issue tracker where the status of any defect can be easily obtained.
- [x] Yes 
- [ ] No
* The project has a published Security Policy.
- [x] Yes 
- [ ] No
* The project has a home page which provides high level information about its status and purpose.
- [x] Yes 
- [ ] No
* The project has a public communication channel where community members can engage with maintainers.
- [x] Yes 
- [ ] No
* The project has a publicly available location where members can review and contribute to documentation.
- [x] Yes 
- [ ] No

## 6.   PR Plan
Update the repository documentation indicating that it is part of the .NET Foundation. Posts on social networks.

## 7.   Infrastructure Requirements
We are currently relying on GitHub and Azure DevOps pipelines.

**Comment by ChrisSfanos** [comment]
Hello everyone - I'll be driving the on-boarding process for Xamarin Community Toolkit.  We will be following the checklist below

## CLA
- [ ] Project Agreement Signing via DocuSign
- [ ] CLA Onboarding via GitHub

## Project Onboarding
- [ ] Public Announcement via the .NET Foundation site/etc
- [ ] Joining the Project leader mailing list
- [ ] Joining the Project leader Slack channel
- [ ] Updating license/copyright in the repo + updating file headers
- [ ] Reviewing the .NET Foundation Code of Conduct
- [ ] Add Project to the .NET Foundation project list
- [ ] Project layout cleanup (as appropriate)
- [ ] README Guidance updates 
- [ ] Project website updates (outside of GitHub)

**Comment by ChrisSfanos** [comment]
Project agreement is out for signing

**Comment by ChrisSfanos** [comment]
CLA is signed
I was also able to configure the CLA bot because the Xamarin org already has granted the bot the required perms.  I'll send out a set of instructions for the remaining steps shortly

**Comment by jfversluis** [comment]
Great! Thank you @ChrisSfanos !

**Comment by ChrisSfanos** [comment]
Looks like all checklist items are complete - this wraps up the onboarding process.  Welcome to the .NET Foundation!
