### ISSUE TITLE
Code Signing Certificate Request: Unity Container

### ISSUE THREAD

**Issue by ENikS** [dotnet-foundation/projects#97]
### Please fill in the information below

- **Project Name:** Unity Container
- **LastPass Email (or send offline):** unitycontainer@eniks.com

Certificate onboarding checklist:

- [x] Register trade name @ChrisSfanos
- [x] Create organization with DigiCert
- [x] Create configuration in Code Signing Service
- [x] Provide credentials in shared folder in LastPass
- [x] Request certificate from DigiCert
- [x] Received certificate and finalize sign service configuration

**Comment by ENikS** [comment]
@ChrisSfanos 

I've filed an application for trade name but it requires some legal help. I've created [an issue](https://github.com/dotnet-foundation/projects/issues/96) for that.

**Comment by clairernovotny** [comment]
@ENikS you don't need to do that, we handle the trade name bits.

**Comment by ChrisSfanos** [comment]
Yep, I'll handle the registration - go ahead and dump your application and I'll take care of this today

**Comment by ENikS** [comment]
I've created DigiCert organization 

Are there more detailed info on last 4 steps in the checklist?

**Comment by clairernovotny** [comment]
@ENikS you won't need to do that, we handle everything. We'll set it up in our signing service and share the credentials when it's set up. It could take 1-3 weeks depending on DigiCert's turnaround.

**Comment by ChrisSfanos** [comment]
Trade name registration was submitted this morning

**Comment by ENikS** [comment]
Will this signing facilitate NuGet signing as well?

**Comment by clairernovotny** [comment]
Yes, the signing service handles exe, dll, vsix, nupkg, etc.

**Comment by clairernovotny** [comment]
Looks like you may need to sign into last pass as per the dialog below.

![image](https://user-images.githubusercontent.com/1427284/92531601-97db3680-f1fc-11ea-9f36-c9b2ec7390a5.png)


I just invited you to the shared LastPass where the cert is setup and configured.

Few things:
1. Here's a template of how to add code signing to the build pipeline: https://github.com/novotnyllc/CodeSigningDemo
2. Once signing is configured, please add `dotnetfoundation` as a co-owner in NuGet. 
3. If you have any 3rd party binaries in your packages, you'll need a whitelist.txt to include on your binaries and not the other ones in the nupkg.

I'm happy to review any PR's/pipelines

**Comment by ENikS** [comment]
I generated these keys on their website but I don't see any shares or invitations.

**Comment by ENikS** [comment]
Accepted the share

**Comment by ENikS** [comment]
@clairernovotny 

Is there a sample using GitHub actions to sign the library? 
We are not using azure pipeline in our CDs
